INSERT INTO core_schema.saint_lives (name_ro, life_description_ro)
VALUES (
    'Sfântul Cuvios Eftimie cel Mare',
    '# Viața, Minunile și Moștenirea Sfântului Cuvios Eftimie cel Mare: O Cercetare Comparativă a Sursele Hagiografice Românești, Grecești și Ruse' || '\n\n' ||
    '## Introducere: Far al Pustiei și Stâlp al Ortodoxiei' || '\n\n' ||
    'Acest raport își propune să ofere o imagine completă și multi-fațetată a Sfântului Cuvios Eftimie cel Mare, sintetizând informații din surse hagiografice și liturgice românești, grecești și rusești. Se va urmări nu doar o simplă compilare de date, ci o analiză aprofundată a moștenirii sale spirituale, teologice și monahale, destinată unui public informat, în contextul unei aplicații digitale. Figura sa se înalță ca un reper fundamental în istoria Bisericii, fiind recunoscut drept un far călăuzitor al monahismului palestinian din secolul al V-lea, un „dascăl al căii împărătești" și un apărător neclintit al dreptei credințe într-o perioadă marcată de profunde tulburări teologice, în special cele care au urmat Sinodului IV Ecumenic de la Calcedon.^1^' || '\n\n' ||
    'Pentru acuratețea istorică și hagiografică, este esențială clarificarea identității Sfântului Eftimie cel Mare († 473), prăznuit la 20 ianuarie, și distingerea sa de alți sfinți omonimi cu care este uneori confundat în sursele populare. Printre aceștia se numără Sfântul Eftimie cel Nou († 889), un mucenic din Peloponez care a trăit o perioadă la Muntele Athos ^3^, și Sfântul Eftimie de Târnovo († c. 1402), patriarh al Bulgariei și ucenic al Sfântului Teodosie de Târnovo.^4^ Raportul de față se va concentra exclusiv asupra figurii Marelui Eftimie, a cărui viață, consemnată de ucenicul său indirect, Chiril din Scythopolis, este prezentată nu doar ca o biografie, ci ca o adevărată teologie a istoriei. Nașterea sa, ce a coincis cu sfârșitul dominației ariene, este înfățișată ca o lucrare a proniEI divine, un semn al „veseliei" (*euthymia*) pe care Dumnezeu o aduce Bisericii Sale după o lungă perioadă de „mâhnire" cauzată de erezie.^5^ Astfel, viața sfântului devine un microcosmos al istoriei mântuirii Bisericii, un model de înțelegere a sfințeniei nu ca un act izolat, ci ca o participare activă la drama cosmică a luptei dintre Adevăr și rătăcire.' || '\n\n' ||
    '## Partea I: Sinaxarul Detaliat al Sfântului Eftimie cel Mare' || '\n\n' ||
    '### Nașterea ca Răspuns la Rugăciune și Anii de Formare (377-406)' || '\n\n' ||
    'Viața Sfântului Eftimie începe sub semnul minunii, într-un context istoric de o importanță crucială pentru Biserică. S-a născut în anul 377 în cetatea Melitene, capitala provinciei Armenia Mică, o regiune ce tocmai ieșea de sub lunga perioadă de influență a ereziei ariene, odată cu apropierea sfârșitului domniei împăratului Valens (364-378).^1^ Părinții săi, Pavel și Dionisia, erau oameni de neam bun, evlavioși, dar profund îndurerați de lipsa unui moștenitor.^6^ În credința lor, au stăruit în rugăciune la biserica Sfântului Mucenic Polieuct din apropierea cetății. Acolo, o vedenie cerească le-a vestit că Dumnezeu le va dărui un fiu „numit cu numele veseliei" (în greacă *Εὐθύμιος*, Euthymios, derivat din *εὐθυμία*, euthymia - voie bună, veselie), a cărui naștere va aduce bucurie Bisericilor.^2^' || '\n\n' ||
    'Rămas orfan de tată la vârsta de trei ani, Eftimie a fost încredințat de mama sa episcopului Otreius al Melitinei. Sub îndrumarea acestuia și a viitorilor episcopi Acachie și Sinodie, tânărul a dovedit o inteligență remarcabilă și o râvnă duhovnicească ieșită din comun. Progresând rapid pe treptele clericale, a fost hirotonit preot și numit supraveghetor (exarh) al mănăstirilor din eparhie, demonstrând de timpuriu calități excepționale de lider spiritual și organizator.^6^' || '\n\n' ||
    '### Calea Pustiei și Întemeierea Vieții de Obște (406-429)' || '\n\n' ||
    'La vârsta de 29 de ani, simțind o chemare profundă spre o viață de nevoință desăvârșită, Sfântul Eftimie a părăsit responsabilitățile administrative și a plecat în pelerinaj la Ierusalim.^6^ Acolo, s-a retras în pustia Faran, într-o peșteră, unde l-a întâlnit pe Cuviosul Teoctist, un alt mare ascet. Timp de cinci ani, cei doi au trăit o viață de asceză riguroasă, bazată pe rugăciune neîncetată și muncă manuală, împletind coșuri pentru a-și asigura cele necesare traiului.^1^' || '\n\n' ||
    'Faima sfințeniei lor a atras numeroși ucenici, ceea ce i-a determinat pe cei doi cuvioși să caute un loc mai retras. S-au așezat într-o peșteră greu accesibilă din ținutul Wadi Mukellik. Deși intenția lor inițială era de a fonda o lavră -- o comunitate de sihaștri care trăiesc în chilii separate, dar se adună pentru slujbele comune -- condițiile aspre ale locului i-au determinat să organizeze o chinovie, adică o mănăstire de obște. Aceasta a fost prima mănăstire de acest fel din deșertul iudaic, avându-l pe Sfântul Teoctist ca egumen (stareț), iar pe Sfântul Eftimie ca părinte duhovnicesc și îndrumător.^1^ Acest model monastic, care îmbina formarea în comunitate cu idealul vieții solitare, a devenit fundamental pentru dezvoltarea monahismului palestinian. Lavra Sfântului Eftimie a funcționat ca o școală duhovnicească pregătitoare pentru monahii care aspirau la nevoințele superioare din Marea Lavră a Sfântului Sava cel Sfințit, unul dintre cei mai renumiți ucenici spirituali ai săi.^6^' || '\n\n' ||
    '### Stâlp al Ortodoxiei în Vremuri de Tulburare (429-473)' || '\n\n' ||
    'Rolul Sfântului Eftimie a depășit granițele vieții monahale, el devenind un apărător esențial al dreptei credințe într-o perioadă de criză teologică. După Sinodul IV Ecumenic de la Calcedon (451), care a dogmatizat învățătura despre cele două firi -- divină și umană -- ale Mântuitorului Hristos, o mare parte a monahismului palestinian a alunecat în erezia monofizită, sub influența unui episcop uzurpator, Teodosie. În acest context tulbure, Sfântul Eftimie a rămas un stâlp neclintit al Ortodoxiei, apărând cu fermitate hotărârile sinodului.^2^' || '\n\n' ||
    'Influența sa a fost decisivă în readucerea la dreapta credință a împărătesei Evdochia, soția împăratului Teodosie al II-lea. Aceasta, fiind o susținătoare a monofizitismului, a fost convinsă de argumentele și de sfințenia vieții Cuviosului Eftimie să se întoarcă la Ortodoxie, un act cu un impact politic și religios considerabil, care a consolidat poziția credincioșilor calcedonieni în Țara Sfântă.^11^ O altă lucrare misionară de anvergură a fost convertirea căpeteniei saracinilor (arabilor), Aspebetos, și a întregului său trib. Minunea vindecării fiului acestuia l-a determinat pe Aspebetos să ceară botezul, primind numele Petru și devenind ulterior primul episcop al arabilor, un moment de o importanță capitală pentru răspândirea creștinismului în acea regiune.^12^' || '\n\n' ||
    '### Adormirea și Moștenirea' || '\n\n' ||
    'Ajuns la o vârstă înaintată, Sfântul Eftimie și-a cunoscut dinainte ziua trecerii la Domnul. Și-a adunat ucenicii, le-a oferit ultimele sale învățături, un adevărat testament spiritual, și a adormit în pace la data de 20 ianuarie 473, la vârsta de 97 de ani.^5^ A fost înmormântat cu cinste în peștera unde își începuse nevoințele.^6^' || '\n\n' ||
    'Moștenirea sa a fost consemnată și transmisă posterității de către Chiril din Scythopolis, un hagiograf de seamă care, deși nu l-a cunoscut direct, a trăit în mănăstirea sa și a cules mărturiile ucenicilor săi. Chiril relatează cum, înainte de a începe scrierea vieții sfântului, a avut o vedenie în care Sfinții Eftimie și Sava i s-au arătat, încurajându-l și dându-i har pentru această lucrare sfântă, confirmând astfel originea divin inspirată a textului hagiografic.^1^' || '\n\n' ||
    '## Partea a II-a: Minunile Sfântului -- Mărturii ale Sfințeniei' || '\n\n' ||
    'Viața Sfântului Eftimie este presărată cu numeroase minuni, care nu sunt simple evenimente extraordinare, ci acte teologice ce dezvăluie sfințenia sa și puterea lui Dumnezeu care lucra prin el. Această minune se încadrează în tipare biblice clare, prezentându-l pe Eftimie ca pe o împlinire a modelelor de sfințenie din Vechiul și Noul Testament.' || '\n\n' ||
    '### Minuni ale Milei Divine' || '\n\n' ||
    'Printre cele mai cunoscute minuni se numără hrănirea a 400 de pelerini care au sosit pe neașteptate la mănăstirea sa, într-un moment în care proviziile erau insuficiente chiar și pentru zece persoane. Prin rugăciunea sfântului, puținele pâini din trapeză s-au înmulțit, săturându-i pe toți.^2^ Această minune, cu ecouri evidente ale înmulțirii pâinilor de către Mântuitorul, arată că mănăstirea sa devenise un nou centru euharistic, un loc al milei și al hranei duhovnicești.' || '\n\n' ||
    'De asemenea, a săvârșit nenumărate vindecări. Pe lângă cea a fiului căpeteniei saracine, care a dus la convertirea unui întreg popor, este cunoscut pentru dezlegarea sterpiciunii multor femei, o minune ce reflectă propria sa naștere minunată.^2^ Asemenea Sfântului Prooroc Ilie, prin rugăciune a adus ploaie în vreme de secetă, vindecând pământul de nerodire și demonstrând puterea sa asupra stihiilor naturii.^2^' || '\n\n' ||
    '### Daruri Duhovnicești' || '\n\n' ||
    'Harul divin care sălășluia în el era adesea vizibil și pentru ceilalți. Ucenicii săi mărturisesc că, în timpul Sfintei Liturghii, un stâlp de foc se pogora din cer și rămânea deasupra sfântului până la sfârșitul slujbei, o mărturie vizibilă a sfințeniei sale sacerdotale și a corectitudinii credinței sale.^7^' || '\n\n' ||
    'Sfântul Eftimie poseda și darul înainte-vederii și al deosebirii gândurilor. El cunoștea starea sufletească a celor ce se apropiau de Sfintele Taine, discernând între cei cu cuget curat și cei întinați.^2^ Și-a prevestit cu exactitate propria sa moarte, pregătindu-și ucenicii pentru trecerea sa la cele veșnice.^19^ Aceste daruri nu sunt simple puteri supranaturale, ci roade ale unei vieți dedicate în întregime lui Dumnezeu, confirmându-l ca un „om al lui Dumnezeu" desăvârșit.' || '\n\n' ||
    '## Partea a III-a: Învățătura și Imnografia' || '\n\n' ||
    '### „Calea Împărătească" a Ascezei' || '\n\n' ||
    'Deși sursele care menționează explicit termenul de „cale împărătească" nu au putut fi accesate în detaliu ^20^, conceptul poate fi reconstituit din învățăturile sale, așa cum au fost consemnate de Chiril din Scythopolis. Acesta reprezintă o cale de mijloc, echilibrată, care evită extremele ascetice dăunătoare și promovează o viață duhovnicească armonioasă. Principiile acestei căi sunt fundamentale pentru înțelegerea spiritualității eftimiene:' || '\n\n' ||
    '- **Lupta împotriva mândriei ascetice:** Sfântul Eftimie îi sfătuia pe ucenici să nu se mândrească cu postul lor și să nu caute lauda oamenilor. El îi îndemna să respecte rânduiala de obște și să mănânce cu moderație, fără a atrage atenția asupra nevoințelor personale.^19^' || '\n\n' ||
    '- **Importanța statorniciei:** Îi avertiza pe monahi împotriva ispitei de a părăsi mănăstirea în căutarea unui loc „mai bun" sau a unui duhovnic „mai sfânt", subliniind că progresul spiritual nu depinde de loc, ci de „credință și de o voință fermă".^19^' || '\n\n' ||
    '- **Superioritatea ascultării:** Prin pilda monahului Auxentius, care s-a îmbolnăvit grav din cauza neascultării, Sfântul Eftimie a întărit principiul că „Domnul iubește ascultarea mai mult decât jertfa, iar neascultarea duce la moarte".^19^' || '\n\n' ||
    '- **Iubirea și smerenia ca temelii:** În ultimele sale cuvinte, a subliniat că iubirea este „cea mai înaltă virtute" și că toate celelalte fapte bune sunt consolidate prin „iubire și smerenie", acestea fiind esența vieții creștine.^19^' || '\n\n' ||
    '### Cinstirea în Imnografie' || '\n\n' ||
    'Cinstirea Sfântului Eftimie cel Mare este reflectată în bogăția imnografică dedicată lui, care subliniază temele teologice centrale ale vieții sale. Textele liturgice, precum troparul și condacul, se regăsesc într-o formă unitară în tradițiile română, greacă și rusă, demonstrând universalitatea venerării sale în Ortodoxie.' || '\n\n' ||
    '| Imn | Text Românesc | Text Grecesc (Transliterare) | Text Slavon Bisericesc (Transliterare) | Teme Teologice Comune |' || '\n' ||
    '| :--- | :--- | :--- | :--- | :--- |' || '\n' ||
    '| **Tropar** | Veseleşte-te pustiu care nu rodeai, bucură-te ceea ce nu aveai durere; că bărbatul doririlor Duhului ţi-a înmulţit ţie fii, sădindu-i cu dreapta cinstire de Dumnezeu şi hrănindu-i cu înfrânarea, spre împlinirea faptelor bune. Cu ale cărui rugăciuni, Hristoase Dumnezeule, mântuieşte sufletele noastre. ^21^ | *Euphraínou éremos i ou tíktousa, euthýmeson i ouk odínousa; óti eplíthyné soi tékna, anír epithymión ton tou Pnévmatos, evseveía phytéfsas, enkrateía ekthrépsas, eis aretón teleiótita. Tais aftoú ikesíais, Christé o Theós, eirínefson tín zoín imón.* ^11^ | *Veselisya pustynya nerazhdayushchaya, blagodushstvuy neboleznavshaya, yako umnozhi tebe chada muzh zhelaniy duhovnykh, blagochestiem nasadiv, vozderzhaniem vospitav dobrodeteley v sovershenstvo. Togo molitvami Khriste Bozhe, umiri zhivot nash.* ^26^ | Pustia neroditoare care devine roditoare prin sfințenie; Eftimie ca „bărbat al doririlor duhovnicești”; Înmulțirea fiilor duhovnicești; Educația monastică prin evlavie și înfrânare. |' || '\n' ||
    '| **Condac** | Întru cinstita naşterea ta, făptura a aflat veselie; şi întru Dumnezeiasca pomenirea ta, cuvioase, bucurie a primit de pe urma multelor tale minuni; din care dai destul şi sufletelor noastre şi ne curăţeşte de spurcăciunea păcatelor, ca să cântăm: Aliluia. ^21^ | *En ti septí gennísei sou, charán i ktísis evrato; kaí en ti theía mními sou Ósie, tín efthymían élave ton pollón sou thavmáton; ex on paráschou plousíos tais psychaís imón, kaí apokátharon amartimatón kilídas, ópos psállomen, Alliloúia.* ^11^ | *V chestnem rozhdestve tvoem radost'' tvar'' obrete, i v bozhestvenney pamyati tvoey, prepodobne, blagodushie priyat mnogikh tvoikh chudes, ot nikhzhe podazhd'' bogatno v dushi nasha, i ochisti grekhov skverny, yako da poem: Alliluiya.* ^26^ | Bucuria creației la nașterea sfântului; Minunile ca sursă de „voie bună”; Puterea de a curăți păcatele; Lauda neîncetată (Aliluia). |' || '\n\n' ||
    'Acatistul Sfântului Eftimie, deși mai puțin răspândit decât al altor mari cuvioși, este o lucrare de o profundă evlavie, disponibilă în limbile română și rusă.^4^ Acesta dezvoltă temele din tropar și condac, lăudându-l pe sfânt pentru viața sa îngerească și pentru minunile sale, cu un accent deosebit pe rolul său de „ajutor al familiilor fără copii", o referință directă la minunea propriei sale nașteri și la darul său de a dezlega sterpiciunea.^39^' || '\n\n' ||
    '### Reprezentarea Iconografică' || '\n\n' ||
    'Icoanele Sfântului Cuvios Eftimie cel Mare respectă canonul iconografic bizantin pentru cuvioșii părinți ai pustiei. El este înfățișat ca un bătrân cu o barbă lungă și albă, simbol al înțelepciunii duhovnicești dobândite prin îndelungată nevoință. Poartă veșmintele monahale ale schimei mari, care indică treapta cea mai înaltă a vieții călugărești. De obicei, ține în mână un sul desfășurat, pe care este scris un citat din învățăturile sale, simbolizând rolul său de dascăl și legiuitor al vieții monahale. În alte reprezentări, poartă o cruce, semn al mărturisirii credinței și al urmării lui Hristos pe calea jertfei. Fundalul icoanei este adesea peisajul arid al pustiei, spațiul teologic al întâlnirii omului cu Dumnezeu, pe care sfântul l-a transformat, prin viața sa, într-o „grădină înfloritoare" a Duhului.^13^' || '\n\n' ||
    '## Concluzie: Eftimie cel Mare -- Actualitatea unui Părinte al Pustiului' || '\n\n' ||
    'În concluzie, Sfântul Cuvios Eftimie cel Mare se distinge ca o figură monumentală a secolului al V-lea, a cărui moștenire a modelat profund spiritualitatea creștin-răsăriteană. Contribuțiile sale esențiale includ organizarea monahismului palestinian într-un sistem coerent și ierarhizat, apărarea hotărâtă a Ortodoxiei calcedoniene într-un moment critic pentru unitatea Bisericii și, mai presus de toate, exemplul personal de sfințenie, bazat pe „calea împărătească" a echilibrului, smereniei și iubirii.' || '\n\n' ||
    'Relevanța sa contemporană este incontestabilă. Într-o lume a extremelor și a căutărilor spirituale adesea dezorientate, învățăturile Sfântului Eftimie despre discernământ, despre importanța comunității și a ascultării, și despre necesitatea de a evita mândria duhovnicească oferă un guis practic și sigur. El rămâne, peste veacuri, un „dascăl al căii împărătești" și un rugător fierbinte pentru toți creștinii care caută mântuirea.' || '\n\n' ||
    '### Recomandări pentru Dezvoltarea Aplicației' || '\n\n' ||
    'Pentru a transpune acest studiu cuprinzător într-o aplicație Android utilă și accesibilă, se recomandă o structură modulară care să permită utilizatorilor să exploreze diferitele fațete ale vieții și moștenirii sfântului:' || '\n\n' ||
    '- **Modul Biografic:** O prezentare cronologică a vieții sale, împărțită în capitole clare: „Tinerețea și Chemarea", „Lupta din Pustiu", „Părinte al Monahilor" și „Apărător al Credinței".' || '\n\n' ||
    '- **Modul „Pateric":** O colecție a zicerilor sale, organizate tematic (despre smerenie, rugăciune, ispite, iubirea aproapelui) și cu funcție de căutare.' || '\n\n' ||
    '- **Modul „Războiul Nevăzut":** O secțiune dedicată conceptului de *logismoi*, care să explice etapele ispitei și armele spirituale pentru a le combate, oferind sfaturi practice bazate pe învățăturile sfântului.' || '\n\n' ||
    '- **Modul Liturgic și Imnografic:** Să includă textele complete ale Acatistului, Troparului și Condacului, cu opțiunea de a asculta versiuni audio în română, rusă și greacă.' || '\n\n' ||
    '- **Modul Iconografic:** O galerie de icoane de înaltă rezoluție, cu explicații interactive pentru simbolurile cheie (Crucea Tau, toiagul, sulul, porcul și clopotul), clarificând originile și semnificațiile acestora.' || '\n\n' ||
    'Această structură va transforma raportul academic într-un instrument dinamic și accesibil pentru edificare spirituală, îndeplinind scopul final al utilizatorului.' || '\n\n' ||
    '#### Works cited' || '\n\n' ||
    '1. Sfântul Cuvios Eftimie cel Mare -- Cuvântul Înaltpreasfințitului Părinte Calinic, accessed August 7, 2025, [[https://www.arhiepiscopiasucevei.ro/sfantul-cuvios-eftimie-cel-mare-cuvantul-inaltpreasfintitului-parinte-calinic-2/]{.underline}](https://www.arhiepiscopiasucevei.ro/sfantul-cuvios-eftimie-cel-mare-cuvantul-inaltpreasfintitului-parinte-calinic-2/)' || '\n' ||
    '2. 20 ianuarie Sfantul Cuvios Eftimie cel Mare - Sfintele Icoane, accessed August 7, 2025, [[https://www.sfinteleicoane.ro/sfinti-ianuarie/34-sfantul-cuvios-eftimie-cel-mare.html]{.underline}](https://www.sfinteleicoane.ro/sfinti-ianuarie/34-sfantul-cuvios-eftimie-cel-mare.html)' || '\n' ||
    '3. Viața Sfântului Cuvios Mucenic Eftimie cel Nou - Doxologia, accessed August 7, 2025, [[https://doxologia.ro/viata-sfantului-cuvios-mucenic-eftimie-cel-nou]{.underline}](https://doxologia.ro/viata-sfantului-cuvios-mucenic-eftimie-cel-nou)' || '\n' ||
    '4. Sf. Eftimie cel Mare mare ocrotitor in case icoana -patron celor nascuti 20 ianuarie, accessed August 7, 2025, [[https://www.mgargenti.ro/sfinti-ortodoxi-nume-barbati/sf-eftimie-cel-mare-mare-ocrotitor-in-case-icoana-patron--286043]{.underline}](https://www.mgargenti.ro/sfinti-ortodoxi-nume-barbati/sf-eftimie-cel-mare-mare-ocrotitor-in-case-icoana-patron--286043)' || '\n' ||
    '5. Viața Sfântului Cuvios Eftimie cel Mare | Doxologia, accessed August 7, 2025, [[https://doxologia.ro/viata-sfantului-cuvios-eftimie-cel-mare]{.underline}](https://doxologia.ro/viata-sfantului-cuvios-eftimie-cel-mare)' || '\n' ||
    '6. Eftimie cel Mare - OrthodoxWiki, accessed August 7, 2025, [[https://ro.orthodoxwiki.org/Eftimie_cel_Mare]{.underline}](https://ro.orthodoxwiki.org/Eftimie_cel_Mare)' || '\n' ||
    '7. 20 Ianuarie - Preacuviosul Eftimie cel Mare :: Calendar ortodox - Sfintii zilei - Sinaxar, accessed August 7, 2025, [[https://www.calendar-ortodox.ro/luna/ianuarie/ianuarie20.htm]{.underline}](https://www.calendar-ortodox.ro/luna/ianuarie/ianuarie20.htm)' || '\n' ||
    '8. Φώτης Κόντογλου - Ὁ Ἥλιος τῆς Ἐρήμου. Ὁ Μέγας Εὐθύμιος, accessed August 7, 2025, [[http://users.uoa.gr/~nektar/arts/tributes/fwths_kontogloy/o_megas_ey8ymios.htm]{.underline}](http://users.uoa.gr/~nektar/arts/tributes/fwths_kontogloy/o_megas_ey8ymios.htm)' || '\n' ||
    '9. Δ'' ΟΙΚΟΥΜΕΝΙΚΗ ΣΥΝΟΔΟΣ, accessed August 7, 2025, [[https://www.monipetraki.gr/oikoumend.html]{.underline}](https://www.monipetraki.gr/oikoumend.html)' || '\n' ||
    '10. Сегодня, 29 июля, Церковь вспоминает святых отцов IV Вселенского Собора, accessed August 7, 2025, [[https://foma.ru/cerkov-vspominaet-svjatyh-otcov-iv-vselenskogo-sobora.html]{.underline}](https://foma.ru/cerkov-vspominaet-svjatyh-otcov-iv-vselenskogo-sobora.html)' || '\n' ||
    '11. Ὁ Βίος τοῦ Ὁσίου Εὐθυμίου τοῦ Μεγάλου - Αρχική, accessed August 7, 2025, [[https://www.profitisilias.gr/enoria/index.php/eortologio/2010-09-20-05-05-20/639-sios-e-thymios-megas]{.underline}](https://www.profitisilias.gr/enoria/index.php/eortologio/2010-09-20-05-05-20/639-sios-e-thymios-megas)' || '\n' ||
    '12. Άγιος Ευθύμιος ο Μέγας - Pemptousia, accessed August 7, 2025, [[https://www.pemptousia.gr/2023/01/agios-efthimios-o-megas/]{.underline}](https://www.pemptousia.gr/2023/01/agios-efthimios-o-megas/)' || '\n' ||
    '13. Άγιος Ευθύμιος ο Μέγας - Βικιπαίδεια, accessed August 7, 2025, [[https://el.wikipedia.org/wiki/%CE%86%CE%B3%CE%B9%CE%BF%CF%82_%CE%95%CF%85%CE%B8%CF%8D%CE%BC%CE%B9%CE%BF%CF%82_%CE%BF_%CE%9C%CE%AD%CE%B3%CE%B1%CF%82]{.underline}](https://el.wikipedia.org/wiki/%CE%86%CE%B3%CE%B9%CE%BF%CF%82_%CE%95%CF%85%CE%B8%CF%8D%CE%BC%CE%B9%CE%BF%CF%82_%CE%BF_%CE%9C%CE%AD%CE%B3%CE%B1%CF%82)' || '\n' ||
    '14. Euthymius the Great - Wikipedia, accessed August 7, 2025, [[https://en.wikipedia.org/wiki/Euthymius_the_Great]{.underline}](https://en.wikipedia.org/wiki/Euthymius_the_Great)' || '\n' ||
    '15. Sfântul Eftimie cel Mare. Ce trebuie să facă bărbații pe 20 ianuarie - Stirile ProTV, accessed August 7, 2025, [[https://stirileprotv.ro/divers/sfantul-eftimie-cel-mare-ce-trebuie-sa-faca-barbatii-pe-20-ianuarie.html]{.underline}](https://stirileprotv.ro/divers/sfantul-eftimie-cel-mare-ce-trebuie-sa-faca-barbatii-pe-20-ianuarie.html)' || '\n' ||
    '16. Πώς γράφτηκε ο βίος του οσίου Ευθυμίου του Μεγάλου - Pemptousia, accessed August 7, 2025, [[https://www.pemptousia.gr/2023/01/pos-graftike-o-vios-tou-osiou-efthimiou-tou-megalou/]{.underline}](https://www.pemptousia.gr/2023/01/pos-graftike-o-vios-tou-osiou-efthimiou-tou-megalou/)' || '\n' ||
    '17. This electronic thesis or dissertation has been downloaded from the ..., accessed August 7, 2025, [[https://kclpure.kcl.ac.uk/portal/files/2930189/366991.pdf]{.underline}](https://kclpure.kcl.ac.uk/portal/files/2930189/366991.pdf)' || '\n' ||
    '18. Cyril de Scythopolis Et Les Monasteries Du Desert PDF - Scribd, accessed August 7, 2025, [[https://www.scribd.com/document/358927739/Cyril-de-Scythopolis-et-les-monasteries-du-desert-pdf]{.underline}](https://www.scribd.com/document/358927739/Cyril-de-Scythopolis-et-les-monasteries-du-desert-pdf)' || '\n' ||
    '19. Venerable Euthymius the Great - Orthodox Church in America, accessed August 7, 2025, [[https://www.oca.org/saints/lives/2011/01/20/100238-venerable-euthymius-the-great]{.underline}](https://www.oca.org/saints/lives/2011/01/20/100238-venerable-euthymius-the-great)' || '\n' ||
    '20. ziarullumina.ro, accessed August 7, 2025, [[https://ziarullumina.ro/actualitate-religioasa/stiri/sfantul-eftimie-cel-mare-dascalul-caii-imparatesti-120158.html]{.underline}](https://ziarullumina.ro/actualitate-religioasa/stiri/sfantul-eftimie-cel-mare-dascalul-caii-imparatesti-120158.html)' || '\n' ||
    '21. Canon de rugăciune către Sfântul Cuvios Eftimie cel Mare (1 ..., accessed August 7, 2025, [[https://doxologia.ro/canon-de-rugaciune-catre-sfantul-cuvios-eftimie-cel-mare-1]{.underline}](https://doxologia.ro/canon-de-rugaciune-catre-sfantul-cuvios-eftimie-cel-mare-1)' || '\n' ||
    '22. Troparul Sfântului Cuvios Eftimie cel Mare - Doxologia, accessed August 7, 2025, [[https://doxologia.ro/troparul-sfantului-cuvios-eftimie-cel-mare]{.underline}](https://doxologia.ro/troparul-sfantului-cuvios-eftimie-cel-mare)' || '\n' ||
    '23. Απολυτίκιο Οσίου Ευθυμίου του Μεγάλου - 20 Ιανουαρίου - Ι.Μ. Αγίου Ραφαήλ Μυτιλήνης, accessed August 7, 2025, [[https://www.youtube.com/watch?v=vVYuvelLlic]{.underline}](https://www.youtube.com/watch?v=vVYuvelLlic)' || '\n' ||
    '24. 20/1/2022 | ΟΣΙΟΣ ΕΥΘΥΜΙΟΣ Ο ΜΕΓΑΣ | ΟΡΘΡΟΣ & ΘΕΙΑ ΛΕΙΤΟΥΡΓΙΑ - YouTube, accessed August 7, 2025, [[https://www.youtube.com/watch?v=z28Imbkr2T8]{.underline}](https://www.youtube.com/watch?v=z28Imbkr2T8)' || '\n' ||
    '25. Απολυτίκιο Αγ. Ευθυμίου - 20 ΙΑΝΟΥΑΡΙΟΥ - YouTube, accessed August 7, 2025, [[https://www.youtube.com/watch?v=_Ri23X7TTjw]{.underline}](https://www.youtube.com/watch?v=_Ri23X7TTjw)' || '\n' ||
    '26. ПРЕПОДОБНЫЙ ЕВФИМИЙ ВЕЛИКИЙ - Храм Святых Царственных Страстотерпцев в Ясеневе, accessed August 7, 2025, [[https://www.hramstrastoterpcy.ru/2020/02/prepodobnyj-evfimij-velikij/]{.underline}](https://www.hramstrastoterpcy.ru/2020/02/prepodobnyj-evfimij-velikij/)' || '\n' ||
    '27. Тропарь и кондак прп. Евфимию Великому, accessed August 7, 2025, [[https://www.sedmitza.ru/text/951237.html]{.underline}](https://www.sedmitza.ru/text/951237.html)' || '\n' ||
    '28. Полный Тропарион (Тома I-II), 20/2 Преподобного Евфимия ..., accessed August 7, 2025, [[https://azbyka.ru/otechnik/Pravoslavnoe_Bogosluzhenie/polnyj-troparion/6_19]{.underline}](https://azbyka.ru/otechnik/Pravoslavnoe_Bogosluzhenie/polnyj-troparion/6_19)' || '\n' ||
    '29. Condacul Sfântului Cuvios Eftimie cel Mare - Doxologia, accessed August 7, 2025, [[https://doxologia.ro/condacul-sfantului-cuvios-eftimie-cel-mare]{.underline}](https://doxologia.ro/condacul-sfantului-cuvios-eftimie-cel-mare)' || '\n' ||
    '30. Όσιος Ευθύμιος ο Μέγας - Ορθόδοξος Συναξαριστής, accessed August 7, 2025, [[https://www.saint.gr/3322/saint.aspx]{.underline}](https://www.saint.gr/3322/saint.aspx)' || '\n' ||
    '31. Όσιος Ευθύμιος ο Μέγας - Ορθόδοξος Συναξαριστής, accessed August 7, 2025, [[https://www.saint.gr/13322/downloadpdf.aspx]{.underline}](https://www.saint.gr/13322/downloadpdf.aspx)' || '\n' ||
    '32. 20-01 † Μνήµη τοῦ Ὁσίου Πατρὸς ἡµῶν Εὐθυµίου τοῦ Μεγάλου. ΟΡΘΡΟΣ Ἦχος Δι Θε ος - melodos.com, accessed August 7, 2025, [[https://melodos.com/bibliothiki/wp-content/uploads/2018/01/20-01-2022-%CE%8C%CF%81%CE%B8%CF%81%CE%BF%CF%82-%CE%91%CE%B3%CE%AF%CE%BF%CF%85-%CE%95%CF%85%CE%B8%CF%85%CE%BC%CE%AF%CE%BF%CF%85.pdf]{.underline}](https://melodos.com/bibliothiki/wp-content/uploads/2018/01/20-01-2022-%CE%8C%CF%81%CE%B8%CF%81%CE%BF%CF%82-%CE%91%CE%B3%CE%AF%CE%BF%CF%85-%CE%95%CF%85%CE%B8%CF%85%CE%BC%CE%AF%CE%BF%CF%85.pdf)' || '\n' ||
    '33. 20 Ιανουαρίου, μνήμη του Οσίου Πατρός ημών Ευθυμίου του μεγάλου: Συναξάριον, Υμνολογική εκλογή. | ΟΡΘΟΔΟΞΗ ΠΟΡΕΙΑ -- orp.gr, accessed August 7, 2025, [[https://www.orp.gr/wordpress/?p=310]{.underline}](https://www.orp.gr/wordpress/?p=310)' || '\n' ||
    '34. Преподобному Евфимию Великому (тропарь, кондак) - ПСАЛОМЩИКЪ - <, accessed August 7, 2025, [[http://diak.ortox.ru/*_prepodobnym/view/id/1104791]{.underline}](http://diak.ortox.ru/*_prepodobnym/view/id/1104791)' || '\n' ||
    '35. Акафист преподобному ЕВФИМИЮ ВЕЛИКОМУ - Православная Херсонщина, accessed August 7, 2025, [[http://www.pravoslavie.ks.ua/rubric/prepodobnym-/article/akafist-prepodobnomu-evfimiyu-velikomu]{.underline}](http://www.pravoslavie.ks.ua/rubric/prepodobnym-/article/akafist-prepodobnomu-evfimiyu-velikomu)' || '\n' ||
    '36. Viaţa şi Acatistul Sfântului Cuvios Eftimie cel Mare - Carti Bisericesti, accessed August 7, 2025, [[https://cartibisericesti.ro/viata-si-acatistul-sfantului-cuvios-eftimie-cel-mare/]{.underline}](https://cartibisericesti.ro/viata-si-acatistul-sfantului-cuvios-eftimie-cel-mare/)' || '\n' ||
    '37. Acatistul Sfântului Eftimie cel Mare - YouTube, accessed August 7, 2025, [[https://www.youtube.com/watch?v=W5N-5DWjiR0]{.underline}](https://www.youtube.com/watch?v=W5N-5DWjiR0)' || '\n' ||
    '38. Acatistul Sfântului Cuvios Eftimie - Arhiepiscopia Bucureștilor, accessed August 7, 2025, [[https://arhiepiscopiabucurestilor.ro/stiri/carte-recomandata/editura-institutului-biblic-si-de-misiune-ortodoxa/acatistul-sfantului-0]{.underline}](https://arhiepiscopiabucurestilor.ro/stiri/carte-recomandata/editura-institutului-biblic-si-de-misiune-ortodoxa/acatistul-sfantului-0)' || '\n' ||
    '39. Acatistul Sfantului Eftimie cel Mare, ajutorul familiilor fara copii - 20 ianuarie - YouTube, accessed August 7, 2025, [[https://www.youtube.com/watch?v=tKxM3iaeEH4]{.underline}](https://www.youtube.com/watch?v=tKxM3iaeEH4)' || '\n' ||
    '40. Acatistul Sfântului Mucenic Efrem cel Nou - Doxologia, accessed August 7, 2025, [[https://doxologia.ro/acatistul-sfantului-mucenic-efrem-cel-nou]{.underline}](https://doxologia.ro/acatistul-sfantului-mucenic-efrem-cel-nou)' || '\n' ||
    '41. Acatistul Sfântului Cuvios Eftimie - YouTube, accessed August 7, 2025, [[https://www.youtube.com/watch?v=QYHXmEQR-_k]{.underline}](https://www.youtube.com/watch?v=QYHXmEQR-_k)' || '\n' ||
    '42. Sfântul Cuvios Eftimie cel Mare - 20 ianuarie #Sinaxar - YouTube, accessed August 7, 2025, [[https://www.youtube.com/watch?v=g7K9fvc_h9g]{.underline}](https://www.youtube.com/watch?v=g7K9fvc_h9g)' || '\n' ||
    '43. Saint Euthymius the Great, ( Άγιος Ευθύμιος ο Μέγας ) Hand Painted Greek Orthodox Icon. - Etsy, accessed August 7, 2025, [[https://www.etsy.com/listing/945656143/saint-euthymius-the-great-agios]{.underline}](https://www.etsy.com/listing/945656143/saint-euthymius-the-great-agios)' || '\n' ||
    '44. SAINT EUTHYMIUS THE GREAT, accessed August 7, 2025, [[https://artisgr.shop/en/saints/82589-saint-euthymius-the-great.html]{.underline}](https://artisgr.shop/en/saints/82589-saint-euthymius-the-great.html)' || '\n' ||
    '45. St Euthymius the Great, icon 17th c. Dionysiou Monastery, Mt Athos, Greece, accessed August 7, 2025, [[https://www.bridgemanimages.com/en/chris-hellier/st-euthymius-the-great-icon-17th-c-dionysiou-monastery-mt-athos-greece/nomedium/asset/3262606]{.underline}](https://www.bridgemanimages.com/en/chris-hellier/st-euthymius-the-great-icon-17th-c-dionysiou-monastery-mt-athos-greece/nomedium/asset/3262606)' || '\n' ||
    '46. Orthodox icon of Saint Euthymius the Great - orthodoxmonasteryicons.com, accessed August 7, 2025, [[https://orthodoxmonasteryicons.com/products/euthymius-the-great-1]{.underline}](https://orthodoxmonasteryicons.com/products/euthymius-the-great-1)' || '\n' ||
    '47. Saint Euthymius the Great - Orthodox icon of Mount Athos - Athonian, accessed August 7, 2025, [[https://www.athonian.gr/orthodox-icons/saints-male-en/saint-euthymios-the-great-106-1/]{.underline}](https://www.athonian.gr/orthodox-icons/saints-male-en/saint-euthymios-the-great-106-1/)' || '\n' ||
    '48. SAINT EUTHYMIUS THE GREAT, accessed August 7, 2025, [[https://artisgr.shop/en/saints/83929-saint-euthymius-the-great.html]{.underline}](https://artisgr.shop/en/saints/83929-saint-euthymius-the-great.html)' || '\n' ||
    '49. Icoana Sfantului Eftimie cel Mare, cod:SFR136 - Icoane Ortodoxe, accessed August 7, 2025, [[https://icoana.net/icoane/icoana-sfantului-eftimie-cel-mare-codsfr136/]{.underline}](https://icoana.net/icoane/icoana-sfantului-eftimie-cel-mare-codsfr136/)' || '\n' ||
    '50. Icoana Sfântul Cuvios Eftimie cel Mare - Obiecte de Cult Grecia, accessed August 7, 2025, [[https://obiectecultgrecia.ro/obiect-de-cult-115-Icoana-Sfantul-Cuvios-Eftimie-cel-Mare]{.underline}](https://obiectecultgrecia.ro/obiect-de-cult-115-Icoana-Sfantul-Cuvios-Eftimie-cel-Mare)' || '\n' ||
    '51. Icoana cu Rama si Sticla Sfantul Cuvios Eftimie cel Mare, 30 x 22 cm - eMAG.ro, accessed August 7, 2025, [[https://www.emag.ro/icoana-cu-rama-si-sticla-sfantul-cuvios-eftimie-cel-mare-30-x-22-cm-ic-0120-sfeftimiecelmare/pd/DGHTL2BBM/]{.underline}](https://www.emag.ro/icoana-cu-rama-si-sticla-sfantul-cuvios-eftimie-cel-mare-30-x-22-cm-ic-0120-sfeftimiecelmare/pd/DGHTL2BBM/)' || '\n' ||
    '52. Sfântul Eftimie cel Mare icoana rara numit cu numele veseliei - MG Argenti, accessed August 7, 2025, [[https://www.mgargenti.ro/icoane-rare-sfinti-nume-barbati/sf%C3%A2ntul-eftimie-cel-mare-icoana-rara-numit-cu-numele-veseli--279624]{.underline}](https://www.mgargenti.ro/icoane-rare-sfinti-nume-barbati/sf%C3%A2ntul-eftimie-cel-mare-icoana-rara-numit-cu-numele-veseli--279624)' || '\n' ||
    '53. Εικόνα Άγιος Ευθύμιος † Ευαγγελίδης Δ. Ηλίας - Εκκλησιαστικά Είδη, accessed August 7, 2025, [[https://evagelidis.com/%CE%B5%CE%BA%CE%BA%CE%BB%CE%B7%CF%83%CE%B9%CE%B1%CF%83%CF%84%CE%B9%CE%BA%CE%AC-%CE%B5%CE%AF%CE%B4%CE%B7/%CE%B5%CE%B9%CE%BA%CF%8C%CE%BD%CE%B5%CF%82-%CE%B1%CE%B3%CE%AF%CE%99%CF%89%CE%BD/%CE%B5%CE%B9%CE%BA%CF%8C%CE%BD%CE%B1-%CE%AC%CE%B3%CE%B9%CE%BF%CF%82-%CE%B5%CF%85%CE%B8%CF%8D%CE%BC%CE%B9%CE%BF%CF%82/]{.underline}](https://evagelidis.com/%CE%B5%CE%BA%CE%BA%CE%BB%CE%B7%CF%83%CE%B9%CE%B1%CF%83%CF%84%CE%B9%CE%BA%CE%AC-%CE%B5%CE%AF%CE%B4%CE%B7/%CE%B5%CE%B9%CE%BA%CF%8C%CE%BD%CE%B5%CF%82-%CE%B1%CE%B3%CE%AF%CE%99%CF%89%CE%BD/%CE%B5%CE%B9%CE%BA%CF%8C%CE%BD%CE%B1-%CE%AC%CE%B3%CE%B9%CE%BF%CF%82-%CE%B5%CF%85%CE%B8%CF%8D%CE%BC%CE%B9%CE%BF%CF%82/)' || '\n' ||
    '54. Άγιος Ευθύμιος ο Μέγας εικόνα - KAPPADOKIS, accessed August 7, 2025, [[https://kappadokis.eu/%CE%86%CE%B3%CE%B9%CE%BF%CF%82-%CE%95%CF%85%CE%B8%CF%8D%CE%BC%CE%B9%CE%BF%CF%82-%CE%BC%CE%AD%CE%B3%CE%B1%CF%82-%CE%B5%CE%B9%CE%BA%CF%8C%CE%BD%CE%B1-%CE%B5%CE%B9%CE%BA%CF%8C%CE%BD%CE%B5%CF%82-%CE%91%CE%B3%CE%AF%CE%BF%CE%BD-%CE%B5%CE%B9%CE%BA%CE%BF%CE%BD%CE%B5%CF%83-%CE%B1%CE%B3%CE%AF%CE%BF%CE%BD]{.underline}](https://kappadokis.eu/%CE%86%CE%B3%CE%B9%CE%BF%CF%82-%CE%95%CF%85%CE%B8%CF%8D%CE%BC%CE%B9%CE%BF%CF%82-%CE%BC%CE%AD%CE%B3%CE%B1%CF%82-%CE%B5%CE%B9%CE%BA%CF%8C%CE%BD%CE%B1-%CE%B5%CE%B9%CE%BA%CF%8C%CE%BD%CE%B5%CF%82-%CE%91%CE%B3%CE%AF%CE%BF%CE%BD-%CE%B5%CE%B9%CE%BA%CE%BF%CE%BD%CE%B5%CF%83-%CE%B1%CE%B3%CE%AF%CE%BF%CE%BD)' || '\n' ||
    '55. Άγιος Ευθύμιος ο Μέγας - Orthodoxes eikones, accessed August 7, 2025, [[https://www.orthodoxes-eikones.gr/eikona-agios-eythymios-o-megas_1.html]{.underline}](https://www.orthodoxes-eikones.gr/eikona-agios-eythymios-o-megas_1.html)' || '\n' ||
    '56. Άγιος Ευθύμιος - Monastiriaka, accessed August 7, 2025, [[https://www.monastiriaka.gr/agios-efthymios-1]{.underline}](https://www.monastiriaka.gr/agios-efthymios-1)'
);
