INSERT INTO core_schema.saint_lives (name_ro, life_description_ro)
VALUES (
    'Sfânta Xenia de Sankt Petersburg',
    '# Hagiografie Comparată și Fenomenologie Spirituală: Sfânta Xenia de Sankt Petersburg' || '\n\n' ||
    '## Introducere: Ontologia Înstrăinării și Arhetipul Pelerinului în Teologia Răsăriteană' || '\n\n' ||
    'În vastul tezaur al spiritualității ortodoxe, numele „Xenia" transcende simpla funcție de apelativ onomastic, devenind un veritabil program teologic. Derivat din grecescul *xenos*, termenul comportă o polivalență semantică ce oscilează între „străin", „oaspete" și „pelerin". Această etimologie nu este accidentală, ci definește însăși esența vieții creștine autentice, înțeleasă ca o înstrăinare voluntară de duhul lumii căzute pentru o familiarizare progresivă cu Împărăția Cerurilor. Cercetarea de față își propune să exploreze, într-o manieră exhaustivă și academică, viața, teologia și cultul Sfintei Xenia de Sankt Petersburg, o văduvă a secolului al XVIII-lea care a îmbrățișat nebunia pentru Hristos în inima imperiului țarist.^1^' || '\n\n' ||
    'Prezentul raport va analiza modul în care această figură feminină a reconfigurat percepția asupra sfințeniei, transformând slăbiciunea socială (văduvia, nebunia aparentă) în instrumente de putere duhovnicească. De asemenea, vom investiga detaliat geografia sacră a venerării sale în România și Republica Moldova, identificând moaștele, icoanele făcătoare de minuni și practicile devoționale specifice.^3^' || '\n\n' ||
    '### Dualitatea Numelui și Confuzia Hagiografică' || '\n\n' ||
    'Este imperiv, din capul locului, să disociem pe Sfânta Xenia de Sankt Petersburg de Sfânta Cuvioasă Xenia de Roma. Sfânta Xenia de Sankt Petersburg întruchipează modelul paradoxal al sfințeniei urbane, agresive în smerenia sa, cunoscută sub numele de *iurodivîi* (nebună pentru Hristos), un model care nu fuge de lume, ci o confruntă prin inversarea valorilor sociale în mijlocul cetății.^1^' || '\n\n' ||
    '## Partea II: Sfânta Xenia de Sankt Petersburg -- Nebunia pentru Hristos ca Formă Supremă de Iubire' || '\n\n' ||
    'Dacă Xenia de Roma a ales calea clasică a retragerii, Sfânta Xenia de Sankt Petersburg a ales calea mult mai periculoasă și paradoxală a expunerii totale prin nebunie simulată. Viața sa se desfășoară pe fundalul Rusiei secolului al XVIII-lea, o perioadă de occidentalizare forțată și de secularizare a elitelor, inițiată de Petru cel Mare.' || '\n\n' ||
    '### 2.1. Biografie și Context Social: O Viață Întreruptă' || '\n\n' ||
    'Xenia Grigorievna Petrova s-a născut în jurul anilor 1719-1730, într-o familie de condiție bună, probabil din mica nobilime. S-a căsătorit cu colonelul Andrei Teodorovici Petrov, care deținea funcția de capelmaistru (dirijor) al corului imperial de la curtea Țarinei Elisabeta Petrovna.^1^ Această funcție plasa familia Petrov în cercurile apropiate curții, asigurându-le o viață confortabilă și mondenă în Sankt Petersburg.' || '\n\n' ||
    'Tragedia a lovit brusc când Xenia avea 26 de ani. Soțul ei, Andrei, a murit subit în timpul unei petreceri, fără a avea timp să se spovedească și să se împărtășească.^8^ În teologia ortodoxă rusă a vremii, moartea fără sacramente („fără lumânare") era privită cu o groază metafizică, sufletul celui decedat fiind considerat în mare pericol de a nu dobândi mântuirea.' || '\n\n' ||
    '### 2.2. Convertirea prin Substituție: „Andrei a murit? Nu, Xenia a murit!"' || '\n\n' ||
    'Reacția Xeniei la această pierdere a fost una care sfidează logica psihologică și intră în teritoriul misticii. Iubirea ei pentru soț a fost atât de intensă încât a decis să-și sacrifice propria identitate și viață pentru a ispăși păcatele lui și pentru a se ruga pentru sufletul său. În ziua înmormântării, ea a apărut îmbrăcată în uniforma militară a soțului ei (vesta verde și caftanul roșu) și a declarat rudelor și cunoscuților: „Andrei Teodorovici nu a murit; a murit Xenia Grigorievna, iar Andrei Teodorovici trăiește".^1^' || '\n\n' ||
    'Această afirmație nu era o negare psihotică a realității, ci un act de asumare vicariantă. Xenia a decis să moară ea față de lume (să renunțe la identitatea de văduvă respectabilă, la avere, la nume) pentru ca, prin nevoința ei sub numele lui Andrei, să atragă mila lui Dumnezeu asupra sufletului acestuia. Când rudele, îngrijorate că ea își dona casa și averea săracilor, au cerut autorităților să intervină, medicii și oficialii au examinat-o și au concluzionat că este perfect sănătoasă mintal, având dreptul să dispună de bunurile sale.^6^' || '\n\n' ||
    '### 2.3. Asceza Urbană și Fenomenul „Iurodivîi"' || '\n\n' ||
    'Timp de 45 de ani, Sfânta Xenia a rătăcit pe străzile cartierului „Petersburgskaya Storona" (Partea Petersburgului), devenind o figură emblematică a orașului. Modelul său ascetic, *nebunia pentru Hristos*, presupune o luptă totală împotriva mândriei (kenoză).' || '\n\n' ||
    '- **Vestimentația Simbolică:** După ce uniforma soțului s-a uzat, Xenia a continuat să poarte haine în culorile acesteia -- fustă roșie și bluză verde sau invers -- refuzând haine călduroase de iarnă, în ciuda gerurilor cumplite din Sankt Petersburg.^9^ Această fidelitate cromatică era o mărturie continuă a legământului său de dragoste și jertfă.' || '\n' ||
    '- **Sărăcia Radicală:** Refuza banii, acceptând doar monede mici („copeici cu regele călare") pe care le dăruia imediat altor săraci. Nu avea adăpost, petrecându-și nopțile în câmp deschis, în rugăciune, făcând mătănii în zăpadă.^10^' || '\n' ||
    '- **Umilința:** Accepta batjocura copiilor și a celor neînțelegători fără a se mânia, considerând insultele ca pe un medicament pentru suflet.^11^' || '\n\n' ||
    '### 2.4. Clarviziunea și Rolul Profetic în Societate' || '\n\n' ||
    'Sub masca vorbirii neinteligibile, Xenia oferea avertismente și profeții care se împlineau cu exactitate, funcționând ca o conștiință vie a orașului.' || '\n\n' ||
    '- **Moartea Împărătesei:** În 1761, Xenia a alergat pe străzi strigând „Coaceți clătite! Toată Rusia coace clătite!", o referire la tradiția rusă de a oferi clătite (blini) la înmormântări. La scurt timp, Împărăteasa Elisabeta Petrovna a murit.^6^' || '\n' ||
    '- **Cazul Țarului Ivan al VI-lea:** A prezis moartea violentă a acestuia, strigând despre „râuri de sânge".^12^' || '\n' ||
    '- **Intervenții în Viața Privată:** Sfânta avea o grijă deosebită pentru destinele familiilor. Un episod celebru este cel al familiei Golubev. Xenia i-a spus unei fete de 17 ani: „Tu stai aici și faci cafea, iar soțul tău își îngroapă soția la Ohta! Fugi repede!". Fata, ascultând-o, a alergat la cimitir, unde a întâlnit un tânăr doctor care tocmai își îngropase soția și leșinase de durere. Cei doi s-au căsătorit ulterior, trăind o viață fericită.^9^' || '\n\n' ||
    '## Partea III: Geografia Venerării și Cultul în România' || '\n\n' ||
    'Venerarea Sfintei Xenia în România a cunoscut o explozie după căderea comunismului, fiind facilitată de traducerea vieții sale și de aducerea de relicve. Credincioșii români au rezonat profund cu modelul ei de jertfă pentru familie.' || '\n\n' ||
    '### 3.1. Mănăstirea „Sfântul Ioan Rusul" -- Centrul Național de Pelerinaj' || '\n\n' ||
    'Situată în comuna Slobozia, județul Giurgiu, această mănăstire a devenit principalul centru de cult dedicat Sfintei Xenia în România. Mănăstirea a fost înființată în 2008, pe ruinele unei foste unități militare a Poliției de Frontieră.^15^' || '\n\n' ||
    '- **Hramul și Ocrotirea:** Sfânta Xenia este cinstită ca a doua ocrotitoare (alături de Sfântul Ioan Rusul), fiind considerată **ocrotitoare a familiei**.^15^' || '\n' ||
    '- **Festivități Liturgice:** Pe 24 ianuarie, mii de pelerini participă la Sfânta Liturghie arhierească.^15^' || '\n\n' ||
    '### 3.2. Prezența Moaștelor în București și Alte Localități' || '\n\n' ||
    '- **Biserica Mihai Vodă:** Păstrează racle cu sfinți, inclusiv Sf. Xenia.^8^' || '\n' ||
    '- **Biserica Sfântul Nicolae -- Rusă (a Studenților):** Păstrează o părticică din moaștele sfintei.^8^' || '\n' ||
    '- **Biserica din Comana-Herești (Giurgiu):** Și-a asumat hramul Sfinților Ioan Rusul și Xenia.^17^' || '\n' ||
    '- **Schitului Sihăstria Putnei (Suceava):** A dezvoltat o tradiție liturgică bogată legată de Sfânta Xenia.^3^' || '\n\n' ||
    '### 3.3. Practici Devoționale Specifice în România' || '\n\n' ||
    'În România, Sfânta Xenia este supranumită „grabnic ajutătoare" pentru: **găsirea unui loc de muncă**, **căsătorie** și **vindecarea de vicii** (în special alcoolismul).^1, 20^' || '\n\n' ||
    '## Partea IV: Cultul și Tradițiile în Republica Moldova' || '\n\n' ||
    '### 4.1. Mănăstirea Hîncu și Confuzia „Panaghia Xenia"' || '\n\n' ||
    'Mănăstirea Hîncu este un punct nodal pentru pelerinii care o caută pe Sfânta Xenia. Deși „Panaghia Xenia" este o icoană a Maicii Domnului din Grecia ^21^, în evlavia populară locală cinstirea acesteia se împletește cu venerarea sfintei ruse, pelerinii rugându-se pentru izbăvirea de „întristare" și boli.^23^' || '\n\n' ||
    '### 4.2. Chișinău -- Icoane și Liturghie' || '\n\n' ||
    '- **Biserica „Sfântul Dumitru":** Deține o icoană mare a Sfintei Xenia în pronaos.^25^' || '\n' ||
    '- **Catedrala Mitropolitană „Nașterea Domnului":** Găzduiește periodic relicve aduse, intensificând rugăciunile către Sfânta Xenia.^26^' || '\n\n' ||
    '## Partea V: Fenomenul Scrisorilor către Sfânta Xenia' || '\n\n' ||
    '### 5.1. Mecanismul Ritual' || '\n\n' ||
    'Credincioșii lasă bilețele scrise cu cererile lor la mormântul sfintei din Sankt Petersburg. Logica acestui gest este una a intimității: Xenia este o „bunică" sau o „mamă" căreia îi poți scrie detaliat necazul tău.^28^' || '\n\n' ||
    '### 5.2. Digitalizarea Cultului' || '\n\n' ||
    'Există site-uri web (stxenia.org, doxologia.ro) unde credincioșii pot trimite „scrisori online" către Sfânta Xenia, care sunt uneori duse fizic la mormânt.^29, 30^' || '\n\n' ||
    '## Partea VI: Analiză Liturgică și Imnografică Comparată' || '\n\n' ||
    '### 6.1. Acatistul Sfintei Xenia de Sankt Petersburg' || '\n\n' ||
    'Acest text pune accent pe paradoxul nebuniei. Termenul „nebunia părută" este crucial: sfânta nu era bolnavă psihic, ci simula nebunia ca asceză.^33^' || '\n' ||
    '- **Troparul (Glas 4/7):** „Iubind sărăcia lui Hristos, acum te îndulcești de ospățul cel veșnic...".^34^' || '\n\n' ||
    '## Partea VII: Iconografie -- Distincții Vizuale Esențiale' || '\n\n' ||
    '### 7.1. Sfânta Xenia de Sankt Petersburg' || '\n\n' ||
    '- **Vestimentație:** Hainele civile (fustă roșie, vestă verde), basma simplă.^1^' || '\n' ||
    '- **Fundal:** Biserica din cimitirul Smolensk sau peisaj urban de iarnă.' || '\n' ||
    '- **Atribute:** Toiag de pelerin sau rozariu (mătănii).' || '\n' ||
    '- **Vârstă:** Femeie în vârstă, cu părul alb.' || '\n\n' ||
    '## Concluzii și Sinteză' || '\n\n' ||
    'Sfânta Xenia de Sankt Petersburg ne învață calea **confruntării** profetice și a sfințirii cetății prin suferință asumată. Popularitatea sa răspunde nevoii de sfințire a eșecului și a suferinței în societatea modernă. Xenia oferă demnitate celor marginalizați și speranță familiilor în criză.' || '\n\n' ||
    '#### Works cited' || '\n\n' ||
    '1. Xenia of Saint Petersburg - Wikipedia, accessed January 20, 2026, [[https://en.wikipedia.org/wiki/Xenia_of_Saint_Petersburg]{.underline}](https://en.wikipedia.org/wiki/Xenia_of_Saint_Petersburg)' || '\n' ||
    '2. Viața Sfintei Cuvioase Xenia din Roma - Doxologia, accessed January 20, 2026, [[https://doxologia.ro/viata-sfintei-cuvioase-xenia-din-roma]{.underline}](https://doxologia.ro/viata-sfintei-cuvioase-xenia-din-roma)' || '\n' ||
    '3. SLUJBA SFINTEI FERICITEI SANKT PETERBURG, accessed January 20, 2026, [[https://www.sihastriaputnei.ro/sites/default/files/attachments/2024/01/01.24_slujba_cuv._xenia.pdf]{.underline}](https://www.sihastriaputnei.ro/sites/default/files/attachments/2024/01/01.24_slujba_cuv._xenia.pdf)' || '\n' ||
    '4. Cuvioasa Xenia din Petersburg, cinstită la Mănăstirea „Sfântul Ioan Rusul" - Ziarul Lumina, accessed January 20, 2026, [[https://ziarullumina.ro/actualitate-religioasa/stiri/cuvioasa-xenia-din-petersburg-cinstita-la-manastirea-sfantul-ioan-rusul-177891.html]{.underline}](https://ziarullumina.ro/actualitate-religioasa/stiri/cuvioasa-xenia-din-petersburg-cinstita-la-manastirea-sfantul-ioan-rusul-177891.html)' || '\n' ||
    '5. Procesiune cu sfinte moaște și sfințire a două troițe la Mănăstirea Hîncu - Altarul Credinței, accessed January 20, 2026, [[https://altarulcredintei.md/procesiune-cu-sfinte-moaste-si-sfintire-a-doua-troite-la-manastirea-hincu/]{.underline}](https://altarulcredintei.md/procesiune-cu-sfinte-moaste-si-sfintire-a-doua-troite-la-manastirea-hincu/)' || '\n' ||
    '6. Xenia din St. Petersburg - OrthodoxWiki, accessed January 20, 2026, [[https://ro.orthodoxwiki.org/index.php?title=Xenia_din_St._Petersburg&mobileaction=toggle_view_desktop]{.underline}](https://ro.orthodoxwiki.org/index.php?title=Xenia_din_St._Petersburg&mobileaction=toggle_view_desktop)' || '\n' ||
    '7. Sf.cuv.Xenia -Evsevia ocrotitoare tuturor femeilor icoana rara - MG Argenti, accessed January 20, 2026, [[http://www.mgargenti.ro/icoane-ortodoxe-sfinti-nume-femei/sf-cuv-xenia-evsevia-ocrotitoare-tuturor-femeilor-icoana-ra--286343]{.underline}](http://www.mgargenti.ro/icoane-ortodoxe-sfinti-nume-femei/sf-cuv-xenia-evsevia-ocrotitoare-tuturor-femeilor-icoana-ra--286343)' || '\n' ||
    '8. Darul Sfintei Xenia de Sankt Petersburg CrestinOrtodox.ro, accessed January 20, 2026, [[https://www.crestinortodox.ro/reportaj/darul-sfintei-xenia-sankt-petersburg-146490.html]{.underline}](https://www.crestinortodox.ro/reportaj/darul-sfintei-xenia-sankt-petersburg-146490.html)' || '\n' ||
    '9. Sfânta Cuvioasă Xenia, cea nebună pentru Hristos și făcătoarea de minuni din Sankt Petersburg în Rusia (XVIII). - Calendox, accessed January 20, 2026, [[https://calendar.ortodox.md/calendar/entry/RU/1323]{.underline}](https://calendar.ortodox.md/calendar/entry/RU/1323)' || '\n' ||
    '10. Viața Sfintei Xenia din Sankt Petersburg - Doxologia, accessed January 20, 2026, [[https://doxologia.ro/viata-sfintei-xenia-din-sankt-petersburg]{.underline}](https://doxologia.ro/viata-sfintei-xenia-din-sankt-petersburg)' || '\n' ||
    '11. The Life of St. Xenia of St. Petersburg - YouTube, accessed January 20, 2026, [[https://www.youtube.com/watch?v=3Wwe0Xa5j_g]{.underline}](https://www.youtube.com/watch?v=3Wwe0Xa5j_g)' || '\n' ||
    '12. St. Xenia of St. Petersburg, Russia | American Carpatho-Russian Orthodox Diocese of North America, accessed January 20, 2026, [[https://www.acrod.org/orthodox-christianity/articles/saints/st-xenia-petersburg]{.underline}](https://www.acrod.org/orthodox-christianity/articles/saints/st-xenia-petersburg)' || '\n' ||
    '13. Icon of St. Xenia the Fool-for-Christ - 21st c. - English - (1XE14), accessed January 20, 2026, [[https://uncutmountainsupply.com/icons/of-saints/by-name/v-z/icon-of-st-xenia-the-fool-for-christ-21st-c-english-1xe14/]{.underline}](https://uncutmountainsupply.com/icons/of-saints/by-name/v-z/icon-of-st-xenia-the-fool-for-christ-21st-c-english-1xe14/)' || '\n' ||
    '14. Xenia din St. Petersburg - OrthodoxWiki, accessed January 20, 2026, [[https://ro.orthodoxwiki.org/Xenia_din_St._Petersburg]{.underline}](https://ro.orthodoxwiki.org/Xenia_din_St._Petersburg)' || '\n' ||
    '15. Sf. Xenia a fost cinstită la Mănăstirea „Sf. Ioan Rusul" din Episcopia Giurgiului - Basilica, accessed January 20, 2026, [[https://basilica.ro/sf-xenia-a-fost-cinstita-la-manastirea-sf-ioan-rusul-din-episcopia-giurgiului/]{.underline}](https://basilica.ro/sf-xenia-a-fost-cinstita-la-manastirea-sf-ioan-rusul-din-episcopia-giurgiului/)' || '\n' ||
    '16. Sf. Xenia din Sankt Petersburg sărbatorită la mănăstirea Sf. Ioan Rusul - YouTube, accessed January 20, 2026, [[https://www.youtube.com/watch?v=sQcfAR357vI]{.underline}](https://www.youtube.com/watch?v=sQcfAR357vI)' || '\n' ||
    '17. Moastele Sfantului Ioan Rusul in Romania, accessed January 20, 2026, [[https://www.eviasieghina.ro/moastele-sfantului-ioan-rusul-in-romania/]{.underline}](https://www.eviasieghina.ro/moastele-sfantului-ioan-rusul-in-romania/)' || '\n' ||
    '18. 24 Ianuarie Si 11 Septembrie Slujba, Acatistul Si Paraclisul Sfintei Xenia de Petersburg, accessed January 20, 2026, [[https://ro.scribd.com/document/468157911/24-ianuarie-si-11-septembrie-Slujba-Acatistul-si-Paraclisul-Sfintei-Xenia-de-Petersburg]{.underline}](https://ro.scribd.com/document/468157911/24-ianuarie-si-11-septembrie-Slujba-Acatistul-si-Paraclisul-Sfintei-Xenia-de-Petersburg)' || '\n' ||
    '19. Sfânta Cuvioasă Xenia din Sankt Petersburg - Minuni - Doxologia, accessed January 20, 2026, [[https://doxologia.ro/sfant-sarbatoare/118847/minuni/c/8223]{.underline}](https://doxologia.ro/sfant-sarbatoare/118847/minuni/c/8223)' || '\n' ||
    '20. Icoana cu Sfânta Xenia din Sankt Petersburg - Reproducere, accessed January 20, 2026, [[https://atelier-de-icoane.ro/icoana-cu-sfanta-xenia-din-sankt-petersburg-reproducere-1005008]{.underline}](https://atelier-de-icoane.ro/icoana-cu-sfanta-xenia-din-sankt-petersburg-reproducere-1005008)' || '\n' ||
    '21. „Panaghia Xenia": icoana Maicii Domnului care a călătorit pe mare, într-un cufăr, accessed January 20, 2026, [[https://blog.bizanticons.ro/2024/08/14/panaghia-xenia-icoana-maicii-domnului-care-a-calatorit-pe-mare-intr-un-cufar/]{.underline}](https://blog.bizanticons.ro/2024/08/14/panaghia-xenia-icoana-maicii-domnului-care-a-calatorit-pe-mare-intr-un-cufar/)' || '\n' ||
    '22. Kato Xenia, ridicată prin voia Maicii Domnului - Basilica.ro, accessed January 20, 2026, [[https://basilica.ro/kato-xenia-ridicata-prin-voia-maicii-domnului/]{.underline}](https://basilica.ro/kato-xenia-ridicata-prin-voia-maicii-domnului/)' || '\n' ||
    '23. Prăznuirea icoanei făcătoare de minuni ,,Potolește întristările noastre" la mănăstirea Hîncu, accessed January 20, 2026, [[https://ortodox.md/praznuirea-icoanei-facatoare-de-minuni-potoleste-intristarile-noastre-la-manastirea-hincu/?mode=list]{.underline}](https://ortodox.md/praznuirea-icoanei-facatoare-de-minuni-potoleste-intristarile-noastre-la-manastirea-hincu/?mode=list)' || '\n' ||
    '24. Prăznuirea Icoanei făcătoare de minuni ,,Potolește Întristarea mea" la mănăstirea ,,Cuvioasa Parascheva" Hîncu - Altarul Credinței, accessed January 20, 2026, [[https://altarulcredintei.md/praznuirea-icoanei-facatoare-de-minuni-potoleste-intristarea-mea-la-manastirea-cuvioasa-parascheva-hincu/]{.underline}](https://altarulcredintei.md/praznuirea-icoanei-facatoare-de-minuni-potoleste-intristarea-mea-la-manastirea-cuvioasa-parascheva-hincu/)' || '\n' ||
    '25. File:Icoană în partea sudică a pronaosului din Biserica Sf. Dumitru din Chișinău.jpg, accessed January 20, 2026, [[https://commons.wikimedia.org/wiki/File:Icoan%C4%83_%C3%AEn_partea_sudic%C4%83_a_pronaosului_din_Biserica_Sf._Dumitru_din_Chi%C8%99in%C4%83u.jpg]{.underline}](https://commons.wikimedia.org/wiki/File:Icoan%C4%83_%C3%AEn_partea_sudic%C4%83_a_pronaosului_din_Biserica_Sf._Dumitru_din_Chi%C8%99in%C4%83u.jpg)' || '\n' ||
    '26. La Catedrala Mitropolitană din Chişinău au fost aduse spre închinare icoana şi părticele din moaştele Sfintei Matrona de la Moscova - Altarul Credinței, accessed January 20, 2026, [[https://altarulcredintei.md/la-catedrala-mitropolitana-din-chisinau-au-fost-aduse-spre-inchinare-icoana-si-particele-din-moastele-sfintei-matrona-de-la-moscova/]{.underline}](https://altarulcredintei.md/la-catedrala-mitropolitana-din-chisinau-au-fost-aduse-spre-inchinare-icoana-si-particele-din-moastele-sfintei-matrona-de-la-moscova/)' || '\n' ||
    '27. La Catedrala mitropolitană din Chişinău vor fi aduse spre închinare icoana făcătoare de minuni a Maicii Domnului din Ierusalim (Ierusalimitissa) şi racla cu moaştele Sfântului Ierarh Nectarie de Eghina - Mitropolia Moldovei, accessed January 20, 2026, [[https://mitropolia.md/la-catedrala-mitropolitana-din-chisinau-vor-fi-aduse-spre-inchinare-icoana-facatoare-de-minuni-a-maicii-domnului-din-ierusalim-ierusalimitissa-si-racla-cu-moastele-sfantului-ierarh-nectarie-de-eghin/]{.underline}](https://mitropolia.md/la-catedrala-mitropolitana-din-chisinau-vor-fi-aduse-spre-inchinare-icoana-facatoare-de-minuni-a-maicii-domnului-din-ierusalim-ierusalimitissa-si-racla-cu-moastele-sfantului-ierarh-nectarie-de-eghin/)' || '\n' ||
    '28. Minunile Sfintei Xenia din Petersburg - Ziarul Lumina, accessed January 20, 2026, [[https://ziarullumina.ro/actualitate-religioasa/documentar/minunile-sfintei-xenia-din-petersburg-203292.html]{.underline}](https://ziarullumina.ro/actualitate-religioasa/documentar/minunile-sfintei-xenia-din-petersburg-203292.html)' || '\n' ||
    '29. Mt. Zion Xenia -- Aplicații pe Google Play, accessed January 20, 2026, [[https://play.google.com/store/apps/details?id=com.subsplashconsulting.s_T73XFP&hl=ro]{.underline}](https://play.google.com/store/apps/details?id=com.subsplashconsulting.s_T73XFP&hl=ro)' || '\n' ||
    '30. St. Xenia of St. Petersburg, accessed January 20, 2026, [[https://www.stxenia.org/stxenia]{.underline}](https://www.stxenia.org/stxenia)' || '\n' ||
    '31. Submitting Prayer Request to St. Xenia of Petersburg : r/OrthodoxChristianity - Reddit, accessed January 20, 2026, [[https://www.reddit.com/r/OrthodoxChristianity/comments/o5soc9/submitting_prayer_request_to_st_xenia_of/]{.underline}](https://www.reddit.com/r/OrthodoxChristianity/comments/o5soc9/submitting_prayer_request_to_st_xenia_of/)' || '\n' ||
    '32. Sfânta Cuvioasă Xenia din Sankt Petersburg - Doxologia, accessed January 20, 2026, [[https://doxologia.ro/sfanta-cuvioasa-xenia-din-sankt-petersburg]{.underline}](https://doxologia.ro/sfanta-cuvioasa-xenia-din-sankt-petersburg)' || '\n' ||
    '33. Acatistul Sfintei Xenia CrestinOrtodox.ro, accessed January 20, 2026, [[https://www.crestinortodox.ro/acatiste/acatistul-sfintei-xenia-67103.html]{.underline}](https://www.crestinortodox.ro/acatiste/acatistul-sfintei-xenia-67103.html)' || '\n' ||
    '34. Acatistul Sfintei Xenia din Sankt Petersburg - Doxologia, accessed January 20, 2026, [[https://doxologia.ro/acatistul-sfintei-xenia-din-sankt-petersburg]{.underline}](https://doxologia.ro/acatistul-sfintei-xenia-din-sankt-petersburg)' || '\n' ||
    '35. Acatistul SF Xenia | PDF - Scribd, accessed January 20, 2026, [[https://ro.scribd.com/doc/315872859/Acatistul-Sf-Xenia]{.underline}](https://ro.scribd.com/doc/315872859/Acatistul-Sf-Xenia)' || '\n' ||
    '36. Troparul Sfintei Cuvioase Xenia din Sankt Petersburg - Doxologia, accessed January 20, 2026, [[https://doxologia.ro/troparul-sfintei-cuvioase-xenia-din-sankt-petersburg]{.underline}](https://doxologia.ro/troparul-sfintei-cuvioase-xenia-din-sankt-petersburg)' || '\n' ||
    '37. Acatistul Sfintei Xenia CrestinOrtodox.ro, accessed January 20, 2026, [[https://www.crestinortodox.ro/acatiste/acatistul-sfintei-xenia-136342.html]{.underline}](https://www.crestinortodox.ro/acatiste/acatistul-sfintei-xenia-136342.html)' || '\n' ||
    '38. Sfânta Cuvioasă Xenia din Roma, diaconița (în lume - Eusebia), dimpreună cu 2 slujitoare ale sale (V). - Calendox, accessed January 20, 2026, [[https://calendar.ortodox.md/calendar/entry/RO/138]{.underline}](https://calendar.ortodox.md/calendar/entry/RO/138)' || '\n' ||
    '39. Troparul Sfintei Cuvioase Xenia - Doxologia, accessed January 20, 2026, [[https://doxologia.ro/troparul-sfintei-cuvioase-xenia]{.underline}](https://doxologia.ro/troparul-sfintei-cuvioase-xenia)' || '\n' ||
    '40. Icoana Sfanta Cuvioasa Xenia -Sarbatori crestin- ortodoxe - Divinart, accessed January 20, 2026, [[https://divinart.ro/icoana-sfanta-cuvioasa-xenia/]{.underline}](https://divinart.ro/icoana-sfanta-cuvioasa-xenia/)' || '\n' ||
    '41. Saint Xenia of Saint Petersburg Icon - S271 - Legacy Icons, accessed January 20, 2026, [[https://legacyicons.com/saint-xenia-of-saint-petersburg-icon-s271/]{.underline}](https://legacyicons.com/saint-xenia-of-saint-petersburg-icon-s271/)'
);