INSERT INTO core_schema.saint_lives (name_ro, life_description_ro)
VALUES (
    'Sfântul Pantelimon',
    '# Hagiografie, Cult Terapeutic și Etnologie Sacră: O Monografie Exhaustivă a Vieții, Minunilor și Moștenirii Sfântului Mare Mucenic Pantelimon' || '\n\n' ||
    '## Introducere: Arhetipul Vindecătorului în Conștiința Eclesială' || '\n\n' ||
    'În istoria bimilenară a creștinismului, figura Sfântului Mare Mucenic și Tămăduitor Pantelimon se proiectează cu o pregnanță excepțională, transcendând simpla cinstire liturgică pentru a deveni un fenomen spiritual complex, care unifică teologia suferinței, practica medicală și tradiția populară agrară. Prăznuit anual la data de 27 iulie, Sfântul Pantelimon, supranumit „Doctorul fără de arginți" (*Anargyroi*), reprezintă modelul absolut al medicului creștin care a reușit să armonizeze știința hipocratică cu harismatica vindecării divine, refuzând comercializarea actului terapeutic și transformând spitalul în spațiu al filantropiei și mărturisirii.^1^' || '\n\n' ||
    'Prezenta cercetare își propune o analiză exhaustivă a fenomenului „Pantelimon", investigând straturile istorice ale persecuției dioclețiene din Nicomidia, dinamica convertirii unui tânăr intelectual al antichității târzii, și supraviețuirea cultului său prin moaștele răspândite în întreaga oikumene creștină. De la marile lavre athonite până la spitalele de urgență din România contemporană, și de la textele imnografice bizantine până la mitul folcloric al lui „Pintilie Călătorul", raportul de față va deconstrui și reconstrui imaginea sfântului, bazându-se pe surse hagiografice primare, erminii iconografice și studii etnografice.^4^' || '\n\n' ||
    '## I. Contextul Istoric și Genealogia Spirituală în Nicomidia' || '\n\n' ||
    '### 1.1. Nicomidia: Epicentrul Persecuției și al Rezistenței' || '\n\n' ||
    'Pentru a înțelege dimensiunea sacrificiului Sfântului Pantelimon, este imperativă plasarea sa în contextul geopolitic al Nicomidiei (actualul Izmit, Turcia) de la sfârșitul secolului al III-lea și începutul secolului al IV-lea. Capitală a părții de răsărit a Imperiului Roman sub tetrarhia lui Dioclețian, cetatea era un focar de cultură elenistică, dar și centrul administrativ al „Marii Persecuții" (303-313 d.Hr.). Într-un mediu saturat de temple păgâne și de o curte imperială ostilă creștinismului (condusă de Maximian Galerius în regiune), adeziunea la Hristos nu era o opțiune privată, ci un act de trădare statală.^7^' || '\n\n' ||
    '### 1.2. Dualitatea Familială și Onomastica Profetică' || '\n\n' ||
    'Sfântul s-a născut în jurul anului 275 d.Hr. (unele surse indică 284), într-o familie care reflecta însăși tensiunea religioasă a imperiului.' || '\n\n' ||
    '- **Eustorgiu (Tatăl):** Senator influent și păgân devotat, Eustorgiu întruchipa ordinea veche, dorind pentru fiul său o carieră strălucită în administrația imperială sau la curte. El a facilitat accesul tânărului la educația clasică (gramatică, retorică, filozofie) și la cultul idolilor.^7^' || '\n' ||
    '- **Euvula (Mama):** Creștină în ascuns, Euvula (pomenită ca sfântă la 30 martie) reprezintă influența maternă decisivă. Deși a murit când Pantelimon era copil, ea a reușit să planteze semințele credinței, care aveau să germineze mai târziu sub influența preotului Ermolae. Pierderea mamei a marcat prima traumă a sfântului, împingându-l inițial spre conformismul patern.^7^' || '\n\n' ||
    'Numele primit la naștere, **Pantoleon**, se traduce prin „cel în toate puternic ca un leu" sau „cu totul leu". Această onomastică sugerează forță, dominanță și ferocitate, atribute apreciate în societatea romană militarizată. Metamorfoza numelui în **Pantelimon** („cel cu totul milostiv"), survenită odată cu botezul sau cu recunoașterea sfințeniei sale, marchează o inversiune teologică fundamentală: puterea nu mai rezidă în forța brută a leului, ci în capacitatea infinită de a manifesta mila divină (eleos).^2^' || '\n\n' ||
    '## II. Formarea Intelectuală și „Metanoia": De la Hipocrate la Hristos' || '\n\n' ||
    '### 2.1. Ucenicia la Eufrosin și Ascensiunea la Curte' || '\n\n' ||
    'Dovedind capacități intelectuale superioare, tânărul Pantoleon a fost încredințat spre instruire lui **Eufrosin**, cel mai renumit medic al timpului, care servea ca arhiatru (medic principal) la curtea împăratului Maximian. Sub tutela acestuia, Pantoleon a deprins tainele medicinei galenice și hipocratice, excelând în diagnostic și tratament farmacologic.^7^' || '\n\n' ||
    'Frumusețea sa fizică, manierele aristocratice și competența profesională l-au propulsat rapid în atenția împăratului, care intenționa să-l numească medic personal. Această perspectivă a unei cariere fulminante subliniază magnitudinea renunțării sale ulterioare; Pantoleon nu era un marginal, ci un membru al elitei intelectuale și sociale, având totul de pierdut în termeni lumești prin convertire.^2^' || '\n\n' ||
    '### 2.2. Pedagogia Preotului Ermolae' || '\n\n' ||
    'Catalizatorul convertirii a fost întâlnirea cu bătrânul preot **Ermolae** (pomenit împreună cu mucenicii Ermip și Ermocrat), care supraviețuise masacrul celor 20.000 de mucenici din Nicomidia (303 d.Hr.) și trăia ascuns. Ermolae, observându-l pe tânărul medic trecând zilnic prin fața casei sale, a inițiat un dialog maieutic, contrastând limitările medicinei umane cu omnipotencia „Doctorului sufletelor și trupurilor".^7^' || '\n\n' ||
    'Argumentul lui Ermolae a fost unul existențial: „Lui Asclipios și Galen le cunoști limitele; ei nu pot vindeca moartea. Hristos însă dăruiește viață veșnică". Această cateheză a reactivat memoria învățăturilor mamei sale, Euvula, creând o criză de conștiință în tânărul medic.^9^' || '\n\n' ||
    '### 2.3. Minunea Viperei și Botezul' || '\n\n' ||
    'Momentul trecerii de la teorie la credința vie a fost unul dramatic. Întorcându-se de la Ermolae, Pantoleon a găsit pe drum un copil mort, mușcat de o viperă, reptila fiind încă prezentă lângă trup. Într-un gest de ultimă instanță, el a invocat numele lui Hristos ca test suprem de adevăr: „Dacă Tu ești Dumnezeu, să învieze copilul și să moară vipera".^9^' || '\n\n' ||
    'Învierea instantanee a copilului și moartea reptilei au funcționat ca o teofanie personală. Pantoleon s-a întors la Ermolae, a cerut botezul și a rămas șapte zile lângă bătrânul preot pentru a aprofunda tainele liturghiei și ale dogmei. Botezul a marcat nu doar schimbarea numelui în Pantelimon, ci și schimbarea paradigmei medicale: vindecarea nu mai era rezultatul exclusiv al *tehnè*-ului (artei) medicale, ci o sinergie între tratament și rugăciune.^2^' || '\n\n' ||
    '## III. Activitatea Terapeutică și Conflictul Profesional' || '\n\n' ||
    '### 3.1. Vindecarea Orbului și Convertirea Tatălui' || '\n\n' ||
    'Un moment crucial în hagiografie este vindecarea unui orb din naștere, pe care nici Eufrosin, nici alți medici nu reușiseră să-l ajute. Pantelimon l-a vindecat invocând numele Sfintei Treimi, chiar în fața tatălui său, Eustorgiu. Impactul a fost dublu: orbul și-a recăpătat vederea fizică și spirituală (devenind creștin), iar Eustorgiu a abandonat idolatria, sfărâmând statuile zeilor din casa sa și primind botezul înainte de a muri.^8^' || '\n\n' ||
    '### 3.2. Invidia Breslei și Denunțul' || '\n\n' ||
    'Succesul lui Pantelimon, care începuse să trateze gratuit („fără de arginți"), a destabilizat economia medicală a Nicomidiei. Ceilalți medici, pierzându-și pacienții și veniturile, au recurs la arma politică: denunțul. Ei l-au acuzat pe Pantelimon în fața lui Maximian nu doar de prozelitism creștin, ci și de insultă la adresa zeului Asclipios și de subminarea autorității imperiale prin refuzul cultului oficial.^2^ Denunțul a fost catalizat de vindecarea orbului, care, interogat fiind, l-a mărturisit pe Hristos și pe medicul Pantelimon, fiind imediat decapitat la ordinul împăratului, devenind astfel un „înaintemergător" în martiriu pentru vindecătorul său.' || '\n\n' ||
    '## IV. Fenomenologia Martiriului: Suferință, Miracol și Moarte' || '\n\n' ||
    'Procesul și execuția Sfântului Pantelimon (cca. 303-305 d.Hr.) sunt descrise în actele martirice (*Passio*) cu detalii care subliniază intervenția supranaturală.' || '\n\n' ||
    '### 4.1. Interogatoriul și Sfidarea Idolilor' || '\n\n' ||
    'Adus în fața lui Maximian, Pantelimon a refuzat apostazia. Pentru a dovedi neputința idolilor, a propus un test public: un paralitic a fost adus în fața preoților păgâni, care s-au rugat zadarnic zeilor lor. Pantelimon, prin simpla rugăciune, l-a ridicat pe bolnav, provocând furia împăratului și admirația mulțimii.^1^' || '\n\n' ||
    '### 4.2. Ciclul Torturilor și Teofaniile' || '\n\n' ||
    'Hagiografia consemnează o serie de torturi (ciclul chinurilor), fiecare fiind urmată de o minune care anula efectul distructiv asupra trupului sfântului:' || '\n\n' ||
    '1.  **Sfâșierea:** Spânzurat pe lemn și sfâșiat cu gheare de fier, rănile i-au fost vindecate miraculos prin apariția lui Hristos sub chipul preotului Ermolae.^2^' || '\n' ||
    '2.  **Plumbul Topit:** Aruncat într-un cazan cu plumb clocotit, focul s-a stins, iar metalul s-a răcit la atingerea trupului său.^1^' || '\n' ||
    '3.  **Marea:** Aruncat în mare cu o piatră de gât, piatra a devenit ușoară ca un dop de plută, iar sfântul a pășit pe valuri.^1^' || '\n' ||
    '4.  **Roata cu Țepi:** Legat pe o roată prevăzută cu lame ascuțite și prăvălită de la înălțime, dispozitivul s-a dezintegrat, rănind călăii, în timp ce mucenicul a rămas nevătămat.' || '\n\n' ||
    '### 4.3. Execuția și Semnele Finale' || '\n\n' ||
    'În cele din urmă, a fost condamnat la decapitare. Dus sub un măslin uscat în afara cetății, călăii nu au putut executa sentința (săbiile se îndoiau ca ceara) până când sfântul nu și-a terminat rugăciunea și nu le-a dat permisiunea.' || '\n\n' ||
    'În momentul tăierii capului, s-au produs două fenomene supranaturale majore:' || '\n\n' ||
    '- **Lapte în loc de sânge:** Din gâtul mucenicului a țâșnit lapte, simbol al purității și al hranei duhovnicești pe care Biserica o primește prin sfinți.^1^' || '\n' ||
    '- **Înverzirea Măslinului:** Măslinul uscat a înverzit instantaneu și s-a umplut de roade, devenind un martor vegetal al învierii.^1^' || '\n\n' ||
    'Trupul său a fost aruncat în foc, dar a rămas neatins de flăcări, fiind recuperat de creștini și îngropat pe moșia scolasticului Adamantie. Autorii biografiei sale au fost chiar ucenicii săi care au asistat la martiriu: **Lavrentie, Vasoi și Provian**.^1^' || '\n\n' ||
    '## V. Geografia Sacră: Traseul și Localizarea Sfintelor Moaște' || '\n\n' ||
    'Moaștele Sfântului Pantelimon sunt printre cele mai răspândite în lumea ortodoxă, fiind fragmentate pentru a binecuvânta nenumărate lăcașuri. Analiza distribuției lor relevă o rețea complexă de pelerinaj.' || '\n\n' ||
    '### 5.1. Muntele Athos și Moștenirea Athonită' || '\n\n' ||
    'Capul Sfântului Pantelimon, considerat cel mai prețios odor, se păstrează la **Mănăstirea Rusikon (Sfântul Pantelimon)** din Muntele Athos, fiind sursa principală a mirului și a vindecărilor pentru pelerini. Alte fragmente importante se află la Mănăstirea Sfântul Pavel și la alte așezăminte athonite.^13^' || '\n\n' ||
    '### 5.2. Moaștele în România: O Prezență Densă' || '\n\n' ||
    '| **Locație (Oraș/Regiune)** | **Lăcaș de Cult** | **Istoric și Detalii ale Moaștelor** | **Sursa** |' || '\n' ||
    '| :--- | :--- | :--- | :--- |' || '\n' ||
    '| **București** | **Mănăstirea Plumbuita** | Ctitorie din sec. XVI. Deține fragmente de moaște alături de cele ale Sf. Gheorghe, Sf. Nicolae și Sf. Ioan cel Nou. | ^15^ |' || '\n' ||
    '| **București** | **Biserica „Sf. Pantelimon" - Foișorul de Foc** | Biserică istorică (atestată 1752). Hram dublu (Sf. Pantelimon și Sf. Parascheva). Moaștele sunt expuse permanent. | ^18^ |' || '\n' ||
    '| **București** | **Paraclisul Reședinței Patriarhale** | Păstrează moaștele de la fosta mănăstire Sf. Pantelimon (ctitoria lui Grigore Ghica al II-lea, azi demolată), aduse ocazional la procesiuni. | ^20^ |' || '\n' ||
    '| **București** | **Biserica „Sf. Gheorghe - Capra"** | Primește spre închinare moaștele de la Paraclisul Patriarhal cu ocazia hramului. | ^20^ |' || '\n' ||
    '| **Constanța** | **Catedrala Arhiepiscopală** | Deține moaște permanente. Pe 27 iulie are loc o procesiune majoră pe străzile orașului vechi, împreună cu moaștele Sfinților Epictet și Astion. | ^21^ |' || '\n' ||
    '| **Moinești** | **Spitalul Municipal de Urgență** | Biserica din incintă deține moaște aduse de la Mănăstirea Durău (Neamț). Istoric: Moaștele au venit de la Athos în Rusia, apoi la Mănăstirea Neamț, Durău și infine Moinești. | ^24^ |' || '\n' ||
    '| **Iași** | **Catedrala Metropolitană** | Eveniment istoric: În octombrie 2024, Capul Sfântului a fost adus de la Mănăstirea Sf. Pavel (Athos) pentru pelerinajul Sfintei Parascheva. | ^25^ |' || '\n\n' ||
    'Acest tabel demonstrează o „cartografie a vindecării" în România, unde moaștele sfântului sunt strategic plasate atât în centre istorice (București, Constanța), cât și în legătură directă cu instituțiile medicale (Moinești).' || '\n\n' ||
    '## VI. Sincretism și Etnografie: „Pintilie Călătorul"' || '\n\n' ||
    'În calendarul popular românesc, sărbătoarea de pe 27 iulie marchează un prag critic al anului agricol și meteorologic, personificat de **Pintilie Călătorul** (o adaptare fonetică a numelui Pantelimon).' || '\n\n' ||
    '### 6.1. Semnificația Agrară și Meteorologică' || '\n\n' ||
    'Tradiția populară consideră că în această zi „se călătorește vara", adică vara începe să cedeze locul toamnei. Semnele naturale asociate acestui prag sunt:' || '\n\n' ||
    '- **Răcirea apelor:** Se spune că „cerbul iese din râu" sau „piatra intră în apă", marcând momentul în care scăldatul devine periculos sau apa devine rece.' || '\n' ||
    '- **Migrația:** Începe pregătirea păsărilor călătoare (berze, cocostârci) pentru plecare.' || '\n' ||
    '- **Vegetația:** Frunza teiului se întoarce pe dos, semnalând doliul verii care trece.^4^' || '\n\n' ||
    '### 6.2. Tabu-uri și Superstiții' || '\n\n' ||
    'Pintilie este perceput uneori ca un frate mai mic al Sfântului Ilie (Pintilie = Sântilie cel Mic sau Șchiop), având putere asupra grindinei și focului.' || '\n\n' ||
    '- **Interdicția muncii:** Este strict interzis lucrul la câmp sau în gospodărie („nelucrare"). Se crede că cei care muncesc riscă trăsnete, grindină peste recolte sau boli („lovituri", „ceasuri negre").' || '\n' ||
    '- **Ocrotitorul Cojocarilor:** Meseriașii cojocari îl cinsteau în mod special, deoarece această dată anunța apropierea sezonului rece, când munca lor devenea vitală.^4^' || '\n' ||
    '- **Ritualuri alimentare:** Se mănâncă porumb fiert și dovleci, iar fructele (mere, pere) se împart de pomană pentru ca pomii să nu facă viermi anul următor.^28^' || '\n\n' ||
    'Deși aceste practici sunt superstiții tolerate de Biserică ca manifestări ale evlaviei populare, ele arată cum țăranul român a integrat funcția de tămăduitor a sfântului cu cea de protector al ciclurilor naturii.' || '\n\n' ||
    '## VII. Sfântul Pantelimon în Bioetică și Asistența Spitalicească' || '\n\n' ||
    'Legătura dintre Sfântul Pantelimon și medicina modernă din România este instituționalizată prin patronajul a numeroase spitale și prin prezența capelelor în incinta acestora.' || '\n\n' ||
    '### 7.1. Instituții Medicale sub Ocrotirea Sfântului' || '\n\n' ||
    '- **Spitalul Clinic de Urgență „Sf. Pantelimon" (București):** Unul dintre pilonii sistemului de urgență din capitală. Biserica din curtea spitalului (pr. Ștefan Oproiu) oferă asistență religioasă continuă din 1998, oficiind Sfântul Maslu săptămânal pentru pacienți.^30^' || '\n' ||
    '- **Spitalul de Psihiatrie Voila (Câmpina):** Biserica cu hramul Sf. Pantelimon deservește o categorie vulnerabilă de pacienți, subliniind rolul sfântului în vindecarea bolilor mintale și sufletești.^32^' || '\n' ||
    '- **Spitalul Municipal Moinești:** Aici, actul medical este împletit cu cel liturgic, biserica deținând moaște și organizând conferințe medicale internaționale sub egida sfântului.^24^' || '\n\n' ||
    '### 7.2. Rugăciunea Medicului' || '\n\n' ||
    'Există rugăciuni specifice ^33^ în care medicii cer sfântului nu doar succesul tratamentului, ci și păstrarea „conștiinței drepte", pentru a vedea în pacient „un semen" și nu un caz clinic, refuzând discriminarea și mercantilismul excesiv. Aceasta actualizează modelul „fără de arginți" într-o lume dominată de costurile sănătății.' || '\n\n' ||
    '## VIII. Analiză Liturgică și Imnografică' || '\n\n' ||
    '### 8.1. Acatistul: Structură și Teologie' || '\n\n' ||
    'Acatistul Sfântului Pantelimon ^34^ este structurat pe 13 condace și 13 icoase. Textul nu este doar narativ, ci profund teologic.' || '\n\n' ||
    '- **Condacul 1:** Introduce tema „Doctorului fără de arginți", cerând vindecare trupească și sufletească.' || '\n' ||
    '- **Icosul 1:** Laudă „judecata adâncă" a sfântului de a alege credința în detrimentul carierei păgâne.' || '\n' ||
    '- **Condacul 2:** Folosește metafora „trestiei neînfrânte" pentru a descrie rezistența sa psihologică în fața presiunii sociale și a idolatriei paterne.' || '\n\n' ||
    '### 8.2. Rugăciunea lui Eremei Schimnicul' || '\n\n' ||
    'O rugăciune deosebită, atribuită Episcopului Eremei Schimnicul ^38^, realizează o diagnoză spirituală a pacientului. Aceasta enumeră „bolile" morale care cauzează suferința: lenea, invidia, mândria, vorbirea de rău. Textul sugerează că vindecarea fizică fără cea morală este incompletă, poziționând boala ca un simptom al unei dezordini lăuntrice.' || '\n\n' ||
    '## IX. Iconografie: Erminia Bizantină' || '\n\n' ||
    'Conform **Erminiei lui Dionisie din Furna**, Sfântul Pantelimon este reprezentat distinct de alți sfinți ^5^:' || '\n\n' ||
    '- **Fizionomie:** Tânăr, fără barbă (imberb), cu părul ondulat, reflectând vârsta sa fragedă și puritatea.' || '\n' ||
    '- **Atribute:** Ține în mâna stângă o **cutie de medicamente** (sipet) și în dreapta o **linguriță** (pentru administrarea leacurilor) sau o pană de scris. Uneori ține o cruce, simbolul martiriului.' || '\n' ||
    '- **Vestimentație:** Poartă tunica de dedesubt și o mantie (hlamidă), adesea roșie, simbolizând sângele vărsat, dar și statutul său nobil.' || '\n\n' ||
    'Această reprezentare vizuală îl face imediat recognoscibil credincioșilor, cutia și lingurița devenind simboluri euharistice ale vindecării prin împărtășirea cu har.' || '\n\n' ||
    '## Sinteză și Concluzii' || '\n\n' ||
    'Studiul exhaustiv al vieții și cultului Sfântului Mare Mucenic Pantelimon relevă o figură care a reușit imposibila sinteză între știință și credință, între elita imperială și marginalii societății, între suferința atroce a martiriului și blândețea vindecării.' || '\n\n' ||
    '1.  **Dimensiunea Istorică:** Sfântul nu este o legendă eterică, ci un martir atestat istoric, victimă a persecuției sistematice din Nicomidia, a cărui moarte a zguduit conștiința contemporanilor săi.' || '\n' ||
    '2.  **Dimensiunea Terapeutică:** Prin refuzul plății și prin integrarea rugăciunii în actul medical, Pantelimon a fondat deontologia bioeticii creștine, rămânând patronul incontestabil al medicilor și farmaciștilor.' || '\n' ||
    '3.  **Dimensiunea Culturală:** În spațiul românesc, metamorfoza sa în „Pintilie Călătorul" demonstrează capacitatea creștinismului popular de a cosmiciza sfințenia, transformând data martiriului într-un reper astronomic și agrar vital pentru comunitatea rurală.' || '\n\n' ||
    'Astfel, Sfântul Pantelimon rămâne, la aproape două milenii de la martiriul său, o prezență vie și activă, ale cărui moaște continuă să adune pelerini, iar al cărui nume continuă să fie invocat în sălile de operație și în rugăciunile șoptite ale celor în suferință. El este, prin excelență, „Doctorul cel mult iubitor", dovada că mila divină poate vindeca ceea ce medicina umană declară incurabil.' || '\n\n' ||
    '#### Works cited' || '\n\n' ||
    '1. Viața Sfântului Mare Mucenic și Tămăduitor Pantelimon - Doxologia, accessed January 26, 2026, [[https://doxologia.ro/viata-sfantului-mare-mucenic-tamaduitor-pantelimon]{.underline}](https://doxologia.ro/viata-sfantului-mare-mucenic-tamaduitor-pantelimon)' || '\n' ||
    '2. Minunile din ziua în care Sfântului Pantelimon i-a fost tăiat capul -- ce s-a întâmplat în acele momente? | Doxologia, accessed January 26, 2026, [[https://doxologia.ro/minunile-din-ziua-care-sfantului-pantelimon-i-fost-taiat-capul-ce-s-intamplat-acele-momente]{.underline}](https://doxologia.ro/minunile-din-ziua-care-sfantului-pantelimon-i-fost-taiat-capul-ce-s-intamplat-acele-momente)' || '\n' ||
    '3. Sfântul Mare Mucenic și Tămăduitor Pantelimon - Doxologia, accessed January 26, 2026, [[https://doxologia.ro/sfantul-mare-mucenic-tamaduitor-pantelimon]{.underline}](https://doxologia.ro/sfantul-mare-mucenic-tamaduitor-pantelimon)' || '\n' ||
    '4. Pantelimon sau Pintilie Călătorul (27 iulie): hotarul calendaristic între vară și toamnă - Tradiții, Sărbători și Obiceiuri | Vatra MCP, accessed January 26, 2026, [[https://vatra-mcp.ro/artisti-si-patrimoniu/traditii-sarbatori-si-obiceiuri/pantelimon-sau-pintilie-calatorul-27-iulie-hotarul-calendaristic-intre-vara-si-toamna/]{.underline}](https://vatra-mcp.ro/artisti-si-patrimoniu/traditii-sarbatori-si-obiceiuri/pantelimon-sau-pintilie-calatorul-27-iulie-hotarul-calendaristic-intre-vara-si-toamna/)' || '\n' ||
    '5. Icoana Sfântului Pantelimon de la Mănăstirea Sf. Pantelimon | Muntele Athos - Mount Athos, accessed January 26, 2026, [[https://mount-athos.org/ro/mount-athos/icons-relics/panteleimon]{.underline}](https://mount-athos.org/ro/mount-athos/icons-relics/panteleimon)' || '\n' ||
    '6. Clasificarea spitalelor din romania, accessed January 26, 2026, [[https://oldsite.ms.ro/wp-content/uploads/2023/02/Clasificarea-spitalelor-din-romania.pdf]{.underline}](https://oldsite.ms.ro/wp-content/uploads/2023/02/Clasificarea-spitalelor-din-romania.pdf)' || '\n' ||
    '7. Sfântul Mare Mucenic Pantelimon -- Cuvântul Înaltpreasfințitului Părinte Calinic - Doxologia, accessed January 26, 2026, [[https://doxologia.ro/sfantul-mare-mucenic-pantelimon-cuvantul-inaltpreasfintitului-parinte-calinic]{.underline}](https://doxologia.ro/sfantul-mare-mucenic-pantelimon-cuvantul-inaltpreasfintitului-parinte-calinic)' || '\n' ||
    '8. Sfântul Mare Mucenic Pantelimon, făcătorul de minuni - Editura Doxologia |, accessed January 26, 2026, [[https://edituradoxologia.ro/sites/default/files/pdf/2024/11/extras_sf._pantelimon_-_brosura.pdf]{.underline}](https://edituradoxologia.ro/sites/default/files/pdf/2024/11/extras_sf._pantelimon_-_brosura.pdf)' || '\n' ||
    '9. viaţa şi acatistul sfântului mare mucenic şi tămăduitor pantelimon - Ziarul Lumina, accessed January 26, 2026, [[https://ziarullumina.ro/media/file/Viata-si-Acatistul-Sfantului-Pantelimon.pdf]{.underline}](https://ziarullumina.ro/media/file/Viata-si-Acatistul-Sfantului-Pantelimon.pdf)' || '\n' ||
    '10. Icoana Sfântul Pantelimon - aurită, accessed January 26, 2026, [[https://icoane-art.ro/icoana-stantul-pantelimon-aurita-2]{.underline}](https://icoane-art.ro/icoana-stantul-pantelimon-aurita-2)' || '\n' ||
    '11. Icoana Sfantului Pantelimon, cod:DR119, accessed January 26, 2026, [[https://icoana.net/icoane/icoana-sfantului-pantelimon-coddr119/]{.underline}](https://icoana.net/icoane/icoana-sfantului-pantelimon-coddr119/)' || '\n' ||
    '12. Cine este, de fapt, Pintilie Călătorul? - Doxologia, accessed January 26, 2026, [[https://doxologia.ro/cine-este-de-fapt-pintilie-calatorul]{.underline}](https://doxologia.ro/cine-este-de-fapt-pintilie-calatorul)' || '\n' ||
    '13. Mănăstirea Sfântul Pantelimon de pe Muntele Athos, accessed January 26, 2026, [[https://mount-athos.org/ro/mount-athos/monasteries/saint-panteleimon]{.underline}](https://mount-athos.org/ro/mount-athos/monasteries/saint-panteleimon)' || '\n' ||
    '14. Moaștele Sfântului Pantelimon din Muntele Athos - Doxologia, accessed January 26, 2026, [[https://doxologia.ro/moastele-sfantului-pantelimon-din-muntele-athos]{.underline}](https://doxologia.ro/moastele-sfantului-pantelimon-din-muntele-athos)' || '\n' ||
    '15. Sfinte moaște - Mănăstirea Plumbuita, accessed January 26, 2026, [[http://manastirea-plumbuita.ro/sfinte-moaste/]{.underline}](http://manastirea-plumbuita.ro/sfinte-moaste/)' || '\n' ||
    '16. Manastirea Plumbuita CrestinOrtodox.ro, accessed January 26, 2026, [[https://www.crestinortodox.ro/biserici-manastiri/manastirea-plumbuita-67866.html]{.underline}](https://www.crestinortodox.ro/biserici-manastiri/manastirea-plumbuita-67866.html)' || '\n' ||
    '17. Mănăstirea Plumbuita - Arhiepiscopia Bucureștilor, accessed January 26, 2026, [[https://arhiepiscopiabucurestilor.ro/exarhat/manastiri/manastirea-plumbuita]{.underline}](https://arhiepiscopiabucurestilor.ro/exarhat/manastiri/manastirea-plumbuita)' || '\n' ||
    '18. Biserica „Sfântul Pantelimon" - Foișorul de Foc (București) - OrthodoxWiki, accessed January 26, 2026, [[https://ro.orthodoxwiki.org/Biserica_%E2%80%9ESf%C3%A2ntul_Pantelimon%E2%80%9D_-_Foi%C8%99orul_de_Foc_(Bucure%C8%99ti)]{.underline}](https://ro.orthodoxwiki.org/Biserica_%E2%80%9ESf%C3%A2ntul_Pantelimon%E2%80%9D_-_Foi%C8%99orul_de_Foc_(Bucure%C8%99ti))' || '\n' ||
    '19. Biserica Sfantul Pantelimon - Foisorul de Foc - Crestin Ortodox, accessed January 26, 2026, [[https://www.crestinortodox.ro/biserici-manastiri/biserica-sfantul-pantelimon-foisorul-foc-137722.html]{.underline}](https://www.crestinortodox.ro/biserici-manastiri/biserica-sfantul-pantelimon-foisorul-foc-137722.html)' || '\n' ||
    '20. Istoria unei foste mănăstiri închinate Sfântului Pantelimon - Ziarul Lumina, accessed January 26, 2026, [[https://ziarullumina.ro/actualitate-religioasa/documentar/istoria-unei-foste-manastiri-inchinate-sfantului-pantelimon-135760.html]{.underline}](https://ziarullumina.ro/actualitate-religioasa/documentar/istoria-unei-foste-manastiri-inchinate-sfantului-pantelimon-135760.html)' || '\n' ||
    '21. Procesiune religioasă cu moaştele Sfântului Pantelimon, la Constanţa | Puterea credintei, accessed January 26, 2026, [[https://www.antenasatelor.ro/lada-de-zestre/puterea-credintei/puterea-credintei/procesiune-religioasa-cu-moastele-sfantului-pantelimon-la-constanta-id33030.html]{.underline}](https://www.antenasatelor.ro/lada-de-zestre/puterea-credintei/puterea-credintei/procesiune-religioasa-cu-moastele-sfantului-pantelimon-la-constanta-id33030.html)' || '\n' ||
    '22. Sarbatoarea Sfantului Pantelimon la Constanta CrestinOrtodox.ro, accessed January 26, 2026, [[https://www.crestinortodox.ro/stiri/arhiepiscopia-tomisului/sarbatoarea-sfantului-pantelimon-constanta-96390.html]{.underline}](https://www.crestinortodox.ro/stiri/arhiepiscopia-tomisului/sarbatoarea-sfantului-pantelimon-constanta-96390.html)' || '\n' ||
    '23. Moaștele Sfântului Pantelimon vor fi purtate în procesiune în Constanța - Basilica.ro, accessed January 26, 2026, [[https://basilica.ro/moastele-sfantului-pantelimon-vor-fi-purtate-in-procesiune-in-constanta/]{.underline}](https://basilica.ro/moastele-sfantului-pantelimon-vor-fi-purtate-in-procesiune-in-constanta/)' || '\n' ||
    '24. Moastele Sfantului Pantelimon, la Moinesti - Spital Clinic Municipal de Urgenta Moinesti, accessed January 26, 2026, [[https://www.spitalmoinesti.ro/moastele-sfantului-pantelimon-la-moinesti/]{.underline}](https://www.spitalmoinesti.ro/moastele-sfantului-pantelimon-la-moinesti/)' || '\n' ||
    '25. Minunile Sfântului Mare și Mucenic Tămăduitor Pantelimon, de la Muntele Athos, la Iași, accessed January 26, 2026, [[https://adevarul.ro/stiri-interne/evenimente/minunile-sfantului-mare-si-mucenic-tamaduitor-2393243.html]{.underline}](https://adevarul.ro/stiri-interne/evenimente/minunile-sfantului-mare-si-mucenic-tamaduitor-2393243.html)' || '\n' ||
    '26. (Video) Unde se găsesc Moaștele Sfântului Mare Mucenic și Tămăduitor Pantelimon, accessed January 26, 2026, [[https://doxologia.ro/video-unde-se-gasesc-moastele-sfantului-mare-mucenic-tamaduitor-pantelimon]{.underline}](https://doxologia.ro/video-unde-se-gasesc-moastele-sfantului-mare-mucenic-tamaduitor-pantelimon)' || '\n' ||
    '27. Pintilie Călătorul sau Sf. Pantelimon tămăduitorul -- ziua în care vara își ia rămas bun și oferă loc toamnei // TRADIȚII POPULARE, accessed January 26, 2026, [[https://calatoriicugust.com/pintilie-calatorul-sau-sf-pantelimon-tamaduitorul-ziua-in-care-vara-isi-ia-ramas-bun-si-ofera-loc-toamnei-traditii-populare/]{.underline}](https://calatoriicugust.com/pintilie-calatorul-sau-sf-pantelimon-tamaduitorul-ziua-in-care-vara-isi-ia-ramas-bun-si-ofera-loc-toamnei-traditii-populare/)' || '\n' ||
    '28. Pantelimonul, Sf. Ilie Cel Mic - cimec.ro, accessed January 26, 2026, [[https://cimec.ro/etnografie2/sarbatori-si-obiceiuri-traditionale/sarbatori-si-obiceiuri-de-vara/pantelimonul-sf-ilie-cel-mic/]{.underline}](https://cimec.ro/etnografie2/sarbatori-si-obiceiuri-traditionale/sarbatori-si-obiceiuri-de-vara/pantelimonul-sf-ilie-cel-mic/)' || '\n' ||
    '29. Superstiţii la sărbătoarea Sfântului Sfântul Pantelimon, doctorul fără de arginţi. Ce păţeşti dacă munceşti pe 27 iulie şi cum alungi ceasurile rele - Adevarul, accessed January 26, 2026, [[https://adevarul.ro/stiri-locale/calarasi/superstitii-la-sarbatoarea-sfantului-sfantul-1953861.html]{.underline}](https://adevarul.ro/stiri-locale/calarasi/superstitii-la-sarbatoarea-sfantului-sfantul-1953861.html)' || '\n' ||
    '30. Servicii Religioase - Spitalul Clinic de Urgenta „Sf. Pantelimon" Bucuresti, accessed January 26, 2026, [[https://urgentapantelimon.ro/servicii-religioase/]{.underline}](https://urgentapantelimon.ro/servicii-religioase/)' || '\n' ||
    '31. Spitalul Clinic De Urgență " Sf.Pantelimon" - Ministerul Sănătății, accessed January 26, 2026, [[https://ms.ro/ro/unitati-sanitare/spitalul-clinic-de-urgenta-sfpantelimon/]{.underline}](https://ms.ro/ro/unitati-sanitare/spitalul-clinic-de-urgenta-sfpantelimon/)' || '\n' ||
    '32. Hramul de Sf. Pantelimon al Bisericii Spitalului de Psihiatrie Voila, accessed January 26, 2026, [[https://spitalulvoila.ro/hramul-de-sf-pantelimon-al-bisericii-spitalului-de-psihiatrie-voila/]{.underline}](https://spitalulvoila.ro/hramul-de-sf-pantelimon-al-bisericii-spitalului-de-psihiatrie-voila/)' || '\n' ||
    '33. Rugăciune pentru medici și personalul sanitar* | Arhiepiscopia Romanului si Bacaului, accessed January 26, 2026, [[https://eprb.ro/rugaciune-pentru-medici-si-personalul-sanitar]{.underline}](https://eprb.ro/rugaciune-pentru-medici-si-personalul-sanitar)' || '\n' ||
    '34. Acatistul Sfantului Mare Mucenic Pantelimon - Parohia Sfanta Vineri Drumul Taberei, accessed January 26, 2026, [[http://www.parohiasfantavineridt.ro/rugaciuni/acatistul-sfantului-pantelimon/]{.underline}](http://www.parohiasfantavineridt.ro/rugaciuni/acatistul-sfantului-pantelimon/)' || '\n' ||
    '35. Acatistul Sfantului Pantelimon CrestinOrtodox.ro, accessed January 26, 2026, [[https://www.crestinortodox.ro/acatiste/acatistul-sfantului-pantelimon-67089.html]{.underline}](https://www.crestinortodox.ro/acatiste/acatistul-sfantului-pantelimon-67089.html)' || '\n' ||
    '36. Acatistul Sfantului Pantelimon | PDF - Scribd, accessed January 26, 2026, [[https://ro.scribd.com/document/185694157/Acatistul-Sfantului-Pantelimon]{.underline}](https://ro.scribd.com/document/185694157/Acatistul-Sfantului-Pantelimon)' || '\n' ||
    '37. Acatistul Sfântului Mare Mucenic și tămăduitor Pantelimon - Doxologia, accessed January 26, 2026, [[https://doxologia.ro/acatistul-sfantului-mare-mucenic-tamaduitor-pantelimon]{.underline}](https://doxologia.ro/acatistul-sfantului-mare-mucenic-tamaduitor-pantelimon)' || '\n' ||
    '38. Rugăciunea Preasfinţitului Eremei (Schimnicul) către Sfântul Mare Mucenic Pantelimon (vindecătorul de boli) | Doxologia, accessed January 26, 2026, [[https://doxologia.ro/rugaciunea-preasfintitului-eremei-schimnicul-catre-sfantul-mare-mucenic-pantelimon-vindecatorul-de]{.underline}](https://doxologia.ro/rugaciunea-preasfintitului-eremei-schimnicul-catre-sfantul-mare-mucenic-pantelimon-vindecatorul-de)' || '\n' ||
    '39. Rugaciune Catre SF .Pantelimon | PDF - Scribd, accessed January 26, 2026, [[https://de.scribd.com/document/369017703/Rugaciune-Catre-Sf-Pantelimon]{.underline}](https://de.scribd.com/document/369017703/Rugaciune-Catre-Sf-Pantelimon)' || '\n' ||
    '40. erminie | Doxologia, accessed January 26, 2026, [[https://doxologia.ro/cuvinte-cheie/erminie]{.underline}](https://doxologia.ro/cuvinte-cheie/erminie)'
);
