INSERT INTO core_schema.saint_lives (name_ro, life_description_ro)
VALUES (
    'Sfântul Cuvios Antipa de la Calapodești',
    '# Sfântul Antipa: O Viață între Athosul Românesc și cel de la Miazănoapte -- Un Studiu Hagiografic Comparativ' || '\n\n' ||
    '## Partea I: Rădăcinile Sfințeniei -- Perioada Formativă în Moldova' || '\n\n' ||
    '### 1.1. Copilăria și Chemarea Divină' || '\n\n' ||
    'Sfântul Cuvios Antipa de la Calapodești, o figură emblematică a monahismului ortodox din secolul al XIX-lea, și-a început călătoria pământească în anul 1816, în satul Calapodești din județul Bacău, în inima Moldovei istorice.^1^ Numele său de botez a fost Alexandru Luchian.^1^ S-a născut într-o familie de țărani evlavioși, rădăcinile sale spirituale fiind adânc înfipte în solul credinței populare românești. Tatăl său, Gheorghe Constantin Luchian, era diacon la biserica din sat, iar mama sa, Ecaterina Manase, a urmat și ea calea monahală mai târziu în viață, primind numele de Elizaveta.^4^' || '\n\n' ||
    'Alexandru a învățat carte la școala din sat, dar moartea timpurie a tatălui său l-a constrâns să deprindă meșteșugul legătoriei de cărți pentru a-și susține familia.^4^ Această îndeletnicire timpurie l-a pus în contact direct cu lumea cărților, inclusiv cu textele duhovnicești, prefigurând orientarea sa viitoare. Momentul decisiv al vocației sale a avut loc la vârsta de 20 de ani, printr-o experiență mistică profundă. După cum relatează biograful său, tânărul Alexandru „fără de veste a fost cuprins de o negrăită și minunată lumină, care i-a umplut inima de nespusă bucurie".^4^ Acest eveniment teofanic i-a întărit hotărârea de a părăsi lumea și de a-și închina viața lui Dumnezeu.' || '\n\n' ||
    '### 1.2. Primii Pași în Monahism: Schitul Brazi și Mănăstirea Căldărușani' || '\n\n' ||
    'Urmând chemarea divină, prima sa încercare de a intra în obștea marii Mănăstiri Neamț a fost întâmpinată de un refuz din partea starețului.^1^ Acest episod, deși descurajator la prima vedere, se înscrie într-un tipar hagiografic clasic, în care respingerea inițială servește la testarea hotărârii viitorului sfânt și la demonstrarea faptului că planul lui Dumnezeu se împlinește adesea pe căi neașteptate, departe de prestigiul centrelor monahale renumite.' || '\n\n' ||
    'Calea sa l-a purtat apoi spre Țara Românească, la Mănăstirea Căldărușani, un focar al tradițiilor paisiene.^2^ Aici a petrecut doi ani (aproximativ 1836-1837), îndeplinind ascultări dificile, fără a avea o chilie proprie sau haine adecvate, dând dovadă de o smerenie profundă.^2^ Alte surse menționează că a fost tuns în monahism la Schitul Brazi din Vrancea, primind numele de Alimpie.^1^ Este plauzibil ca el să fi petrecut timp în ambele așezăminte, care erau legate spiritual prin moștenirea Sfântului Paisie de la Neamț.' || '\n\n' ||
    'Un moment fundamental în formarea sa duhovnicească a fost întâlnirea cu pustnicul Ghedeon la Căldărușani. De la acest părinte isihast, tânărul frate a deprins pentru prima dată practica Rugăciunii lui Iisus, o disciplină care avea să devină piatra de temelie a întregii sale vieți duhovnicești.^5^ În această perioadă de început, a fost învrednicit de Dumnezeu cu darul lacrimilor și al rugăciunii neîncetate, semne ale unui progres spiritual rapid.^1^ Astfel, formarea sa inițială nu a fost loc într-un context monahal oarecare, ci în epicentrul reînnoirii filocalice care modela spiritualitatea ortodoxă românească, pregătindu-l pentru etapele următoare ale călătoriei sale: Athos și Valaam.' || '\n\n' ||
    '## Partea II: Asceza Athonită -- Două Decenii în Grădina Maicii Domnului' || '\n\n' ||
    '### 2.1. Ucenicia la Schiturile Lacu și Prodromu' || '\n\n' ||
    'Râvnind la o nevoință și mai aspră, monahul Alimpie a plecat spre Sfântul Munte Athos în anul 1837.^1^ S-a stabilit inițial la Schitul românesc Lacu, un loc renumit pentru asprimea vieții ascetice, unde se nevoiau la acea vreme peste 80 de călugări români.^1^ Ulterior, s-a mutat la Schitul Prodromu, un alt centru important al monahismului românesc athonit.^2^ Timp de aproape 15 ani, în aceste schituri, a aprofundat meșteșugul luptei duhovnicești, devenind cunoscut pentru postirea sa, pentru ostenelile neîncetate și pentru adâncirea în rugăciunea inimii.^2^' || '\n\n' ||
    '### 2.2. Maturitatea Duhovnicească la Mănăstirea Esfigmenu' || '\n\n' ||
    'Parcursul său spiritual a urmat o progresie deliberată, specifică formării athonite. De la viața semi-eremitică și aspră a schiturilor românești, a trecut la viața chinovială, mai structurată, a unei mari mănăstiri grecești, Esfigmenu.^1^ Această mutare nu a fost întâmplătoare, ci a marcat o nouă etapă a maturizării sale. Aici a petrecut patru ani și a primit „marele și îngerescul chip al schimniciei", moment în care numele său a fost schimbat în **Antipa**.^1^ Tot la Mănăstirea Esfigmenu a fost hirotonit diacon, integrându-se astfel și în viața liturgică a unei comunități monastice suverane.^1^ Această traiectorie demonstrează un echilibru spiritual remarcabil, îmbinând lupta ascetică personală cu o slujire eclezială formală.' || '\n\n' ||
    '### 2.3. Harismele Duhovnicești' || '\n\n' ||
    'În cele două decenii petrecute în Sfântul Munte, Cuviosul Antipa a fost învrednicit de Dumnezeu cu numeroase daruri duhovnicești (harisme). Sursele hagiografice menționează constant darul lacrimilor, rugăciunea neîncetată a inimii, darul vindecării bolnavilor și înainte-vederea (clarviziunea).^2^ A devenit cinstit în întreg Muntele Athos ca un mare isihast și „lucrător al rugăciunii lui Iisus".^2^' || '\n\n' ||
    'Un eveniment definitoriu pentru ministerul său a fost descoperirea unei icoane făcătoare de minuni a Maicii Domnului, pe care a găsit-o în ruinele unei chilii părăsite.^6^ Această icoană a devenit un semn tangibil al ocrotirii speciale a Născătoarei de Dumnezeu și o confirmare divină a sfințeniei sale. Prima minune consemnată legată de această icoană a fost vindecarea instantanee a unui tâmplar care suferea de holeră, pentru care Sfântul Antipa s-a rugat înaintea ei.^11^ Din acel moment, icoana a devenit un partener nedespărțit în slujirea sa, o sursă de vindecare și sfințire, pe care a purtat-o cu el de la Athos până în Rusia, simbolizând transferul harului athonit către „Athosul de la Miazănoapte".' || '\n\n' ||
    '## Partea III: Pelerin și Misionar -- Întoarcerea în Lume' || '\n\n' ||
    '### 3.1. Scurta Revenire în Moldova (1860-1863)' || '\n\n' ||
    'Iubind mai mult singurătatea și smerenia decât lauda oamenilor, Cuviosul Antipa a părăsit Sfântul Munte în anul 1860 și s-a întors în Moldova, stabilindu-se în mănăstirile din jurul Iașilor.^2^ Însă, faima sfințeniei sale îl precedase. În loc de liniștea căutată, s-a trezit asaltat de mulțimi de credincioși care veneau să-i ceară sfatul și rugăciunile.^2^ Această situație ilustrează o tensiune constantă în viața sa: dorința personală de isihie (liniștire) și ascultarea monahală de a sluji nevoilor aproapelui. Nereușind să găsească izolarea necesară, după trei ani a hotărât să plece din nou, de data aceasta într-un pelerinaj la marea Lavră a Peșterilor din Kiev (Pecerska).^2^' || '\n\n' ||
    '### 3.2. Misiunea de Colectă în Imperiul Rus' || '\n\n' ||
    'Călătoria sa în Imperiul Rus nu a fost doar un pelerinaj personal, ci și o misiune oficială. El primise o „carte de colectă", o scrisoare de binecuvântare pentru strângerea de fonduri, încredințată de obștea Schitului românesc Prodromu.^12^ Timp de mai mulți ani, a îndeplinit această ascultare în marile orașe Moscova și Sankt Petersburg.^8^' || '\n\n' ||
    'Această misiune l-a forțat să trăiască în inima unor metropole aglomerate, un mediu complet opus pustiei pe care o dorea. Cu toate acestea, sfințenia sa nu a putut rămâne ascunsă. A atras numeroși fii duhovnicești din toate clasele sociale, devenind un părinte duhovnicesc renumit.^7^ În mod paradoxal, tocmai prin această ascultare, care părea să contrazică vocația sa la singurătate, darurile sale duhovnicești au rodit și mai mult, devenind un îndrumător pentru nenumărate suflete. Acest parcurs demonstrează o învățătură ortodoxă fundamentală: adevăratul progres duhovnicesc nu se găsește în împlinirea voinței proprii, ci în acceptarea cu smerenie a căii rânduite de Dumnezeu.' || '\n\n' ||
    '## Partea IV: Înflorirea la Valaam -- Athosul de la Miazănoapte' || '\n\n' ||
    '### 4.1. Stabilirea la Mănăstirea Valaam (1865)' || '\n\n' ||
    'În timpul misiunii sale în Rusia, Cuviosul Antipa a auzit de faima Mănăstirii Valaam, situată pe o insulă din Lacul Ladoga, aproape de Finlanda.^2^ A vizitat-o și a fost profund impresionat de viața duhovnicească de acolo, găsind-o foarte asemănătoare cu cea din Sfântul Munte Athos.^7^ După încheierea misiunii de colectare de fonduri pentru Prodromu, în noiembrie 1865, s-a stabilit definitiv la Valaam, alegându-și o chilie în Schitul Tuturor Sfinților.^2^ Aici avea să petreacă ultimii 17 ani ai vieții sale.^2^' || '\n\n' ||
    'Contextul spiritual era ideal. Valaam era un centru major al vieții isihaste, cu legături puternice cu tradiția paisiană, deoarece unii monahi care îl cunoscuseră pe Sfântul Paisie de la Neamț viețuiseră acolo.^4^ Astfel, Sfântul Antipa a găsit un mediu propice pentru continuarea nevoințelor sale.' || '\n\n' ||
    '### 4.2. Părinte Duhovnicesc și Dascăl al Rugăciunii' || '\n\n' ||
    'La Valaam, a fost hirotonit preot, devenind ieroschimonah.^2^ Aici a preluat și lucrarea de stăreție (părinte duhovnicesc), devenind un îndrumător căutat de mulți monahi și pelerini din nordul Rusiei și din Finlanda.^2^ Viața sa a rămas una de asceză extremă: în chilia sa nu avea pat sau scaun, iar postul său era foarte strict, abținându-se complet de la mâncare și băutură în zilele de luni, miercuri și vineri, precum și în prima săptămână a Postului Mare.^13^ Nevoința sa principală a rămas „rugăciunea cea de foc a inimii".^2^ Prin prezența sa, el a devenit o punte vie între cele două mari centre ale monahismului ortodox, transferând în mod conștient spiritul isihast al Athosului în „Athosul de la Miazănoapte".^10^' || '\n\n' ||
    '### 4.3. Ultimele Zile și Adormirea în Domnul (1882)' || '\n\n' ||
    'Sfârșitul său pământesc a fost prevestit de o minune. Cu trei zile înainte de adormirea sa, icoana făcătoare de minuni a Maicii Domnului pe care o purta mereu cu el s-a ridicat cu zgomot și s-a așezat singură pe pieptul său, în timp ce celelalte icoane din chilie au căzut la pământ. Acest semn a fost interpretat ca o prevestire a mutării sale la cele veșnice.^11^' || '\n\n' ||
    'La 10 ianuarie 1882, în timp ce ucenicul său îi citea Acatistul Maicii Domnului, ieroschimonahul Antipa și-a dat în pace sufletul în mâinile Mântuitorului, la vârsta de 66 de ani.^2^ A fost înmormântat în cimitirul de obște al Mănăstirii Valaam.^2^' || '\n\n' ||
    '## Partea V: Moștenirea Spirituală și Cinstirea Postumă' || '\n\n' ||
    '### 5.1. Învățăturile Sfântului Antipa' || '\n\n' ||
    'Deși Sfântul Antipa nu a lăsat scrieri teoretice, viața sa însăși constituie cea mai profundă învățătură. Sursele subliniază dedicarea sa totală față de **Rugăciunea lui Iisus** ^2^, **smerenia** profundă, **ascultarea** dusă până la sacrificiul propriei dorințe de singurătate și **răbdarea** în fața tuturor încercărilor, inclusiv a invidiei venite din partea altora.^8^ Ca părinte duhovnicesc, avea darul de a vedea în sufletele oamenilor și de a-i îndruma pe calea mântuirii.^14^ Imnografia rusă îl laudă ca pe un dascăl care îi cheamă pe păcătoși la pocăință și la umblarea în lumina poruncilor lui Hristos.^16^' || '\n\n' ||
    '### 5.2. Minunile Postume și Aflarea Moaștelor' || '\n\n' ||
    'Cinstirea sa a început imediat după moarte. La doar un an după adormirea sa, în 1883, ucenicul său, ieromonahul Pimen, i-a scris viața, intitulată „Viața vrednică de pomenire a ieroschimonahului Antipa". Această carte, tipărită la Sankt Petersburg, a fost esențială în răspândirea faimei sfințeniei sale în Rusia, Finlanda și Muntele Athos.^12^' || '\n\n' ||
    'În perioada sovietică, mormântul său a fost profanat în anii 1960. După redeschiderea mănăstirii, sfintele sale moaște au fost descoperite oficial la 14 mai 1991. Un semn tradițional al sfințeniei a însoțit acest eveniment: din moaște izvora o mireasmă puternică și plăcută.^7^ Astăzi, sfintele sale moaște se odihnesc în Biserica Sfinților Serghie și Gherman de la Valaam.^7^' || '\n\n' ||
    '### 5.3. Canonizarea și Cinstirea Internațională' || '\n\n' ||
    'Recunoașterea oficială a sfințeniei Cuviosului Antipa a avut loc în etape, reflectând caracterul său pan-ortodox. Cinstirea sa timpurie la Athos, înainte de orice act sinodal, demonstrează procesul organic prin care sfințenia este recunoscută mai întâi de poporul credincios. Întârzierea canonizărilor oficiale din România și Rusia până după 1990 este o consecință directă a persecuției comuniste. Căderea regimurilor atee a permis redescoperirea moaștelor sale și recunoașterea sinodală a unei sfințenii păstrate în evlavia populară și monahală timp de un secol.' || '\n\n' ||
    '| **Tradiție Ortodoxă** | **Nume Comun** | **Zi de Pomenire** | **Data Canonizării** | **Accent Hagiografic/Imnografic** |' || '\n' ||
    '| :--- | :--- | :--- | :--- | :--- |' || '\n' ||
    '| **Română** | Sf. Cuv. Antipa de la Calapodești / Athonitul | 10 ianuarie | 1992 | Subliniază originile sale moldovenești („odrasla Moldovei") și rolul său de punte între România, Athos și Valaam.^12^ |' || '\n' ||
    '| **Greacă (Athonită)** | Όσιος Αντύπας ο Αθωνίτης / ο Μολδαβός | 10 ianuarie | 1906 (neoficial) | Se concentrează pe identitatea sa athonită („o Αθωνίτης") și pe originea sa moldoveană („o Μολδαβός").^6^ |' || '\n' ||
    '| **Rusă** | Преподобный Антипа Валаамский (Афонский) | 10 ianuarie | 2000 | Evidențiază rolul său de stareț al Valaamului („Валаамский"), dascăl al rugăciunii și luminător al „Athosului de la Miazănoapte".^12^ |' || '\n\n' ||
    '### 5.4. Imnografie și Iconografie' || '\n\n' ||
    'Imnografia dedicată Sfântului Antipa reflectă cinstirea sa în diverse culturi ortodoxe.' || '\n\n' ||
    '- **Troparul Românesc:** Pune accent pe călătoria sa simbolică de la Athos la Valaam, numit „Athosul de la miazănoapte", și pe legătura sa cu marii sihaștri ai Moldovei.^21^' || '\n' ||
    '- **Condacul Românesc:** Subliniază originea sa moldoveană („odrasla Moldovei") și nevoințele sale pline de lacrimi și rugăciune.^20^' || '\n' ||
    '- **Imnografia Rusă:** Îl laudă ca pe un „sfeșnic prealuminos" al Valaamului, un „lucrător iscusit al rugăciunii" și un învățător care cheamă la pocăință.^16^' || '\n\n' ||
    'Iconografia sa îl reprezintă, de regulă, ca ieroschimonah, purtând însemnele marii schime, adesea cu un sul sau un metanier în mână, simboluri ale învățăturii și rugăciunii neîncetate. Icoane ale sfântului sunt răspândite în ateliere din România și Rusia, iar icoana de la Valaam conține o părticică din sfintele sale moaște.^7^' || '\n\n' ||
    'În concluzie, Sfântul Cuvios Antipa de la Calapodești se distinge ca o figură de o importanță pan-ortodoxă. Viața sa unește trei mari centre ale spiritualității ortodoxe -- Moldova, Muntele Athos și Valaam -- demonstrând universalitatea și vitalitatea tradiției isihaste. El rămâne un model de ascultare, smerenie și dedicare totală Rugăciunii lui Iisus, a cărui cinstire, reînnoită după decenii de opresiune comunistă, stă mărturie pentru biruința credinței asupra istoriei.' || '\n\n' ||
    '#### Works cited' || '\n\n' ||
    '1. Antipa de la Calapodești - OrthodoxWiki, accessed August 21, 2025, [[https://ro.orthodoxwiki.org/Antipa_de_la_Calapode%C8%99ti]{.underline}](https://ro.orthodoxwiki.org/Antipa_de_la_Calapode%C8%99ti)' || '\n' ||
    '2. Viața Sfântului Cuvios Antipa de la Calapodești - Doxologia, accessed August 21, 2025, [[https://doxologia.ro/viata-sfantului-cuvios-antipa-de-la-calapodesti-0]{.underline}](https://doxologia.ro/viata-sfantului-cuvios-antipa-de-la-calapodesti-0)' || '\n' ||
    '3. Mănăstirea „Sf. Cuv. Antipa Athonitul" Calapodești - Arhiepiscopia Romanului și Bacăului, accessed August 21, 2025, [[https://eprb.ro/manastirea-sf-cuv-antipa-athonitul-calapodesti]{.underline}](https://eprb.ro/manastirea-sf-cuv-antipa-athonitul-calapodesti)' || '\n' ||
    '4. Sfantul Antipa de la Calapodesti - Societatea Teologica, accessed August 21, 2025, [[https://www.societateamuzicala.ro/societateateologica/sfantul-antipa-de-la-calapodesti]{.underline}](https://www.societateamuzicala.ro/societateateologica/sfantul-antipa-de-la-calapodesti)' || '\n' ||
    '5. Sfântul Cuvios Antipa de la Calapodești (1816 - 1882) - Uniti Schimbam, accessed August 21, 2025, [[https://www.unitischimbam.ro/antipa-de-la-calapodesti/]{.underline}](https://www.unitischimbam.ro/antipa-de-la-calapodesti/)' || '\n' ||
    '6. Όσιος Αντίπας ο Αθωνίτης - Ιερά Μητρόπολις Νέας Ιωνίας, Φιλαδελφείας, Ηρακλείου και Χαλκηδόνος, accessed August 21, 2025, [[https://www.nif.gr/agiologio-eortologio/osios-antipas-o-athonitis/]{.underline}](https://www.nif.gr/agiologio-eortologio/osios-antipas-o-athonitis/)' || '\n' ||
    '7. Икона преподобного Антипы Валаамского с частицей мощей, accessed August 21, 2025, [[http://www.svyatalm.ru/index.php/svyatwnimon/298-ikprpant]{.underline}](http://www.svyatalm.ru/index.php/svyatwnimon/298-ikprpant)' || '\n' ||
    '8. St. Antipas the Hesychast | St. Innocent of Alaska Orthodox Monastery, accessed August 21, 2025, [[https://stinnocentmonastery.org/st_antipas_the_hesychast]{.underline}](https://stinnocentmonastery.org/st_antipas_the_hesychast)' || '\n' ||
    '9. Sfântul Antipa de la Calapodeşti, marele nevoitor din Tebaida Nordului - Ziarul Lumina, accessed August 21, 2025, [[https://ziarullumina.ro/actualitate-religioasa/documentar/sfantul-antipa-de-la-calapodesti-marele-nevoitor-din-tebaida-nordului-194922.html]{.underline}](https://ziarullumina.ro/actualitate-religioasa/documentar/sfantul-antipa-de-la-calapodesti-marele-nevoitor-din-tebaida-nordului-194922.html)' || '\n' ||
    '10. Ο Άγιος Αντίπας ο Μολδαβός († 10 Ιανουαρίου 1882) - Pemptousia, accessed August 21, 2025, [[https://www.pemptousia.gr/2014/01/o-agios-antipas-o-moldavos-10-ianouari/]{.underline}](https://www.pemptousia.gr/2014/01/o-agios-antipas-o-moldavos-10-ianouari/)' || '\n' ||
    '11. Contribuții la conturarea Vieții Sfântului Antipa de la Calapodeşti, George Crasnean, accessed August 21, 2025, [[https://sfantulmunteathos.wordpress.com/2013/01/16/contributii-la-conturarea-vietii-sfantului-antipa-de-la-calapodesti-george-crasnean/]{.underline}](https://sfantulmunteathos.wordpress.com/2013/01/16/contributii-la-conturarea-vietii-sfantului-antipa-de-la-calapodesti-george-crasnean/)' || '\n' ||
    '12. Sfântul Antipa de la Calapodești, isihastul român nevoitor în Imperiul Țarist - Ziarul Lumina, accessed August 21, 2025, [[https://ziarullumina.ro/actualitate-religioasa/an-omagial/sfantul-antipa-de-la-calapodesti-isihastul-roman-nevoitor-in-imperiul-tarist-169356.html]{.underline}](https://ziarullumina.ro/actualitate-religioasa/an-omagial/sfantul-antipa-de-la-calapodesti-isihastul-roman-nevoitor-in-imperiul-tarist-169356.html)' || '\n' ||
    '13. DOCUMENTAR: Sfântul Cuvios Antipa de la Calapodeşti -- singurul călugăr athonit român trecut în rândul sfinţilor - Radio România Cultural, accessed August 21, 2025, [[https://www.radioromaniacultural.ro/sectiuni-articole/istorie-filozofie-psihologie/documentar-sfantul-cuvios-antipa-de-la-calapodesti-singurul-calugar-athonit-roman-trecut-in-randul-sfintilor-id21238.html]{.underline}](https://www.radioromaniacultural.ro/sectiuni-articole/istorie-filozofie-psihologie/documentar-sfantul-cuvios-antipa-de-la-calapodesti-singurul-calugar-athonit-roman-trecut-in-randul-sfintilor-id21238.html)' || '\n' ||
    '14. Valaam Patericon | PDF | Monk | Christian Monasticism - Scribd, accessed August 21, 2025, [[https://www.scribd.com/document/514775198/Valaam-Patericon]{.underline}](https://www.scribd.com/document/514775198/Valaam-Patericon)' || '\n' ||
    '15. Antipa de la Calapodești - Wikipedia, accessed August 21, 2025, [[https://ro.wikipedia.org/wiki/Antipa_de_la_Calapode%C8%99ti]{.underline}](https://ro.wikipedia.org/wiki/Antipa_de_la_Calapode%C8%99ti)' || '\n' ||
    '16. Преподобному Антипе Валаамскому, Афонскому (тропари, кондак, молитва и величание) - ПСАЛОМЩИКЪ - <, accessed August 21, 2025, [[http://diak.ortox.ru/*_prepodobnym/view/id/1215620]{.underline}](http://diak.ortox.ru/*_prepodobnym/view/id/1215620)' || '\n' ||
    '17. Акафист преподобному Антипе Валаамскому - Молитвослов - Азбука веры, accessed August 21, 2025, [[https://azbyka.ru/molitvoslov/akafist-prepodobnomu-antipe-valaamskomu.html]{.underline}](https://azbyka.ru/molitvoslov/akafist-prepodobnomu-antipe-valaamskomu.html)' || '\n' ||
    '18. Sfântul Antipa Athonitul -- singurul călugăr athonit român trecut în rândul sfinților, accessed August 21, 2025, [[https://doxologia.ro/sfantul-antipa-athonitul-singurul-calugar-athonit-roman-trecut-randul-sfintilor]{.underline}](https://doxologia.ro/sfantul-antipa-athonitul-singurul-calugar-athonit-roman-trecut-randul-sfintilor)' || '\n' ||
    '19. Viața Sfântului Cuvios Antipa de la Calapodești - Doxologia, accessed August 21, 2025, [[https://doxologia.ro/viata-sfantului-cuvios-antipa-de-la-calapodesti]{.underline}](https://doxologia.ro/viata-sfantului-cuvios-antipa-de-la-calapodesti)' || '\n' ||
    '20. Condacul Sfântului Cuvios Antipa de la Calapodești - Doxologia, accessed August 21, 2025, [[https://doxologia.ro/condacul-sfantului-cuvios-antipa-de-la-calapodesti]{.underline}](https://doxologia.ro/condacul-sfantului-cuvios-antipa-de-la-calapodesti)' || '\n' ||
    '21. Troparul Sfântului Cuvios Antipa de la Calapodești - Doxologia, accessed August 21, 2025, [[https://doxologia.ro/troparul-sfantului-cuvios-antipa-de-la-calapodesti]{.underline}](https://doxologia.ro/troparul-sfantului-cuvios-antipa-de-la-calapodesti)' || '\n' ||
    '22. Slujba - // Sfinti Romani, accessed August 21, 2025, [[https://www.sfintiromani.ro/ro/pagina/32/ianuarie_antipa_de_la_calapodesti_slujba.html]{.underline}](https://www.sfintiromani.ro/ro/pagina/32/ianuarie_antipa_de_la_calapodesti_slujba.html)' || '\n' ||
    '23. Преподобный Антипа Валаамский, accessed August 21, 2025, [[https://sobor-rf.ru/zhitiya-svyatyh-category/23-yanvarya-pamyat-prepodobnogo-antipy-valaamskogo/]{.underline}](https://sobor-rf.ru/zhitiya-svyatyh-category/23-yanvarya-pamyat-prepodobnogo-antipy-valaamskogo/)' || '\n' ||
    '24. Icoana Sfantului Cuvios Antipa de la Calapodesti, cod:SFR114 - Icoane Ortodoxe, accessed August 21, 2025, [[https://icoana.net/icoane/icoana-sfantului-cuvios-antipa-de-la-calapodesti-codsfr114/]{.underline}](https://icoana.net/icoane/icoana-sfantului-cuvios-antipa-de-la-calapodesti-codsfr114/)' || '\n' ||
    '25. Sf. Cuv. Antipa de la Calapodești - EIKON, accessed August 21, 2025, [[https://www.icoaneortodoxe.com.ro/shop/atelierul-de-icoane-eikon/sf-cuv-antipa-de-la-calapodesti/]{.underline}](https://www.icoaneortodoxe.com.ro/shop/atelierul-de-icoane-eikon/sf-cuv-antipa-de-la-calapodesti/)' || '\n' ||
    '26. St Antipas of Valaam | Orthodox Icons - Damascene Gallery, accessed August 21, 2025, [[https://damascenegallery.com/products/st-antipas-of-valaam-orthodox-icons]{.underline}](https://damascenegallery.com/products/st-antipas-of-valaam-orthodox-icons)'
);
