INSERT INTO core_schema.saint_lives (name_ro, life_description_ro)
VALUES (
    'Sfântul Mucenic Polieuct',
    '# Modele de Sfințenie: Sfântul Mucenic Polieuct din Melitina (9 Ianuarie)' || '\n\n' ||
    '## Introducere: Primul Martir din Meletina -- Un Martor Făurit în Prietenie' || '\n\n' ||
    'Viața Sfântului Mucenic Polieuct este o mărturie vibrantă a modului în care prietenia, revelația divină și curajul public pot culmina într-un „botez al sângelui", transformând un ostaș al împăratului pământesc într-un martir al Împăratului Ceresc. Povestea sa, petrecută în inima unei persecuții acerbe, rămâne un etalon al fidelității absolute față de Hristos.' || '\n\n' ||
    '### Context Istoric: Un Ostaș în Roma lui Decius' || '\n\n' ||
    'Sfântul Polieuct a fost un ostaș de seamă în armata romană, staționat în cetatea Melitina din Armenia, în timpul domniilor împăraților Deciu (249--251) și Valerian (253--259).^1^ Această perioadă a fost marcată de una dintre cele mai sistematice și severe persecuții împotriva creștinilor. Un edict imperial aspru poruncea tuturor cetățenilor, cu o presiune deosebită asupra funcționarilor publici și a militarilor, să se lepede de Hristos și să aducă jertfe zeilor păgâni, sub amenințarea unor chinuri înfricoșătoare și a pedepsei capitale.^1^' || '\n\n' ||
    'Natura acestei persecuții a fost un factor determinant în modelarea martiriului Sfântului Polieuct. Nu era vorba doar de o credință privată, ci de o cerere publică de conformare, un test de loialitate față de statul roman și panteonul său. Refuzul de a jertfi idolilor era interpretat nu doar ca un act de impietate religioasă, ci și ca unul de trădare politică. Acest context a forțat credința creștină să iasă din spațiul privat și să intre în arena publică, transformând fiecare act de mărturisire într-o confruntare directă cu puterea imperială. Răspunsul Sfântului Polieuct a fost pe măsura provocării: nu o credință tăcută, ci o contra-mărturie la fel de publică și radicală. Actele sale de a rupe edictul și de a sfărâma idolii ^3^ nu au fost gesturi impulsive, ci un răspuns teologic direct la cererea publică de apostazie. Astfel, acțiunea statului a devenit catalizatorul care a forjat caracterul specific al mărturiei sale, demonstrând că martiriul nu este un eveniment pasiv, ci o replică activă și curajoasă la pretențiile totalitare ale puterilor lumești.' || '\n\n' ||
    '### „Frați prin afecțiune": Prietenia ca Vehicul al Mântuirii' || '\n\n' ||
    'În centrul convertirii Sfântului Polieuct se află prietenia sa excepțională cu un alt ostaș, Nearh. Sursele hagiografice subliniază profunzimea acestei legături, descriind-o ca pe o dragoste mai presus de cea frățească.^2^ Nearh era un creștin dreptcredincios și, în fața edictului imperial, măhnirea sa nu izvora din teama de propria moarte, ci din durerea că persecuția îi va despărți veșnic, el mergând la Hristos, iar Polieuct, prietenul său păgân, rămânând în întuneric.^3^' || '\n\n' ||
    'Această preocupare profundă pentru destinul etern al prietenului său transformă relația lor într-un instrument al providenței divine. Dragostea lui Nearh nu a fost una pur emoțională, ci una soteriologică -- el se îngrijea activ de mântuirea sufletului lui Polieuct. Făcea acest lucru prin mijloace concrete: îi citea din Sfintele Scripturi și îi arăta deșertăciunea închinării la idoli, sădind semințele credinței în inima lui.^6^ Când Polieuct a fost condus la moarte, ultimele sale cuvinte nu au fost adresate familiei sale, ci lui Nearh, amintindu-i de un legământ tainic: „Ține minte legământul nostru de dragoste!".^3^ Această frază enigmatică sugerează că legătura lor depășea o simplă camaraderie militară. Ea implică existența unui jurământ spiritual, un pact de frățietate duhovnicească ce transcendea diferențele lor religioase și loialitatea față de Roma. Acest „legământ" poate fi interpretat ca esența însăși a prieteniei creștine autentice: un angajament reciproc de a călători împreună spre Hristos, chiar dacă unul dintre prieteni îl conduce pe celălalt pe cale. Astfel, relația lor devine un model pastoral puternic, arătând cum o prietenie bazată pe dragoste jertfelnică poate deveni o cale spre convertire și sfințenie.' || '\n\n' ||
    '### Viziunea Divină și Transformarea Radicală' || '\n\n' ||
    'Punctul culminant al procesului de convertire a lui Polieuct a fost o viziune divină pe care a avut-o cu câteva zile înainte de martiriul său. El i-a povestit lui Nearh cum Însuși Hristos i s-a apropiat, i-a luat haina veche și murdară de ostaș și l-a îmbrăcat cu o haină nouă, de o frumusețe și un preț de nedescris, cu nasturi de aur. Mai mult, Hristos i-a dăruit un cal înaripat.^8^' || '\n\n' ||
    'Nearh, luminat de Duhul Sfânt, a tâlcuit imediat vedenia. Lepădarea hainei vechi și îmbrăcarea celei noi simboliza transformarea radicală a lui Polieuct: părăsirea păgânătății și îmbrăcarea în Hristos prin credința cea dreaptă, o metaforă puternică pentru taina Botezului și pentru *metanoia* (schimbarea minții și a inimii). Calul înaripat, a explicat Nearh, însemna alergarea grabnică și neîmpiedicată spre cer, o imagine a urgenței eshatologice și a puterii supranaturale pe care martirul o primește pentru a-și duce la bun sfârșit nevoința.^3^ În acel moment, Polieuct a mărturisit că, deși nu avea numele de „creștin", inima sa ardea deja pentru Hristos atunci când Nearh îi citea din Evanghelie. Îi lipsea doar numele, nu și râvna și osârdia.^3^ Această viziune a fost confirmarea divină a unei convertiri interioare care era deja în curs, pecetluind decizia sa de a-L mărturisi public pe Hristos.' || '\n\n' ||
    '### Martiriul: Mărturisire Publică și Botezul Sângelui' || '\n\n' ||
    'Întărit de viziune și de tâlcuirea lui Nearh, Polieuct a trecut de la credința interioară la mărturisirea publică. A mers în târg, a citit porunca împărătească, a defăimat-o și a rupt-o în bucăți. Apoi, văzând o procesiune păgână, a sfărâmat doisprezece idoli, trântindu-i la pământ.^3^ Acest act de sfidare l-a adus în fața socrului său, Felix, care era dregătorul însărcinat cu persecutarea creștinilor.^3^' || '\n\n' ||
    'În fața judecății, Polieuct a rămas neclintit. A refuzat să fie înduplecat de lacrimile soției sale, Paulina, sau de promisiunile socrului său, afirmând că nu-i pasă de cele pământești, ci caută spre cele cerești și nepieritoare.^1^ Atitudinea sa reflectă învățătura creștină despre prioritatea absolută a Împărăției lui Dumnezeu. Condamnat la moarte prin tăierea capului, a mers la locul execuției cu bucurie. Prin jertfa sa, el a primit ceea ce Biserica numește „botezul sângelui". Deoarece convertirea și martiriul său au avut loc înainte de a putea primi taina botezului cu apă, vărsarea sângelui pentru Hristos este considerată echivalentă, o cale de mântuire și de unire deplină cu El.^3^ Mărturia sa curajoasă a avut un impact profund, determinând pe mulți dintre cei prezenți să creadă în Hristos, împlinind astfel cuvintele că „sângele martirilor este sămânța creștinilor".^3^' || '\n\n' ||
    '### Cinstire și Imnografie' || '\n\n' ||
    'Cinstirea Sfântului Polieuct s-a răspândit rapid în Biserică. O biserică măreață a fost construită în cinstea sa la Constantinopol, atestând importanța cultului său.^9^ Iconografia îl înfățișează în mod constant ca ostaș, subliniind dubla sa identitate: soldat al Romei și, mai presus de toate, „ostaș al lui Hristos".^2^' || '\n\n' ||
    '| Tradiție | Tropar (Text original) | Condac (Text original) | Traducere și Teme Teologice Cheie |' || '\n' ||
    '| :--- | :--- | :--- | :--- |' || '\n' ||
    '| **Română (Glas 4)** | *Mucenicul Tău, Doamne, Polieuct, întru nevoința sa, cununa nestricăciunii a dobândit de la Tine, Dumnezeul nostru; că având puterea Ta, pe chinuitori a învins; zdrobit-a și ale demonilor neputincioase îndrăzniri. Pentru rugăciunile lui, mântuiește sufletele noastre, Hristoase Dumnezeule.* ^6^ | (Textul standard este cel slavon/grec) | *Mucenicul Tău, Doamne, Polieuct...* **Teme:** Puterea divină, biruința asupra chinuitorilor, înfrângerea demonilor, cununa nestricăciunii. |' || '\n' ||
    '| **Rusă (Глас 4)** | *Му́ченик Твой, Го́споди, Полие́вкт во страда́нии свое́м вене́ц прия́т нетле́нный от Тебе́, Бо́га на́шего...* ^13^ | *Спа́су прикло́ншу во Иорда́не главу́, сокруши́шася змие́в главы́. Полие́вктова же глава́ отсе́кшаяся льсти́ваго посрами́.* ^13^ | **Tropar:** *Mucenicul Tău, Doamne, Polieuct...* (Identic cu cel românesc). **Condac:** *Când Mântuitorul Și-a plecat capul în Iordan, capetele balaurilor s-au zdrobit. Iar capul lui Polieuct, fiind tăiat, pe cel viclean l-a rușinat.* **Teme:** Biruință cosmică, martiriul ca participare la victoria lui Hristos asupra satanei. |' || '\n' ||
    '| **Greacă (Ἦχος δ'')** | *Ὁ Μάρτυς σου Κύριε, ἐν τῇ ἀθλήσει αὐτοῦ, τὸ στέφος ἐκομίσατο τῆς ἀφθαρσίας, ἐκ σοῦ τοῦ Θεοῦ ἡμῶν...* ^17^ | *Τοῦ Σωτῆρος κλίναντος ἐν Ἰορδάνῃ, κεφαλήν ἐθλάσθησαν, αἱ τῶν δρακόντων κεφαλαί· τοῦ Πολυεύκτου ἡ κάρα δέ, ἀποτμηθεῖσα τόν δόλιον ᾔσχυνε.* ^18^ | **Tropar:** *Mucenicul Tău, Doamne, în lupta sa...* (Troparul standard al mucenicilor). **Condac:** *Când Mântuitorul Și-a plecat capul în Iordan, capetele balaurilor au fost zdrobite; iar capul lui Polieuct, fiind tăiat, pe cel viclean l-a rușinat.* **Teme:** Identice cu cele din tradiția rusă. |' || '\n\n' ||
    '#### Works cited' || '\n\n' ||
    '1. Sf. Mc. Polieuct; Sf. Ier. Petru, Episcopul Sevastiei - Ziarul Lumina, accessed August 20, 2025, [[https://ziarullumina.ro/teologie-si-spiritualitate/sinaxar/sf-mc-polieuct-sf-ier-petru-episcopul-sevastiei-151040.html]{.underline}](https://ziarullumina.ro/teologie-si-spiritualitate/sinaxar/sf-mc-polieuct-sf-ier-petru-episcopul-sevastiei-151040.html)' || '\n' ||
    '2. 9 ianuarie Sfantul Mucenic Polieuct - Sfintele Icoane, accessed August 20, 2025, [[https://www.sfinteleicoane.ro/sfinti-ianuarie/20-sfantul-mucenic-polieuct.html]{.underline}](https://www.sfinteleicoane.ro/sfinti-ianuarie/20-sfantul-mucenic-polieuct.html)' || '\n' ||
    '3. Viața Sfântului Mucenic Polieuct | Doxologia, accessed August 20, 2025, [[https://doxologia.ro/viata-sfantului-mucenic-polieuct]{.underline}](https://doxologia.ro/viata-sfantului-mucenic-polieuct)' || '\n' ||
    '4. Sfântul Mucenic Polieuct | Calendar religios - Radio Antena Satelor, accessed August 20, 2025, [[https://www.antenasatelor.ro/lada-de-zestre/calendar-religios/sfantul-mucenic-polieuct-id19355.html]{.underline}](https://www.antenasatelor.ro/lada-de-zestre/calendar-religios/sfantul-mucenic-polieuct-id19355.html)' || '\n' ||
    '5. 9 Ianuarie - mucenicul Polieuc; cuviosul Eustratie :: Calendar ortodox - Sfintii zilei - Sinaxar - Vietile sfintilor - Sarbatori ortodoxe, accessed August 20, 2025, [[https://www.calendar-ortodox.ro/luna/ianuarie/ianuarie09.htm]{.underline}](https://www.calendar-ortodox.ro/luna/ianuarie/ianuarie09.htm)' || '\n' ||
    '6. Acatistul Sfântului Mucenic Polieuct | PDF - Scribd, accessed August 20, 2025, [[https://www.scribd.com/document/760776446/Acatistul-Sfantului-Mucenic-Polieuct]{.underline}](https://www.scribd.com/document/760776446/Acatistul-Sfantului-Mucenic-Polieuct)' || '\n' ||
    '7. Saints Polyeuct and Nearchus: Brothers by affection - Q Spirit, accessed August 20, 2025, [[https://qspirit.net/saints-polyeuct-nearchus/]{.underline}](https://qspirit.net/saints-polyeuct-nearchus/)' || '\n' ||
    '8. Martyr Polyeuktos of Melitene in Armenia - Orthodox Church in America, accessed August 20, 2025, [[https://www.oca.org/saints/lives/2011/01/09/100134-martyr-polyeuktos-of-melitene-in-armenia]{.underline}](https://www.oca.org/saints/lives/2011/01/09/100134-martyr-polyeuktos-of-melitene-in-armenia)' || '\n' ||
    '9. Άγιος Πολύευκτος - Κωνσταντινούπολη - Εγκυκλοπαίδεια Μείζονος Ελληνισμού, accessed August 20, 2025, [[http://constantinople.ehw.gr/forms/fLemmaBodyExtended.aspx?lemmaID=10917]{.underline}](http://constantinople.ehw.gr/forms/fLemmaBodyExtended.aspx?lemmaID=10917)' || '\n' ||
    '10. Εκκλησία Αγίου Πολυεύκτου • Τοποθεσία, Φωτογραφίες και Πληροφορίες σχετικά • Πολιτιστικό Απογραφή, accessed August 20, 2025, [[https://kulturenvanteri.com/el/yer/ayios-polieuktos-kilisesi/]{.underline}](https://kulturenvanteri.com/el/yer/ayios-polieuktos-kilisesi/)' || '\n' ||
    '11. Canon de rugăciune către Sfântul Mucenic Polieuct - Doxologia, accessed August 20, 2025, [[https://doxologia.ro/canon-de-rugaciune-catre-sfantul-mucenic-polieuct]{.underline}](https://doxologia.ro/canon-de-rugaciune-catre-sfantul-mucenic-polieuct)' || '\n' ||
    '12. Sfântul Mucenic Polieuct - Doxologia, accessed August 20, 2025, [[https://doxologia.ro/sfantul-mucenic-polieuct]{.underline}](https://doxologia.ro/sfantul-mucenic-polieuct)' || '\n' ||
    '13. Полиевкт Мелитинский: житие, иконы, день памяти - Азбука веры, accessed August 20, 2025, [[https://azbyka.ru/days/sv-polievkt-melitinskij]{.underline}](https://azbyka.ru/days/sv-polievkt-melitinskij)' || '\n' ||
    '14. Месяцеслов на 2025 год - 22 января. Тропари, кондаки, молитвы дня. Календарь. - Православный молитвослов, accessed August 20, 2025, [[https://xn----7sbahbba0chrecjllhdbcuymu3s.xn--p1ai/07_calendar/01/22.html]{.underline}](https://xn----7sbahbba0chrecjllhdbcuymu3s.xn--p1ai/07_calendar/01/22.html)' || '\n' ||
    '15. 9/22 Мученика Полиевкта (259). Святителя Филиппа, митрополита Московского и всея России, чудотворца (1569). Воспоминание труса (землетрясения), бывшего в Сигме (869). - Азбука веры, accessed August 20, 2025, [[https://azbyka.ru/otechnik/Pravoslavnoe_Bogosluzhenie/polnyj-troparion/6_9]{.underline}](https://azbyka.ru/otechnik/Pravoslavnoe_Bogosluzhenie/polnyj-troparion/6_9)' || '\n' ||
    '16. Мученику Полиевкту Мелитинскому (тропарь, condac și rugăciune) - ПСΑΛОМЩИКЪ - <, accessed August 20, 2025, [[http://diak.ortox.ru/__muchenikam_i_ispovednikam/view/id/1112203]{.underline}](http://diak.ortox.ru/__muchenikam_i_ispovednikam/view/id/1112203)' || '\n' ||
    '17. Άγιος Πολύευκτος - Ορθόδοξος Συναξαριστής, accessed August 20, 2025, [[https://www.saint.gr/11103/downloadpdf.aspx]{.underline}](https://www.saint.gr/11103/downloadpdf.aspx)' || '\n' ||
    '18. Ἅγιος Πολύευκτος ὁ Μάρτυρας (9 Ιανουαρίου) - Ι.Ν. Αγίας Βαρβάρας Δήμου Μεταμόρφωσης, accessed August 20, 2025, [[https://agiavarvaramet.gr/agios-polyefktos-martyras-9-ianouariou/]{.underline}](https://agiavarvaramet.gr/agios-polyefktos-martyras-9-ianouariou/)'
);