INSERT INTO core_schema.saint_lives (name_ro, life_description_ro)
VALUES (
    'Sfânta Cuvioasă Domnica',
    '# Modele de Sfințenie: Sfânta Cuvioasă Domnica (8 Ianuarie)' || '\n\n' ||
    '## Introducere: Proorocița Cetății Imperiale' || '\n\n' ||
    'Viața Sfintei Cuvioase Domnica este povestea unei transformări remarcabile, a unei călătorii spirituale care a purtat-o de pe tărâmul păgân al Africii de Nord în inima pulsantă a Imperiului Creștin, Constantinopol. Aici, prin asceză și har divin, ea a devenit o maică duhovnicească, făcătoare de minuni și proorociță, a cărui sfințenie a fost recunoscută de însăși ierarhia Bisericii.' || '\n\n' ||
    '### De la Cartagina la Constantinopol: O Călătorie a Credinței' || '\n\n' ||
    'Sfânta Domnica era de neam elin, născută în Cartagina, un important centru al Africii Romane.^32^ În timpul domniei împăratului Teodosie cel Mare (379-395), mânată de o chemare interioară, a călătorit la Constantinopol împreună cu alte patru fecioare.^32^ Sosirea ei în capitala imperiului nu a fost un eveniment întâmplător. Sursele hagiografice subliniază un detaliu ecleziologic important: Sfântul Nectarie, Patriarhul Constantinopolului (381-397), a avut o „descoperire dumnezeiască" cu privire la ea.^32^' || '\n\n' ||
    'Acest element subliniază un principiu fundamental al Ortodoxiei: recunoașterea sfințeniei este o sinergie între lucrarea tainică a lui Dumnezeu și discernământul ierarhiei Bisericii. Nu a fost o auto-proclamare a sfințeniei de către Domnica, ci recunoașterea, ghidată de Duhul Sfânt, a harului care lucra în ea de către păstorul cetății. În urma acestei revelații, Patriarhul Nectarie a primit-o, a învrednicit-o de Sfântul Botez și, ulterior, a tuns-o în monahism.^32^ Mai târziu, Sfânta Domnica a întemeiat o mănăstire închinată Sfântului Prooroc Zaharia, unde a adunat în jurul ei o obște de fecioare pe care le-a îndrumat pe calea mântuirii.^35^ Călătoria ei nu a fost, așadar, doar una geografică, ci o trecere de la păgânism la plinătatea vieții în Hristos, validată și integrată în viața Bisericii prin lucrarea arhiereului.' || '\n\n' ||
    '### Minuni de Putere și Proorocie' || '\n\n' ||
    'După ce a îmbrățișat viața monahală, Sfânta Domnica s-a dedicat unor aspre nevoințe, postului și rugăciunii, iar Dumnezeu a înzestrat-o cu daruri duhovnicești excepționale. Minunile sale atestă o putere harismatică ce se manifesta asupra naturii, a timpului și a lumii nevăzute.' || '\n\n' ||
    'Cea mai cunoscută minune este salvarea unor corăbieri prinși într-o furtună pe mare. Aflându-se în pericol de moarte, aceștia au fost mântuiți după ce sfânta a turnat untdelemn sfințit în apele învolburate, care s-au liniștit pe dată.^32^ Acest act amintește de minunea Mântuitorului, arătând că sfinții primesc putere de la Hristos pentru a stăpâni stihiile.' || '\n\n' ||
    'Pe lângă puterea asupra naturii, Sfânta Domnica a primit și darul proorociei. Ea a prevăzut moartea împăratului Teodosie și l-a înștiințat despre aceasta.^32^ De asemenea, a avut viziuni ale tainelor dumnezeiești, văzând un înger pogorându-se pentru a sfinți apele la praznicul Botezului Domnului.^32^ O altă minune, relatată în sursele grecești, demonstrează darul său de pătrundere duhovnicească. O doamnă de rang înalt, suspectând că este otrăvită de un slujitor, a venit la sfântă. Prin rugăciune, Cuvioasa Domnica a descoperit că, de fapt, era vorba de vrăjitorie, găsind în perna femeii plăcuțe metalice cu inscripții satanice. Sfânta nu doar că a demascat răul, dar l-a și adus la pocăință pe slujitorul vinovat și a îndemnat-o pe stăpână la iertare, restabilind pacea în acea casă.^38^' || '\n\n' ||
    'A trăit până la adânci bătrâneți, ajungând până în timpul domniilor împăraților Leon (457-474) și Zenon (474-491), și a trecut la Domnul în pace, cunoscându-și dinainte ceasul sfârșitului.^32^' || '\n\n' ||
    '### Cinstire și Imnografie' || '\n\n' ||
    'Cinstirea Sfintei Domnica este reflectată în imnografia și iconografia Bisericii. Troparul românesc (Glas 8) este un imn clasic închinat cuvioaselor maici, subliniind calea universală a ascezei:' || '\n\n' ||
    '„Întru tine, maică, cu osârdie s-a mântuit cel după chip; că, luând crucea, ai urmat lui Hristos; şi lucrând, ai învăţat să nu se uite la trup, căci este trecător; ci să poarte grijă de suflet, de lucrul cel nemuritor. Pentru aceasta şi cu îngerii împreună se bucură, Preacuvioasă Maică Domnica, duhul tău." ^39^' || '\n\n' ||
    'Acest tropar evidențiază tema centrală a monahismului: biruința asupra trupului trecător pentru a dobândi viața veșnică a sufletului.' || '\n\n' ||
    'Apolitichionul grecesc (Glas 4), pe de altă parte, accentuează un aspect specific al lucrării sale:' || '\n\n' ||
    '*„Ἀγάπῃ τῇ κρείττονι, καταυγασθεῖσα τόν νοῦν, ἀσκήσει ἐξέλαμψας, ὥσπερ λαμπάς φαεινή, Δομνίκα πανεύφημε· ὅθεν Μοναζουσῶν σε, ὁδηγόν φωτοφόρον, ἔδειξεν ὁ Δεσπότης, διά βίου καί λόγου. Ὧ πρέσβευε θεοφόρε, σώζεσθαι ἅπαντας."* ^40^' || '\n\n' ||
    '(Traducere: „Luminată fiind la minte de dragostea cea mai înaltă, prin asceză ai strălucit ca o făclie luminoasă, Domnica prealăudată; pentru aceasta Stăpânul te-a arătat povățuitoare purtătoare de lumină a monahiilor, prin viață și prin cuvânt. Pentru care roagă-te, purtătoare de Dumnezeu, să se mântuiască toți.")' || '\n\n' ||
    'Imnul grecesc o numește în mod explicit „povățuitoare purtătoare de lumină a monahiilor", subliniind rolul ei de stareță și îndrumătoare duhovnicească. Diferența de accent între cele două tradiții imnografice nu este una de contradicție, ci de completare, arătând diversele fațete ale sfințeniei sale. Iconografia o înfățișează ca o cuvioasă maică, adesea ținând în mână crucea, simbol al urmării lui Hristos.^42^ În evlavia populară, ea este cinstită în mod special ca ajutătoare a femeilor la naștere.^42^' || '\n\n' ||
    '#### Works cited' || '\n\n' ||
    '32. Sfânta Cuvioasă Domnica din Cartagina, care a viețuit în vremea împăratului Teodosie cel Mare (+474). - Calendar ortodox, accessed August 20, 2025, [[https://calendar.ortodox.md/calendar/entry/RO/1276]{.underline}](https://calendar.ortodox.md/calendar/entry/RO/1276)' || '\n' ||
    '33. Οσία Δομνίκη - Ορθόδοξος Συναξαριστής, accessed August 20, 2025, [[https://www.saint.gr/127/saint.aspx]{.underline}](https://www.saint.gr/127/saint.aspx)' || '\n' ||
    '34. Sf.Cuv.Domnica patroana celor nascuti 8 ianuarie-icoana - MG Argenti, accessed August 20, 2025, [[http://www.mgargenti.ro/icoane-argint-sfinti-ortodocsi-mucenite-si-cuvioase/sf-cuv-domnica-patroana-celor-nascuti-8-ianuarie-icoana--300379]{.underline}](http://www.mgargenti.ro/icoane-argint-sfinti-ortodocsi-mucenite-si-cuvioase/sf-cuv-domnica-patroana-celor-nascuti-8-ianuarie-icoana--300379)' || '\n' ||
    '35. Преподобная Домника Константинопольская, игумения - Ortox, accessed August 20, 2025, [[https://ortox.ru/sv/prepodobnaya-domnika-konstantinopolskaya-igumeniya/]{.underline}](https://ortox.ru/sv/prepodobnaya-domnika-konstantinopolskaya-igumeniya/)' || '\n' ||
    '36. Sfanta Domnica icoana - Cadouri pentru cei ce navigheaza - MG Argenti, accessed August 20, 2025, [[https://www.mgargenti.ro/icoane-ortodoxe-sfinti-nume-femei/sfanta-domnica-icoana-cadouri-pentru-cei-ce-navigheaza--280153]{.underline}](https://www.mgargenti.ro/icoane-ortodoxe-sfinti-nume-femei/sfanta-domnica-icoana-cadouri-pentru-cei-ce-navigheaza--280153)' || '\n' ||
    '37. Sfânta Cuvioasă Domnica - Doxologia, accessed August 20, 2025, [[https://doxologia.ro/sfanta-cuvioasa-domnica]{.underline}](https://doxologia.ro/sfanta-cuvioasa-domnica)' || '\n' ||
    '38. Οσία Δομνίκα, Η πλουσιοπάροχη δόξα που απέκτησε! - Pemptousia, accessed August 20, 2025, [[https://www.pemptousia.gr/2022/09/osia-domnika-i-plousioparochi-doxa-pou-apektise/]{.underline}](https://www.pemptousia.gr/2022/09/osia-domnika-i-plousioparochi-doxa-pou-apektise/)' || '\n' ||
    '39. Troparul Sfintei Cuvioase Domnica | Doxologia, accessed August 20, 2025, [[https://doxologia.ro/troparul-sfintei-cuvioase-domnica]{.underline}](https://doxologia.ro/troparul-sfintei-cuvioase-domnica)' || '\n' ||
    '40. Ὁσία Δομνίκη (8 Ιανουαρίου) - Ι.Ν. Αγίας Βαρβάρας Δήμου ..., accessed August 20, 2025, [[https://agiavarvaramet.gr/osia-domniki-8-ianouariou/]{.underline}](https://agiavarvaramet.gr/osia-domniki-8-ianouariou/)' || '\n' ||
    '41. Οσία Δομνίκη - Ορθόδοξος Συναξαριστής, accessed August 20, 2025, [[https://www.saint.gr/1127/downloadpdf.aspx]{.underline}](https://www.saint.gr/1127/downloadpdf.aspx)' || '\n' ||
    '42. Aγία Δομνίκη - Εικόνα εκκλησιαστική Αγίου Όρους - Athonian, accessed August 20, 2025, [[https://www.athonian.gr/eikones-agiou-orous/agies/agia-domniki-1/]{.underline}](https://www.athonian.gr/eikones-agiou-orous/agies/agia-domniki-1/)' || '\n' ||
    '43. Святая Преподобная Домника, Купить именную икону из янтаря ..., accessed August 20, 2025, [[https://yantar.ua/pictures/svyataya-prepodobnaya-domnika-60191.html]{.underline}](https://yantar.ua/pictures/svyataya-prepodobnaya-domnika-60191.html)'
);