INSERT INTO core_schema.saint_lives (name_ro, life_description_ro)
VALUES (
    'Sfântul Cuvios Eustratie',
    '# Un Stâlp al Olimpului: Viața, Nevoințele și Minunile Sfântului Părintelui Nostru Eustratie Făcătorul de Minuni' || '\n\n' ||
    '## Introducere: Identificarea Sfântului' || '\n\n' ||
    'În sinaxarul Bisericii Ortodoxe, la data de 9 ianuarie, este prăznuit un mare ascet și părinte duhovnicesc al secolului al IX-lea, cunoscut sub numele de Sfântul Cuvios Eustratie Făcătorul de Minuni (în greacă, *Όσιος Ευστράτιος ο Θαυματουργός*; în slavonă, *Преподобный Евстратий Чудотворец*). El este cinstit ca un model de nevoință monahală, un apărător al dreptei credințe în vremuri de prigoană și un vas ales al harului dumnezeiesc, prin care s-au săvârșit nenumărate minuni.' || '\n\n' ||
    'O analiză comparativă a tradițiilor hagiografice din diverse spații ortodoxe -- românesc, grecesc, rus și englez -- relevă o remarcabilă consecvență în relatarea vieții sale. Această unitate nu este întâmplătoare, ci provine din faptul că toate aceste sinaxare se bazează pe o singură sursă primară, o biografie grecească aproape contemporană cu sfântul, catalogată de către bolandiști sub indicativul **BHG 645**.^1^ Acest text fundamental, păstrat în manuscrisul *Sabbaiticus 242* la Biblioteca Patriarhală din Ierusalim, constituie izvorul principal al cunoașterii noastre despre viața sa.^2^ Prin urmare, prezentul studiu nu urmărește să reconcilieze narațiuni divergente, ci să expună bogăția și profunzimea unei tradiții hagiografice unitare și venerabile, așa cum a fost ea transmisă de-a lungul secolelor.' || '\n\n' ||
    '## Partea I: Calea spre Lepădarea de Lume: Din Tarsia pe Muntele Sfânt' || '\n\n' ||
    '### A. O temelie evlavioasă: Nașterea și educația (cca. 772/3 d.Hr.)' || '\n\n' ||
    'Sfântul Eustratie s-a născut într-o familie de creștini evlavioși și înstăritți din Asia Mică Bizantină, în jurul anului 772 sau 773.^5^ Sursele indică drept loc de naștere o localitate numită Vitzianí (sau Tarsia) din thema (provincia) Optimatoi, în Bitinia.^6^ Părinții săi, Gheorghe și Megheti, i-au oferit nu doar o creștere aleasă în frica de Dumnezeu, ci și o educație laică temeinică, specifică familiilor de vază ale vremii.^7^ Acest context este esențial pentru înțelegerea parcursului său duhovnicesc, deoarece sărăcia și nevoințele pe care le-a îmbrățișat mai târziu nu au fost o condiție impusă de viață, ci o alegere conștientă și radicală, o jertfă adusă lui Dumnezeu din dragoste.' || '\n\n' ||
    '### B. Focul nestins: Chemarea la monahism' || '\n\n' ||
    'La vârsta de douăzeci de ani, când mulți tineri de rangul său ar fi urmat o carieră în administrația imperială sau în armată, Eustratie a simțit în inima sa o chemare arzătoare spre o viață dedicată în întregime lui Dumnezeu. Mânat de o „râvnă dumnezeiască" și de o „dragoste aprinsă pentru Domnul", a luat hotărârea de a părăsi în taină casa părintească, renunțând la moștenire, la confort și la toate legăturile lumești pentru a urma calea îngerească a monahismului.^7^ Acest act de părăsire a lumii este un motiv clasic în hagiografie, subliniind întâietatea chemării divine asupra oricărei afecțiuni sau obligații pământești.' || '\n\n' ||
    '### C. Mănăstirea Avgarilor: Un creuzet duhovnicesc pe Muntele Olimp' || '\n\n' ||
    'Destinația tânărului Eustratie a fost renumitul centru monahal de pe Muntele Olimp al Bitiniei, un loc care, prin geografia și istoria sa, juca un rol strategic în viața Bisericii. Proximitatea față de Constantinopol, capitala imperiului, și rețeaua de drumuri care îl legau de aceasta, făceau din Muntele Olimp nu doar un loc de retragere, ci și un centru de influență teologică și politică.^1^ Mănăstirile de aici erau adevărate fortărețe spirituale, capabile să se implice în dezbaterile dogmatice ale vremii, fiind în același timp protejate de terenul abrupt și greu accesibil.^2^ Această combinație unică de izolare și accesibilitate a transformat Olimpului Bitiniei într-un bastion al Ortodoxiei, în special în timpul crizei iconoclaste.' || '\n\n' ||
    'Eustratie a ales Mănăstirea Avgarilor (sau Avgar), un așezământ ctitorit la începutul secolului al VIII-lea și închinat Sfinților Doctori fără de arginți Cosma și Damian.^1^ Aici viețuiau deja ca monahi doi unchi ai săi după mamă, Grigorie, care era și egumenul mănăstirii, și Vasile, amândoi cunoscuți pentru asceza lor.^7^ Această legătură de rudenie i-a facilitat intrarea în obște, dar nu i-a diminuat cu nimic rigoarea nevoințelor personale. Primind tunderea în monahism, a intrat în „viața cea ostenitoare și cinstită a monahilor", începând un drum de șaptezeci și cinci de ani de luptă duhovnicească.^10^' || '\n\n' ||
    '## Partea II: Războiul nevăzut: O viață de nevoințe ascetice' || '\n\n' ||
    'Viața Cuviosului Eustratie este un exemplu elocvent al modului în care asceza, în tradiția ortodoxă, nu este un scop în sine, ci o metodologie duhovnicească riguroasă, o „tehnologie spirituală" menită să curățească sufletul și să transforme trupul într-un vas curat al Duhului Sfânt. Detaliile precise și cuantificabile ale nevoințelor sale, consemnate de hagiograf, nu sunt simple descrieri, ci modele prescrise pentru cei ce doresc să urmeze aceeași cale a sfințeniei.' || '\n\n' ||
    '### A. Practica sărăciei și a smereniei radicale' || '\n\n' ||
    'Încă de la început, s-a dedicat slujirii tuturor fraților din obște cu „inimă osârdnică și cuget smerit".^7^ Sărăcia sa materială era absolută: nu poseda nimic altceva decât o singură haină aspră din păr de capră și o piele de oaie pe care dormea.^7^ Nu avea chilie personală, ci se odihnea unde se nimerea la sfârșitul zilei, demonstrând o totală lepădare de confort și o încredere deplină în purtarea de grijă a lui Dumnezeu.^10^' || '\n\n' ||
    '### B. Trupul supus pentru Dumnezeu: Austeritatea fizică' || '\n\n' ||
    'Hagiografiile sale subliniază în mod constant o practică ascetică extraordinară, care a durat întreaga sa viață monahală de 75 de ani: nu a dormit niciodată întins pe spate sau pe partea stângă, ci doar pe partea dreaptă.^7^ Această nevoință specifică și de lungă durată denotă o înțelegere profundă a trupului ca arenă a războiului duhovnicesc. Dieta sa era una dintre cele mai aspre, constând doar din pâine și apă.^12^' || '\n\n' ||
    '### C. Rugăciunea neîncetată: Respirația sufletului' || '\n\n' ||
    'Nopțile sale erau dedicate privegherilor neîntrerupte și metaniilor.^10^ În timpul tuturor slujbelor bisericești, stătea în sfântul altar și repeta neîncetat în sine rugăciunea lui Iisus: „Doamne, miluiește!" (în greacă, *Κύριε, ἐλέησον*).^9^ Această practică, centrată pe invocarea constantă a numelui divin, este o mărturie a tradiției isihaste timpurii și este prezentată ca fiind sursa directă a puterii sale duhovnicești. Legătura cauzală dintre această disciplină spirituală și fizică intensă și darul ulterior al facerii de minuni este una dintre lecțiile centrale ale vieții sale: harul divin lucrează prin efortul uman (sinergie), iar sfințenia este rodul unei lupte de o viață.' || '\n\n' ||
    '## Partea III: Un Păstor în Furtuna Iconoclasmului' || '\n\n' ||
    '### A. O conducere acceptată din ascultare: Alegerea ca egumen' || '\n\n' ||
    'După adormirea în Domnul a unchilor săi, Grigorie și Vasile, și a succesorului acestora, Eustatie, obștea mănăstirii l-a rugat cu insistență pe Cuviosul Eustratie să preia conducerea duhovnicească. Deși se considera nevrednic, a acceptat egumenia din ascultare și din dragoste pentru frați, devenind păstorul lor într-o perioadă de mari încercări pentru Biserică.^7^' || '\n\n' ||
    '### B. Mărturisirea credinței: Prigoana sub Leon al V-lea Armeanul (813-820)' || '\n\n' ||
    'Contextul istoric al egumeniei sale a fost marcat de cel de-al doilea val al iconoclasmului, inițiat de împăratul Leon al V-lea Armeanul. Aceasta a fost o perioadă de prigoană aprigă împotriva ortodocșilor, în special a monahilor, care erau cei mai fermi apărători ai cinstirii sfintelor icoane.^7^' || '\n\n' ||
    'La îndemnul marelui ascet contemporan, Sfântul Ioanichie cel Mare, cu care a legat o prietenie duhovnicească, Eustratie a părăsit mănăstirea pentru a se refugia de furia prigonitorilor. A pribegit prin munți și pustietăți, ascunzându-se în peșteri și locuri greu accesibile.^7^ În cele din urmă, a fost prins și dus la Constantinopol, unde a fost întemnițat și a suferit multe batjocuri și chinuri pentru credința sa ortodoxă, mărturisindu-L astfel pe Hristos nu doar prin asceză, ci și prin pătimire.^9^' || '\n\n' ||
    '### C. Triumful Ortodoxiei și întoarcerea acasă' || '\n\n' ||
    'După asasinarea lui Leon al V-lea și, în cele din urmă, după restaurarea definitivă a cinstirii icoanelor, cunoscută ca Triumful Ortodoxiei (anul 843), Cuviosul Eustratie s-a întors la Mănăstirea Avgarilor și și-a reluat îndatoririle de egumen, continuând să-și păstorească turma cu înțelepciune și dragoste.^7^' || '\n\n' ||
    '## Partea IV: Arătarea Harului Dumnezeiesc: Minunile Făcătorului de Minuni' || '\n\n' ||
    'Nevoințele sale îndelungate și smerenia sa adâncă l-au făcut un vas ales al Duhului Sfânt, iar virtuțile sale lăuntrice s-au manifestat în exterior sub forma unor puteri supranaturale. Minunile sale nu sunt simple acte de putere, ci expresii ale dragostei și milei sale desăvârșite.' || '\n\n' ||
    '### A. Minunea milosteniei radicale' || '\n\n' ||
    'Generozitatea sa izvora dintr-o totală detașare de cele materiale. Își dădea haina de pe el unui sărac sau calul său unui soldat aflat la ananghie.^9^ Într-un act de credință absolută în providența divină, a dăruit singurul bou al mănăstirii unui țăran sărman care și-l pierduse pe al său.^9^ Întorcându-se odată de la Constantinopol cu o sumă mare de bani primită de la împărat pentru nevoile mănăstirii, a împărtit toți banii săracilor pe care i-a întâlnit pe drum, înainte de a ajunge la porțile propriei mănăstiri.^9^' || '\n\n' ||
    '### B. Minunea autorității duhovnicești: Purtarea păcatelor altuia' || '\n\n' ||
    'Cea mai profundă și rară dintre minunile sale este cea a asumării păcatelor unui om deznădăjduit. Găsind pe drum un bărbat care, copleșit de mulțimea păcatelor sale, se pregătea să se spânzure, Sfântul Eustratie a intervenit. A luat mâna acelui om, a pus-o pe grumazul său și a rostit cuvinte de o putere duhovnicească cutremurătoare: „De acum înainte, fiule, asupra mea să fie greutatea păcatelor tale. În ziua Judecății, eu voi răspunde pentru ele în locul tău. Tu doar aruncă funia aceasta și nădăjduiește în Dumnezeu".^8^' || '\n\n' ||
    'Acest act extraordinar este o mărturie a stării de *theosis* (îndumnezeire) la care ajunsese sfântul. Asumându-și păcatele altuia, Cuviosul Eustratie nu manifestă doar o compasiune omenească, ci participă în mod direct la lucrarea preoțească și mântuitoare a lui Hristos Însuși, Cel care „a purtat păcatele noastre în trupul Său, pe lemn". Această minune reprezintă punctul culminant al teologiei vieții sale, dezvăluind că scopul final al ascezei nu este doar mântuirea personală, ci și participarea activă, prin har, la mântuirea aproapelui.' || '\n\n' ||
    '### C. Minunea puterii asupra bolii, naturii și morții' || '\n\n' ||
    'Sursele afirmă că a săvârșit „nenumărate minuni", printre care vindecarea bolnavilor, stingerea incendiilor și chiar învierea morților.^8^ O relatare specifică descrie salvarea unei corăbii. În timpul unei călătorii pe Marea Marmara (Propontida), corabia a lovit o stâncă și a început să ia apă. Prin rugăciunile sfântului, gaura din corabie s-a oprit din a mai lăsa apa să intre până când toți pasagerii au debarcat în siguranță. Imediat ce cuviosul a pășit pe uscat, corabia s-a scufundat, arătând că doar prezența sa o menținuse la suprafață.^8^' || '\n\n' ||
    '## Partea V: Fericita Adormire și Vederarea Peste Veacuri' || '\n\n' ||
    '### A. Testamentul final: O moștenire în cuvinte' || '\n\n' ||
    'Simțindu-și sfârșitul aproape, la venerabila vârstă de 95 de ani, și-a adunat ucenicii și le-a lăsat ultimul său cuvânt de învățătură, o sinteză a întregii sale vieți monahale: „S-a sfârșit vremea vieții mele; de aceea, fiii mei iubiți, păziți legământul pe care l-ați primit, știind că toate cele de acum sunt trecătoare, iar cele viitoare vor fi veșnice; sârguiți-vă să vă învredniciți de partea celor mântuiți".^10^' || '\n\n' ||
    '### B. O viață împlinită: Trecerea în pace la Domnul (cca. 867/8 d.Hr.)' || '\n\n' ||
    'După ce și-a binecuvântat ucenicii, și-a ridicat ochii spre cer și a rostit cuvintele Mântuitorului: „În mâinile Tale, Doamne, încredințez duhul meu!", și astfel a adormit în pace.^9^ A trăit 95 de ani, dintre care 75 i-a petrecut în neîncetate nevoințe monahale.' || '\n\n' ||
    '### C. Cinstirea și imnografia' || '\n\n' ||
    'Biserica Ortodoxă îl prăznuiește pe Sfântul Cuvios Eustratie Făcătorul de Minuni în fiecare an, la data de 9 ianuarie.^7^' || '\n\n' ||
    '## Anexă: Imnografia Sfântului Cuvios Eustratie (9 ianuarie)' || '\n\n' ||
    '**Tabelul 1: Tropare și Condace pentru Sfântul Cuvios Eustratie Făcătorul de Minuni**' || '\n\n' ||
    '| Limba | Tip | Text | Sursa(e) |' || '\n' ||
    '| :--- | :--- | :--- | :--- |' || '\n' ||
    '| Engleză | Tropar (Glasul 8) | „By a flood of tears you made the desert fertile, / and your longing for God brought forth fruits in abundance. / By the radiance of miracles you illumined the whole universe! / O our holy father Eustratius, pray to Christ our God to save our souls!" | ^24^ |' || '\n' ||
    '| Greacă | Apolytikion (Glasul 8) | *(Notă: Troparul standard folosit în practica greacă este echivalentul celui din limba engleză, pe Glasul 8. Sursele care indică un alt tropar se referă, de regulă, la Sfântul Mucenic Eustratie din 13 decembrie.)* | ^18^ |' || '\n' ||
    '| Slavonă Bisericească/Rusă | Tropar | *(Notă: În sursele rusești consultate nu a fost identificat un tropar specific pentru Sfântul Eustratie de la Olimp. În astfel de cazuri, practica liturgică utilizează un tropar comun pentru un sfânt cuvios.)* | ^26^ |' || '\n' ||
    '| Română | Tropar/Condac | *(Notă: În sursele românești nu a fost găsit un tropar sau condac specific. Slujba sa este adesea combinată cu cea a Sfântului Mucenic Polieuct, pomenit în aceeași zi, sau se folosește o slujbă comună a cuvioșilor.)* | ^29^ |' || '\n\n' ||
    '#### Works cited' || '\n\n' ||
    '1. dergipark.org.tr, accessed August 20, 2025, [[https://dergipark.org.tr/en/pub/awa/issue/87730/1570805#:~:text=The%20spreading%20of%20monks%20at,to%20Saints%20Cosmas%20and%20Damianos.]{.underline}](https://dergipark.org.tr/en/pub/awa/issue/87730/1570805#:~:text=The%20spreading%20of%20monks%20at,to%20Saints%20Cosmas%20and%20Damianos.)' || '\n' ||
    '2. The Monastery of Agaurwn at Mount Olympus in Bithynia Through the Life of Saint Eustratios (BHG 645) - DergiPark, accessed August 20, 2025, [[https://dergipark.org.tr/en/pub/awa/issue/87730/1570805]{.underline}](https://dergipark.org.tr/en/pub/awa/issue/87730/1570805)' || '\n' ||
    '3. The Monastery of Agaurwn at Mount Olympus in Bithynia Through the Life of Saint Eustratios (BHG 645) - DergiPark, accessed August 20, 2025, [[https://dergipark.org.tr/en/download/article-file/4302822]{.underline}](https://dergipark.org.tr/en/download/article-file/4302822)' || '\n' ||
    '4. Life of Eustratios of Agaurwn (BHG 645): introduction, critical edition of the text, translation and commentary - OpenArchives.gr, accessed August 20, 2025, [[https://www.openarchives.gr/aggregator-openarchives/edm/phdtheses/000040-10442_44987?language=en]{.underline}](https://www.openarchives.gr/aggregator-openarchives/edm/phdtheses/000040-10442_44987?language=en)' || '\n' ||
    '5. Евстратий Тарсийский - Википедия, accessed August 20, 2025, [[https://ru.wikipedia.org/wiki/%D0%95%D0%B2%D1%81%D1%82%D1%80%D0%B0%D1%82%D0%B8%D0%B9_%D0%A2%D0%B0%D1%80%D1%81%D0%B8%D0%B9%D1%81%D0%BA%D0%B8%D0%B9]{.underline}](https://ru.wikipedia.org/wiki/%D0%95%D0%B2%D1%81%D1%82%D1%80%D0%B0%D1%82%D0%B8%D0%B9_%D0%A2%D0%B0%D1%80%D1%81%D0%B8%D0%B9%D1%81%D0%BA%D0%B8%D0%B9)' || '\n' ||
    '6. Ο βίος του Αγίου Ευστρατίου Αγαύρων (BHG 645): εισαγωγή, κριτική έκδοση, μετάφραση, σχολιασμός - Εθνικό Αρχείο Διδακτορικών Διατριβών, accessed August 20, 2025, [[https://www.didaktorika.gr/eadd/handle/10442/44987]{.underline}](https://www.didaktorika.gr/eadd/handle/10442/44987)' || '\n' ||
    '7. Όσιος Ευστράτιος ο Θαυματουργός - Ορθόδοξος Συναξαριστής, accessed August 20, 2025, [[https://www.saint.gr/1102/saint.aspx]{.underline}](https://www.saint.gr/1102/saint.aspx)' || '\n' ||
    '8. «Синаксарь», составленный афонским иеромонахом Макарием ..., accessed August 20, 2025, [[https://azbyka.ru/otechnik/Makarij-Simonopetrskij-Bonne/sinaksar-sostavlennyj-afonskim-ieromonahom-makariem-iz-obiteli-simonopetra-tom-3/9_5]{.underline}](https://azbyka.ru/otechnik/Makarij-Simonopetrskij-Bonne/sinaksar-sostavlennyj-afonskim-ieromonahom-makariem-iz-obiteli-simonopetra-tom-3/9_5)' || '\n' ||
    '9. Synaxarion of Saint Eustratios the Wonderworker (January 9th) : r/OrthodoxChristianity - Reddit, accessed August 20, 2025, [[https://www.reddit.com/r/OrthodoxChristianity/comments/107j0le/synaxarion_of_saint_eustratios_the_wonderworker/]{.underline}](https://www.reddit.com/r/OrthodoxChristianity/comments/107j0le/synaxarion_of_saint_eustratios_the_wonderworker/)' || '\n' ||
    '10. Viața Sfântului Cuvios Eustratie | Doxologia, accessed August 20, 2025, [[https://doxologia.ro/viata-sfantului-cuvios-eustratie]{.underline}](https://doxologia.ro/viata-sfantului-cuvios-eustratie)' || '\n' ||
    '11. Евстратий - преподобный | Жития святых Дмитрия Ростовского, accessed August 20, 2025, [[https://idrp.ru/content/article/zhitiya-svyatih-lib101/]{.underline}](https://idrp.ru/content/article/zhitiya-svyatih-lib101/)' || '\n' ||
    '12. Saint Eustratius the Wonderworker - Orthodox Church in America, accessed August 20, 2025, [[https://www.oca.org/saints/lives/1950/01/09/100138-saint-eustratius-the-wonderworker]{.underline}](https://www.oca.org/saints/lives/1950/01/09/100138-saint-eustratius-the-wonderworker)' || '\n' ||
    '13. THE VENERABLE EUSTRATIUS - January 9 - Orthodox Net, accessed August 20, 2025, [[https://www.orthodox.net/menaion-january/09-the-venerable-eustratius.html]{.underline}](https://www.orthodox.net/menaion-january/09-the-venerable-eustratius.html)' || '\n' ||
    '14. Ὅσιος Εὐστράτιος ὁ Θαυματουργός (9 Ιανουαρίου), accessed August 20, 2025, [[https://agiosgeorgiosparalimniou.org.cy/index.php/iera-paradosi/vioiagion/10248-osios-eustratios-thavmatourgos-9-ianouariou]{.underline}](https://agiosgeorgiosparalimniou.org.cy/index.php/iera-paradosi/vioiagion/10248-osios-eustratios-thavmatourgos-9-ianouariou)' || '\n' ||
    '15. Venerable Eustratius the Wonderworker (9th c.) - Ancient Faith Ministries, accessed August 20, 2025, [[https://www.ancientfaith.com/podcasts/saintoftheday/45695/]{.underline}](https://www.ancientfaith.com/podcasts/saintoftheday/45695/)' || '\n' ||
    '16. Sfântul Cuvios Eustratie - Doxologia, accessed August 20, 2025, [[https://doxologia.ro/sfantul-cuvios-eustratie]{.underline}](https://doxologia.ro/sfantul-cuvios-eustratie)' || '\n' ||
    '17. Όσιος Ευστράτιος - 9 Ιανουαρίου - Βίοι Αγίων - Εορτολόγιο - YouTube, accessed August 20, 2025, [[https://www.youtube.com/watch?v=tXvqoOKe2yY]{.underline}](https://www.youtube.com/watch?v=tXvqoOKe2yY)' || '\n' ||
    '18. Απολυτίκιο Αγίου Ευστρατίου - 13 ΔΕΚΕΜΒΡΙΟΥ | Δημήτριος Παπαγιαννόπουλος, accessed August 20, 2025, [[https://www.youtube.com/watch?v=gf-hIIsmdpo]{.underline}](https://www.youtube.com/watch?v=gf-hIIsmdpo)' || '\n' ||
    '19. Απολυτίκιο Αγ. Ευστρατίου, Αυξεντίου, Ευγενίου, Μαρδαρίου και Ορέστη - 13 ΔΕΚΕΜΒΡΙΟΥ, accessed August 20, 2025, [[https://www.youtube.com/watch?v=BBp_77qKwHM]{.underline}](https://www.youtube.com/watch?v=BBp_77qKwHM)' || '\n' ||
    '20. Άγιοι Ευστράτιος, Αυξέντιος, Ευγένιος, Μαρδάριος και Ορέστης - Ορθόδοξος Συναξαριστής, accessed August 20, 2025, [[https://www.saint.gr/3258/saint.aspx]{.underline}](https://www.saint.gr/3258/saint.aspx)' || '\n' ||
    '21. Άγιος Ευστράτιος ο Μάρτυρας - Αγιορείτικη θρησκευτική εικόνα - Athonian, accessed August 20, 2025, [[https://www.athonian.gr/eikones-agiou-orous/agioi/agios-efstratios-1/]{.underline}](https://www.athonian.gr/eikones-agiou-orous/agioi/agios-efstratios-1/)' || '\n' ||
    '22. Εικόνα Άγιος Ευστράτιος Χειροποίητη - ekivotos.com, accessed August 20, 2025, [[https://www.ekivotos.com/el/eikona-agios-eustratios-xeiropoiiti]{.underline}](https://www.ekivotos.com/el/eikona-agios-eustratios-xeiropoiiti)' || '\n' ||
    '23. Άγιος Ευστράτιος -- Εικονογραφίες | Εικόνες & Αγιογραφίες, accessed August 20, 2025, [[https://agiografies.info/portfolio/agios-eystratios/]{.underline}](https://agiografies.info/portfolio/agios-eystratios/)' || '\n' ||
    '24. Saint Eustratius the Wonderworker - Troparion & Kontakion - Orthodox Church in America, accessed August 20, 2025, [[https://www.oca.org/saints/troparia/2023/01/09/100138-saint-eustratius-the-wonderworker]{.underline}](https://www.oca.org/saints/troparia/2023/01/09/100138-saint-eustratius-the-wonderworker)' || '\n' ||
    '25. Troparia and kontakia for January 9 - Orthodox Church in America, accessed August 20, 2025, [[https://www.oca.org/saints/troparia/2025/01/09]{.underline}](https://www.oca.org/saints/troparia/2025/01/09)' || '\n' ||
    '26. Преподобному Иову, Ущельскому чудотворцу (тропарь, кондак, молитва и величание), accessed August 20, 2025, [[http://diak.ortox.ru/*_prepodobnym/view/id/1214817]{.underline}](http://diak.ortox.ru/*_prepodobnym/view/id/1214817)' || '\n' ||
    '27. Месяцеслов на 2025 год - 10 апреля. Тропари, кондаки, молитвы дня. Календарь. - Православный молитвослов, accessed August 20, 2025, [[https://xn----7sbahbba0chrecjllhdbcuymu3s.xn--p1ai/07_calendar/04/10.html]{.underline}](https://xn----7sbahbba0chrecjllhdbcuymu3s.xn--p1ai/07_calendar/04/10.html)' || '\n' ||
    '28. ПСΑΛОМЩИКЪ - - Ortox, accessed August 20, 2025, [[http://diak.ortox.ru/__muchenikam_i_ispovednikam]{.underline}](http://diak.ortox.ru/__muchenikam_i_ispovednikam)' || '\n' ||
    '29. (VIDEO) Troparul Sfântului Mucenic Polieuct (9 ianuarie) - YouTube, accessed August 20, 2025, [[https://www.youtube.com/watch?v=ESFACeMAaNk]{.underline}](https://www.youtube.com/watch?v=ESFACeMAaNk)' || '\n' ||
    '30. 9 Ianuarie - mucenicul Polieuc; cuviosul Eustratie :: Calendar ortodox - Sfintii zilei - Sinaxar - Vietile sfintilor - Sarbatori ortodoxe, accessed August 20, 2025, [[https://www.calendar-ortodox.ro/luna/ianuarie/ianuarie09.htm]{.underline}](https://www.calendar-ortodox.ro/luna/ianuarie/ianuarie09.htm)' || '\n' ||
    '31. test - Uniti Schimbam, accessed August 20, 2025, [[https://www.unitischimbam.ro/test/page/380/]{.underline}](https://www.unitischimbam.ro/test/page/380/)'
);