INSERT INTO core_schema.saint_lives (name_ro, life_description_ro)
VALUES (
    'Sfântul Dimitrie cel Nou',
    '# Raport de Cercetare Exhaustiv: Hagiografia, Istoria, Cultul și Iconografia Sfântului Cuvios Dimitrie cel Nou, Ocrotitorul Bucureștilor' || '\n\n' ||
    '## Rezumat Executiv' || '\n\n' ||
    'Prezentul document constituie o analiză fundamentală și detaliată dedicată Sfântului Cuvios Dimitrie cel Nou (Basarabov), destinată integrării într-o aplicație mobilă cu caracter religios-educativ. Raportul sintetizează date hagiografice, istorice, liturgice și iconografice, extrase dintr-un corpus vast de surse documentare, pentru a oferi dezvoltatorului o bază de date narativă completă. Analiza evidențiază transformarea unui păstor smerit din secolul al XIII-lea în patronul spiritual al capitalei României, explorând în profunzime episoadele istorice cruciale (Războiul Ruso-Turc din 1768-1774, epidemiile de ciumă și holeră), detaliile artistice ale raclei de argint și structura complexă a pelerinajului contemporan.' || '\n\n' ||
    '## Capitolul I: Cadrul Istoric și Geopolitic al Secolului al XIII-lea' || '\n\n' ||
    '### 1.1. Contextul Vlaho-Bulgar' || '\n\n' ||
    'Sfântul Cuvios Dimitrie cel Nou a trăit în veacul al XIII-lea, o perioadă de profundă transformare politică și spirituală în Peninsula Balcanică. Sursele istorice și hagiografice îl plasează temporal în timpul Imperiului de la Târnovo (Țaratul Vlaho-Bulgar, 1185--1396), o entitate statală întemeiată prin revolta fraților Petru și Asan.^1^ Această încadrare nu este doar cronologică, ci și identitară. Hagiografia subliniază explicit originea sa etnică: Sfântul era „vlah" (român) de neam, născut în satul Basarabov (sau Basarabi), situat pe valea râului Lom, în apropierea cetății Ruse (actualmente în Bulgaria).^1^' || '\n\n' ||
    'Această apartenență la neamul românesc din sudul Dunării, menționată de istorici precum Pr. Prof. Mircea Păcurariu în lucrările despre „Sfinți dacoromani", explică legătura organică și rapiditatea cu care cultul său a fost asimilat ulterior la nord de Dunăre.^1^ Satul Basarabov, așezat într-o zonă de contact cultural și etnic, a devenit astfel punctul de geneză al unei spiritualități isihaste specifice acelei epoci.' || '\n\n' ||
    '### 1.2. Profilul Social și Spiritual Inițial' || '\n\n' ||
    'Provenind dintr-o familie de țărani săraci ^4^, Dimitrie nu a avut acces la o educație scolastică formală, ci a urmat „școala pustiei" și a muncii simple. Îndeletnicirea sa inițială a fost aceea de păstor; el păștea oile și vitele sătenilor din Basarabov pe câmpurile din lunca Lomului.^1^ Această ocupație, recurentă în biografiile marilor sfinți biblici și patristici (de la Moise și David până la păstorii din Betleem), i-a oferit cadrul propice pentru rugăciune neîncetată și contemplare.^1^' || '\n\n' ||
    'Deși resursele sale materiale erau extrem de limitate, tradiția consemnează o milostenie ieșită din comun: din puținul pe care îl primea ca plată de la proprietarii vitelor, o parte o dăruia celor și mai săraci decât el.^1^ Această atitudine denotă o înțelegere timpurie a evangheliei, transcendând condiția socială prin virtute.' || '\n\n' ||
    '## Capitolul II: Hagiografia Detaliată -- De la Păstor la Anahoret' || '\n\n' ||
    '### 2.1. Episodul „Cuibul de Pasăre": O Teologie a Sensibilității' || '\n\n' ||
    'Unul dintre cele mai impresionante episoade din viața Sfântului, esențial pentru înțelegerea profilului său psihologic și duhovnicesc, este incidentul cuibul de pasăre. În timp ce păștea vitele, Dimitrie a călcat din greșeală pe un pui de pasăre ascuns în iarbă, strivindu-l.^1^' || '\n\n' ||
    'Reacția sa la acest accident aparent minor dezvăluie o conștiință extrem de fină. Copleșit de durere pentru distrugerea unei vieți create de Dumnezeu, Dimitrie și-a impus un canon de o asprime rară: timp de trei ani, a umblat desculț cu piciorul care strivise puiul.^1^ A îndurat gerul iernilor balcanice, arșița verii și rănile provocate de pietre și mărăcini, oferind această suferință fizică ca act de pocăință. Teologul Dumitru Stăniloae comenta acest episod ca fiind o dovadă a „fineții" și „delicateții" specifice sfinților, oameni care au depășit orice urmă de egoism și violență interioară.^1^ Acest detaliu hagiografic a influențat direct iconografia ulterioară, sfântul fiind adesea reprezentat cu un picior sau ambele picioare goale.^7^' || '\n\n' ||
    '### 2.2. Retragerea în Monahism și Viața Eremitică' || '\n\n' ||
    'Simțind chemarea spre o viață dedicată exclusiv lui Dumnezeu, Dimitrie a părăsit comunitatea și a intrat într-o mănăstire din zonă.^1^ Totuși, dorul de liniște absolută (isiha) l-a determinat să aleagă calea anahoretismului. S-a retras într-o peșteră săpată în stâncile abrupte de pe malul râului Lom, un mediu ostil și izolat.^1^' || '\n\n' ||
    'În această peșteră, Sfântul Dimitrie a dus o luptă nevăzută, petrecând în post strict și rugăciune neîncetată, necunoscut de oameni. Finalul vieții sale pământești este marcat de aceeași discreție: simțindu-și sfârșitul aproape prin descoperire divină, s-a așezat între două lespezi de piatră, care i-au servit drept sicriu și pat de moarte, și și-a încredințat sufletul lui Dumnezeu în singurătate.^1^' || '\n\n' ||
    '## Capitolul III: Descoperirea Moaștelor și Fenomenologia Primelor Minuni' || '\n\n' ||
    '### 3.1. Taina Apelor și Revelația' || '\n\n' ||
    'Trupul Sfântului a rămas ascuns în peșteră pentru o lungă perioadă de timp -- sursele variază între trei secole ^9^ și cinci secole.^6^ În acest interval, apele râului Lom au inundat peștera, acoperind sfintele moaște cu prund și mâl.^5^ Descoperirea lor nu a fost rezultatul hazardului, ci al unei intervenții miraculoase.' || '\n\n' ||
    'Tradiția relatează că o copilă din satul Basarabov, care pătimea de un duh necurat (demonizată), a avut un vis în care Sfântul i s-a arătat, spunându-i: „Dacă părinții tăi mă vor scoate din apă, eu te voi tămădui".^5^' || '\n\n' ||
    '### 3.2. Scoaterea la Lumină și Prima Vindecare' || '\n\n' ||
    'Călăuziți de visul copilei și, conform unor relatări, de o lumină cerească ce strălucea deasupra apei, sătenii și preoții au mers la locul indicat. Au descoperit trupul neputrezit, acoperit de aluviuni, dar răspândind o bună-mireasmă.^11^ În momentul atingerii de sfintele moaște, copila s-a vindecat instantaneu, aceasta fiind prima minune publică a Sfântului Dimitrie după adormirea sa.^5^' || '\n\n' ||
    '### 3.3. Refuzul de a Părăsi Basarabovul (Prima Tentativă)' || '\n\n' ||
    'Vestea minunilor s-a răspândit rapid în Balcani și la nord de Dunăre. Un domnitor al Țării Românești (neidentificat nominal, dar anterior perioadei fanariote târzii) a dorit să aducă moaștele la București. Delegația trimisă a ridicat moaștele, dar carul cu boi s-a oprit inexplicabil la o fântână aproape de Rusciuc (Ruse) și nu a mai putut fi clintit.^10^' || '\n\n' ||
    'Interpretând acest blocaj ca un semn divin, preoții au recurs la o metodă biblică (similară cu aducerea Chivotului Legii): au înjugat doi juncani tineri și neînvățați, lăsându-i liberi să meargă unde va voi Sfântul. Animalele s-au întors singure, fără a fi mânate, în mijlocul satului Basarabov.^10^ Înțelegând voia Sfântului, domnitorul a ctitorit o biserică nouă în Basarabov pentru a adăposti moaștele, unde acestea au rămas cinstite timp de secole.^1^' || '\n\n' ||
    '## Capitolul IV: Translatio Reliquiarum -- 1774: Context și Protagoniști' || '\n\n' ||
    'Momentul crucial pentru istoria religioasă a Bucureștiului a survenit în contextul Războiului Ruso-Turc din 1768--1774, un conflict major care a afectat profund Principatele Române și teritoriile de la sud de Dunăre.' || '\n\n' ||
    '### 4.1. Generalul Petru Saltikov vs. Ivan Saltikov' || '\n\n' ||
    'Există o dezbatere istoriografică privind identitatea generalului rus care a dispus ridicarea moaștelor. Sursele bisericești românești îl menționează preponderent pe generalul **Petru Saltikov** (sau Saltâcov).^3^ Alte surse istorice și biografice indică faptul că feldmareșalul **Ivan Petrovici Saltikov** (fiul lui Piotr Semionovici Saltikov) a fost cel activ în campaniile din 1768-1774 și 1787-1792.^13^ Este plauzibil ca tradiția să fi reținut numele tatălui sau să existe o confuzie onomastică, însă acțiunea istorică rămâne certă: un general rus, ajungând în Basarabov și găsind satul devastat sau în pericol, a decis protejarea moaștelor.' || '\n\n' ||
    'Motivația generalului a fost una de protecție: pentru a preveni profanarea sfintelor moaște de către trupele otomane (musulmane), acesta a poruncit ca racla să fie transportată în Rusia.^3^' || '\n\n' ||
    '### 4.2. Rolul Negustorului Hagi Dimitrie' || '\n\n' ||
    'Când cortegiul funerar a ajuns la București, în iulie 1774, a avut loc o intervenție providențială. Un negustor bogat și influent, **Hagi Dimitrie**, descris ca fiind macedo-român și având rangul de „biv vel sluger" (fost mare sluger), avea relații apropiate cu comandamentul armatei ruse.^3^' || '\n\n' ||
    'Hagi Dimitrie, împreună cu **Mitropolitul Grigorie al II-lea** al Țării Românești (1760--1787), s-a prezentat în fața generalului Saltikov cu o rugăminte fierbinte. Argumentația lor a fost dublă, bazată pe dreptate istorică și compasiune:' || '\n\n' ||
    '1.  **Mângâiere pentru Popor:** Țara Românească suferise pagube materiale imense și pierderi de vieți omenești din cauza războiului purtat pe teritoriul ei. Moaștele ar fi servit ca o „mângâiere" morală și spirituală pentru poporul greu încercat.^3^' || '\n' ||
    '2.  **Originea Etnică:** S-a subliniat faptul că Sfântul era „valah" (român) de neam, deci locul său firesc era printre români.^3^' || '\n\n' ||
    '### 4.3. Acordul și Instalarea la București' || '\n\n' ||
    'Generalul rus a fost impresionat de aceste argumente și, dând dovadă de evlavie, a acceptat să lase trupul Sfântului la București. Totuși, a păstrat pentru sine și pentru Rusia o parte din moaște: mâna dreaptă a Sfântului Dimitrie, care a fost trimisă la Kiev (la Lavra Peșterilor), unde se crede că se păstrează și astăzi.^3^' || '\n\n' ||
    'Moaștele au fost așezate cu mare cinste în Catedrala Mitropolitană din București în luna **iulie 1774**.^3^ De la acea dată, Sfântul Dimitrie cel Nou a devenit protectorul spiritual al orașului, deși proclamarea oficială ca „Ocrotitor al Bucureștilor" a fost făcută mai târziu, de către Mitropolitul Filaret al II-lea (1792-1793).^16^' || '\n\n' ||
    '## Capitolul V: Tezaurul Artistic -- Istoria și Descrierea Raclelor' || '\n\n' ||
    'Prezența Sfântului la București a impus realizarea unor racle pe măsura cinstei acordate. Istoria consemnează trei etape distincte în protejarea moaștelor.' || '\n\n' ||
    '### 5.1. Evoluția Raclelor (1774--Prezent)' || '\n\n' ||
    '1.  **Prima Raclă (1774 -- cca. 1864):** Inițial, moaștele au fost păstrate în racla de lemn cu care fuseseră aduse de la Basarabov. Informațiile despre aceasta sunt modeste, fiind menționată sumar în jurnalele de epocă.^18^' || '\n' ||
    '2.  **A Doua Raclă (1864 -- 1879):** În timpul păstoririi Mitropolitului Nifon Rusăilă (sau Grigorie al II-lea, sursele fiind ușor divergente privind gradul de suprapunere), s-a confecționat o nouă raclă de lemn, îmbrăcată parțial în tablă de argint și zinc, capitonată cu catifea. O fâșie de argint în formă de cruce din această raclă a fost conservată și montată ulterior în interiorul capacului raclei actuale.^18^' || '\n' ||
    '3.  **Racla Actuală (1879 -- Prezent):** Este capodopera de argint care adăpostește astăzi moaștele. A fost realizată la inițiativa Episcopului Ghenadie Petrescu al Argeșului (viitor Mitropolit Primat), fiind finalizată în decembrie 1879 și donată Mitropoliei în ianuarie 1880.^18^' || '\n\n' ||
    '### 5.2. Analiza Artistică și Tehnică a Raclei Actuale' || '\n\n' ||
    'Racla din 1879 este un monument de artă ecleziastică, realizat din argint masiv de înaltă puritate („proba 14").' || '\n\n' ||
    '**Specificații Tehnice:**' || '\n\n' ||
    '- **Greutate:** Aproximativ 27 ocale și 100 dramuri (unități vechi), o cantitate impresionantă de metal prețios.^19^' || '\n' ||
    '- **Cost:** 22.800 lei (la valoarea din 1880), sumă strânsă prin subscripție publică și contribuția personală a episcopului Ghenadie, lista donatorilor fiind publicată în Monitorul Oficial nr. 35/1880.^18^' || '\n\n' ||
    '**Programul Iconografic:** Decorația este realizată în relief (repoussé), cu elemente poleite cu aur, structurată astfel ^14^:' || '\n\n' ||
    '| **Element** | **Detalii Iconografice** |' || '\n' ||
    '| :--- | :--- |' || '\n' ||
    '| **Capacul** | Chipul Sfântului Dimitrie în mărime naturală, înconjurat de un grilaj auriu. |' || '\n' ||
    '| **Marginea** | 12 Serafimi (6 pe fiecare latură), separați de stâlpișori de argint. |' || '\n' ||
    '| **Frontispiciu** | Icoana Sfintei Treimi și scena Încoronării Maicii Domnului. |' || '\n' ||
    '| **Baza** | Arhanghelul Gavriil ținând semnul Bunei Vestiri. |' || '\n' ||
    '| **Laturile** | 8 scene narative din viața Sfântului (păstoritul, descoperirea, minunile), separate de coloane. |' || '\n' ||
    '| **Picioarele** | Patru picioare masive din argint, stilizate (labe de leu). |' || '\n\n' ||
    'Moaștele sunt înveșmântate în haine prețioase, având pe cap o mitră de argint și o coroană poleită cu aur.^19^' || '\n\n' ||
    '## Capitolul VI: Cronica Minunilor -- Taumaturgia Istorică și Contemporană' || '\n\n' ||
    'Sfântul Dimitrie cel Nou și-a câștigat titlul de „Ocrotitor" prin intervenții directe în momentele critice ale istoriei Bucureștiului.' || '\n\n' ||
    '### 6.1. Marile Minuni Istorice (Salvarea Cetății)' || '\n\n' ||
    '**Ciuma lui Caragea (1813-1814)** În timpul domniei lui Ioan Gheorghe Caragea, o epidemie devastatoare de ciumă bubonică a lovit Țara Românească. Bucureștiul era un oraș al morții, cu zeci de victime zilnic. La disperarea domnitorului și a poporului, călugării de la Mănăstirea „Sfinții Împărați Constantin și Elena" au scos racla în procesiune, ocolind orașul. Cronicile vremii atestă că, din ziua procesiunii, numărul morților a scăzut brusc, iar epidemia și-a pierdut virulența, încetând la scurt timp.^4^' || '\n\n' ||
    '**Seceta din 1827** Sub domnia lui Grigore Ghica, seceta amenința cu foametea generalizată. Racla a fost purtată pe „Podul Mogoșoaiei" (actuala Calea Victoriei). Colonelul Papazoglu, martor ocular, notează în memoriile sale un fapt uluitor: „Când sosiră în capul Podului Mogoșoaiei, începu să plouă. Vodă și boierii și norodul care erau după Sfânt fura udați până la piele. Și ploaia a ținut trei zile".^20^' || '\n\n' ||
    '**Holera din 1831** În timpul administrației rusești (Regulamentul Organic), sub generalul Pavel D. Kiseleff, holera a lovit capitala. Deși străin, Kiseleff a respectat credința localnicilor și a ordonat, pe 15 septembrie 1831, ca moaștele să fie duse pe Câmpia Filaretului. Acolo, în prezența armatei și a clerului, s-au făcut rugăciuni. Rezultatul a fost imediat: mortalitatea a scăzut de la 160 de decese pe zi până la dispariția completă a bolii în octombrie.^20^' || '\n\n' ||
    '**Protecția în Război (1877 și 1918)** În Războiul de Independență (1877), un colonel a pus bilețele cu numele celor șapte fii ai săi sub capul Sfântului; toți s-au întors vii de pe front.^12^ În 1918, sub ocupație germano-bulgară, un grup de soldați bulgari a încercat să fure racla din catedrală pentru a o duce la sud de Dunăre. Au reușit să o încarce într-o mașină, dar o ceață densă și supranaturală i-a dezorientat complet, vehiculul învârtindu-se în cerc în jurul Bucureștiului până dimineața, când au fost prinși, iar moaștele recuperate.^11^' || '\n\n' ||
    '### 6.2. Minuni Personale și Contemporane' || '\n\n' ||
    '**Pedeapsa și Îndreptarea (Monahul Lavrentie)** Un monah numit Lavrentie, închinându-se, a rupt în taină o părticică din moaște. Pe loc a rămas mut și cu gura încleștată. Doar după rugăciuni intense și mărturisirea faptei și-a recăpătat graiul.^12^ Similar, surorile Aspra și Ecaterina din Cernavodă au încercat să ia o părticică pentru biserica lor, dar caii căruței nu au putut fi clintiți din loc până nu au returnat fragmentul.^10^' || '\n\n' ||
    '**Vindecarea Femeii în Comă (Caz Recent)** O minune intens mediatizată relatează cazul unei mame a cinci copii, aflată în comă la spital, cu diagnostic grav (posibil cancer). Medicii nu îi mai dădeau șanse. Familia s-a rugat la racla Sfântului. Femeia s-a trezit brusc, și-a scos perfuziile și a cerut să meargă la Sfântul Dimitrie, povestind că un bătrân i s-a arătat în vedenie poruncindu-i: „Scoală și du-te acasă la copii și la soț!".^20^' || '\n\n' ||
    '## Capitolul VII: Iconografia și Simbolistica Vizuală' || '\n\n' ||
    'Reprezentarea vizuală a Sfântului Dimitrie cel Nou este guvernată de canoane stricte, menite să îl distingă de Sfântul Mare Mucenic Dimitrie, Izvorâtorul de Mir.' || '\n\n' ||
    '### 7.1. Elemente Distinctive ale Erminiei' || '\n\n' ||
    '- **Fizionomia:** Este pictat ca un bătrân venerabil, cu barbă lungă și căruntă, reflectând înțelepciunea și asceza, spre deosebire de Sf. Mare Mucenic Dimitrie care este reprezentat ca un tânăr militar.^5^' || '\n' ||
    '- **Veșmintele:** Poartă haine monahale -- anteriu, rasă și mantie neagră (simbol al morții față de lume). Pe cap poartă camilafcă sau culion cu cruce.^5^' || '\n' ||
    '- **Atribute:** În mâna dreaptă ține o Cruce (semnul urmării lui Hristos), iar în stânga un rotulus (sul) cu texte ascetice sau mătănii.^5^' || '\n' ||
    '- **Picioarele Desculțe:** Cel mai particular element iconografic este reprezentarea sa desculț (uneori cu un singur picior gol, alteori cu ambele). Aceasta nu este o simplă alegere estetică, ci o trimitere directă la canonul de trei ani de penitență pentru strivirea puiului de pasăre, simbolizând sensibilitatea sa extremă față de creație și asprimea nevoinței.^5^' || '\n\n' ||
    '## Capitolul VIII: Analiza Liturgică și Imnografică (Acatistul)' || '\n\n' ||
    'Pentru secțiunea de resurse a aplicației, Acatistul constituie textul central. Analiza sa relevă teologia sfințeniei Cuviosului.' || '\n\n' ||
    '### 8.1. Structura și Temele Acatistului' || '\n\n' ||
    'Acatistul este structurat în 13 Condace și 12 Icosuri. Din analiza textului ^22^:' || '\n\n' ||
    '- **Condacul 1:** Îl definește prin funcția sa principală: „Apărătorule al nostru de necazuri" și „Făcătorule de minuni".' || '\n' ||
    '- **Icosul 1:** Subliniază victoria asupra lumii nevăzute încă din timpul vieții: „ai biruit pe demonul cel fără de trup".' || '\n' ||
    '- **Icosul 2:** Abordează paradoxul moaștelor: „materia nu se supune firii", evidențiind neputrezirea ca semn al harului.' || '\n' ||
    '- **Condacul 9:** Propune o „sociologie" a pelerinajului, chemând toate categoriile sociale: „bogații la cel sărac cu duhul, săracii la îmbogățitorul, bolnavii la doctorul cel fără de plată".' || '\n' ||
    '- **Icosul 10:** Folosește metafora arhitecturală „Zid ești credincioșilor", reiterând rolul de fortăreață spirituală a Bucureștiului.' || '\n\n' ||
    '## Capitolul IX: Cultul Actual și Pelerinajul -- „Calea Sfinților"' || '\n\n' ||
    '### 9.1. Calendarul Liturgic' || '\n\n' ||
    'Sfântul este prăznuit pe **27 octombrie**, imediat după Sf. Mare Mucenic Dimitrie (26 octombrie). Recent, Sfântul Sinod a instituit o a doua sărbătoare, pe **13 iulie**, dedicată **Aducerii Moaștelor la București** (comemorând evenimentul din 1774), o dată importantă de integrat în calendarul aplicației.^15^' || '\n\n' ||
    '### 9.2. Procesiunea „Calea Sfinților"' || '\n\n' ||
    'Pelerinajul de toamnă include o procesiune complexă, devenită tradiție, desfășurată de regulă pe 23 sau 24 octombrie.' || '\n\n' ||
    '- **Traseul Coloanei 1:** Pleacă de la Catedrala Patriarhală cu moaștele Sf. Dimitrie cel Nou. Traseu: Str. Patriarhiei -- Bd. Regina Maria -- baza Dealului Patriarhiei (Piața Unirii).^24^' || '\n' ||
    '- **Traseul Coloanei 2:** Pleacă de la Catedrala Mitropolitană „Sfântul Spiridon -- Nou" cu alte moaște (ex: Sf. Nectarie, Sf. C-tin și Elena). Traseu: Calea Șerban Vodă -- Str. Bibescu Vodă -- baza Dealului Patriarhiei.^24^' || '\n' ||
    '- **Întâlnirea:** Cele două coloane se unesc la baza Dealului și urcă împreună spre Altarul de Vară pentru primirea solemnă de către Patriarh.^25^' || '\n\n' ||
    '## Recomandări pentru Implementarea în Aplicația Android' || '\n\n' ||
    'Pe baza cercetării, se propune următoarea structură a conținutului în aplicație:' || '\n\n' ||
    '| **Modul** | **Conținut Recomandat** | **Detalii Tehnice/UX** |' || '\n' ||
    '| :--- | :--- | :--- |' || '\n' ||
    '| **Viața (Bios)** | Narativul complet, cu accent pe episodul „cuibul" și anahoretism. | Text scrollable, imagini inserate (picturi cu picioarele desculțe). |' || '\n' ||
    '| **Harta Pelerinajului** | Traseul „Calea Sfinților" cu puncte de interes (Catedrala, Sf. Spiridon Nou, Piața Unirii). | Integrare Google Maps API cu layere pentru procesiune. |' || '\n' ||
    '| **Minuni (Audio/Text)** | Categoriile de minuni (Istorice vs. Personale) prezentate ca „Studii de caz". | Funcție de „Share" pentru mărturii. |' || '\n' ||
    '| **Calendar & Notificări** | 27 Octombrie (Hram) și 13 Iulie (Aducerea Moaștelor). | Push notifications cu troparul zilei. |' || '\n' ||
    '| **Acatist** | Textul integral cu funcție de bookmarking la Icosuri. | Opțiune de „Mod de noapte" pentru citire în timpul privegherilor. |' || '\n\n' ||
    'Această structură asigură valorificarea completă a informațiilor hagiografice și istorice, transformând aplicația într-un ghid spiritual și practic indispensabil pelerinului modern.' || '\n\n' ||
    '#### Works cited' || '\n\n' ||
    '1. viaţa, acatistul ªi paraclisul sfântului cuvios dimitrie cel nou, ocrotitorul bucureªtilor - Ziarul Lumina, accessed January 26, 2026, [[https://ziarullumina.ro/media/file/Dimitrie-cel-Nou-Viata-si-Acatistul.pdf]{.underline}](https://ziarullumina.ro/media/file/Dimitrie-cel-Nou-Viata-si-Acatistul.pdf)' || '\n' ||
    '2. Sfântul Dimitrie cel Nou, ocrotitorul Bucureștilor -- credință, tradiție și pelerinaj, accessed January 26, 2026, [[https://www.bucurestifm.ro/2025/10/27/sfantul-dimitrie-cel-nou-ocrotitorul-bucurestilor-credinta-traditie-si-pelerinaj/]{.underline}](https://www.bucurestifm.ro/2025/10/27/sfantul-dimitrie-cel-nou-ocrotitorul-bucurestilor-credinta-traditie-si-pelerinaj/)' || '\n' ||
    '3. Cum au ajuns moaștele Sfântului Dimitrie Basarabov la București? - Doxologia, accessed January 26, 2026, [[https://doxologia.ro/cum-au-ajuns-moastele-sfantului-dimitrie-basarabov-la-bucuresti]{.underline}](https://doxologia.ro/cum-au-ajuns-moastele-sfantului-dimitrie-basarabov-la-bucuresti)' || '\n' ||
    '4. Cuviosul Dimitrie cel Nou, sfântul care a învins ciuma şi holera - Ziarul Lumina, accessed January 26, 2026, [[https://ziarullumina.ro/actualitate-religioasa/documentar/cuviosul-dimitrie-cel-nou-sfantul-care-a-invins-ciuma-si-holera-166580.html]{.underline}](https://ziarullumina.ro/actualitate-religioasa/documentar/cuviosul-dimitrie-cel-nou-sfantul-care-a-invins-ciuma-si-holera-166580.html)' || '\n' ||
    '5. Icoana Sfantului Cuvios Dimitrie cel Nou CrestinOrtodox.ro, accessed January 26, 2026, [[https://www.crestinortodox.ro/sarbatori/sfantul-dimitrie-nou-basarabov/icoana-sfantului-cuvios-dimitrie-nou-159019.html]{.underline}](https://www.crestinortodox.ro/sarbatori/sfantul-dimitrie-nou-basarabov/icoana-sfantului-cuvios-dimitrie-nou-159019.html)' || '\n' ||
    '6. Sfantul Dimitrie cel Nou, accessed January 26, 2026, [[https://sfdimitrie.org/biserica-noastra/sfantul-dimitrie-cel-nou/]{.underline}](https://sfdimitrie.org/biserica-noastra/sfantul-dimitrie-cel-nou/)' || '\n' ||
    '7. Știai de ce Sfântul Dimitrie cel Nou este pictat desculț în unele icoane? - Bizanticons Blog, accessed January 26, 2026, [[https://blog.bizanticons.ro/2023/10/24/stiai-de-ce-sfantul-dimitrie-cel-nou-este-pictat-descult-in-unele-icoane/]{.underline}](https://blog.bizanticons.ro/2023/10/24/stiai-de-ce-sfantul-dimitrie-cel-nou-este-pictat-descult-in-unele-icoane/)' || '\n' ||
    '8. În 26 şi 27 octombrie, sărbătorirea Sfinţilor Dimitrie. Tradiţii populare de Sâmedru, patronul iernii pastorale. Cine este Sfântul Dimitrie cel Nou, cel care ocroteşte Bucureştiul din 1792 - TVR Info, accessed January 26, 2026, [[https://tvrinfo.ro/in-26-si-27-octombrie-sarbatorirea-sfintilor-dimitrie-traditii-populare-de-samedru-patronul-iernii-pastorale-cine-este-sfantul-dimitrie-cel-nou-cel-care-ocroteste-bucurestiul-din-1792_941201/]{.underline}](https://tvrinfo.ro/in-26-si-27-octombrie-sarbatorirea-sfintilor-dimitrie-traditii-populare-de-samedru-patronul-iernii-pastorale-cine-este-sfantul-dimitrie-cel-nou-cel-care-ocroteste-bucurestiul-din-1792_941201/)' || '\n' ||
    '9. Icoana Cuviosului Dimitrie, cel retras din lume, pentru lume - Ziarul Lumina, accessed January 26, 2026, [[https://ziarullumina.ro/actualitate-religioasa/documentar/icoana-cuviosului-dimitrie-cel-retras-din-lume-pentru-lume-127360.html]{.underline}](https://ziarullumina.ro/actualitate-religioasa/documentar/icoana-cuviosului-dimitrie-cel-retras-din-lume-pentru-lume-127360.html)' || '\n' ||
    '10. Viața Sfântului Cuvios Dimitrie cel Nou, Ocrotitorul Bucureștilor, ale cărui moaște sunt la Catedrala Patriarhală | Doxologia, accessed January 26, 2026, [[https://doxologia.ro/viata-sfantului-cuvios-dimitrie-cel-nou-ocrotitorul-bucurestilor-ale-carui-moaste-sunt-la-catedrala]{.underline}](https://doxologia.ro/viata-sfantului-cuvios-dimitrie-cel-nou-ocrotitorul-bucurestilor-ale-carui-moaste-sunt-la-catedrala)' || '\n' ||
    '11. Cum au fost furate moaștele Sfântului Dimitrie cel Nou în 1918? - Bizanticons Blog, accessed January 26, 2026, [[https://blog.bizanticons.ro/2024/10/23/cum-au-fost-furate-moastele-sfantului-dimitrie-cel-nou-in-1918/]{.underline}](https://blog.bizanticons.ro/2024/10/23/cum-au-fost-furate-moastele-sfantului-dimitrie-cel-nou-in-1918/)' || '\n' ||
    '12. Moaștele Sfântului Dimitrie cel Nou, făcătoare de mari minuni - Doxologia, accessed January 26, 2026, [[https://doxologia.ro/moastele-sfantului-dimitrie-cel-nou-facatoare-de-mari-minuni]{.underline}](https://doxologia.ro/moastele-sfantului-dimitrie-cel-nou-facatoare-de-mari-minuni)' || '\n' ||
    '13. Ivan Saltykov - Wikipedia, accessed January 26, 2026, [[https://en.wikipedia.org/wiki/Ivan_Saltykov]{.underline}](https://en.wikipedia.org/wiki/Ivan_Saltykov)' || '\n' ||
    '14. Minuni la racla cu moastele Sfantului Dimitrie CrestinOrtodox.ro, accessed January 26, 2026, [[https://www.crestinortodox.ro/sarbatori/sfantul-dimitrie-nou-basarabov/minuni-racla-moastele-sfantului-dimitrie-158994.html]{.underline}](https://www.crestinortodox.ro/sarbatori/sfantul-dimitrie-nou-basarabov/minuni-racla-moastele-sfantului-dimitrie-158994.html)' || '\n' ||
    '15. Aducerea moaștelor Sfântului Dimitrie cel Nou la București -- Scurt istoric - Doxologia, accessed January 26, 2026, [[https://doxologia.ro/aducerea-moastelor-sfantului-dimitrie-cel-nou-la-bucuresti-scurt-istoric]{.underline}](https://doxologia.ro/aducerea-moastelor-sfantului-dimitrie-cel-nou-la-bucuresti-scurt-istoric)' || '\n' ||
    '16. Sfântul Dimitrie cel Nou, de peste două veacuri ajutător al bucureștenilor - Basilica.ro, accessed January 26, 2026, [[https://basilica.ro/sfantul-dimitrie-cel-nou-de-peste-doua-veacuri-ajutator-al-bucurestenilor-2/]{.underline}](https://basilica.ro/sfantul-dimitrie-cel-nou-de-peste-doua-veacuri-ajutator-al-bucurestenilor-2/)' || '\n' ||
    '17. Sfântul Dimitrie cel Nou, de peste două veacuri ajutător al bucureştenilor - Doxologia, accessed January 26, 2026, [[https://doxologia.ro/sfantul-dimitrie-cel-nou-de-peste-doua-veacuri-ajutator-al-bucurestenilor]{.underline}](https://doxologia.ro/sfantul-dimitrie-cel-nou-de-peste-doua-veacuri-ajutator-al-bucurestenilor)' || '\n' ||
    '18. Istoricul raclei Sfântului Cuvios Dimitrie cel Nou, Ocrotitorul Bucureștilor - Ziarul Lumina, accessed January 26, 2026, [[https://ziarullumina.ro/actualitate-religioasa/documentar/istoricul-raclei-sfantului-cuvios-dimitrie-cel-nou-ocrotitorul-bucurestilor-184815.html]{.underline}](https://ziarullumina.ro/actualitate-religioasa/documentar/istoricul-raclei-sfantului-cuvios-dimitrie-cel-nou-ocrotitorul-bucurestilor-184815.html)' || '\n' ||
    '19. Racla Sfantului Dimitrie cel Nou - donatorul si mesterul ei ..., accessed January 26, 2026, [[https://www.crestinortodox.ro/religie/racla-sfantului-dimitrie-nou-donatorul-mesterul-69533.html]{.underline}](https://www.crestinortodox.ro/religie/racla-sfantului-dimitrie-nou-donatorul-mesterul-69533.html)' || '\n' ||
    '20. Minunile Sfantului Dimitrie Basarabov CrestinOrtodox.ro, accessed January 26, 2026, [[https://www.crestinortodox.ro/sarbatori/sfantul-dimitrie-nou-basarabov/minunile-sfantului-dimitrie-basarabov-137849.html]{.underline}](https://www.crestinortodox.ro/sarbatori/sfantul-dimitrie-nou-basarabov/minunile-sfantului-dimitrie-basarabov-137849.html)' || '\n' ||
    '21. Minunile Sfantului Dimitrie cel Nou :: Stiri si informatii de actualitate ortodoxa, accessed January 26, 2026, [[https://www.noutati-ortodoxe.ro/minunile-sfantului-dimitrie-cel-nou_l34942_p0.html]{.underline}](https://www.noutati-ortodoxe.ro/minunile-sfantului-dimitrie-cel-nou_l34942_p0.html)' || '\n' ||
    '22. Acatistul Sfantului Cuvios Dimitrie cel Nou, Ocrotitorul Bucureştilor ..., accessed January 26, 2026, [[https://www.noutati-ortodoxe.ro/acatistul-sfantului-cuvios-dimitrie-cel-nou-ocrotitorul-bucure-351-tilor-text_l79439_p0.html]{.underline}](https://www.noutati-ortodoxe.ro/acatistul-sfantului-cuvios-dimitrie-cel-nou-ocrotitorul-bucure-351-tilor-text_l79439_p0.html)' || '\n' ||
    '23. Din 2024, Sf. Dimitrie cel Nou este sărbătorit și în iulie. 250 de ani de la aducerea moaștelor în București, accessed January 26, 2026, [[https://arhiepiscopiabucurestilor.ro/stiri/evenimente-bisericesti/din-2024-sf-dimitrie-cel-nou-este-sarbatorit-si-iulie-250-de-ani-de-la]{.underline}](https://arhiepiscopiabucurestilor.ro/stiri/evenimente-bisericesti/din-2024-sf-dimitrie-cel-nou-este-sarbatorit-si-iulie-250-de-ani-de-la)' || '\n' ||
    '24. Procesiunea „Calea Sfinților" are loc joi în București. Traficul este restricționat în centrul Capitalei | Antena 3 CNN, accessed January 26, 2026, [[https://www.antena3.ro/actualitate/religie/procesiunea-calea-sfintilor-are-loc-joi-in-bucuresti-traficul-este-restrictionat-in-centrul-capitalei-764134.html]{.underline}](https://www.antena3.ro/actualitate/religie/procesiunea-calea-sfintilor-are-loc-joi-in-bucuresti-traficul-este-restrictionat-in-centrul-capitalei-764134.html)' || '\n' ||
    '25. Sărbătoarea Sfântului Dimitrie cel Nou/ Procesiunea Calea Sfinților - în Capitală - Agerpres, accessed January 26, 2026, [[https://agerpres.ro/culte/2025/10/23/sarbatoarea-sfantului-dimitrie-cel-nou-procesiunea-calea-sfintilor---in-capitala--1496169]{.underline}](https://agerpres.ro/culte/2025/10/23/sarbatoarea-sfantului-dimitrie-cel-nou-procesiunea-calea-sfintilor---in-capitala--1496169)' || '\n' ||
    '26. Procesiune de Sfântul Dimitrie cel Nou în București, joi. Unde și pentru cât timp va fi restricționat traficul rutier - Euronews, accessed January 26, 2026, [[https://www.euronews.ro/articole/procesiune-bucuresti-calea-sfintilor-sfantul-dimitrie-cel-nou-23-octombrie-2025-program-restrictii]{.underline}](https://www.euronews.ro/articole/procesiune-bucuresti-calea-sfintilor-sfantul-dimitrie-cel-nou-23-octombrie-2025-program-restrictii)'
);
