INSERT INTO core_schema.saint_lives (name_ro, life_description_ro)
VALUES (
    'Sfântul Ierarh Ghelasie de la Râmeț',
    '# Raport de Cercetare Exhaustiv: Sfântul Ierarh Ghelasie de la Râmeț, Pustnicul Ioan David și Continuitatea Isihastă în Munții Apuseni' || '\n\n' ||
    '## I. Prolegomene: Cadrul Geografic și Spiritual al Văii Geoagiului' || '\n\n' ||
    '### 1.1. Etimologia și Sacralitatea Locului' || '\n\n' ||
    'Pentru a înțelege profunzimea duhovnicească a vieții Sfântului Ierarh Ghelasie și a succesorilor săi spirituali, precum pustnicul Ioan David, este imperativ să analizăm mai întâi „recipientul" geografic și istoric care a găzduit aceste nevoințe: Mănăstirea Râmeț și împrejurimile sale. Situată în inima Munților Trascău, pe valea îngustă și stâncoasă a Geoagiului, mănăstirea nu este doar un simplu așezământ, ci o fortăreață naturală a ortodoxiei transilvănene.^1^' || '\n\n' ||
    'Toponimia locului este revelatoare. Numele „Râmeț" derivă, conform analizelor istorice și filologice, din termenul latin *eremita* (pustnic/eremit).^1^ Această etimologie sugerează o realitate istorică anterioară oricărei atestări documentare scrise: înainte de a exista ziduri de piatră, existau „temple" vii, oameni care s-au retras în scobiturile munților pentru a căuta liniștea (*isihia*) și comuniunea neîntreruptă cu Dumnezeu. Astfel, Râmețul se definește prin excelență ca fiind „locul eremiților", un spaçiu consacrat rugăciunii solitare care, în timp, s-a cristalizat într-o viață de obște (cenobitică).^1^' || '\n\n' ||
    '### 1.2. Catedrala Munților și Rezistența prin Credință' || '\n\n' ||
    'Adesea supranumită „Catedrala Munților", Mănăstirea Râmeț a funcționat ca un centru de rezistență spirituală și națională. Izolarea geografică -- accesul fiind posibil doar prin chei înguste și poteci abrupte -- a protejat comunitatea monahală de ingerințele directe ale autorităților politice ostile sau de invaziile militare rapide. Râul Râmeț, care și-a săpat albia prin „adâncul stâncilor și desișul codrilor", a creat un areal de rai.^1^ Această frumusețe naturală austeră a oferit cadrul perfect pentru asceză: peșterile și grotele din versanți au devenit primele chilii, iar fructele sălbatice și apa izvoarelor au constituit hrana primilor nevoitori.^1^' || '\n\n' ||
    'Cercetările arheologice, coroborate cu analiza osemintelor descoperite în perimetrul mănăstirii, indică existența unei vieți monahale organizate încă din secolele XI-XII, mult înainte de secolul al XIV-lea al Sfântului Ghelasie.^2^ Profesorul Botezatu, analizând aceste resturi osteologice, a confirmat continuitatea locuirii și a nevoinței, demonstrând că „lavra mănăstirească" are rădăcini adânci în istoria medievală timpurie a Transilvaniei.^2^' || '\n\n' ||
    '## II. Contextul Istoric și Eclesiastic: Ortodoxia Transilvăneană în Secolul al XIV-lea' || '\n\n' ||
    '### 2.1. Presiunea Angevină și Rolul Ierarhului' || '\n\n' ||
    'Secolul al XIV-lea, perioada în care a activat Sfântul Ierarh Ghelasie, a fost unul de maximă presiune pentru populația ortodoxă din Transilvania. Regatul Ungariei, aflat sub conducerea dinastiei de Anjou (prin Ludovic I cel Mare, menționat în inscripția de la Râmeț), a dus o politică agresivă de unificare religioasă, favorizând catolicismul și limitând drepturile „schismaticilor" (ortodocșilor).^3^' || '\n\n' ||
    'În acest context politic ostil, prezența unui **Arhiepiscop** ortodox la Râmeț este un fapt istoric de o importanță capitală. Titulatura de „Arhiepiscop" (*Arhiepiscopului Ghelasie*), descoperită în inscripția din 1377, indică nu doar un simplu stareț, ci o autoritate bisericească superioară, recunoscută canonic și respectată de populație, care coordona viața spirituală a românilor din Transilvania.^5^ Faptul că un ierarh ortodox putea rezida și activa într-o mănăstire de piatră, lăsând mărturii epigrafice și iconografice într-o epocă de persecuție, demonstrează puterea și prestigiul de care se bucura Sfântul Ghelasie, precum și protecția divină care acoperea „Catedrala Munților".^4^' || '\n\n' ||
    '### 2.2. Legătura cu Isihasmul și Muntele Athos' || '\n\n' ||
    'Tradiția monahală de la Râmeț din secolul al XIV-lea nu era izolată de marile curente spirituale ale Bizanțului. Aceasta este epoca Sfântului Grigorie Palama și a renașterii isihaste. Hagiografia Sfântului Ghelasie menționează explicit că acesta a deprins „meșteșugul luptei duhovnicești" de la „cei mai iscusiți eremiți".^6^ Această formulare sugerează o filiație spirituală directă sau indirectă cu Muntele Athos. Mulți călugări din Carpați călătoreau la Athos sau erau ucenici ai celor reveniți de acolo, aducând cu ei practica rugăciunii inimii și rigoarea ascezei sinaite.^7^' || '\n\n' ||
    'Mănăstirea Râmeț, în timpul Sfântului Ghelasie, funcționa după un model idioritmic combinat cu cel chinovial: călugării trăiau în asceză severă în timpul săptămânii (model eremitic) și se reuneau pentru Liturghie în weekend (model chinovial), o structură tipică schiturilor athonite (skete).^1^' || '\n\n' ||
    '## III. Hagiografia Sfântului Ierarh Ghelasie: Analiză Detaliată a Vieții și Nevoințelor' || '\n\n' ||
    '### 3.1. Tinerețea și Formarea Ascetică' || '\n\n' ||
    'Sfântul Ghelasie a fost „originar din partea locului", un detaliu hagiografic esențial care subliniază legătura sa organică cu pământul și poporul pe care avea să-l păstorească.^6^ Încă din tinerețe a simțit chemarea spre viața monahală, luând „jugul lui Hristos". Prima etapă a vieții sale duhovnicești a fost marcată de retragerea în pustie. El s-a nevoit inițial ca sihastru pe valea pârâului Râmeț, locuind probabil în peșteri sau adăposturi improvizate, expus intemperiilor și luptelor nevăzute cu demonii.^6^' || '\n\n' ||
    'Regimul său de viață era unul de o asprime extremă, specifică marilor asceți ai pustiei egiptene. Hagiografia consemnează că:' || '\n\n' ||
    '- **Postul Săptămânal:** În toată săptămâna (de luni până vineri), Sfântul Ghelasie nu primea mâncare trupească.' || '\n' ||
    '- **Hrana Euharistică:** Se „îndestula numai cu Preacuratele Taine" (Sfânta Împărtășanie), subliniind centralitatea Euharistiei ca sursă primară de viață.^6^' || '\n' ||
    '- **Masa Comunală:** Mânca doar sâmbăta și duminica, la trapeza mănăstirii, împreună cu ucenicii săi, menținând astfel comuniunea frățească.^6^' || '\n\n' ||
    '### 3.2. Starețul și Cei 12 Ucenici' || '\n\n' ||
    'După perioada de purificare în pustie, Ghelasie a coborât în obște, asumându-și rolul de egumen (stareț). Modelul său de organizare a comunității a fost unul apostolic: tradiția menționează că avea **doisprezece ucenici**, imitând numărul Apostolilor Mântuitorului.^6^ Această structură nu este întâmplătoare; ea indică intenția sfântului de a crea o școală duhovnicească completă, capabilă să perpetueze tradiția.' || '\n\n' ||
    'Programul zilnic al comunității sub conducerea sa îmbina munca fizică („ascultarea") cu rugăciunea neîncetată:' || '\n\n' ||
    '- **Ziua:** Mergea cu ucenicii la muncă (adunat fân, treburi gospodărești).' || '\n' ||
    '- **Noaptea:** Făcea priveghere și săvârșea Sfânta Liturghie. Această inversare a ritmului circadian (noaptea dedicată luminii divine) este o trăsură distinctivă a monahismului isihast.^6^' || '\n\n' ||
    '### 3.3. Păstorul „Mocanilor" și Vindecătorul' || '\n\n' ||
    'Dincolo de zidurile mănăstirii, Sfântul Ghelasie era părintele duhovnicesc al întregii Țări a Moților. Hagiografia notează o dinamică interesantă a pastorației sale: în posturi, el urca la sihaștrii din peșteri pentru a se ruga cu ei, iar apoi cobora în mănăstire unde îl așteptau „credincioșii și mocanii de prin munți".^6^' || '\n\n' ||
    'Faima sa de vindecător a atras mulțimi de suferinzi. Textul hagiografic specifică faptul că la el veneau „mai ales cei stăpâniți de duhuri rele" (demonizați), pe care îi vindeca prin rugăciune. Această putere asupra duhurilor necurate este un semn al curăției inimii și al îndrăznelii (*parrhesia*) pe care o dobândise în fața lui Dumnezeu.^6^' || '\n\n' ||
    '## IV. Minunea de la Hopați: Hidrologie Sacră și Teologie' || '\n\n' ||
    'Unul dintre episoadele centrale ale vieții Sfântului Ghelasie, care are o rezonanță liturgică și practică până în zilele noastre, este **minunea izvorului de la Hopați**.' || '\n\n' ||
    '### 4.1. Narațiunea Evenimentului' || '\n\n' ||
    'Într-o zi de vară toridă, sfântul se afla împreună cu ucenicii săi la adunat fânului în poiana mănăstirii, numită Hopați. Căldura excesivă a provocat o sete chinuitoare întregii obști. Într-un gest care amintește de marii patriarhi biblici, Sfântul Ghelasie a căzut la rugăciune.' || '\n\n' ||
    'Hagiografia descrie momentul cu precizie: „Cuviosul Ghelasie a căzut la rugăciune și îndată a aflat un izvor cu apă".^6^ Alte variante ale tradiției, păstrate în imnografie (Acatist), adaugă detaliul că sfântul a lovit pământul sau a făcut semnul crucii cu toiagul, replicând astfel minunea lui Moise în deșert, când a scos apă din stânca Horeb.^9^' || '\n\n' ||
    '### 4.2. Permanența Izvorului și Schitul Hopați' || '\n\n' ||
    'Apa izvorâtă prin rugăciunea sfântului nu a fost un fenomen temporar. Izvorul există și astăzi, fiind cunoscut sub numele de „Izvorul Cuviosului Ghelasie". Apa sa este considerată tămăduitoare, iar sătenii și pelerinii o iau pentru „sănătate și binecuvântare".^6^' || '\n\n' ||
    'În memoria acestui eveniment și pentru a sacraliza locul, în anul 2015 au început lucrările pentru ridicarea unui așezământ monahal chiar pe locul minunii. **Schitul „Izvorul Sfântului Ghelasie" de la Hopați** a fost sfințit în 2022, având hramul „Sfântul Ierarh Ghelasie de la Râmeț" și „Acoperământul Maicii Domnului". Ansamblul este construit sub formă de cetate, cu o clopotniță la intrare și un corp de chilii, marcând izvorul cu o cruce de piatră.^10^ Acesta a devenit un loc de pelerinaj distinct, legat organic de mănăstirea mamă.' || '\n\n' ||
    '## V. Fenomenologia Sfârșitului: Legenda Asinului și Eclesiologia Clopotelor' || '\n\n' ||
    'Moartea Sfântului Ghelasie este învăluită într-o aură de mister și minune, elemente care subliniază legătura dintre sfânt și creația necuvântătoare.' || '\n\n' ||
    '### 5.1. Cunoașterea Sfârșitului' || '\n\n' ||
    'Aflat din nou în poiana de la munte cu asinul său, Sfântul Ghelasie și-a cunoscut dinainte sfârșitul prin descoperire dumnezeiască. Și-a chemat ucenicii pentru ultimele povețe, un testament spiritual care se concentrează pe trei piloni:' || '\n\n' ||
    '1.  Trăirea în dragoste desăvârșită.' || '\n' ||
    '2.  Iubirea față de Biserică.' || '\n' ||
    '3.  Fuga de păcat (beție, desfrâu).^6^' || '\n\n' ||
    'După ce i-a sărutat pe toți, și-a dat sufletul în mâinile lui Hristos, chiar acolo, în mijlocul naturii pe care o sfințise prin rugăciune.' || '\n\n' ||
    '### 5.2. Procesiunea Asinului' || '\n\n' ||
    'Tradiția locală consemnează un fapt uimitor: trupul neînsuflețit al ierarhului a fost așezat pe asinul său. Fără a fi ghidat de mână omenească, animalul a coborât potecile abrupte ale muntelui, purtând povara sfântă spre mănăstire. În momentul în care cortegiul a început coborârea, clopotele de la șapte biserici din satele învecinate au început să bată singure, vestind credincioșilor mutarea la Domnul a părintelui lor.^3^' || '\n\n' ||
    'Când asinul a ajuns în fața bisericii vechi, s-a oprit, iar copita sa s-a imprimat miraculos în piatră. Această piatră cu urma copitei se păstrează și astăzi în muzeul mănăstirii, fiind o mărturie tangibilă a tradiției.^3^ Sfântul a fost îngropat lângă zidul bisericii, iar mormântul său a devenit imediat loc de pelerinaj.^6^' || '\n\n' ||
    '## VI. Arheologia Sfințeniei: Inscripția din 1377 și Pictorul Mihul' || '\n\n' ||
    'Timp de secole, viața Sfântului Ghelasie a circulat preponderent pe cale orală. Secolul XX a adus însă confirmările științifice irefutabile, transformând legenda în istorie documentată.' || '\n\n' ||
    '### 6.1. Descoperirea Inscripției (1978)' || '\n\n' ||
    'În timpul lucrărilor de restaurare a bisericii vechi din 1978, specialiștii au scos la iveală, pe al doilea strat de pictură de pe peretele care desparte naosul de pronaos, o inscripție slavonă crucială.' || '\n\n' ||
    'Textul inscripției este:' || '\n\n' ||
    '*„Scris-am eu mult greșitul robul lui Dumnezeu Mihul zugravul de la Crișul Alb în timpul Arhiepiscopului Ghelasie, anul 1377, 2 iulie, în zilele regelui Ludovic"*.^4^' || '\n\n' ||
    '### 6.2. Implicații Istorice și Teologice' || '\n\n' ||
    'Această frază scurtă este fundamentală pentru istoria Bisericii Ortodoxe Române:' || '\n\n' ||
    '1.  **Atestarea Ierarhică:** Confirmă existența unui Arhiepiscop ortodox în Transilvania în 1377, contrazicând tezele istoriografice care susțineau lipsa de organizare a românilor în acea perioadă.' || '\n' ||
    '2.  **Identitatea Sfântului:** Validează numele „Ghelasie" păstrat de tradiție.' || '\n' ||
    '3.  **Școala de Pictură:** Menționarea lui „Mihul zugravul de la Crișul Alb" dovedește existența unei școli locale de pictură bisericească și a unor legături culturale cu zona Zarandului (Crișul Alb), sugerând un spațiu cultural românesc unitar.^5^' || '\n' ||
    '4.  **Datarea:** Ziua de 2 iulie 1377 oferă un reper cronologic fix pentru activitatea sfântului.' || '\n\n' ||
    '## VII. Revelarea Moaștelor: Inundația din 1925 și Antropologia Teologică' || '\n\n' ||
    'Dacă inscripția a confirmat numele și funcția, natura a scos la iveală trupul sfântului.' || '\n\n' ||
    '### 7.1. Inundația Providențială' || '\n\n' ||
    'În primăvara anului 1925, o viitură puternică a lovit valea Râmețului. Apele au săpat în jurul bisericii vechi, dislocând mormintele. După retragerea apelor, localnicii și monahii au găsit un craniu care fusese scos din pământ și purtat de ape.' || '\n\n' ||
    'Detaliile descoperirii sunt de natură miraculoasă:' || '\n\n' ||
    '- **Procesiunea Apei:** Craniul a ocolit biserica de trei ori pe luciul apei, oprindu-se „pe creasta altarului" sau la fereastra sfântului altar.^12^' || '\n' ||
    '- **Semnele Sfințeniei:** Craniul avea o culoare galbenă, ca ceara, și emana o mireasmă plăcută, diferită de mirosul pământului sau al descompunerii. Acestea sunt semne clasice ale sfintelor moaște în tradiția ortodoxă.^12^' || '\n\n' ||
    '### 7.2. Tăinuirea și Redescoperirea' || '\n\n' ||
    'Inițial, preotul satului a reînhumat craniul, dar tradiția locului l-a identat imediat ca fiind al Sfântului Ghelasie. Ulterior, săpăturile arheologice au scos la iveală și alte părți din schelet. Astăzi, aceste moaște se află spre închinare în biserica nouă a mănăstirii, fiind izvor de tămăduiri pentru credincioși.^13^' || '\n\n' ||
    'Cazuri contemporane de vindecare sunt documentate: o femeie din Negrești-Oaș vindecată de epilepsie în urma unui vis care o îndruma spre Râmeț; un paralitic din Cocora-Alba care a plecat pe picioarele lui după rugăciuni la raclă.^6^' || '\n\n' ||
    '## VIII. Dimensiunea Liturgică: Exegeza Acatistului și a Canonului' || '\n\n' ||
    'Pentru integrarea în aplicația Android, este esențială prezentarea și înțelegerea textelor liturgice dedicate sfântului. Acestea nu sunt doar poezie religioasă, ci teologie rugătoare care sintetizează viața și darurile sfântului.' || '\n\n' ||
    '### 8.1. Analiza Acatistului Sfântului Ghelasie' || '\n\n' ||
    'Acatistul este structurat în 13 Condace și 12 Icoase.' || '\n\n' ||
    '- **Icosul 1:** Îl numește „înger în trup" și „lauda cea preaiubită a călugărilor", evidențiind dubla sa natură: pământească prin naștere, cerească prin trăire.^14^' || '\n' ||
    '- **Condacul 2:** Face o paralelă directă cu Moise: „Pe pământ ca un alt Moise te-ai arătat... căci, cu toiagul semnul crucii făcând, ai izvorât apă din loc pietros".^9^ Această tipologie biblică îl plasează pe Ghelasie în linia marilor conducători de popor care au grijă și de nevoile materiale (apa) ale turmei.' || '\n' ||
    '- **Condacul 10:** Subliniază continuitatea minunilor după moarte: „după trecerea ta la cele veșnice nu încetezi a-i împărtăși de faceri de bine".^9^' || '\n\n' ||
    '### 8.2. Canonul și Rugăciunea pentru Ploaie' || '\n\n' ||
    'Canonul de rugăciune, cântat la Utrenie, aprofundează temele teologice:' || '\n\n' ||
    '- **Cântarea 3:** Laudă rigoarea organizatorică a sfântului („bună rânduială în toate"), arătând că sfințenia nu înseamnă haos, ci disciplină duhovnicească.^15^' || '\n' ||
    '- **Rugăciunea la Vreme de Secetă:** Datorită minunii izvorului, Sfântul Ghelasie este invocat special pentru aducerea ploii. Aplicația trebuie să includă textul acestei rugăciuni, care cere lui Dumnezeu să „poruncească norilor" să slobozească ploaia, invocând mijlocirea Sfântului Ghelasie.^16^' || '\n\n' ||
    '### 8.3. Troparul (Glas 1)' || '\n\n' ||
    'Textul imnografic central: *„De Dumnezeu purtătorule, Părintele nostru Ghelasie, povățuitorul călugărilor, preoților și credincioșilor, podoaba cuvioșilor și lauda arhiereilor, sprijinitorul celor în necazuri și făcătorule de minuni..."*.^18^' || '\n\n' ||
    '## IX. Filiația Duhovnicească: Continuitatea Sfințeniei la Râmeț' || '\n\n' ||
    'Istoria mănăstirii Râmeț este marcată de figuri care asigură continuitatea sfințeniei peste veacuri, legând epoca medievală de cea modernă.' || '\n\n' ||
    '### 9.1. Pustnicul Ioan David: „Ioan de la Râmeț"' || '\n\n' ||
    'Cea mai probabilă referință pentru „Ioan" în contextul sfințeniei la Râmeț este **Cuviosul Ioan David**, un mare isihast al secolului XX.' || '\n\n' ||
    '- **Profil Duhovnicesc:** Fratele Ioan David a fost un pustnic care a viețuit în pădurile din jurul mănăstirii, având darul rugăciunii inimii, al înainte-vederii și al facerii de minuni.^19^' || '\n' ||
    '- **Recunoașterea Athonită:** Schimonahul Mamant de la Chilia „Sfântul Gheorghe"-Colciu din Athos, care l-a cunoscut personal, mărturisea: „Am cunoscut mulți părinți cu viață sfântă aici în Sfântul Munte Athos, dar la măsura sfințeniei fratelui Ioan, pe nimeni!".^19^' || '\n' ||
    '- **Legătura cu Obștea:** Deși pustnic, el a fost un sfătuitor tainic al mănăstirii și un stâlp de rugăciune, continuând exact modelul Sfântului Ghelasie (retragere în pustie și povățuire a obștii).' || '\n\n' ||
    '### 9.2. Sfântul Dometie și Rădăcina „Ioan"' || '\n\n' ||
    'O altă figură centrală este **Sfântul Cuvios Dometie cel Milostiv** (Dometie Manolache, 1924-1975), starețul care a reînviat mănăstirea în perioada comunistă.' || '\n\n' ||
    '- **Legătura de Nume:** Tatăl Sfântului Dometie se numea **Ioan**.^20^ Deși un detaliu biografic, acesta subliniază mediul de evlavie din care a provenit.' || '\n' ||
    '- **Continuitatea Misiunii:** Așa cum Ghelasie a fost „arhiepiscop" și păstor într-o vreme de persecuție (angevină), Dometie a fost „arhiepiscopul nenumit" al Apusenilor în timpul persecuției comuniste, fiind un adevărat „apostol al moților". El a restaurat biserica veche (unde s-au găsit moaștele lui Ghelasie) și a revigorat viața duhovnicească.^20^' || '\n\n' ||
    '## X. Strategii de Implementare în Aplicația Android' || '\n\n' ||
    '### 10.1. Structura Modulelor' || '\n\n' ||
    '| **Modul** | **Conținut Recomandat** | **Detalii Tehnice/Surse** |' || '\n' ||
    '| :--- | :--- | :--- |' || '\n' ||
    '| **Viața Sfântului (Sinaxar)** | Text narativ detaliat: tinerețea, cei 12 ucenici, minunea izvorului, adormirea și legenda asinului. | Integrare text din.^6^ Audio (Voiceover) opțional. |' || '\n' ||
    '| **Istoric și Arheologie** | Prezentarea inscripției din 1377 (imagine + traducere) și a descoperirii moaștelor din 1925. | Tabel cronologic (1377, 1762 - distrugere Bukow, 1925 - inundație, 1978 - inscripție, 1992 - canonizare). Surse:.^4^ |' || '\n' ||
    '| **Rugăciuni și Imnografie** | Text complet: Acatistul, Canonul, Troparul. Include buton special pentru „Rugăciune la vreme de secetă". | Format text scrollable. Audio pentru Tropar (Glas 1). Surse:.^9^ |' || '\n' ||
    '| **Panteonul Râmețului** | Subsecțiune despre **Pustnicul Ioan David** și **Sf. Dometie**. | Clarificarea legăturii dintre Ghelasie și urmașii săi spirituali. Sursa:.^19^ |' || '\n' ||
    '| **Harta Pelerinului** | Locații GPS: Mănăstirea Râmeț, Schitul Hopați (Izvorul), Muzeul (Piatra cu urma asinului). | Integrare hărți pentru Schitul Hopați.^10^ |' || '\n\n' ||
    '### 10.2. Tabel Cronologic Comparativ' || '\n\n' ||
    '| **Anul** | **Evenimentul** | **Semnificația** |' || '\n' ||
    '| :--- | :--- | :--- |' || '\n' ||
    '| **sec. XI-XII** | Existența monahismului la Râmeț | Confirmată de analiza osemintelor (Prof. Botezatu). |' || '\n' ||
    '| **1377 (2 iulie)** | Inscripția lui Mihul Zugravul | Atestarea documentară a Arhiepiscopului Ghelasie. |' || '\n' ||
    '| **1762** | Distrugerea de către Generalul Bukow | Tunurile austriece distrug mănăstirea; viața monahală continuă greu. |' || '\n' ||
    '| **1925** | Marea Inundație | Descoperirea miraculoasă a Craniului Sfântului Ghelasie. |' || '\n' ||
    '| **1978** | Restaurarea Bisericii Vechi | Descoperirea inscripției care confirmă numele și rangul sfântului. |' || '\n' ||
    '| **1992 (20 iunie)** | Canonizarea Oficială | Sfântul Sinod recunoaște cultul Sfântului Ghelasie (Prăznuire 30 Iunie). |' || '\n' ||
    '| **2022** | Sfințirea Schitului Hopați | Monumentalizarea locului minunii izvorului. |' || '\n\n' ||
    '#### Works cited' || '\n\n' ||
    '1. Sfântul Ghelasie de la Râmeț, o viață plină de miracole - Ziarul Lumina, accessed January 26, 2026, [[https://ziarullumina.ro/actualitate-religioasa/documentar/sfantul-ghelasie-de-la-ramet-o-viata-plina-de-miracole-172608.html]{.underline}](https://ziarullumina.ro/actualitate-religioasa/documentar/sfantul-ghelasie-de-la-ramet-o-viata-plina-de-miracole-172608.html)' || '\n' ||
    '2. Mănăstirea Râmeț - Doxologia, accessed January 26, 2026, [[https://doxologia.ro/manastirea-ramet]{.underline}](https://doxologia.ro/manastirea-ramet)' || '\n' ||
    '3. Ghelasie de la Râmeț - OrthodoxWiki, accessed January 26, 2026, [[https://ro.orthodoxwiki.org/Ghelasie_de_la_R%C3%A2me%C8%9B]{.underline}](https://ro.orthodoxwiki.org/Ghelasie_de_la_R%C3%A2me%C8%9B)' || '\n' ||
    '4. Sfântul Ierarh Ghelasie de la Râmeț | Doxologia, accessed January 26, 2026, [[https://doxologia.ro/sfantul-ierarh-ghelasie-de-la-ramet-1]{.underline}](https://doxologia.ro/sfantul-ierarh-ghelasie-de-la-ramet-1)' || '\n' ||
    '5. Sfântul Ghelasie şi izvorul duhovnicesc de la Râmeţ - Ziarul Lumina, accessed January 26, 2026, [[https://ziarullumina.ro/actualitate-religioasa/documentar/sfantul-ghelasie-si-izvorul-duhovnicesc-de-la-ramet-8508.html]{.underline}](https://ziarullumina.ro/actualitate-religioasa/documentar/sfantul-ghelasie-si-izvorul-duhovnicesc-de-la-ramet-8508.html)' || '\n' ||
    '6. Viața Sfântului Ierarh Ghelasie de la Râmeț | Doxologia, accessed January 26, 2026, [[https://doxologia.ro/viata-sfantului-ierarh-ghelasie-de-la-ramet]{.underline}](https://doxologia.ro/viata-sfantului-ierarh-ghelasie-de-la-ramet)' || '\n' ||
    '7. Viata Sfantului Ghelasie de la Ramet CrestinOrtodox.ro, accessed January 26, 2026, [[https://www.crestinortodox.ro/sfinti/viata-sfantului-ghelasie-la-ramet-73020.html]{.underline}](https://www.crestinortodox.ro/sfinti/viata-sfantului-ghelasie-la-ramet-73020.html)' || '\n' ||
    '8. Sfântul Ghelasie de la Râmeț -- Cuvântul Înaltpreasfințitului Părinte Calinic, accessed January 26, 2026, [[https://www.arhiepiscopiasucevei.ro/sfantul-ghelasie-de-la-ramet-cuvantul-inaltpreasfintitului-parinte-calinic-2/]{.underline}](https://www.arhiepiscopiasucevei.ro/sfantul-ghelasie-de-la-ramet-cuvantul-inaltpreasfintitului-parinte-calinic-2/)' || '\n' ||
    '9. Acatistul Sfântului Ghelasie de la Râmet - pr. Iulian Nistea, accessed January 26, 2026, [[https://www.nistea.com/spiritualitatea/acatistul-sfantului-ghelasie-de-la-ramet/570]{.underline}](https://www.nistea.com/spiritualitatea/acatistul-sfantului-ghelasie-de-la-ramet/570)' || '\n' ||
    '10. Târnosirea bisericii Schitului „Izvorul Sfântului Ghelasie" de la Hopagi, Alba - Ziarul Lumina, accessed January 26, 2026, [[https://ziarullumina.ro/actualitate-religioasa/stiri/tarnosirea-bisericii-schitului-izvorul-sfantului-ghelasie-de-la-hopagi-alba-173228.html]{.underline}](https://ziarullumina.ro/actualitate-religioasa/stiri/tarnosirea-bisericii-schitului-izvorul-sfantului-ghelasie-de-la-hopagi-alba-173228.html)' || '\n' ||
    '11. Târnosirea bisericii Schitului „Izvorul Sfântului Ghelasie" de la Hopagi (Mănăstirea Râmeț), protopopiatul Aiud - Arhiepiscopia Ortodoxă Alba Iulia, accessed January 26, 2026, [[https://reintregirea.ro/tarnosirea-bisericii-schitului-izvorul-sfantului-ghelasie-de-la-hopagi-manastirea-ramet]{.underline}](https://reintregirea.ro/tarnosirea-bisericii-schitului-izvorul-sfantului-ghelasie-de-la-hopagi-manastirea-ramet)' || '\n' ||
    '12. Până în anul 1978 se ştiau puţine lucruri despre acest sfânt trăitor pe pământ românesc, în străvechea mănăstire de la Râmeţ (jud. Alba), situată pe valea Geoagiului, într-o poziţie geografică de un farmec cu totul aparte. Biserica veche a mănăstirii - lucrată din piatră şi împodobită cu frumoase fresce - // Sfinti Romani, accessed January 26, 2026, [[https://www.sfintiromani.ro/ro/pagina/211/iunie_ghelasie_de_la_ramet_viata.html]{.underline}](https://www.sfintiromani.ro/ro/pagina/211/iunie_ghelasie_de_la_ramet_viata.html)' || '\n' ||
    '13. Viaţa şi Acatistul Sfântului Ierarh GHELASIE DE LA RÂMEŢ - Arhiepiscopia Ortodoxă Alba Iulia, accessed January 26, 2026, [[https://reintregirea.ro/articole/2341-viata-si-acatistul-sfantului-ierarh-ghelasie-de-la-ramet.html]{.underline}](https://reintregirea.ro/articole/2341-viata-si-acatistul-sfantului-ierarh-ghelasie-de-la-ramet.html)' || '\n' ||
    '14. Acatistul Sfântului Ierarh Ghelasie de la Râmeţ - Doxologia, accessed January 26, 2026, [[https://doxologia.ro/acatistul-sfantului-ierarh-ghelasie-de-la-ramet]{.underline}](https://doxologia.ro/acatistul-sfantului-ierarh-ghelasie-de-la-ramet)' || '\n' ||
    '15. Canon de rugăciune către Sfântul Ierarh Ghelasie de la Râmeţ | Doxologia, accessed January 26, 2026, [[https://doxologia.ro/canon-de-rugaciune-catre-sfantul-ierarh-ghelasie-de-la-ramet]{.underline}](https://doxologia.ro/canon-de-rugaciune-catre-sfantul-ierarh-ghelasie-de-la-ramet)' || '\n' ||
    '16. Rugăciune către Sfântul Ghelasie de la Râmeţ | Doxologia, accessed January 26, 2026, [[https://doxologia.ro/rugaciune-catre-sfantul-ghelasie-de-la-ramet]{.underline}](https://doxologia.ro/rugaciune-catre-sfantul-ghelasie-de-la-ramet)' || '\n' ||
    '17. Rugăciuni la vreme de secetă - Porunca Iubirii - Editura Agaton, accessed January 26, 2026, [[https://poruncaiubirii.agaton.ro/articol/245/rug%C4%83ciuni-la-vreme-de-secet%C4%83/zlib/zlib/constants]{.underline}](https://poruncaiubirii.agaton.ro/articol/245/rug%C4%83ciuni-la-vreme-de-secet%C4%83/zlib/zlib/constants)' || '\n' ||
    '18. Troparul Sfântului Ierarh Ghelasie de la Râmeţ | Doxologia, accessed January 26, 2026, [[https://doxologia.ro/troparul-sfantului-ierarh-ghelasie-de-la-ramet]{.underline}](https://doxologia.ro/troparul-sfantului-ierarh-ghelasie-de-la-ramet)' || '\n' ||
    '19. Aflarea moaștelor Sfântului Cuvios Dometie cel Milostiv de la Râmeț | Reîntregirea - Arhiepiscopia Ortodoxă Alba Iulia, accessed January 26, 2026, [[https://reintregirea.ro/aflarea-moastelor-sfantului-cuvios-dometie-cel-milostiv-de-la-ramet]{.underline}](https://reintregirea.ro/aflarea-moastelor-sfantului-cuvios-dometie-cel-milostiv-de-la-ramet)' || '\n' ||
    '20. Viața Sfântului Cuvios Dometie cel Milostiv de la Râmeț - Doxologia, accessed January 26, 2026, [[https://doxologia.ro/viata-sfantului-cuvios-dometie-cel-milostiv-de-la-ramet]{.underline}](https://doxologia.ro/viata-sfantului-cuvios-dometie-cel-milostiv-de-la-ramet)'
);
