INSERT INTO core_schema.saint_lives (name_ro, life_description_ro)
VALUES (
    'Sfântul Mare Mucenic Gheorghe',
    '# Sfântul Mare Mucenic Gheorghe, Purtătorul de Biruință: O Analiză Exhaustivă a Hagiografiei, Teologiei, Imnografiei și Tradițiilor Etnografice' || '\n\n' ||
    '## Introducere' || '\n\n' ||
    'În vasta constelație a sfințeniei creștine, puține figuri au reușit să capteze imaginația colectivă și să inspire o venerație atât de profundă și universală precum Sfântul Mare Mucenic Gheorghe. Cunoscut în întreaga lume creștină sub epitetul de „Purtătorul de Biruință" (*Tropeophoros*), Sfântul Gheorghe transcende granițele geografice, confesionale și culturale, devenind un arhetip al curajului divin și al luptei neobosite împotriva forțelor întunericului. Prezentul raport de cercetare își propune să ofere o explorare exhaustivă, multidimensională și riguroasă a vieții, martiriului, minunilor și tradițiilor asociate acestui „Prinț al Martirilor". Obiectivul central al acestei lucrări este de a depăși simpla narare a evenimentelor hagiografice pentru a pătrunde în straturile profunde ale semnificațiilor teologice, istorice și antropologice care au transformat un tribun militar roman din secolul al IV-lea într-unul dintre cei mai iubiți sfinți ai creștinătății.' || '\n\n' ||
    'Cercetarea de față sintetizează date din surse variate, acoperind spectrul istoric al Imperiului Roman târziu, analiza textelor liturgice și a imnografiei bizantine, geografia sacră a relicvelor (cu un accent special pe spațiul românesc și athonit), precum și complexul univers al tradițiilor populare, unde figura sfântului se împletește fascinant cu riturile agrare de regenerare a timpului și spațiului. De la Capadocia la Nicomedia, de la Lida la Voroneț și de la teologia mistică a „balaurului" la practicile apotropaice împotriva strigoilor din satele românești, acest raport urmărește firul roșu al prezenței Sfântului Gheorghe în conștiința umanității.' || '\n\n' ||
    'Vom analiza în detaliu contextul politic și militar al persecuției lui Dioclețian, mecanismele martiriului ca mărturisire publică, simbolistica complexă a iconografiei ecvestre, precum și rolul sfântului ca patron spiritual al armatelor și comunităților. O atenție deosebită va fi acordată sincretismului religios și folcloric, evidențiind modul în care sărbătoarea „Sângiorzului" structurează calendarul pastoral și definește identitatea spirituală a poporului român.' || '\n\n' ||
    '## I. Contextul Istoric și Hagiografic: Imperiul, Armata și Mărturisirea' || '\n\n' ||
    'Pentru a înțelege magnitudinea sacrificiului Sfântului Gheorghe, este imperativ să reconstruim peisajul istoric și social al Imperiului Roman la sfârșitul secolului al III-lea și începutul secolului al IV-lea. Aceasta a fost o perioadă de transformări profunde, marcată de reformele administrative ale lui Dioclețian și de tensiunea crescândă dintre cultul imperial tradițional și creștinismul emergent.' || '\n\n' ||
    '### 1.1. Originea și Cadrul Familial: Între Capadocia și Palestina' || '\n\n' ||
    'Sursele hagiografice și tradiția bisericească converg în a plasa nașterea Sfântului Gheorghe într-o familie de viță nobilă și credință creștină, situată la confluența a două regiuni esențiale pentru istoria creștinismului timpuriu: Capadocia și Palestina.' || '\n\n' ||
    'Tatăl său, Gerontius (Gerontie), era originar din Capadocia, o provincie din Asia Mică renumită pentru relieful său accidentat, care a forjat caractere puternice, și pentru o tradiție militară robustă. Capadocia a oferit Bisericii un număr impresionant de sfinți și teologi, iar apartenența tatălui la această regiune sugerează o moștenire a rigorii și a tenacității.^1^ Se menționează în unele sinaxare că Gerontius însuși ar fi suferit moarte martirică pentru Hristos, lăsându-i tânărului Gheorghe un model patern de sacrificiu suprem.' || '\n\n' ||
    'Mama sa, Polychronia, provenea din Palestina, mai precis din cetatea Lida (Diospolis, actualul Lod din Israel). Această legătură maternă cu Țara Sfântă este crucială, deoarece ea l-a conectat pe Gheorghe cu spațiul fizic al Revelației și al activității Mântuitorului. După moartea prematură a tatălui său, Polychronia s-a mutat împreună cu fiul ei în Palestina, unde familia deținea vaste proprietăți și averi.^1^ Educația pe care Gheorghe a primit-o sub tutela mamei sale a fost una profund creștină, axată pe virtuțile evlaviei, ale milosteniei și ale curajului duhovnicesc. Această formare timpurie a constituit fundamentul pe care s-a construit ulterior personalitatea sa eroică, pregătindu-l pentru confruntarea inevitabilă cu autoritatea păgână.' || '\n\n' ||
    '### 1.2. Ascensiunea Militară: Tribunus în Garda Imperială' || '\n\n' ||
    'La vârsta maturității, Gheorghe a ales cariera armelor, un parcurs firesc pentru un tânăr aristocrat din acea epocă. Calitățile sale fizice excepționale -- statura impozantă, forța, frumusețea chipului -- dublate de o inteligență tactică și o disciplină riguroasă, i-au asigurat o ascensiune rapidă în ierarhia militară romană.' || '\n\n' ||
    'Sursele istorice și hagiografice notează că, încă de la vârsta de 20 de ani, Gheorghe ajunsese la ranguri înalte, fiind integrat în structurile de elită ale armatei.^1^ El a devenit *Tribunus* (comandant de cohortă) și, ulterior, a fost primit în *Scholae Palatinae* sau *Comitatus*, garda personală a împăratului, unitatea responsabilă direct de securitatea suveranului. Această poziție nu era doar una de prestigiu militar, ci și de influență politică. Gheorghe se afla în proximitatea imediată a centrului de putere, la Nicomedia, capitala administrativă a Răsăritului în sistemul Tetrarhiei instaurat de Dioclețian.' || '\n\n' ||
    'Faptul că Dioclețian îl prețuia pe tânărul ofițer și îl avansase în onoruri subliniază dramatismul situației ulterioare. Gheorghe nu era un marginal al societății romane, ci un membru privilegiat al elitei, un om care avea totul de pierdut din punct de vedere lumesc -- putere, bogăție, statut -- prin mărturisirea credinței sale. Alegerea sa de a renunța la toate acestea conferă actului său martiric o greutate morală și o semnificație exemplară deosebită.' || '\n\n' ||
    '### 1.3. Marea Persecuție și Edictul lui Dioclețian (303 d.Hr.)' || '\n\n' ||
    'Contextul politic s-a deteriorat dramatic începând cu anul 303 d.Hr. Până atunci, Dioclețian manifestase o atitudine de relativă toleranță, perioada fiind cunoscută ca „Mica Pace a Bisericii". Creștinii ajunseseră să ocupe funcții importante în administrație și armată, iar Biserica se dezvolta vizibil. Totuși, sub influența nefastă a Cezarului său, Galeriu -- un păgân fanatic, devotat vechilor culte și posibil influențat de mama sa, Romula, o preoteasă a zeilor munților -- Dioclețian a fost convins că prezența creștinilor atrage mânia zeilor și destabilizează imperiul.^1^' || '\n\n' ||
    'În februarie 303, a fost emis primul dintr-o serie de patru edicte de persecuție. Aceastea prevedeau distrugerea lăcașurilor de cult, arderea Scripturilor, confiscarea proprietăților bisericești și degradarea creștinilor din funcțiile publice. Lozinca sub care se desfășura această campanie de epurare era *„Nomen christianorum deleto"* (Numele creștinilor să fie șters).^1^ Împăratul, autoproclamat *Dominus et Deus* (Domn și Zeu), a impus sacrificiul ritual obligatoriu ca test de loialitate civică. Refuzul de a jertfi zeilor era echivalat cu înalta trădare (*laesa maiestas*).' || '\n\n' ||
    '### 1.4. Confessio Fidei: Mărturisirea în Fața Senatului' || '\n\n' ||
    'Momentul decisiv în viața Sfântului Gheorghe a survenit în timpul unei adunări a consiliului imperial la Nicomedia, unde se discuta intensificarea măsurilor represive împotriva „ateilor" (cum erau numiți creștinii). Asistând la cruzimea deciziilor și la suferința fraților săi întru Hristos, Gheorghe a decis să acționeze.' || '\n\n' ||
    'Pregătindu-se pentru moarte, el și-a vândut averile, a împărțit banii săracilor și a eliberat sclavii din gospodăria sa, renunțând la orice legătură materială cu lumea.^1^ Apoi, s-a înfățișat înaintea împăratului și a Senatului. Mărturisirea sa a fost directă, curajoasă și lipsită de echivoc: „Sunt creștin". El a denunțat iraționalitatea închinării la idoli și injustiția persecuției.' || '\n\n' ||
    'Dioclețian, șocat de „trădarea" ofițerului său favorit, a încercat inițial o abordare diplomatică, promițându-i onoruri și mai mari, bogății și siguranță dacă ar accepta să jertfească zeilor. Răspunsul Sfântului Gheorghe a rămas celebru în analele hagiografice: „Singurul Împărat este Hristos". Acest refuz categoric a spulberat orice speranță de compromis și a declanșat mecanismul teribil al torturii.^1^' || '\n\n' ||
    '## II. Martiriul: O Teologie a Suferinței și Biruinței' || '\n\n' ||
    'Hagiografia Sfântului Gheorghe descrie o succesiune de chinuri care depășesc capacitatea naturală de îndurare a corpului uman. Aceste descrieri nu au doar rolul de a impresiona, ci funcționează ca o demonstrație teologică: trupul martirului, locuit de harul Duhului Sfânt, devine un câmp de luptă unde materia este transfigurată și legile fizicii sunt suspendate pentru a arăta puterea lui Dumnezeu.' || '\n\n' ||
    '### 2.1. Etapele Torturii și Semnificațiile Lor' || '\n\n' ||
    'Procesul martiric al Sfântului Gheorghe este marcat de intervenții miraculoase repetate, care transformă tortura într-o formă de predicare publică.' || '\n\n' ||
    '1.  **Sulița**: Prima încercare de a-l ucide a fost lovirea cu sulițele. Însă, printr-o minune, vârfurile de fier s-au înmuiat ca ceara la contactul cu trupul sfântului, neputând să-l rănească.^1^ Aceasta simbolizează neputința armelor lumești împotriva ostașului lui Hristos.' || '\n' ||
    '2.  **Roata cu Săbii (Dintele de fier)**: Sfântul a fost legat pe o roată prevăzută cu lame ascuțite și cuie, suspendată deasupra unor sulițe înfipte în pământ. În timp ce roata era învârtită, trupul său ar fi trebuit să fie sfârtecat. Deși a suferit răni grave, un înger al Domnului a coborât, a oprit roata, l-a dezlegat și i-a vindecat rănile instantaneu. Apariția sfântului nevătămat a provocat stupoare în rândul torționarilor și a mulțimii.^1^' || '\n' ||
    '3.  **Groapa cu Var**: Într-o încercare de a-i dizolva complet trupul, împăratul a poruncit să fie aruncat într-o groapă adâncă, plină cu var nestins, și lăsat acolo timp de trei zile. Varul, o substanță extrem de corozivă, nu l-a afectat. Când soldații au deschis groapa, l-au găsit pe Gheorghe viu, stând în picioare și lăudând pe Dumnezeu, cu trupul intact. Această minune trimite la simbolistica Învierii și a coborârii în iad, de unde cel drept iese neatins.' || '\n' ||
    '4.  **Încălțămintea cu Cuie**: A fost forțat să alerge purtând încălțăminte de fier, înroșită în foc, având cuie ascuțite în interior. Această tortură viza distrugerea voinței prin durere continuă la fiecare pas, însă sfântul a alergat invocând numele Domnului, transformând cursa durerii într-o procesiune a credinței.' || '\n' ||
    '5.  **Băutura Otrăvită**: Vrăjitorul Athanasie, renumit pentru știința sa ocultă, a fost chemat să prepare o otravă letală. Gheorghe a băut cupa otrăvită după ce a făcut semnul Sfintei Cruci deasupra ei și a rămas nevătămat. Prin aceasta, s-a împlinit promisiunea evanghelică: „de vor bea ceva de moarte, nu-i va vătăma" (Marcu 16:18). Această minune a demonstrat superioritatea puterii divine asupra magiei și vrăjitoriei păgâne.' || '\n\n' ||
    '### 2.2. Minunile din Timpul Martiriului și Convertirile' || '\n\n' ||
    'Perioada de detenție și tortură a fost, paradoxal, una de intensă activitate misionară. Minunile săvârșite de Sfântul Gheorghe în acest context au dus la convertiri spectaculoase, chiar în inima curții imperiale.' || '\n\n' ||
    '- **Învierea Mortului**: Provocat de vrăjitorul Athanasie să-și dovedească puterea Dumnezeului său, Sfântul Gheorghe a înviat un mort dintr-un mormânt vechi din apropiere. Această minune a avut un impact devastator asupra audienței. Vrăjitorul Athanasie, văzând înfrângerea morții, a căzut la picioarele sfântului, mărturisind pe Hristos, și a fost martirizat pe loc, spălându-și păcatele în propriul sânge.^1^' || '\n' ||
    '- **Convertirea Împărătesei Alexandra**: Unul dintre cele mai dramatice episoade este convertirea soției împăratului Dioclețian, numită în hagiografie Alexandra (identificată uneori cu Prisca). Văzând curajul, seninătatea și minunile sfântului, inima ei s-a deschis către Adevăr. Ea a mărturisit credința creștină în fața soțului ei, un gest de o audacitate incredibilă. Dioclețian a condamnat-o la moarte împreună cu Gheorghe. Tradiția spune că, în drum spre locul execuției, ea a cerut să se odihnească puțin și și-a dat sufletul în mâinile Domnului, scăpând astfel de sabia călăului (alte surse spun că a fost decapitată).^1^' || '\n' ||
    '- **Minunea din temniță**: Chiar și în închisoare, oamenii veneau la el. Un fermier sărac, Glicherie, i s-a plâns că boul său a murit. Sfântul i-a spus să meargă acasă că boul e viu. Glicherie s-a întors văzând minunea și a strigat „Mare este Dumnezeul lui Gheorghe!", fiind și el martirizat imediat.' || '\n\n' ||
    '### 2.3. Execuția și Dies Natalis' || '\n\n' ||
    'Văzând că toate metodele de tortură eșuează și că prezența lui Gheorghe devine un catalizator pentru convertirea maselor și a propriei armate, Dioclețian a emis sentința finală: decapitarea prin sabie.' || '\n\n' ||
    'La data de **23 aprilie 303 d.Hr.**, Sfântul Mare Mucenic Gheorghe a fost dus la locul execuției, în afara zidurilor Nicomediei. El și-a plecat capul sub sabie cu bucurie, mulțumind lui Dumnezeu pentru că a ajuns la limanul biruinței. Această zi a rămas înscrisă în calendarul Bisericii drept *Dies Natalis* -- ziua nașterii sale pentru viața veșnică.^4^' || '\n\n' ||
    'Trupul său a fost recuperat de creștini și, conform dorinței sale testamentare, a fost transportat în Palestina, la Lida, patria mamei sale, unde a fost înmormântat cu mare cinste.' || '\n\n' ||
    '## III. Minunea cu Balaurul: Exegeză, Simbolism și Iconografie' || '\n\n' ||
    'Dintre toate minunile atribuite Sfântului Gheorghe, cea a uciderii balaurului (dragonului) este, fără îndoială, cea mai iconică. Ea a definit reprezentarea sa vizuală și a cimentat statutul său de sfânt cavaler în conștiința populară. De olsașă această minune nu apare în actele martirice cele mai timpurii, ea s-a cristalizat în tradiția hagiografică (în special în *Legenda Aurea* din secolul al XIII-lea și în surse bizantine mai vechi, din secolele XI-XII) și a devenit centrală pentru înțelegerea rolului său cosmic.^6^' || '\n\n' ||
    '### 3.1. Narațiunea Legendei' || '\n\n' ||
    'Legenda plasează evenimentul în apropierea cetății Silena (identificată uneori cu Beirut sau o locație din Libia/Capadocia, ori chiar lângă Lida). Un balaur imens și veninos își făcuse sălaș într-un lac din apropierea cetății, terorizând populația. Pentru a ține fiara departe de ziduri, locuitorii erau nevoiți să îi ofere zilnic ofrande: la început oi, iar când acestea s-au terminat, copii aleși prin tragere la sorți.^3^' || '\n\n' ||
    'Drama atinge paroxismul când sorțul cade pe unica fiică a împăratului cetății. Deși tatăl încearcă să o răscumpere cu aur și argint, poporul revoltat cere sacrificiul. Prințesa este dusă la marginea lacului, așteptându-și sfârșitul tragic. În acest moment critic, apare Sfântul Gheorghe, călare, în trecere prin acea regiune. Aflând cauza lacrimilor fetei și văzând balaurul ieșind din ape, sfântul nu fuge. Încrezător în puterea Sfintei Cruci și invocând ajutorul lui Hristos, el atacă fiara, o străpunge cu sulița și o doboară la pământ.^3^' || '\n\n' ||
    'Un detaliu interesant al legendei este că Gheorghe nu ucide balaurul imediat. El îi cere prințesei să-și lege brâul de gâtul fiarei rănite și să o ducă în cetate „ca pe un câine blând". Această imagine a răului domesticit și târât în văzul lumii are o forță simbolică aparte. În piața cetății, în fața mulțimii îngrozite, Gheorghe ucide balaurul cu sabia, condiționând salvarea cetății de convertirea la creștinism. Se spune că 25.000 de oameni, inclusiv împăratul, s-au botezat în acea zi, iar în locul unde a fost ucis balaurul a izvorât o apă tămăduitoare.^3^' || '\n\n' ||
    '### 3.2. Hermeneutica Simbolului: Niveluri de Interpretare' || '\n\n' ||
    'Această minune suportă multiple grile de lectură, de la istoric la mistic și psihologic:' || '\n\n' ||
    '1.  **Nivelul Istoric-Politic**: În această cheie, balaurul îl reprezintă pe Împăratul Dioclețian sau Imperiul Roman păgân, care „devora" creștinii prin persecuții. Prințesa este Biserica tânără, amenințată cu extincția. Sfântul Gheorghe este brațul înarmat al credinței care, prin puterea lui Hristos, învinge „fiara" politică și oprește tributul de sânge al martirilor.^2^' || '\n' ||
    '2.  **Nivelul Dogmatic și Spiritual**: Balaurul este diavolul, „șarpele cel vechi" (Apocalipsa 20:2). Sulița sfântului, care în iconografie se termină adesea cu o cruce, reprezintă puterea Crucii lui Hristos. Victoria nu este una fizică, ci spirituală: credința învinge idolatria și păcatul.' || '\n' ||
    '3.  **Nivelul Psihologic și Ascetic**: În spiritualitatea ortodoxă, balaurul simbolizează patimile și impulsurile subconștiente haotice (frica, furia, desfrânarea). Sfântul Gheorghe este modelul creștinului luptător (ascetul) care, stăpânind trupul (calul), străpunge patima cu sulița rugăciunii și a trezviei. Salvarea prințesei poate fi interpretată ca salvarea sufletului (*anima*) din ghearele păcatului.^7^ Episcopul Macarie explică faptul că această luptă ne ajută să „ucidem balaurii patimilor, ispitelor, fricilor și îndoielilor".^8^' || '\n' ||
    '4.  **Simbolismul Meteorologic și Cosmic**: În tradiția populară, balaurul este adesea asociat cu norii de furtună și grindină care distrug recoltele. Uciderea balaurului este un act de cosmizare, de restabilire a echilibrului natural necesar agriculturii. Sfântul devine astfel un garant al fertilității și al protecției recoltelor.^5^' || '\n\n' ||
    '### 3.3. Evoluția Iconografică' || '\n\n' ||
    'Reprezentarea vizuală a Sfântului Gheorghe a evoluat semnificativ. În primele secole, el era pictat ca un martir pedestru, ținând o cruce în mână. Odată cu răspândirea legendei balaurului, imaginea sa a devenit dinamică: un tânăr cavaler (fără barbă, semn al tinereții veșnice), călare pe un cal alb (simbol al harului sau al biruinței), purtând mantie roșie (culoarea sângelui martiric) și străpungând balaurul.' || '\n\n' ||
    'Un element iconografic particular, întâlnit în unele icoane, este prezența unui tânăr mic de statură, așezat pe cal în spatele sfântului, ținând un vas în mână. Acesta face referire la o altă minune: eliberarea unui tânăr din robia sarcinilor (din Creta sau Mitilene) și aducerea lui instantanee în casa părintească, chiar în momentul când îi servea vin stăpânului său sau când părinții săi îi făceau pomenirea.^9^' || '\n\n' ||
    '## IV. Imnografia și Liturgica: Teologia Cântată' || '\n\n' ||
    'Textele liturgice dedicate Sfântului Gheorghe constituie o sinteză teologică a vieții și semnificației sale, fiind capodopere ale imnografiei bizantine.' || '\n\n' ||
    '### 4.1. Troparul (Glasul 4)' || '\n\n' ||
    'Acest imn central al sărbătorii și definește rolurile multiple ale sfântului:' || '\n\n' ||
    '*„Ca un izbăvitor al celor robiţi şi celor săraci ocrotitor, celor bolnavi doctor, împăraţilor ajutător, purtătorule de biruinţă, Mare Mucenice Gheorghe, roagă pe Hristos Dumnezeu să mântuiască sufletele noastre."*.^10^' || '\n\n' ||
    '**Analiză**: Textul structurează funcțiile sfântului: eliberator (al celor prinși de dușmani sau de patimi), protector social (al săracilor), vindecător (doctor fără de arginți) și sprijin al autorității politice creștine legitime (împăraților). Titlul *Tropeophoros* (Purtător de biruință) rezumă identitatea sa.' || '\n\n' ||
    '### 4.2. Condacul (Glasul 4)' || '\n\n' ||
    '*„Lucrat fiind de Dumnezeu, te-ai arătat lucrător preacinstit al dreptei credinţe, spicele virtuţilor adunându-ţi. Că semănând cu lacrimi, cu veselie seceri şi luptând cu sânge, pe Hristos ai luat. Şi cu rugăciunile tale sfinte, dai tuturor iertare de greşeli."*.^9^' || '\n\n' ||
    '**Analiză**: Imnul folosește o metaforă agricolă profundă („lucrat", „spice", „semănând", „seceri"). Numele „Gheorghe" provine din grecescul *Georgios* (țăran, lucrător al pământului). Condacul face un joc de cuvinte teologic: Gheorghe, cultivatorul pământului, devine cultivatorul credinței. Sângele vărsat este sămânța care produce recolta mântuirii și a iertării.' || '\n\n' ||
    '### 4.3. Canonul și Paraclisul' || '\n\n' ||
    'Există dezbateri academice privind autorul Canonului din Utrenie. Unele manuscrise și acrostihul indică pe **Sfântul Iosif Imnograful** („Primește lauda, sfinte Gheorghe, Iosif") ^13^, în timp ce tradiția menționează contribuții ale **Sfântului Teofan Mărturisitorul** sau **Ioan Damaschin**. Paraclisul este o rugăciune de implorare intensă, folosită la vreme de necaz, unde sfântul este invocat ca „grabnic ajutător".^14^' || '\n\n' ||
    '## V. Geografie Sacră: Moaște, Ctitorii și Răspândirea Cultului' || '\n\n' ||
    'Venerarea Sfântului Gheorghe a generat o rețea globală de locuri sfinte, relicvele sale fiind considerate surse de har și protecție.' || '\n\n' ||
    '### 5.1. Lida (Lod) și Sărbătoarea din 3 Noiembrie' || '\n\n' ||
    'Centrul mondial al cultului este Lida (Israel), unde se află mormântul sfântului. Pe **3 noiembrie**, Biserica Ortodoxă (în special cea din Ierusalim și Rusia, dar și în calendarul românesc cu cruce neagră) prăznuiește „Așezarea moaștelor Sfântului Mare Mucenic Gheorghe în Lida" și sfințirea bisericii sale zidite în vremea împăratului Constantin cel Mare.^16^ Pentru palestinieni, Sfântul Gheorghe (*Mar Jiries*) este un erou național și local, venerat inclusiv de musulmani, care îl asociază cu figura coranică misterioasă *Al-Khidr* („Cel Verde"), un profet nemuritor asociat cu apa și vegetația.^2^' || '\n\n' ||
    '### 5.2. Sfântul Munte Athos: „Grădina Maicii Domnului și a Sfântului Gheorghe"' || '\n\n' ||
    'Athosul este un bastion al venerării sale:' || '\n\n' ||
    '- **Mănăstirea Zografou**: Este închinată Sfântului Gheorghe și are o istorie miraculoasă a fondării (sec. X). Trei frați nobili (Moise, Aaron, Ioan) nu se puteau decide asupra hramului. Au lăsat o scândură nespictată în biserică și s-au rugat. Dimineața, au găsit chipul Sfântului Gheorghe pictat pe scândură prin minune (*Acheiropoietos* - nefăcut de mână omenească).^18^ Mănăstirea păstrează și steagul de luptă al lui Ștefan cel Mare, care poartă efigia sfântului.^20^' || '\n' ||
    '- **Mănăstirea Xenofont**: Păstrează **mâna dreaptă a Sfântului Gheorghe**, considerată una dintre cele mai prețioase relicve ale mănăstirii, alături de o icoană monumentală în mozaic (sec. X-XI).^21^' || '\n\n' ||
    '### 5.3. Relicve și Locuri Sfinte în România' || '\n\n' ||
    'România este un spațiu unde cultul Sfântului Gheorghe este structural identității naționale:' || '\n\n' ||
    '- **Mănăstirea Cernica**: Recent, s-a clarificat faptul că mănăstirea deține **Capul Sfântului Gheorghe** (sau un fragment major din craniu), relicvă de o importanță excepțională. În octombrie 2024, acest odor a fost purtat în procesiune istorică în Mărginimea Sibiului, marcând o revitalizare a cultului relicvelor sale.^23^' || '\n' ||
    '- **Biserica Sfântul Gheorghe Nou (București)**: Situată la kilometrul zero, este o ctitorie brâncovenească fundamentală. Deși hramul este Sf. Gheorghe, biserica adăpostește **mâna dreaptă a Sfântului Ierarh Nicolae** ^24^ și moaștele Sfântului Martir Constantin Brâncoveanu. Este importantă distincția: mâna de la Sf. Gheorghe Nou este a Sfântului Nicolae, nu a Sfântului Gheorghe. Totuși, biserica rămâne un centru major de celebrare a hramului.' || '\n' ||
    '- **Mănăstirea Voroneț**: Ridicată de Ștefan cel Mare în 1488 într-un timp record (3 luni și 3 săptămâni), ca mulțumire adusă Sfântului Gheorghe pentru victoria împotriva turcilor, la sfatul Sfântului Daniil Sihastrul. Hramul este Sfântul Gheorghe. Aici se află mormântul Sfântului Daniil Sihastrul.^27^ Pictura exterioară și hramul fac din Voroneț un monument votiv închinat „Purtătorului de Biruință".' || '\n' ||
    '- **Biserica Titan (Parcul IOR) și Biserica Andronache**: Au primit recent fragmente din moaștele Sfântului Gheorghe, intensificând cultul în București.^29^' || '\n\n' ||
    '**Notă de Distincție**: Trebuie evitată confuzia cu **Sfântul Gheorghe Pelerinul (Lazăr)**, un sfânt român canonizat recent, ale cărui moaște se află la Mănăstirea Văratec și parțial la Mănăstirea Țigănești. Acesta este un ascet din secolul al XX-lea, diferit de Marele Mucenic.^30^' || '\n\n' ||
    '## VI. Patronajul Militar: De la Legiuni la Armata Română' || '\n\n' ||
    'Legătura dintre Sfântul Gheorghe și casta militară este indisolubilă. Ștefan cel Mare, domnitorul Moldovei, purta imaginea sfântului pe steagurile sale de luptă, considerându-l generalul celest care îi conducea oștile spre victorie.^31^' || '\n\n' ||
    'Această tradiție a fost recuperată oficial în epoca modernă. În anul **1996**, printr-un ordin al Ministrului Apărării Naționale, Sfântul Mare Mucenic Gheorghe a fost desemnat oficial **Ocrotitorul Forțelor Terestre Române**.^31^ Această decizie recunoaște virtuțile militare exemplare ale sfântului: curajul, disciplina, sacrificiul pentru o cauză superioară și loialitatea absolută. Ziua de 23 aprilie este sărbătorită în garnizoanele din țară și în teatrele de operațiuni cu ceremonii militare și religioase, marcând simbioza dintre *militia saecularis* (armata statului) și *militia Christi* (armata spirituală).' || '\n\n' ||
    'Alte țări care îl au ca patron spiritual includ Anglia (din 1222, sub Richard Inima de Leu), Georgia, Malta, Lituania și Serbia, demonstrând universalitatea apelului său marțial.^32^' || '\n\n' ||
    '## VII. Tradiții și Obiceiuri Populare: Sângiorzul, Armindenul și Lupta cu Strigoii' || '\n\n' ||
    'În spațiul românesc, sărbătoarea de 23 aprilie, numită popular **Sângiorz**, este mult mai mult decât o comemorare religioasă; este un prag cosmic esențial în calendarul popular, marcând începutul verii pastorale.' || '\n\n' ||
    '### 7.1. Ciclul Pastoral: Sângiorzul și Sânmedru' || '\n\n' ||
    'Calendarul popular împarte anul în două anotimpuri simetrice: vara (de la Sângiorz la Sânmedru/Sf. Dumitru) și iarna (de la Sânmedru la Sângiorz). Se spune că Sfântul Gheorghe „ia cheile vremii" de la Sfântul Dumitru pentru a deschide codrul și a aduce căldura, înverzind natura.^5^' || '\n\n' ||
    'La Sângiorz are loc „Alesul" sau „Sâmbra Oilor", momentul urcării turmelor la munte. Se realizează „Măsurișul laptelui", un ritual economic și social prin care se stabilește cantitatea de brânză cuvenită fiecărui proprietar de oi, în funcție de cât lapte dau oile sale la această dată.^5^' || '\n\n' ||
    '### 7.2. Mânecătoarea și Lupta cu Strigoii' || '\n\n' ||
    'Noaptea dinspre 23 aprilie, numită „Mânecătoarea", este considerată un timp magic și periculos. Tradiția spune că cerurile se deschid, dar și granițele infernului devin permeabile. Este noaptea în care **strigoii** (vii sau morți) ies să se bată la hotare pentru a fura „mana" laptelui și a câmpului.^33^' || '\n\n' ||
    '- **Războiul ocult**: Strigoii se luptă folosind limbile de la melițe (unelte de prelucrat cânepa) sau coase furate. Miza este fertilitatea satului: cine câștigă lupta ia mana vacilor și a grâului pentru anul respectiv.^34^' || '\n' ||
    '- **Ritualuri apotropaice (de apărare)**:' || '\n' ||
    '    - **Usturoiul**: Este arma principală. Oamenii se ung cu usturoi pe frunte, în piept, pe spate și la încheieturi. Ușile și ferestrele caselor și grajdurilor sunt unse cu mujdei pentru a împiedica intrarea duhurilor malefice.^33^' || '\n' ||
    '    - **Ascunderea melițelor**: Femeile ascund limbile de meliță pentru ca strigoii să nu le poată folosi drept arme.' || '\n' ||
    '    - **Focul Viu**: Tinerii aprind focuri pe dealuri și sar peste ele pentru purificare. Fumul și lumina au rolul de a alunga forțele întunericului.^5^' || '\n' ||
    '    - **Zgomotul**: Se sună din buciume și se fac zgomote puternice pentru a speria spiritele.' || '\n\n' ||
    '### 7.3. Armindenul și Ritul Ramurii Verzi' || '\n\n' ||
    'Legat strâns de perioada Sângiorzului (uneori suprapus cu 1 Mai sau 23 Aprilie) este obiceiul **Armindenului**. Acesta constă în așezarea unei ramuri verzi (fag, stejar, salcie) sau a unui pom întreg la porțile caselor, la intrările în grajduri și la ferestre.^35^' || '\n\n' ||
    'Această ramură, numită „Arminden", are rol protector și fertilizator. Ea apără gospodăria de strigoi și aduce vigoarea vegetală în spațiul uman. Ramura este păstrată până la coacerea grâului, când este folosită pentru a aprinde cuptorul în care se coace prima pâine din noua recoltă, închizând astfel ciclul agrar.^35^ De asemenea, se pun rugi de mărăcini sau măceș la porți pentru ca strigoii să se încurce în ghimpi.^33^' || '\n\n' ||
    '### 7.4. Obiceiuri Regionale Specifice' || '\n\n' ||
    '- **Jocul Banilor (Sângeorz-Băi)**: Un obicei unic în zona Năsăudului. Este un dans ritualic desfășurat în duminica de după Sângiorz (sau chiar de sărbătoare), unde flăcăii plătesc ceterașii pentru a juca fetele. Este un dans al curtatului și al oficializării relațiilor premaritale („aici se legau iubirile").^37^' || '\n' ||
    '- **Sângiorzul (Obicei din Maramureș/Transilvania)**: Un flăcău este ales și îmbrăcat complet în crengi verzi, devenind o personificare a naturii (un „Green Man" autohton). El este purtat prin sat și udat cu apă la fiecare gospodărie. Dacă „Sângiorzul" este udat bine, va fi ploaie și belșug; dacă nu, va fi secetă. Este un rit de fertilitate arhaic, precreștin, supraviețuind sub patronajul sfântului.^38^' || '\n' ||
    '- **Scăldatul în rouă**: În dimineața sărbătorii, înainte de răsăritul soarelui, fetele și flăcăii se tăvălesc în rouă sau se spală în apă curgătoare pentru a fi sănătoși, frumoși și feriți de boli tot anul.^39^' || '\n\n' ||
    '## Concluzii' || '\n\n' ||
    'Analiza complexă a figurii Sfântului Mare Mucenic Gheorghe relevă o personalitate care a depășit cu mult cadrul istoric al secolului al IV-lea, devenind un pilon fundamental al spiritualității și culturii europene și orientale.' || '\n\n' ||
    '1.  **Dimensiunea Teologică**: Sfântul Gheorghe întruchipează victoria paradoxală a creștinismului -- biruința prin jertfă. Minunea cu balaurul rămâne o cateheză vizuală despre lupta nevăzută cu patimile și despre curajul necesar confruntării cu răul social și politic.' || '\n' ||
    '2.  **Dimensiunea Etnografică**: În spațiul românesc, „Sângiorzul" este un fenomen cultural total. El gestionează timpul (deschiderea anului pastoral), spațiul (protecția hotarelor de strigoi) și viața (riturile de fertilitate și sănătate). Sincretismul dintre sfântul militar și zeitatea agrară a vegetației este perfect, creând un calendar popular viu.' || '\n' ||
    '3.  **Dimensiunea Națională**: Prin patronajul asupra Armatei Române și prin prezența moaștelor sale (Cernica, Titan, Athos), Sfântul Gheorghe rămâne un protector activ al neamului, invocat de la voievozii medievali până la militarii contemporani.' || '\n\n' ||
    'Astfel, Sfântul Gheorghe nu este doar o amintire a trecutului, ci o prezență dinamică, „Purtătorul de Biruință" care continuă să lupte cu balaurii istoriei și ai sufletului uman.' || '\n\n' ||
    '### Tablou Sinoptic: Relicvele Majore ale Sfântului Gheorghe și Locațiile Lor' || '\n\n' ||
    '| **Locație** | **Țară** | **Tipul Relicvei** | **Detalii și Semnificație** | **Sursă** |' || '\n' ||
    '| :--- | :--- | :--- | :--- | :--- |' || '\n' ||
    '| **Lida (Lod)** | Israel | Mormântul și Moaște | Centrul istoric al cultului; Biserica zidită în sec. IV. | ^16^ |' || '\n' ||
    '| **Mănăstirea Xenofont** | Muntele Athos (Grecia) | Mâna Dreaptă | Relicva principală a mănăstirii; Icoană în mozaic (sec. X). | ^21^ |' || '\n' ||
    '| **Mănăstirea Zografou** | Muntele Athos (Grecia) | Fragmente și Icoane | Icoana *Acheiropoietos* (nefăcută de mână); „Casa Sfântului Gheorghe". | ^18^ |' || '\n' ||
    '| **Mănăstirea Cernica** | România (Ilfov) | Capul (Cranium) | Odor de mare preț, purtat în procesiune în 2024 în Sibiu. | ^23^ |' || '\n' ||
    '| **Biserica Sf. Gheorghe Nou** | România (București) | Fragmente minore | Hram principal; adăpostește Mâna Sf. Nicolae (confuzie frecventă). | ^24^ |' || '\n' ||
    '| **Biserica Titan (IOR)** | România (București) | Fragment osos | Adus recent pentru venerarea credincioșilor din Capitală. | ^29^ |' || '\n' ||
    '| **Mănăstirea Voroneț** | România (Suceava) | Prezență prin Hram | Ctitorie votivă ridicată în 3 luni și 3 săptămâni. | ^27^ |' || '\n\n' ||
    '### Structura Comparativă: Tradiții Bisericești vs. Tradiții Populare' || '\n\n' ||
    '| **Aspect** | **Tradiția Bisericească (Dogmatică)** | **Tradiția Populară (Etnografică)** |' || '\n' ||
    '| :--- | :--- | :--- |' || '\n' ||
    '| **Semnificația Zilei** | *Dies Natalis* (Ziua martiriului); Biruința credinței. | Începutul anului pastoral; Înverzirea naturii; „Cheile vremii". |' || '\n' ||
    '| **Inamicul** | Diavolul, idolatria, prigonitorii (simbolizați de Balaur). | Strigoii (care fură mana), frigul, sterilitatea. |' || '\n' ||
    '| **Arme de luptă** | Crucea, Rugăciunea, Sângele martiric. | Usturoiul, Focul Viu, Ramura de Arminden, Zgomotul. |' || '\n' ||
    '| **Ritualuri** | Sfânta Liturghie, Agheasma, Procesiuni cu icoane. | Scăldatul în rouă, Urzicatul, Jocul Banilor, Udătorii. |' || '\n' ||
    '| **Rolul Sfântului** | Martir, Ocrotitor, Vindecător, Patron Militar. | Zeu al vegetației, Păstor cosmic, Garant al laptelui. |' || '\n\n' ||
    '#### Works cited' || '\n\n' ||
    '1. Sfântul Gheorghe- cel mai iubit dintre oamenii lui Dumnezeu - Istorie pe scurt, accessed January 25, 2026, [[https://www.istorie-pe-scurt.ro/sfantul-gheorghe-cel-mai-iubit-dintre-oamenii-lui-dumnzeu/]{.underline}](https://www.istorie-pe-scurt.ro/sfantul-gheorghe-cel-mai-iubit-dintre-oamenii-lui-dumnzeu/)' || '\n' ||
    '2. De ce îl cinstesc palestinienii pe Sfântul Mucenic Gheorghe? - Doxologia, accessed January 25, 2026, [[https://doxologia.ro/de-ce-il-cinstesc-palestinienii-pe-sfantul-mucenic-gheorghe]{.underline}](https://doxologia.ro/de-ce-il-cinstesc-palestinienii-pe-sfantul-mucenic-gheorghe)' || '\n' ||
    '3. Sfantul Mare Mucenic Gheorghe, purtatorul de biruinta CrestinOrtodox.ro, accessed January 25, 2026, [[https://www.crestinortodox.ro/sfantul-gheorghe/sfantul-mare-mucenic-gheorghe-purtatorul-biruinta-148567.html]{.underline}](https://www.crestinortodox.ro/sfantul-gheorghe/sfantul-mare-mucenic-gheorghe-purtatorul-biruinta-148567.html)' || '\n' ||
    '4. Sfântul Gheorghe - Wikipedia, accessed January 25, 2026, [[https://ro.wikipedia.org/wiki/Sf%C3%A2ntul_Gheorghe]{.underline}](https://ro.wikipedia.org/wiki/Sf%C3%A2ntul_Gheorghe)' || '\n' ||
    '5. Sfântul Mare Mucenic Gheorghe, purtătorul de biruință - între credințe și obiceiuri, accessed January 25, 2026, [[https://www.cultura.ro/sfantul-mare-mucenic-gheorghe-purtatorul-de-biruinta-intre-credinte-si-obiceiuri/]{.underline}](https://www.cultura.ro/sfantul-mare-mucenic-gheorghe-purtatorul-de-biruinta-intre-credinte-si-obiceiuri/)' || '\n' ||
    '6. Ce nu știam despre balaurul din icoana Sfântul Gheorghe? - Bizanticons Blog, accessed January 25, 2026, [[https://blog.bizanticons.ro/2021/04/26/ce-nu-stiam-despre-balaurul-din-icoana-sfantului-gheorghe/]{.underline}](https://blog.bizanticons.ro/2021/04/26/ce-nu-stiam-despre-balaurul-din-icoana-sfantului-gheorghe/)' || '\n' ||
    '7. Minunile și semnele biruințelor Sfântului Gheorghe în viața noastră - Doxologia, accessed January 25, 2026, [[https://doxologia.ro/minunile-semnele-biruintelor-sfantului-gheorghe-viata-noastra]{.underline}](https://doxologia.ro/minunile-semnele-biruintelor-sfantului-gheorghe-viata-noastra)' || '\n' ||
    '8. „CUM NE AJUTĂ SFÂNTUL MUCENIC GHEORGHE SĂ UCIDEM BALAURII PATIMILOR, FRICILOR ȘI ÎNDOIELILOR?" - YouTube, accessed January 25, 2026, [[https://www.youtube.com/watch?v=C7bapIu6BEw]{.underline}](https://www.youtube.com/watch?v=C7bapIu6BEw)' || '\n' ||
    '9. Sfântul Mare Mucenic Gheorghe, Purtătorul de Biruință, care s-a săvârşit de sabie în Nicomidia în vremea împăratului Dioclețian (+303). - Calendox, accessed January 25, 2026, [[https://calendar.ortodox.md/calendar/entry/RO/337]{.underline}](https://calendar.ortodox.md/calendar/entry/RO/337)' || '\n' ||
    '10. Troparul Sfântului Mare Mucenic Gheorghe, purtătorul de biruință (1) - Doxologia, accessed January 25, 2026, [[https://doxologia.ro/troparul-sfantului-mare-mucenic-gheorghe-purtatorul-de-biruinta-1-0]{.underline}](https://doxologia.ro/troparul-sfantului-mare-mucenic-gheorghe-purtatorul-de-biruinta-1-0)' || '\n' ||
    '11. Troparul Sf. Mare Mucenic Gheorghe - Parohia Ortodoxă Română Tübingen, accessed January 25, 2026, [[https://parohia-tuebingen.de/ro/show_pray/22]{.underline}](https://parohia-tuebingen.de/ro/show_pray/22)' || '\n' ||
    '12. Acatistul Sfântului Mare Mucenic Gheorghe, Purtătorul de biruință - Doxologia, accessed January 25, 2026, [[https://doxologia.ro/acatistul-sfantului-mare-mucenic-gheorghe-purtatorul-de-biruinta]{.underline}](https://doxologia.ro/acatistul-sfantului-mare-mucenic-gheorghe-purtatorul-de-biruinta)' || '\n' ||
    '13. Sf. Iosif Imnograful: Canon de rugăciune la Sfântul Mare Mucenic Gheorghe, purtătorul de biruință - Parohia Sf. Maxim Mărturisitorul - Sf. Grigore Palama, Copou - Iași, accessed January 25, 2026, [[http://www.parohiacopou.ro/sf-iosif-imnograful-canon-de-rugaciune-la-sfantul-mare-mucenic-gheorghe-purtatorul-de-biruinta]{.underline}](http://www.parohiacopou.ro/sf-iosif-imnograful-canon-de-rugaciune-la-sfantul-mare-mucenic-gheorghe-purtatorul-de-biruinta)' || '\n' ||
    '14. Paraclisul Sf. Gheorghe | PDF - Scribd, accessed January 25, 2026, [[https://ro.scribd.com/document/458432319/Paraclisul-Sf-Gheorghe]{.underline}](https://ro.scribd.com/document/458432319/Paraclisul-Sf-Gheorghe)' || '\n' ||
    '15. Paraclisul Sfântului Mare Mucenic Gheorghe, purtătorul de biruinţă - Doxologia, accessed January 25, 2026, [[https://doxologia.ro/paraclisul-sfantului-mare-mucenic-gheorghe-purtatorul-de-biruinta]{.underline}](https://doxologia.ro/paraclisul-sfantului-mare-mucenic-gheorghe-purtatorul-de-biruinta)' || '\n' ||
    '16. Așezarea moaștelor Sfântului Mare Mucenic Gheorghe în Lida | Doxologia, accessed January 25, 2026, [[https://doxologia.ro/asezarea-moastelor-sfantului-mare-mucenic-gheorghe-lida]{.underline}](https://doxologia.ro/asezarea-moastelor-sfantului-mare-mucenic-gheorghe-lida)' || '\n' ||
    '17. Sfinţirea Bisericii Sfântului Mare Mucenic Gheorghe din Lida, adică aşezarea sfintelor sale moaşte într-însa (IV). - Calendox, accessed January 25, 2026, [[https://calendar.ortodox.md/calendar/entry/RO/c2a9d3e7-9c7c-45dc-a5cd-fa0fe45cdcad]{.underline}](https://calendar.ortodox.md/calendar/entry/RO/c2a9d3e7-9c7c-45dc-a5cd-fa0fe45cdcad)' || '\n' ||
    '18. Icoana făcătoare de minuni a Sfântului Gheorghe de la Mănăstirea Zografu - Doxologia, accessed January 25, 2026, [[https://doxologia.ro/icoana-facatoare-de-minuni-sfantului-gheorghe-de-la-manastirea-zografu]{.underline}](https://doxologia.ro/icoana-facatoare-de-minuni-sfantului-gheorghe-de-la-manastirea-zografu)' || '\n' ||
    '19. Mănăstirea Zografu (Muntele Athos) - OrthodoxWiki, accessed January 25, 2026, [[https://ro.orthodoxwiki.org/M%C4%83n%C4%83stirea_Zografu_(Muntele_Athos)]{.underline}](https://ro.orthodoxwiki.org/M%C4%83n%C4%83stirea_Zografu_(Muntele_Athos))' || '\n' ||
    '20. Mănăstirii Zografu - Muntele Athos, accessed January 25, 2026, [[https://www.munteleathos.ro/ZOGRAFU.HTM]{.underline}](https://www.munteleathos.ro/ZOGRAFU.HTM)' || '\n' ||
    '21. Holy Monastery of Xenophon: the Monastery of Panagia Hodegetria and Saint Georgios - monastiriaka.gr, accessed January 25, 2026, [[https://www.monastiriaka.gr/en/blog/holy-monastery-of-xenophon-the-monastery-of-panagia-hodegetria-and-saint-georgios]{.underline}](https://www.monastiriaka.gr/en/blog/holy-monastery-of-xenophon-the-monastery-of-panagia-hodegetria-and-saint-georgios)' || '\n' ||
    '22. Xenophontos monastery | Athos.Guide, accessed January 25, 2026, [[https://athos.guide/en/monasteries/ksenofont]{.underline}](https://athos.guide/en/monasteries/ksenofont)' || '\n' ||
    '23. Moaștele Sf. Gheorghe de la Cernica au fost primite cu onoruri militare în Mărginimea Sibiului - Basilica, accessed January 25, 2026, [[https://basilica.ro/moastele-sf-gheorghe-de-la-cernica-au-fost-primite-cu-onoruri-militare-in-marginimea-sibiului/]{.underline}](https://basilica.ro/moastele-sf-gheorghe-de-la-cernica-au-fost-primite-cu-onoruri-militare-in-marginimea-sibiului/)' || '\n' ||
    '24. Moastele Sf. Nicolae au fost scoase spre inchinare la Biserica Sf. Gheorghe Nou, accessed January 25, 2026, [[https://www.crestinortodox.ro/stiri/crestinortodox/moastele-sf-nicolae-fost-scoase-spre-inchinare-biserica-sf-gheorghe-nou-74624.html]{.underline}](https://www.crestinortodox.ro/stiri/crestinortodox/moastele-sf-nicolae-fost-scoase-spre-inchinare-biserica-sf-gheorghe-nou-74624.html)' || '\n' ||
    '25. Moaştele Sfântului Ioan Botezătorul la Biserica „Sfântul Gheorghe"-Nou - Ziarul Lumina, accessed January 25, 2026, [[https://ziarullumina.ro/actualitate-religioasa/stiri/moastele-sfantului-ioan-botezatorul-la-biserica-sfantul-gheorghe-nou-194319.html]{.underline}](https://ziarullumina.ro/actualitate-religioasa/stiri/moastele-sfantului-ioan-botezatorul-la-biserica-sfantul-gheorghe-nou-194319.html)' || '\n' ||
    '26. Odoarele bisericii - Biserica Sfântul Gheorghe-Nou, accessed January 25, 2026, [[https://www.sfantulgheorghenou.ro/odoarele-bisericii/]{.underline}](https://www.sfantulgheorghenou.ro/odoarele-bisericii/)' || '\n' ||
    '27. Biserica „Sf. Gheorghe" de la Voroneţ - Revista Culturală Leviathan, accessed January 25, 2026, [[https://leviathan.ro/biserica-sf-gheorghe-de-la-voronet/]{.underline}](https://leviathan.ro/biserica-sf-gheorghe-de-la-voronet/)' || '\n' ||
    '28. Moaștele Sfântului Daniil Sihastrul - Doxologia, accessed January 25, 2026, [[https://doxologia.ro/moastele-sfantului-daniil-sihastrul]{.underline}](https://doxologia.ro/moastele-sfantului-daniil-sihastrul)' || '\n' ||
    '29. Moaștele Sfântului Mare Mucenic Gheorghe la o biserică din Capitală - Ziarul Lumina, accessed January 25, 2026, [[https://ziarullumina.ro/actualitate-religioasa/stiri/moastele-sfantului-mare-mucenic-gheorghe-la-o-biserica-din-capitala-186724.html]{.underline}](https://ziarullumina.ro/actualitate-religioasa/stiri/moastele-sfantului-mare-mucenic-gheorghe-la-o-biserica-din-capitala-186724.html)' || '\n' ||
    '30. Moaștele Sfântului Gheorghe Pelerinul - Doxologia, accessed January 25, 2026, [[https://doxologia.ro/moastele-sfantului-gheorghe-pelerinul]{.underline}](https://doxologia.ro/moastele-sfantului-gheorghe-pelerinul)' || '\n' ||
    '31. Sfantul Gheorghe - Ocrotitorul Ostirii CrestinOrtodox.ro, accessed January 25, 2026, [[https://www.crestinortodox.ro/sfantul-gheorghe/sfantul-gheorghe-ocrotitorul-ostirii-140356.html]{.underline}](https://www.crestinortodox.ro/sfantul-gheorghe/sfantul-gheorghe-ocrotitorul-ostirii-140356.html)' || '\n' ||
    '32. Sf. Gheorghe -- protectorul Forțelor Terestre Române, a numeroase biserici și a mii de români - Bună Ziua Făgăraș, accessed January 25, 2026, [[https://www.bunaziuafagaras.ro/sf-gheorghe-protectorul-armatei-a-numeroase-biserici-si-a-mii-de-romani/]{.underline}](https://www.bunaziuafagaras.ro/sf-gheorghe-protectorul-armatei-a-numeroase-biserici-si-a-mii-de-romani/)' || '\n' ||
    '33. Obiceiuri de primăvară - Sf. Gheorghe - cIMeC, accessed January 25, 2026, [[https://www.cimec.ro/Etnografie/sf-gheorghe/Obiceiuri-de-primavara-Sf-Gheorghe.html]{.underline}](https://www.cimec.ro/Etnografie/sf-gheorghe/Obiceiuri-de-primavara-Sf-Gheorghe.html)' || '\n' ||
    '34. Sfântul Gheorghe şi războiul strigoilor | adevarul.ro, accessed January 25, 2026, [[https://adevarul.ro/stiri-locale/zalau/sfantul-gheorghe-si-razboiul-strigoilor-1530602.html]{.underline}](https://adevarul.ro/stiri-locale/zalau/sfantul-gheorghe-si-razboiul-strigoilor-1530602.html)' || '\n' ||
    '35. Tradiții și obiceiuri la români - 1 Mai - popular: Armindenul (începutul verii) / Maiul / Ziua Pelinului / Ziua bețivilor / creștin: Sf Prooroc Ieremia | Merceria IElena, accessed January 25, 2026, [[https://www.merceriaielena.ro/traditii-si-obiceiuri-la-romani-1-mai-popular-armindenul-inceputul-verii-maiul-ziua-pelinului-ziua-betivilor-crestin-sf-prooroc-ieremia/]{.underline}](https://www.merceriaielena.ro/traditii-si-obiceiuri-la-romani-1-mai-popular-armindenul-inceputul-verii-maiul-ziua-pelinului-ziua-betivilor-crestin-sf-prooroc-ieremia/)' || '\n' ||
    '36. Armindeni, Sărbătoarea Sfântului Proroc Ieremia - cimec.ro, accessed January 25, 2026, [[https://cimec.ro/etnografie2/sarbatori-si-obiceiuri-traditionale/sarbatorile-de-primavara/armindeni-si-sarbatoarea-sfantului-proroc-ieremia/]{.underline}](https://cimec.ro/etnografie2/sarbatori-si-obiceiuri-traditionale/sarbatorile-de-primavara/armindeni-si-sarbatoarea-sfantului-proroc-ieremia/)' || '\n' ||
    '37. Tradiții sângeorzene: Jocul Banilor! - Sângeorz-Băi, accessed January 25, 2026, [[https://sangeorzbai.ro/traditii-sangeorzene-jocul-banilor/]{.underline}](https://sangeorzbai.ro/traditii-sangeorzene-jocul-banilor/)' || '\n' ||
    '38. Sângeorz - Wikipedia, accessed January 25, 2026, [[https://ro.wikipedia.org/wiki/S%C3%A2ngeorz]{.underline}](https://ro.wikipedia.org/wiki/S%C3%A2ngeorz)' || '\n' ||
    '39. Sfântul Gheorghe (Sîngeorzul) -- obiceiuri, credințe și superstiții în Maramureș, accessed January 25, 2026, [[https://cultura-traditionala.ro/sfantul-gheorghe-singeorzul-obiceiuri-credinte-si-superstitii-in-maramures/]{.underline}](https://cultura-traditionala.ro/sfantul-gheorghe-singeorzul-obiceiuri-credinte-si-superstitii-in-maramures/)'
);
