INSERT INTO core_schema.saint_lives (name_ro, life_description_ro)
VALUES (
    'Sfântul Slăvitul Proroc Ilie Tesviteanul',
    '# Focul Profetic și Apa Ascetică: Un Studi Hagiografic și Etnologic Exhaustiv asupra Sfântului Proroc Ilie Tesviteanul și a Sfântului Ierarh Ghelasie de la Râmeț' || '\n\n' ||
    '## 1. Introducere: Fenomenologia Sfințeniei în Spațiul Carpatin' || '\n\n' ||
    'Peisajul spiritual al Ortodoxiei românești este definit de o sinteză profundă între tradiția scripturistică, teologia patristică și un folclor vibrant, care ancorează sacrul în ritmurile anului agrar. Prezentul raport oferă o analiză exhaustivă a două figuri monumentale care domină calendarul liturgic și folcloric al mijlocului de vară: **Sfântul Slăvitul Proroc Ilie Tesviteanul**, prăznuit la 20 iulie, și **Sfântul Ierarh Ghelasie de la Râmeț**, sărbătorit la 30 iunie. Deși separați de milenii și geografie --- unul stând pe culmile aride ale Muntelui Carmel în Israelul antic, celălalt în Munții Apuseni, verzi și stâncoși, ai Transilvaniei --- ambii sfinți împărtășesc o identitate comună de stăpâni ai elementelor, asceți de cel mai înalt ordin și mijlocitori puternici a căror venerare a permeat profund conștiința românească.' || '\n\n' ||
    'Acest document utilizează un set cuprinzător de materiale de cercetare pentru a reconstrui viețile lor, a analiza minunile și a documenta tapiseria bogată de tradiții, superstiții și practici culturale asociate lor. De la „carul de foc" care traversează cerul românesc până la izvorul miraculos din munții Transilvaniei, acest raport explorează dualitatea „foc și apă" care caracterizează hagiografiile lor, demonstrând modul în care teologia dogmatică se întrepătrunde cu trăirea populară.' || '\n\n' ||
    '## 2. Sfântul Proroc Ilie Tesviteanul: Profil Biblic și Teologic' || '\n\n' ||
    '### 2.1. Origini și Chemarea Profetică: Vocația Focului' || '\n\n' ||
    'Sfântul Proroc Ilie (Ilie), al cărui nume ebraic *Eliyahu* semnifică „Yahweh este Dumnezeul meu", reprezintă o figură colosală în istoria monoteismului. Născut în Tesvi (Tishbe) din Galaad, cu aproximativ 900 de ani înainte de Întruparea lui Hristos ^1^, intrarea lui Ilie în lume a fost marcată de semne teofanice care prefigurau destinul său excepțional.' || '\n\n' ||
    'Conform tradiției conservate în sinaxarele ortodoxe, la nașterea sa, tatăl său, Sovac, a fost martorul unei viziuni terifiante și profetice: ființe angelice, îmbrăcate în veșminte albe, l-au înfășurat pe prunc nu în scutece obișnuite, ci în haine de foc, și i-au dat să mănânce o flacără în loc de lapte matern.^2^ Această viziune, tulburătoare pentru un părinte, a fost interpretată de preoții Templului din Ierusalim ca un semn indubitabil al elecțiunii divine. Ei au profețit că Ilie a fost ales de Dumnezeu pentru a judeca triburile lui Israel cu foc și sabie, iar cuvântul său va avea puterea de a arde fărădelegea precum focul mistuie paiele.^4^' || '\n\n' ||
    'Deși provenea din seminția lui Aaron, fiind destinat prin naștere preoției levitice ^2^, vocația lui Ilie a transcendat serviciul liturgic ritualic, evoluând într-o misiune profetică arhetipală. El a trăit și a activat în Regatul de Nord (Israel) în timpul domniei regelui Ahab, o perioadă caracterizată printr-o criză spirituală fără precedent. Ahab, sub influența soției sale feniciene, Isabela (Jezebel) din Sidon, corupsese fidelitatea spirituală a Israelului prin instituționalizarea cultului lui Baal și al Astarteei (Asherah).^2^' || '\n\n' ||
    '### 2.2. Conflictul cu Idolatria și "Legarea Cerurilor"' || '\n\n' ||
    'Conflictul central al vieții lui Ilie a fost lupta împotriva sincretismului și idolatriei impuse de curtea regală. Venerarea lui Baal, un zeu canaanit al furtunii și fertilității, reprezenta o ofensă directă adusă Legământului Mozaic. Răspunsul lui Ilie nu a fost unul pur retoric, ci cosmic. Într-o provocare directă la adresa pretinsei puteri a lui Baal asupra ploii și recoltelor, Ilie s-a înfățișat înaintea lui Ahab și a rostit teribila sentință: *„Viu este Domnul Dumnezeul lui Israel, înaintea Căruia slujesc eu; în acești ani nu va fi nici rouă, nici ploaie decât numai când voi zice eu!"*.^2^' || '\n\n' ||
    'Această declarație a inaugurat o perioadă de secetă severă și foamete care a durat trei ani și șase luni, o pedeapsă menită să întoarcă inimile israeliților înapoi la adevăratul Dumnezeu prin suferință pedagogică.^4^ Seceta a fost o polemică teologică în acțiune: prin sigilarea cerurilor, Ilie a demonstrat că Yahweh, și nu Baal, deține controlul absolut asupra forțelor elementare ale naturii.' || '\n\n' ||
    'În timpul acestei perioade de restriște, profetul s-a retras la pârâul Cherit (sau Cherith), unde a fost hrănit în chip minunat de corbi, care îi aduceau pâine dimineața și carne seara.^1^ Această purtare de grijă divină subliniază separarea totală a profetului de o societate coruptă și dependența sa absolută de Providență. Uscarea pârâului Cherit l-a forțat ulterior să părăsească izolarea și să intre în inima teritoriului păgân.' || '\n\n' ||
    '### 2.3. Minunile din Sarepta Sidonului: Învierea și Euharistia' || '\n\n' ||
    'Călăuzit de Dumnezeu, Ilie a călătorit la Sarepta (Zarephath) în Sidon, patria reginei Isabela și centrul cultului baalic. Aici, in casa unei văduve sărace, el a săvârșit două minuni care prefigurează puterea sacramentală și învierea din Noul Testament.' || '\n\n' ||
    '1.  **Înmulțirea făinii și a untdelemnului:** În ciuda sărăciei extreme, văduva l-a hrănit pe profet cu ultima sa rezervă de hrană. Ca răspuns la credința și ospitalitatea ei, Ilie a binecuvântat covata de făină și vasul de untdelemn, asigurând supraviețuirea lor pe toată durata foametei.^8^ Această minune este adesea interpretată patristic ca o tipologie euharistică --- hrana care nu se epuizează niciodată prin harul divin.' || '\n' ||
    '2.  **Învierea fiului văduvei:** Evenimentul cel mai dramatic a fost moartea fiului gazdei sale. Confruntat cu durerea mamei și cu misterul morții, Ilie a luat trupul copilului, l-a urcat în camera sa de sus și s-a rugat cu o intensitate sfâșietoare, suflând de trei ori asupra lui. Dumnezeu a ascultat rugăciunea profetului, iar sufletul copilului s-a întors în el.^8^ Această înviere este fundamentală în hagiografie, deoarece îl stabilește pe Ilie nu doar ca un judecător aspru, ci și ca un restaurator al vieții, capabil să "deschidă" porțile morții la fel cum a "închis" stăvilarele cerului.' || '\n\n' ||
    '### 2.4. Teofania de pe Muntele Carmel și Masacrul de la Chișon' || '\n\n' ||
    'Momentul culminant al misiunii lui Ilie s-a desfășurat pe Muntele Carmel, unde a convocat pe cei 450 de profeți ai lui Baal și pe cei 400 de profeți ai Astarteei la o confruntare publică a divinităților. Eșecul preoților păgâni de a invoca focul din cer, în ciuda ritualurilor lor frenetice și a automutilării, a contrastat puternic cu succesul lui Ilie.' || '\n\n' ||
    'După ce a reparat altarul Domnului care fusese dărâmat și a poruncit ca jertfa să fie udată abundent cu apă (pentru a elimina orice suspiciune de fraudă), Ilie s-a rugat simplu. Focul Domnului a coborât mistuitor, consumând nu doar jertfa, ci și lemnele, pietrele și apa din șanț.^8^ Poporul, martor la această demonstrație de putere, a căzut cu fața la pământ, strigând: *"Domnul este Dumnezeu!"*.' || '\n\n' ||
    'Acest triumf a fost urmat de o acțiune de purificare radicală: Ilie i-a dus pe profeții mincinoși la pârâul Chișon și i-a ucis, eliminând sursa infecției spirituale din Israel.^8^ Imediat după aceasta, Ilie a urcat pe munte și s-a rugat pentru ploaie. Cerul, care fusese "aramă" timp de trei ani și jumătate, s-a întunecat de nori, și o ploaie torențială a binecuvântat pământul, confirmând ridicarea blestemului.^2^' || '\n\n' ||
    '### 2.5. Horeb și "Adierea de Vânt Subțire"' || '\n\n' ||
    'Fugind de mânia Isabelei, care jurase să-l ucidă, Ilie a călătorit 40 de zile și 40 de nopți până la Muntele Horeb (Sinai), muntele Legii. Aici, el a experimentat o teofanie profund diferită de cea de pe Carmel. Dumnezeu nu i s-a arătat în vântul puternic, nici în cutremur, nici în foc, ci într-o "adiere de vânt subțire" (sau susur blând).^11^ Această revelație sugerează o nouă fază a pedagogiei divine, subliniind mila și intimitatea, în contrast cu puterea cataclismică. La Horeb, Ilie a primit porunca de a-l unge pe Elisei ca succesor al său.^3^' || '\n\n' ||
    '### 2.6. Înălțarea la Cer și Rolul Eschatologic' || '\n\n' ||
    'Unic printre profeți (alături de Enoh), Ilie nu a cunoscut moartea fizică. El a fost ridicat la cer într-un "car de foc tras de cai de foc" (car de foc tras de cai înflăcărați) sub privirile ucenicului său Elisei.^3^ Înainte de înălțare, el a despărțit apele Iordanului cu cojocul său, relicvă pe care i-a lăsat-o lui Elisei împreună cu "îndoita măsură" a duhului său.^3^' || '\n\n' ||
    'Această mutare la cer a alimentat speculații eschatologice imense. În tradiția ortodoxă, Ilie este considerat "Al doilea Înaintemergător" al celei de-a doua veniri a lui Hristos.^6^ Se așteaptă ca el să revină la sfârșitul veacurilor pentru a propovădui pocăința și a înfrunta Antihristul, suferind în cele din urmă moartea fizică pe care a evitat-o inițial.^6^ Apariția sa la Schimbarea la Față a Domnului pe Muntele Tabor, alături de Moise, îl consacră ca reprezentant al Profeților, martor al gloriei Dumnezeului Întrupat.^1^' || '\n\n' ||
    '## 3. "Sânt-Ilie": Arhetipul în Etnografia și Folclorul Românesc' || '\n\n' ||
    'În etosul românesc, figura Prorocului Ilie a suferit un proces complex de sincretism și inculturație, evoluând în "Sânt-Ilie", o divinitate populară solară și atmosferică ce comandă furtunile de vară. Sărbătorit la 20 iulie, praznicul marchează "miezul verii pastorale" și este înconjurat de o rețea densă de tradiții care îmbină evlavia creștină cu rituri agrare precreștine.^18^' || '\n\n' ||
    '### 3.1. Divinitatea Solară și Carul de Foc' || '\n\n' ||
    'Folclorul românesc îl identifică pe Sânt-Ilie cu zeități solare antice (precum Helios sau zeul geto-dac Gebeleizis).^15^ El este perceput nu doar ca un sfânt care se roagă pentru ploaie, ci ca administratorul activ al focului celest.' || '\n\n' ||
    '- **Tunetul ca Roți de Car:** Tradiția susține că, atunci când se aud tunete, este zgomotul roților carului lui Sânt-Ilie care se rostogolesc pe podeaua noroasă a cerului.^20^ El călătorește într-o trăsură cu roți de foc, trasă de doi sau patru cai înaripați (sau albi), vânând demoni.^13^' || '\n' ||
    '- **Biciul de Foc:** Fulgerul este interpretat ca fiind pocnetul biciului lui Ilie. El își folosește armele celeste pentru a lovi dracii care încearcă să se ascundă pe pământ. Această bătălie cosmologică explică interdicția populară de a se ascunde sub anumiți copaci (cum ar fi carpenul) în timpul furtunilor, deoarece demonii se refugiază adesea acolo pentru a scăpa de mânia Sfântului.^13^' || '\n' ||
    '- **Limitarea Divină:** O legendă fascinantă sugerează că puterea lui Ilie este atât de vastă și temperamentul său atât de aprig, încât Dumnezeu a trebuit să îl limiteze. Se spune că, dacă Ilie ar ști exact când este ziua lui de prăznuire, ar sărbători cu atâta bucurie și tunete încât ar putea zgudui sau chiar distruge pământul. De aceea, Dumnezeu îi ține data ascunsă sau îi spune că a trecut deja, pentru a-i tempera entuziasmul.^19^ O altă variațiune afirmă că Dumnezeu i-a luat puterea dintr-o mână și dintr-un picior pentru a preveni distrugerea lumii în zelul său împotriva demonilor.^20^' || '\n\n' ||
    '### 3.2. "Moșii de Sânt-Ilie" și Cultul Morților' || '\n\n' ||
    'Sărbătoarea Sfântului Ilie este, de asemenea, un moment major pentru pomenirea morților, cunoscut sub numele de "Moșii de Sânt-Ilie". Această observanță este concentrată în mod particular asupra copiilor trecuți la cele veșnice.^18^' || '\n\n' ||
    '- **Tabuul Merelor:** Există un tabu strict împotriva consumului de mere (și uneori nuci sau alte fructe noi) înainte de 20 iulie. Se crede că, în lumea de dincolo, Sânt-Ilie scutură mărul din Rai. Dacă o mamă de pe pământ a mâncat mere înainte de timpul stabilit, copiii ei decedați vor plânge deoarece merele din cer vor dispărea din raza lor de acțiune. În schimb, dacă mama se abține, copiii pot culege fructele de aur scuturate de Sfânt.^18^' || '\n' ||
    '- **Ofranda Rituală:** În ziua praznicului, femeile duc mere și alte fructe timpurii la biserică pentru a fi sfințite. Odată sfințite, aceste fructe sunt "eliberate" de sub tabu și devin "mere de aur" pe lumea cealaltă. În satele din Bărăgan și Oltenia, se obișnuiește ca femeile să cheme copii străini sub un măr, să scuture pomul și să dea de pomană merele căzute.^18^' || '\n\n' ||
    '### 3.3. Tradiții Agrare și Apicole: Retezatul Stupilor' || '\n\n' ||
    'Sânt-Ilie marchează un punct de cotitură în anul agricol. Se crede că după această dată, căldura verii începe să scadă, iar aerul se răcorește ("Ilie răcește apa").' || '\n\n' ||
    '| **Obicei** | **Descriere și Semnificație** | **Regiune/Sursă** |' || '\n' ||
    '| :--- | :--- | :--- |' || '\n' ||
    '| **Retezatul Stupilor** | Ilie este patronul apicultorilor. În această zi, bărbații îmbrăcați în haine albe de sărbătoare recoltează mierea ("retezatul stupilor"). Ritualul necesită puritate și este adesea asistat de un copil. | General ^18^ |' || '\n' ||
    '| **Masa Comunală** | După recoltare, mierea nouă este împărtășită cu vecinii și folosită pentru a îndulci țuica, creând "țuica de Sânt-Ilie". Acest act asigură belșugul și protejează stupii de furt. | Transilvania, Muntenia ^18^ |' || '\n' ||
    '| **Plante de Leac** | Dimineața de Sânt-Ilie este momentul propice pentru culegerea plantelor medicinale, în special a busuiocului. Busuiocul sfințit este ars, iar cenușa este folosită pentru tratarea aftelor la copii. | General ^18^ |' || '\n' ||
    '| **Magia Cânepii** | Un obicei arhaic implică fete tinere care se tăvălesc în lanurile de cânepă în ajun. Visul rezultat (cânepă verde vs. uscată) prezice vârsta viitorului soț. | Zone rurale ^5^ |' || '\n\n' ||
    '### 3.4. Marile Târguri: Târgul de Fete de pe Muntele Găina' || '\n\n' ||
    'Conexiunea dintre Sfântul Ilie și munții înalți este exemplificată de "Târgul de Fete de pe Muntele Găina", organizat anual în jurul datei de 20 iulie în Munții Apuseni.^18^' || '\n\n' ||
    '- **Origini și Funcție Socială:** Istoric, acesta era un eveniment de "matchmaking" (pețit) unde locuitorii văilor montane dispersate (Vidra, Bulzești) se întâlneau. Tinerele femei își aduceau zestrea în lăzi pictate, iar căsătoriile erau aranjate de familii.^24^' || '\n' ||
    '- **Mitologie:** Muntele este asociat cu legenda unei găini (Găina) care făcea ouă de aur. Târgul nu este doar comercial; este o "Nedeie" --- un festival pastoral de altitudine care implică muzică populară, dans și afirmarea identității comunitare a moților.^19^ Alte târguri similare au loc la Fălticeni, Covasna ("Nedeia mocănească") și Săcele.^18^' || '\n\n' ||
    '### 3.5. Patronaje Moderne: Aviația și Energia' || '\n\n' ||
    'În România modernă, Sfântul Ilie a dobândit noi patronaje care se aliniază cu atributele sale elementare.' || '\n\n' ||
    '- **Aviația Română:** Începând cu 1913, pionierii aviației române l-au ales ca ocrotitor. Înălțarea sa într-un car zburător îl face arhetipul zborului. Ziua de 20 iulie este Ziua Aviației Române și a Forțelor Aeriene, marcată prin ceremonii militare și demonstrații aeriene.^2^' || '\n' ||
    '- **Sectorul Energetic:** El este, de asemenea, patronul electricienilor și al energeticienilor ("soldații luminii"), o conexiune derivată din comanda sa asupra fulgerului și focului.^25^' || '\n\n' ||
    '## 4. Sfântul Ierarh Ghelasie de la Râmeț: Ascetul Transilvaniei' || '\n\n' ||
    'În timp ce Sfântul Ilie domină calendarul universal, Munții Apuseni adăpostesc un sfânt local de o statură spirituală imensă, al cărui cult se împletește adesea cu evlavia mijlocului de vară în regiune: **Sfântul Ierarh Ghelasie de la Râmeț**, prăznuit la 30 iunie, dar venerat intens pe parcursul verii.' || '\n\n' ||
    '### 4.1. Context Istoric și Inscripția din 1377' || '\n\n' ||
    'Sfântul Ghelasie a trăit în secolul al XIV-lea, o perioadă critică pentru Ortodoxia românească din Transilvania, care se confrunta cu presiuni crescânde din partea Regatului Apostolic al Ungariei. Existența sa este atestată arheologic printr-o inscripție crucială descoperită în 1978 pe al doilea strat de pictură din biserica Mănăstirii Râmeț.^26^' || '\n\n' ||
    '**Inscripția:** *„Am scris eu preapăcătosul rob al lui Dumnezeu Mihul, adică zugravul de la Crișul Alb, cu încuviințarea Arhiepiscopului Ghelasie în zilele regelui Ludovic în anul 6885 , luna iulie 2"*.^29^' || '\n\n' ||
    'Această inscripție este fundamentală pentru istoriografia bisericească românească, deoarece îl identifică pe Ghelasie nu doar ca stareț, ci ca **Arhiepiscop**, dovedind existența unei ierarhii ortodoxe românești organizate în Transilvania mult mai devreme decât se credea anterior. El este primul ierarh ortodox român din teritoriul intracarpatin cunoscut cu numele.^28^' || '\n\n' ||
    '### 4.2. Viața și Ascetismul' || '\n\n' ||
    'Originar din partea locului, Ghelasie și-a început viața spirituală ca sihastru (eremit) de-a lungul Văii Râmețului, îmbrățișând solitudinea aspră și stâncoasă a Apusenilor.^26^ Ascetismul său a fost riguros, amintind de Părinții Deșertului:' || '\n\n' ||
    '- Mânca doar sâmbăta și duminica. În timpul săptămânii, se hrănea exclusiv cu Sfintele Taine (Euharistia).^31^' || '\n' ||
    '- A adunat în jurul său 12 ucenici, oglindind cercul apostolic, și a stabilit o comunitate cenobitică puternică la Râmeț, care a devenit o fortăreață spirituală pentru "mocanii" din munți.^31^' || '\n' ||
    '- Practica privegherea de toată noaptea și rugăciunea neîncetată, devenind un "dascăl al liniștii" (isihie).^27^' || '\n\n' ||
    '### 4.3. Minunile Apei și Pietrei' || '\n\n' ||
    'La fel ca Ilie, Ghelasie a exercitat putere asupra naturii, în special în ceea ce privește apa --- o resursă vitală în verile toride ale munților calcaroși.' || '\n\n' ||
    '1.  **Izvorul Sfântului Ghelasie:** Într-o vară caniculară, în timp ce ucenicii săi strângeau fânul în poiana "Hopați", aceștia sufereau de o sete extremă. Ghelasie a îngenuncheat în rugăciune, a făcut semnul crucii cu toiagul său și a lovit pământul. Un izvor de apă rece a țâșnit instantaneu. Acest izvor, cunoscut sub numele de "Fântâna Vlădichii", curge și astăzi și este venerat pentru proprietățile sale vindecătoare.^31^ Această minune îl plasează într-o directă paralelă tipologică cu Moise în pustie.' || '\n' ||
    '2.  **Măgarul și Urma Copitei:** Tradiția relatează că Ghelasie și-a cunoscut momentul morții. Coborând de la schit spre mănăstire pe un asin, a trecut la Domnul în timp ce călărea. Animalul, ghidat de un instinct divin, a purtat trupul sfântului până la biserică și s-a oprit singur. Se spune că, în momentul opririi, copita măgarului a lăsat o amprentă permanentă în piatră --- o relicvă păstrată acum în muzeul mănăstirii.^29^ La momentul morții sale, clopotele a șapte biserici din jur au început să bată singure.^32^' || '\n\n' ||
    '### 4.4. Descoperirea Relicvelor: Miracolul Inundației din 1925' || '\n\n' ||
    'Canonizarea oficială a Sfântului Ghelasie în 1992 a fost precedată de o "a doua viață" miraculoasă a moaștelor sale, revelate prin apă, făcând ecou minunii izvorului.' || '\n\n' ||
    '- **Inundația:** În primăvara anului 1925, o viitură masivă a inundat curtea mănăstirii. După retragerea apelor, un craniu galben, frumos și plin de mireasmă, a fost găsit depus de ape pe fereastra sfântului altar. Tradiția spune că acesta a ocolit biserica de trei ori pe ape înainte de a se opri.^32^' || '\n' ||
    '- **Identificarea:** Călugării au îngropat inițial craniul cu evlavie, dar fără a-i cunoaște identitatea. Mai târziu, o femeie pe nume Maria din Negrești-Oaș, suferind de epilepsie, a venit la mănăstire în urma unei vedenii. Ea a identificat craniul ca aparținând Sfântului Ghelasie. Atingând relicva și primind Sfântul Maslu, ea s-a vindecat instantaneu.^27^' || '\n' ||
    '- **Venerarea:** Moaștele (capul) sunt acum așezate într-o raclă de lemn în paraclisul mănăstirii Râmeț, fiind un centru major de pelerinaj. Sfântul Ghelasie este invocat în special pentru vindecarea bolilor psihice, a epilepsiei și a posesiunilor demonice.^30^' || '\n\n' ||
    '## 5. Analiză Comparativă: Foc și Apă în Hagiografia Românească' || '\n\n' ||
    '| **Caracteristică** | **Sfântul Proroc Ilie (Sânt-Ilie)** | **Sfântul Ierarh Ghelasie (Sf. Ghelasie)** |' || '\n' ||
    '| :--- | :--- | :--- |' || '\n' ||
    '| **Data Prăznuirii** | 20 Iulie (Mijlocul verii) | 30 Iunie (Începutul verii) |' || '\n' ||
    '| **Element Primordial** | **Foc & Aer:** Tunet, fulger, secetă, ploaie torențială. | **Apă & Pământ:** Izvoare, inundații, munte, piatră. |' || '\n' ||
    '| **Tipologia Minunii** | Cataclismică, punitivă (împotriva demonilor), control cosmic. | Vindecătoare, nutritivă (apă pentru sete), protecție locală. |' || '\n' ||
    '| **Paralelă Biblică** | "Al Doilea Înaintemergător" (Eschatologic). | "Un alt Moise" (Lovirea stâncii pentru apă).^35^ |' || '\n' ||
    '| **Relicve / Prezență** | Ridicat cu trupul la cer; fără moaște (doar cojocul/mantia). | Moaște fizice (craniu) descoperite prin apă; făcătoare de minuni. |' || '\n' ||
    '| **Geografie** | Universală / Muntele Carmel / Cerurile. | Locală / Munții Apuseni / Mănăstirea Râmeț. |' || '\n' ||
    '| **Rol Folcloric** | Judecător al dracilor, stăpân al recoltelor (ferește de grindină). | Vindecător al celor posedați, ocrotitor al bolnavilor. |' || '\n\n' ||
    '**Sinteză Teologică:** În timp ce Ilie reprezintă puterea *transcendentă* a lui Dumnezeu --- focul care mistuie și cerurile care se închid --- Ghelasie reprezintă harul *immanent* --- apa care izvorăște din pământ pentru a mângâia pe cei osteniți. Ilie este sfântul axei "verticale" (înălțare, foc de sus), în timp ce Ghelasie este sfântul axei "orizontale" (pelerinaj, izvoare, descoperirea moaștelor în aluviuni). Împreună, ei cuprind plinătatea experienței credinciosului în vara continentală aspră: teama de furtună și mângâierea izvorului.' || '\n\n' ||
    '## 6. Iconografie, Imnografie și Liturgică' || '\n\n' ||
    '### 6.1. Iconografia Sfântului Ilie' || '\n\n' ||
    'Conform *Erminiei* ieromonahului Dionisie din Furna ^37^, Sfântul Ilie este reprezentat în mai multe forme canonice, fiecare având o teologie vizuală distinctă:' || '\n\n' ||
    '1.  **În Peșteră:** Șezând în gura peșterii de la pârâul Cherit, privind în sus, cu un corb aducându-i o pâine rotundă în cioc. Este înfățișat ca un bătrân cu păr lung și barbă mare, purtând un cojoc (piele de oaie) peste tunică.' || '\n' ||
    '2.  **Înălțarea:** Într-un car de foc tras de cai înaripați, aruncându-și mantia către Elisei care privește de jos. Această imagine domină iconostasele.' || '\n' ||
    '3.  **Masacrul:** Uneori reprezentat lovind cu sabia profeții lui Baal la pârâul Chișon.^39^' || '\n\n' ||
    '### 6.2. Imnografia și Rugăciunile' || '\n\n' ||
    '- **Troparul Sf. Ilie (Glas 4):** Îl numește "Înger în trup", "Temeiul prorocilor" și "Al doilea Înaintemergător al venirii lui Hristos". Subliniază puterea sa de a trimite har de sus (lui Elisei) și de a vindeca bolile.^16^' || '\n' ||
    '- **Troparul Sf. Ghelasie (Glas 1):** Îl numește "De Dumnezeu purtătorule" și "Povățuitorul călugărilor", lăudând nevoințele sale și darul facerii de minuni.^40^' || '\n' ||
    '- **Condacul Sf. Ilie (Glas 2):** "Prorocule și înainte văzătorule al lucrurilor celor mari ale lui Dumnezeu... care cu cuvântul tău ai oprit norii cei curgători de apă".^42^' || '\n' ||
    '- **Acatistul Sf. Ghelasie:** Compară explicit pe sfânt cu Moise: *„Pe pământ ca un alt Moise te-ai arătat... căci cu toiagul semnul crucii făcând, ai izvorât apă din loc pietros"*.^35^' || '\n\n' ||
    '### 6.3. Rugăciuni pentru Ploaie' || '\n\n' ||
    'În *Molitfelnic* și tradiția populară, Ilie este intercesorul suprem pentru ploaie. Rugăciunile ^8^ invocă zelul său pentru a "deschide cerul", recunoscând totodată nevrednicia poporului. Credincioșii se roagă: *„Nu ne omorî cu foame și cu sete... ci poruncește norilor"*, recunoscând autoritatea delegată profetului asupra meteorologiei.' || '\n\n' ||
    '### 6.4. Rugăciune către Sfântul Ilie (Extras Scurt)' || '\n\n' ||
    '*„Depărtează de la noi, preamărite proorocule, prin mijlocirea ta către Domnul, dreapta mânie a lui Dumnezeu; apără orașele, satele și țara noastră de secetă, de foamete, de furtuni năpraznice... Prin rugăciunile tale, întărește poporul nostru binecredincios."*.^44^' || '\n\n' ||
    '## 7. Concluzii și Sinteze' || '\n\n' ||
    'Cercetarea vieții, minunilor și tradițiilor Sfântului Proroc Ilie Tesviteanul, completată de studiul Sfântului Ierarh Ghelasie de la Râmeț, relevă o structură profundă a spiritualității românești. În Ilie, credinciosul confruntă puterea teribilă și majestuoasă a lui Dumnezeu --- Dumnezeul furtunilor, al dreptății absolute și al focului purificator. Ilie este gardianul cosmic, patronul cerurilor (și al aviației moderne) și enforcer-ul rigorist al legii divine. Praznicul său este un eveniment celest, marcat de tunet și de "retezatul" ciclului solar.' || '\n\n' ||
    'În contrast, dar în perfectă armonie calendaristică, Sfântul Ghelasie reprezintă prezența intimă și vindecătoare a sfințeniei în peisajul local. El este "bunicul" Apusenilor, care aduce apa celor însetați și vindecă mințile tulburate. Sfințenia sa este confirmată nu de focul din cer, ci de persistența tăcută a unui izvor și de supraviețuirea miraculoasă a moaștelor prin apele potopului.' || '\n\n' ||
    'Acești doi sfinți, prin "Focul" lui Ilie și "Apa" lui Ghelasie, oferă o imagine completă a înțelegerii ortodoxe asupra sfințeniei: o forță care poate închide cerurile pentru a trezi conștiințele, dar care poate și lovi stânca pentru a adăpa poporul însetat. Moștenirea lor --- păstrată în inscripția de la 1377, în folclorul "carului de foc" și în pelerinajul continuu de la Râmeț --- rămâne un pilon vital al identității religioase și culturale românești.' || '\n\n' ||
    '#### Works cited' || '\n\n' ||
    '1. Viaţa şi minunile Sfîntului Prooroc Ilie Tesvitean - Crestin Ortodox, accessed January 26, 2026, [[https://www.crestinortodox.ro/comunitate/group_discussion_view.php?group_id=943&grouptopic_id=7853]{.underline}](https://www.crestinortodox.ro/comunitate/group_discussion_view.php?group_id=943&grouptopic_id=7853)' || '\n' ||
    '2. DOCUMENTAR: Sfântul şi slăvitul Proroc Ilie Tesviteanul | Agenția de presă Rador, accessed January 26, 2026, [[https://www.rador.ro/2023/07/20/documentar-sfantul-si-slavitul-proroc-ilie-tesviteanul/]{.underline}](https://www.rador.ro/2023/07/20/documentar-sfantul-si-slavitul-proroc-ilie-tesviteanul/)' || '\n' ||
    '3. Viata Sf. PROROC ILIE TESVITEANUL-20 IULIE #ortodox #sinaxar #vietilesfintilor #crestin - YouTube, accessed January 26, 2026, [[https://www.youtube.com/watch?v=avB4sjBPOP8]{.underline}](https://www.youtube.com/watch?v=avB4sjBPOP8)' || '\n' ||
    '4. Sfântul Ilie - Tradiții, Obiceiuri și Superstiții. Ce Să Nu Faci De Sfântul Ilie | Libertatea, accessed January 26, 2026, [[https://www.libertatea.ro/stiri/sfantul-ilie-traditii-obiceiuri-1545051]{.underline}](https://www.libertatea.ro/stiri/sfantul-ilie-traditii-obiceiuri-1545051)' || '\n' ||
    '5. Tradiții, obiceiuri și superstiții de sărbătoarea Sfântului Ilie - : Europa FM, accessed January 26, 2026, [[https://www.europafm.ro/sfantul-ilie-traditii-obiceiuri-si-superstitii-de-ziua-sfantului-care-aduce-ploaia/]{.underline}](https://www.europafm.ro/sfantul-ilie-traditii-obiceiuri-si-superstitii-de-ziua-sfantului-care-aduce-ploaia/)' || '\n' ||
    '6. Viaţa şi minunile Sfîntului Prooroc Ilie Tesviteanul - Pagini Ortodoxe Româneşti, accessed January 26, 2026, [[https://paginiortodoxe.tripod.com/vsiul/07-20-sf_ilie.html]{.underline}](https://paginiortodoxe.tripod.com/vsiul/07-20-sf_ilie.html)' || '\n' ||
    '7. Predică la Sfântul Prooroc Ilie Tesviteanul - Actualitatea Ortodoxa, accessed January 26, 2026, [[http://actualitateaortodoxa.com/articole/Predica_la_Sfantul_Proroc_Ilie_Tesviteanul.php]{.underline}](http://actualitateaortodoxa.com/articole/Predica_la_Sfantul_Proroc_Ilie_Tesviteanul.php)' || '\n' ||
    '8. RUGACIUNE CATRE SFANTUL PROOROC ILIE LA VREME DE SECETA, accessed January 26, 2026, [[https://www.sfantatreimeghencea.ro/rugaciune-catre-sfantul-prooroc-ilie-la-vreme-de-seceta/]{.underline}](https://www.sfantatreimeghencea.ro/rugaciune-catre-sfantul-prooroc-ilie-la-vreme-de-seceta/)' || '\n' ||
    '9. Rugaciune catre Sfantul Proroc Ilie, la vreme de seceta - Crestin Ortodox, accessed January 26, 2026, [[https://www.crestinortodox.ro/rugaciuni/rugaciune-catre-sfantul-proroc-ilie-vreme-seceta-96347.html]{.underline}](https://www.crestinortodox.ro/rugaciuni/rugaciune-catre-sfantul-proroc-ilie-vreme-seceta-96347.html)' || '\n' ||
    '10. Rugăciune către Sfântul Proroc Ilie Tesviteanul la vreme de secetă | Doxologia, accessed January 26, 2026, [[https://doxologia.ro/rugaciune-catre-sfantul-proroc-ilie-tesviteanul-la-vreme-de-seceta]{.underline}](https://doxologia.ro/rugaciune-catre-sfantul-proroc-ilie-tesviteanul-la-vreme-de-seceta)' || '\n' ||
    '11. 20 iulie, SFÎNTUL PROOROC ILIE, accessed January 26, 2026, [[https://www.stavropoleos.ro/wp-content/uploads/Psaltica/Idiomelar/Iulie/iul20.pdf]{.underline}](https://www.stavropoleos.ro/wp-content/uploads/Psaltica/Idiomelar/Iulie/iul20.pdf)' || '\n' ||
    '12. Viața Sfântului Slăvit Proroc Ilie Tesviteanul - Doxologia, accessed January 26, 2026, [[https://doxologia.ro/viata-sfantului-slavit-proroc-ilie-tesviteanul]{.underline}](https://doxologia.ro/viata-sfantului-slavit-proroc-ilie-tesviteanul)' || '\n' ||
    '13. Sfântul Ilie, făcătorul de minuni care tună şi fulgeră. De ce se tem oamenii şi ce nu ai voie să faci în această zi. 20 iulie este și Ziua Aviației Române, accessed January 26, 2026, [[https://tvrinfo.ro/sfantul-ilie-facatorul-de-minuni-care-tuna-si-fulgera-de-ce-se-tem-oamenii-si-ce-nu-ai-voie-sa-faci-in-aceasta-zi-20-iulie-este-i-ziua-avia-iei-romane_934971/]{.underline}](https://tvrinfo.ro/sfantul-ilie-facatorul-de-minuni-care-tuna-si-fulgera-de-ce-se-tem-oamenii-si-ce-nu-ai-voie-sa-faci-in-aceasta-zi-20-iulie-este-i-ziua-avia-iei-romane_934971/)' || '\n' ||
    '14. Rugăciuni la vreme de secetă - Porunca Iubirii - Editura Agaton, accessed January 26, 2026, [[https://poruncaiubirii.agaton.ro/articol/245/rug%C4%83ciuni-la-vreme-de-secet%C4%83/lib/inflate]{.underline}](https://poruncaiubirii.agaton.ro/articol/245/rug%C4%83ciuni-la-vreme-de-secet%C4%83/lib/inflate)' || '\n' ||
    '15. Sfântul Ilie -- Tradiţii, obiceiuri, superstiţii - Occidentul Romanesc, accessed January 26, 2026, [[https://occidentul-romanesc.com/sfantul-ilie-traditii-obiceiuri-superstitii/]{.underline}](https://occidentul-romanesc.com/sfantul-ilie-traditii-obiceiuri-superstitii/)' || '\n' ||
    '16. Troparul Sfântului Slăvitul Proroc Ilie Tesviteanul - Doxologia, accessed January 26, 2026, [[https://doxologia.ro/troparul-sfantului-slavitul-proroc-ilie-tesviteanul]{.underline}](https://doxologia.ro/troparul-sfantului-slavitul-proroc-ilie-tesviteanul)' || '\n' ||
    '17. Acatistul Sfântului Proroc Ilie Tesviteanul | Doxologia, accessed January 26, 2026, [[https://doxologia.ro/acatistul-sfantului-proroc-ilie-tesviteanul]{.underline}](https://doxologia.ro/acatistul-sfantului-proroc-ilie-tesviteanul)' || '\n' ||
    '18. Tradiții, legende și obiceiuri de Sfântul Ilie, aducătorul de ploaie, ce marchează începutul verii pastorale - Adevarul, accessed January 26, 2026, [[https://adevarul.ro/stiri-interne/societate/traditii-legende-si-obiceiuri-de-sfantul-ilie-2458787.html]{.underline}](https://adevarul.ro/stiri-interne/societate/traditii-legende-si-obiceiuri-de-sfantul-ilie-2458787.html)' || '\n' ||
    '19. Credinţe şi tradiţii de Sfântul Ilie AUDIO - Radio România Timișoara, accessed January 26, 2026, [[https://www.radiotimisoara.ro/timp-liber/folclor-traditii/credinte-si-traditii-de-sfantul-ilie-audio-11730.html]{.underline}](https://www.radiotimisoara.ro/timp-liber/folclor-traditii/credinte-si-traditii-de-sfantul-ilie-audio-11730.html)' || '\n' ||
    '20. Tradiţii, obiceiuri şi superstiţii de Sfântul Ilie. Ce se spune că nu e bine să faci pe 20 iulie, accessed January 26, 2026, [[https://www.antena3.ro/actualitate/religie/traditii-obiceiuri-superstitii-sfantul-ilie-20-iulie-680193.html]{.underline}](https://www.antena3.ro/actualitate/religie/traditii-obiceiuri-superstitii-sfantul-ilie-20-iulie-680193.html)' || '\n' ||
    '21. Traditii si obiceiuri de Sfantul Ilie, accessed January 26, 2026, [[https://traditiisidelicii.ro/2019/07/20/traditii-si-obiceiuri-de-sfantul-ilie/]{.underline}](https://traditiisidelicii.ro/2019/07/20/traditii-si-obiceiuri-de-sfantul-ilie/)' || '\n' ||
    '22. Sfântul Proroc Ilie Tesviteanul | Reîntregirea - Arhiepiscopia Ortodoxă Alba Iulia, accessed January 26, 2026, [[https://reintregirea.ro/articole/2510-sfantul-proroc-ilie-tesviteanul.html]{.underline}](https://reintregirea.ro/articole/2510-sfantul-proroc-ilie-tesviteanul.html)' || '\n' ||
    '23. Sf. Ilie, sărbătoare mare în România. Obiceiuri şi tradiţii - - Gazeta din Vest, accessed January 26, 2026, [[https://gazetadinvest.ro/sf-ilie-sarbatoare-mare-in-romania-obiceiuri-si-traditii/]{.underline}](https://gazetadinvest.ro/sf-ilie-sarbatoare-mare-in-romania-obiceiuri-si-traditii/)' || '\n' ||
    '24. The Maiden Fair on Găina Mountain - "A PIECE OF EUROPEAN TREASURE", accessed January 26, 2026, [[http://comenius-legends.blogspot.com/2010/07/maiden-fair-on-gaina-mountain.html]{.underline}](http://comenius-legends.blogspot.com/2010/07/maiden-fair-on-gaina-mountain.html)' || '\n' ||
    '25. Ocrotitorul aviatorilor, energeticienilor şi apicultorilor - Ziarul Lumina, accessed January 26, 2026, [[https://ziarullumina.ro/amp/ocrotitorul-aviatorilor-energeticienilor-si-apicultorilor-103818.html]{.underline}](https://ziarullumina.ro/amp/ocrotitorul-aviatorilor-energeticienilor-si-apicultorilor-103818.html)' || '\n' ||
    '26. Sfântul Ierarh Ghelasie de la Râmeț | Doxologia, accessed January 26, 2026, [[https://doxologia.ro/sfantul-ierarh-ghelasie-de-la-ramet-1]{.underline}](https://doxologia.ro/sfantul-ierarh-ghelasie-de-la-ramet-1)' || '\n' ||
    '27. Sfântul Ghelasie de la Râmeț -- Cuvântul Înaltpreasfințitului Părinte Calinic, accessed January 26, 2026, [[https://www.arhiepiscopiasucevei.ro/sfantul-ghelasie-de-la-ramet-cuvantul-inaltpreasfintitului-parinte-calinic-2/]{.underline}](https://www.arhiepiscopiasucevei.ro/sfantul-ghelasie-de-la-ramet-cuvantul-inaltpreasfintitului-parinte-calinic-2/)' || '\n' ||
    '28. Sfântul Ghelasie de la Râmeţ - dacoromania-alba.ro, accessed January 26, 2026, [[https://www.dacoromania-alba.ro/nr75/sf_ghelasie.htm]{.underline}](https://www.dacoromania-alba.ro/nr75/sf_ghelasie.htm)' || '\n' ||
    '29. Ghelasie de la Râmeț - OrthodoxWiki, accessed January 26, 2026, [[https://ro.orthodoxwiki.org/Ghelasie_de_la_R%C3%A2me%C8%9B]{.underline}](https://ro.orthodoxwiki.org/Ghelasie_de_la_R%C3%A2me%C8%9B)' || '\n' ||
    '30. Viata Sfantului Ghelasie de la Ramet CrestinOrtodox.ro, accessed January 26, 2026, [[https://www.crestinortodox.ro/sfinti/viata-sfantului-ghelasie-la-ramet-73020.html]{.underline}](https://www.crestinortodox.ro/sfinti/viata-sfantului-ghelasie-la-ramet-73020.html)' || '\n' ||
    '31. Viața Sfântului Ierarh Ghelasie de la Râmeț | Doxologia, accessed January 26, 2026, [[https://doxologia.ro/viata-sfantului-ierarh-ghelasie-de-la-ramet]{.underline}](https://doxologia.ro/viata-sfantului-ierarh-ghelasie-de-la-ramet)' || '\n' ||
    '32. Podoaba sfinţită a meleagurilor Râmeţului - Ziarul Lumina, accessed January 26, 2026, [[https://ziarullumina.ro/actualitate-religioasa/documentar/podoaba-sfintita-a-meleagurilor-rametului-26643.html]{.underline}](https://ziarullumina.ro/actualitate-religioasa/documentar/podoaba-sfintita-a-meleagurilor-rametului-26643.html)' || '\n' ||
    '33. Moaștele Sfântului Ghelasie de la Râmeț - Doxologia, accessed January 26, 2026, [[https://doxologia.ro/moastele-sfantului-ghelasie-de-la-ramet]{.underline}](https://doxologia.ro/moastele-sfantului-ghelasie-de-la-ramet)' || '\n' ||
    '34. Viaţa şi Acatistul Sfântului Ierarh Ghelasie de la Râmeţ - Parohia Sfanta Treime, Pitesti, accessed January 26, 2026, [[http://www.sfantatreimepit.ro/moaste_sf_ghelasie.html]{.underline}](http://www.sfantatreimepit.ro/moaste_sf_ghelasie.html)' || '\n' ||
    '35. Acatistul Sfântului Ghelasie de la Râmet - pr. Iulian Nistea, accessed January 26, 2026, [[https://www.nistea.com/spiritualitatea/acatistul-sfantului-ghelasie-de-la-ramet/570]{.underline}](https://www.nistea.com/spiritualitatea/acatistul-sfantului-ghelasie-de-la-ramet/570)' || '\n' ||
    '36. Acatistul Sfantului Ghelasie de la Ramet - Râmeț - Crestin Ortodox, accessed January 26, 2026, [[https://www.crestinortodox.ro/acatiste/acatistul-sfantului-ghelasie-la-ramet-67099.html]{.underline}](https://www.crestinortodox.ro/acatiste/acatistul-sfantului-ghelasie-la-ramet-67099.html)' || '\n' ||
    '37. Erminia picturii bizantine a ieromonahului Dionisie din Furna - Doxologia, accessed January 26, 2026, [[https://doxologia.ro/erminia-picturii-bizantine-ieromonahului-dionisie-din-furna]{.underline}](https://doxologia.ro/erminia-picturii-bizantine-ieromonahului-dionisie-din-furna)' || '\n' ||
    '38. Erminia Picturii Bizantine | PDF - Scribd, accessed January 26, 2026, [[https://ro.scribd.com/document/495483922/Erminia-picturii-bizantine]{.underline}](https://ro.scribd.com/document/495483922/Erminia-picturii-bizantine)' || '\n' ||
    '39. Sfântul Prooroc Ilie Tesviteanul în iconografie | Prof. univ. habil. Dr. Marcel Muntean, accessed January 26, 2026, [[https://radiorenasterea.ro/sfantul-prooroc-ilie-tesviteanul-in-iconografie-prof-univ-habil-dr-marcel-muntean/]{.underline}](https://radiorenasterea.ro/sfantul-prooroc-ilie-tesviteanul-in-iconografie-prof-univ-habil-dr-marcel-muntean/)' || '\n' ||
    '40. Troparul Sfântului Ierarh Ghelasie de la Râmeţ | Doxologia, accessed January 26, 2026, [[https://doxologia.ro/troparul-sfantului-ierarh-ghelasie-de-la-ramet]{.underline}](https://doxologia.ro/troparul-sfantului-ierarh-ghelasie-de-la-ramet)' || '\n' ||
    '41. Sfântul Ierarh Ghelasie de la Râmeț | Doxologia, accessed January 26, 2026, [[https://doxologia.ro/sfantul-ierarh-ghelasie-de-la-ramet]{.underline}](https://doxologia.ro/sfantul-ierarh-ghelasie-de-la-ramet)' || '\n' ||
    '42. Condacul Sfântului Slăvitul Proroc Ilie Tesviteanul - Doxologia, accessed January 26, 2026, [[https://doxologia.ro/condacul-sfantului-slavitul-proroc-ilie-tesviteanul]{.underline}](https://doxologia.ro/condacul-sfantului-slavitul-proroc-ilie-tesviteanul)' || '\n' ||
    '43. Vecernia și Utrenia Sărbătorii Sfântului Proroc Ilie Tesviteanul | e-communio.ro, accessed January 26, 2026, [[http://www.e-communio.ro/stire6523-vecernia-si-utrenia-sarbatorii-sfantului-proroc-ilie-tesviteanul]{.underline}](http://www.e-communio.ro/stire6523-vecernia-si-utrenia-sarbatorii-sfantului-proroc-ilie-tesviteanul)' || '\n' ||
    '44. Cea mai puternică rugăciune către Sfântul Ilie, pentru îndeplinirea dorințelor! Se citește la miez de noapte - KANAL D2, accessed January 26, 2026, [[https://kanald2.ro/cea-mai-puternica-rugaciune-catre-sfantul-ilie-pentru-indeplinirea-dorintelor-se-citeste-la-miez-de-noapte-20417882]{.underline}](https://kanald2.ro/cea-mai-puternica-rugaciune-catre-sfantul-ilie-pentru-indeplinirea-dorintelor-se-citeste-la-miez-de-noapte-20417882)' || '\n' ||
    '45. Rugăciunea Sfântului Ilie care împlinește orice dorință. Se citeşte la oră fixă, atunci când cerurile sunt deschise, accessed January 26, 2026, [[https://www.antena3.ro/actualitate/religie/rugaciune-sfant-ilie-dorinta-646208.html]{.underline}](https://www.antena3.ro/actualitate/religie/rugaciune-sfant-ilie-dorinta-646208.html)' || '\n' ||
    '46. Dionisie Din Furna, Erminia Picturii Bizantine | PDF - Scribd, accessed January 26, 2026, [[https://ro.scribd.com/document/688808097/2-Dionisie-Din-Furna-Erminia-Picturii-Bizantine]{.underline}](https://ro.scribd.com/document/688808097/2-Dionisie-Din-Furna-Erminia-Picturii-Bizantine)' || '\n' ||
    '47. Acatistul Sfântului Ierarh Ghelasie de la Râmeţ - Doxologia, accessed January 26, 2026, [[https://doxologia.ro/acatistul-sfantului-ierarh-ghelasie-de-la-ramet]{.underline}](https://doxologia.ro/acatistul-sfantului-ierarh-ghelasie-de-la-ramet)' || '\n' ||
    '48. Tradiții și superstiții de Sfântul Ilie -- între tunete cerești și obiceiuri pământești, accessed January 26, 2026, [[https://www.desteptarea.ro/traditii-si-superstitii-de-sfantul-ilie-intre-tunete-ceresti-si-obiceiuri-pamantesti/]{.underline}](https://www.desteptarea.ro/traditii-si-superstitii-de-sfantul-ilie-intre-tunete-ceresti-si-obiceiuri-pamantesti/)' || '\n' ||
    '49. Sfinte Moaşte - // Sfinti Romani, accessed January 26, 2026, [[https://www.sfintiromani.ro/ro/pagina/215/iunie_ghelasie_de_la_ramet_moaste.html]{.underline}](https://www.sfintiromani.ro/ro/pagina/215/iunie_ghelasie_de_la_ramet_moaste.html)'
);
