INSERT INTO core_schema.saint_lives (name_ro, life_description_ro)
VALUES (
    'Sfinții Mucenici Ermil și Stratonic',
    '# Coroana Prieteniei: O Hagiografie Comparată a Sfinților Mucenici Ermil și Stratonic' || '\n\n' ||
    '## Introducere: O Legătură Pecetluită în Martiriu' || '\n\n' ||
    'Sfinții Mucenici Ermil și Stratonic, prăznuiți de Biserica Ortodoxă la 13 ianuarie, reprezintă mai mult decât simple figuri istorice din epoca persecuțiilor romane. Viețile lor, transmise de-a lungul secolelor prin tradiția hagiografică, alcătuiesc o narativă profundă despre puterea sfințitoare a prieteniei, un spațiu în care afecțiunea umană devine un canal pentru harul divin și pentru curajul de a înfrunta moartea. Povestea lor nu este doar despre suferință individuală, ci despre modul în care legătura dintre doi oameni poate deveni catalizatorul mărturisirii supreme a credinței.' || '\n\n' ||
    'Prezentul studiu își propune să ofere o analiză sinoptică a relatărilor hagiografice din diverse tradiții ortodoxe -- română ^1^, greacă ^5^, slavonă/rusă ^9^ și cele transmise în limba engleză.^12^ Scopul nu este doar de a compila fapte, ci de a înțelege nuanțele și accentele specifice fiecărei tradiții. Prin compararea acestor surse, se conturează un portret mai bogat și mai complet al sfinților, adaptat pentru un public contemporan care caută profunzime spirituală și relevanță istorică într-un format digital, precum o aplicație mobilă.' || '\n\n' ||
    '## Scena Istorică: Persecuția la Frontiera Dunăreană' || '\n\n' ||
    '### Domnia Paradoxală a Împăratului Liciniu' || '\n\n' ||
    'Contextul istoric al martiriului Sfinților Ermil și Stratonic este esențial pentru înțelegerea semnificației actului lor. Evenimentele se petrec în timpul domniei împăratului Liciniu (308-324 d.Hr.), o figură complexă și contradictorie a istoriei romane târzii.^2^ Marea ironie a acestei perioade constă în faptul că Liciniu, alături de Sfântul Constantin cel Mare, a fost unul dintre semnatarii Edictului de la Milano din anul 313, un act care garanta toleranța religioasă pentru creștini în întregul imperiu.^2^ Cu toate acestea, la scurt timp după acest moment de aparentă pace, Liciniu a inițiat un nou și sângeros val de persecuții împotriva creștinilor.^5^' || '\n\n' ||
    'Această schimbare de atitudine nu a fost un simplu capriciu, ci o manevră geopolitică în cadrul luptei pentru putere cu rivalul său, Constantin. Sursele grecești sugerează că Liciniu a declanșat persecuția pentru a-și consolida sprijinul din partea facțiunilor păgâne din armată și administrație, care priveau cu ostilitate orientarea pro-creștină a lui Constantin.^5^ Istoricul bisericesc Socrate Scolasticul confirmă că Liciniu a complotat în secret împotriva creștinilor înainte de a lansa persecuția deschisă.^13^ În acest context, refuzul Sfinților Ermil și Stratonic de a jertfi zeilor romani transcende un simplu act de credință personală. El devine o declarație politică implicită, o respingere a autorității unui împărat care instrumentaliza religia în scopuri politice și o aliniere la o viziune asupra lumii pe care Constantin începea să o promoveze. Martiriul lor se transformă, astfel, într-o bătălie simbolică în conflictul mai larg pentru sufletul Imperiului Roman.' || '\n\n' ||
    '### Singidunum (Belgrad) în Secolul al IV-lea' || '\n\n' ||
    'Teatrul acestor evenimente a fost cetatea Singidunum, Belgradul de astăzi, un centru militar și administrativ vital la frontiera dunăreană a Imperiului Roman.^2^ Fiind un punct strategic, cetatea era un loc de întâlnire a culturilor și religiilor, unde cultul oficial roman coexista cu o comunitate creștină din ce în ce mai vizibilă și mai rezistentă.' || '\n\n' ||
    '### Datarea Martiriului' || '\n\n' ||
    'Sursele prezintă o ușoară discrepanță în ceea ce privește anul exact al martiriului. Unele menționează anul 303 ^2^, în timpul Marii Persecuții a lui Dioclețian, în timp ce altele indică o dată ulterioară, în jurul anilor 314-315 ^10^ sau chiar 320-322.^5^ Data ulterioară este considerată mai plauzibilă din punct de vedere istoric, deoarece se aliniază cu perioada în care conflictul dintre Liciniu și Constantin s-a intensificat, iar politica anti-creștină a lui Liciniu a devenit manifestă, după o perioadă de relativă acalmie post-Edictul de la Milano.' || '\n\n' ||
    '## Mărturisirea Diaconului: Pătimirea Sfântului Ermil' || '\n\n' ||
    '### Arestarea și Procesul' || '\n\n' ||
    'Narațiunea martiriului începe cu Sfântul Ermil, o figură publică și respectată în comunitatea creștină din Singidunum, având rangul de diacon.^1^ Atunci când a fost denunțat autorităților pentru credința sa, reacția sa nu a fost de teamă, ci de bucurie și entuziasm, considerând arestarea o oportunitate de a-L mărturisi pe Hristos.^3^' || '\n\n' ||
    'Aduse în fața împăratului Liciniu, dialogul său este direct și curajos. La întrebarea dacă este creștin, el răspunde fără ezitare: „Cu slobod glas mărturisesc, nu numai că sunt creștin, ci despre aceasta adeveresc că sunt sfințit Dumnezeului celui nevăzut, și înaintea Lui slujesc în rânduiala diaconiei".^3^ El respinge cu ironie invitația de a sluji zeilor păgâni, numindu-i idoli orbi și surzi, creații ale mâinilor omenești, nevrednici de închinare.^3^' || '\n\n' ||
    '### Calvarul Torturii' || '\n\n' ||
    'Refuzul său ferm atrage mânia împăratului, care ordonă torturarea sa. Sursele hagiografice descriu în detaliu suferințele îndurate:' || '\n\n' ||
    '- Inițial, este lovit peste față cu toiege de aramă ^1^ sau cu un bici de metal.^2^ Sursele grecești menționează „bice cu ghimpi" (*agkathōta mastigia*).^5^' || '\n' ||
    '- După trei zile de închisoare, este adus din nou la judecată și, pentru că rămâne neclintit, este supus unor chinuri și mai cumplite. Este bătut peste pântece cu vergele de salcie, noduroase și răsucite, o tortură descrisă ca fiind deosebit de chinuitoare.^13^' || '\n' ||
    '- În final, trupul îi este sfâșiat cu cârlige de fier.^13^' || '\n\n' ||
    '### Confirmarea Divină' || '\n\n' ||
    'Un moment crucial în desfășurarea evenimentelor are loc în temniță. În mijlocul suferințelor, Sfântul Ermil se roagă, iar un glas din cer îi răspunde, întărindu-l: „Amin, Amin, zic ție, Ermile; după trei zile te vei izbăvi din aceste primejdii și vei primi mare răsplătire pentru pătimirea ta".^3^ Această intervenție supranaturală este un element recurent în literatura martirică. Funcția sa este dublă: din punct de vedere teologic, confirmă că suferința mucenicului este validată și acceptată de Dumnezeu, nefiind o suferință zadarnică. Din punct de vedere narativ, oferă un moment de înălțare spirituală, transformând o scenă de cruzime umană într-o teofanie, o manifestare a prezenței divine. Promisiunea eliberării „după trei zile" creează o tensiune narativă și prefigurează biruința finală prin moarte, oferind cititorului sau ascultătorului certitudinea că Dumnezeu nu își părăsește aleșii nici în cele mai grele încercări.^13^' || '\n\n' ||
    '## Mărturisirea Prietenului: Convertirea Publică a Sfântului Stratonic' || '\n\n' ||
    '### Catalizatorul Compasiunii' || '\n\n' ||
    'Povestea Sfântului Stratonic introduce o dinamică psihologică și spirituală diferită. El este prezentat ca fiind temnicer (paznic la închisoare), prieten apropiat al lui Ermil și creștin în secret.^2^ Spre deosebire de Ermil, a cărui credință este publică și asumată de la început, Stratonic trăiește o tensiune interioară între convingerile sale și datoria sa oficială.' || '\n\n' ||
    'Punctul de cotitură pentru Stratonic nu este o provocare directă la adresa credinței sale, ci spectacolul suferințelor prietenului său. Văzându-l pe Ermil torturat cu brutalitate, Stratonic este copleșit de compasiune. Sursele descriu cum nu își poate stăpâni lacrimile și suspinele.^1^ Această reacție emoțională, profund umană, îl trădează. Călăii și ceilalți soldați observă durerea sa și înțeleg imediat că împărtășește credința prizonierului.^1^' || '\n\n' ||
    '### De la Temnicer la Mucenic' || '\n\n' ||
    'Confruntat direct de împărat, Stratonic nu mai ezită. Momentul de slăbiciune aparentă se transformă într-un act de curaj suprem. El își mărturisește public credința în Hristos.^1^ Este imediat arestat, supus acelorași torturi ca și Ermil și aruncat în aceeași celulă.^13^' || '\n\n' ||
    'Traseul lui Stratonic oferă un model spiritual distinct și extrem de relevant. El reprezintă creștinul care, din prudență sau teamă, își păstrează credința în sfera privată. Transformarea sa nu este rezultatul unui argument teologic, ci este născută din iubire și empatie. Lacrimile sale nu sunt un semn de slăbiciune, ci punctul în care dragostea pentru prietenul său biruie frica pentru propria viață. Astfel, compasiunea devine calea către *parrhesia* -- curajul de a mărturisi public credința. Dumnezeu folosește legătura umană a prieteniei ca instrument pentru a chema un suflet la eroismul martiric.' || '\n\n' ||
    '## Un Râu al Vieții: Martiriul Final și Cinstirea' || '\n\n' ||
    '### Înecul în Dunăre' || '\n\n' ||
    'Actul final al martiriului lor este înecul în fluviul Dunărea (anticul Istru). Sfinții sunt legați, puși într-o plasă sau coș de nuiele (*sarx* în greacă) și aruncați în apele reci ale fluviului.^1^ Sursele grecești adaugă un detaliu de o frumusețe liturgică deosebită: în drum spre locul execuției, cei doi prieteni cântă Doxologia, „Slavă întru cei de sus lui Dumnezeu...", transformând propria execuție într-un ultim act de slujire divină.^17^' || '\n\n' ||
    '### Descoperirea și Cinstirea Moaștelor' || '\n\n' ||
    'Alegerea apei ca instrument al morții este profund simbolică. În creștinism, apa este elementul Botezului, care semnifică moartea față de păcat și renașterea la o viață nouă în Hristos. Aici, fluviul care le aduce moartea fizică devine, în același timp, locul „botezului sângelui" lor, poarta de intrare în viața veșnică.' || '\n\n' ||
    'Mai mult, toate sursele sunt de acord asupra unui detaliu crucial: trupurile lor au fost găsite de creștini pe malul fluviului **în a treia zi**.^5^ Această mențiune nu este accidentală. Este o paralelă tipologică deliberată și puternică cu Învierea lui Hristos. Hagiografii încadrează astfel martiriul lor nu ca pe o înfrângere, ci ca pe o participare directă la biruința lui Hristos asupra morții. Descoperirea trupurilor lor neatinse în a treia zi este un semn vizibil al promisiunii învierii, un mesaj de speranță pentru comunitatea creștină persecutată.' || '\n\n' ||
    'Trupurile lor au fost îngropate cu cinste de creștinii locali în apropiere de Singidunum, iar cultul lor a început imediat.^10^ Mai târziu, cinstirea lor s-a răspândit, surse târzii atestând prezența cinstitelor lor capete în marea biserică Sfânta Sofia din Constantinopol în anul 1200 ^10^, iar sinaxa lor era săvârșită într-o biserică închinată Sfântului Arhanghel Mihail.^5^' || '\n\n' ||
    '## Perspective Teologice și Spirituale' || '\n\n' ||
    '### Teologia Prieteniei' || '\n\n' ||
    'Legătura dintre Ermil și Stratonic este elementul central al acestei hagiografii. Prietenia lor exemplifică modelul creștin de *philia*, o iubire jertfelnică și înălțătoare. Dragostea lui Stratonic pentru Ermil îl face să sufere alături de el (*compassio*) înainte de a deveni martir alături de el. Prietenia lor nu este un simplu detaliu biografic, ci mecanismul prin care se împlinește planul divin pentru amândoi, demonstrând că relațiile umane sfințite pot deveni căi spre desăvârșire.' || '\n\n' ||
    '### Virtutea Curajului' || '\n\n' ||
    'Viețile celor doi sfinți oferă două modele complementare de curaj. Ermil întruchipează curajul mărturisitorului public, ferm și neclintit de la început. Stratonic, pe de altă parte, demonstrează curajul transformării, trecând de la credința ascunsă la mărturisirea publică. Această dualitate face ca povestea lor să fie relevantă pentru toți credincioșii, indiferent de temperamentul sau de parcursul lor spiritual.' || '\n\n' ||
    '### Tradiția Hagiografică' || '\n\n' ||
    'Primele versiuni ale vieții lor datează, probabil, de la sfârșitul secolului al VI-lea (BHG 744-745b) ^15^, fiind ulterior dezvoltate și înfrumusețate de hagiografi precum Sfântul Simeon Metafrastul.^2^ Unele surse slavone îi menționează ca fiind de origine slavă ^10^, o atribuire care este, cel mai probabil, o adăugire culturală ulterioară, reflectând dorința popoarelor slave de la Dunăre de a-i revendica pe acești sfinți locali ca fiind ai lor.' || '\n\n' ||
    '## Sfinții în Liturghie și Iconografie' || '\n\n' ||
    'Cinstirea universală a Sfinților Ermil și Stratonic în Ortodoxie este cel mai bine reflectată în imnografia dedicată lor, care păstrează aceleași teme teologice în diferite limbi.' || '\n\n' ||
    '### Imnografie Comparată a Sfinților Ermil și Stratonic' || '\n\n' ||
    '| **Imn** | **Română (Traducere)** | **Greacă** | **Slavonă Bisericească** | **Engleză (Traducere)** |' || '\n' ||
    '| :--- | :--- | :--- | :--- | :--- |' || '\n' ||
    '| **Tropar (Glas 4)** | Mucenicii Tăi, Doamne, întru nevoințele lor, cununile nestricăciunii au dobândit de la Tine, Dumnezeul nostru; că având puterea Ta, pe chinuitori au învins, zdrobit-au și ale demonilor neputincioase îndrăzniri. Pentru rugăciunile lor, mântuiește sufletele noastre, Hristoase Dumnezeule. ^19^ | Οἱ Μάρτυρές σου Κύριε... ^17^ | Му́ченицы Твои́, Го́споди... ^19^ | Your Martyrs, O Lord, in their courageous contest for You received as the prize the crowns of incorruption... ^10^ |' || '\n' ||
    '| **Condac (Glas 2)** | Din tulburarea cea lumească ieșind, la limanul cel lin v-ați mutat, cu sângiurile muceniciei și cu harul minunilor strălucind, Sfinților Ermil și Stratonic. Pentru aceasta, cu bucurie săvârșim sfântă pomenirea voastră. ^20^ | (Nu este specificat un condac propriu în sursele grecești) | От мирски́я молвы́ избего́сте... ^20^ | You fled from the tumult of the world and have passed over to the quiet haven... O Saints Hermylus and Stratonicus... |' || '\n\n' ||
    '### Tradiția Iconografică' || '\n\n' ||
    'În icoane, Sfinții Ermil și Stratonic sunt aproape întotdeauna reprezentați împreună, subliniind vizual legătura lor de nezdruncinat.' || '\n\n' ||
    '- **Sfântul Ermil** este înfățișat purtând veșmintele unui diacon: stiharul (o tunică lungă) și orarul (o fâșie lungă de material purtată pe umărul stâng). Adesea ține în mână o cruce a martiriului și, uneori, o cădelniță, simbol al slujirii sale diaconești.' || '\n' ||
    '- **Sfântul Stratonic** este reprezentat ca un soldat roman sau temnicer, uneori purtând armură sau o uniformă militară. Și el ține în mână crucea martiriului.' || '\n\n' ||
    'Această reprezentare duală nu este doar o ilustrare a biografiei lor, ci o mărturie vizuală a unității Bisericii: slujitorul altarului și laicul credincios, uniți în aceeași jertfă pentru Hristos.' || '\n\n' ||
    '## Modele Perene pentru Era Digitală' || '\n\n' ||
    'Viețile Sfinților Mucenici Ermil și Stratonic oferă lecții profunde și atemporale: puterea prieteniei de a inspira virtute, necesitatea curajului în fața ostilității și biruința finală a credinței asupra morții. Povestea lor, bogată în detalii istorice și simbolism teologic, este deosebit de potrivită pentru a fi prezentată într-o aplicație modernă, care poate îmbina rigoarea academică cu profunzimea spirituală.' || '\n\n' ||
    'Pentru dezvoltarea unei astfel de aplicații, se recomandă structurarea conținutului pe secțiuni clare, bazate pe acest raport: „Viața Sfinților", „Contextul Istoric", „Semnificații Teologice". Secțiunea dedicată imnografiei poate utiliza direct tabelul comparativ, oferind utilizatorilor posibilitatea de a asculta și de a se ruga cu aceleași imnuri folosite în întreaga lume ortodoxă. O galerie de icoane, cu explicații ale simbolismului vestimentar și al gesturilor, ar putea completa experiența, transformând o simplă aplicație informativă într-un veritabil instrument de cateheză și evlavie. Astfel, mărturia de secole a celor doi prieteni martiri de pe malul Dunării poate continua să inspire și să întărească credința creștinilor în era digitală.' || '\n\n' ||
    '#### Works cited' || '\n\n' ||
    '1. Sinaxar 13 Ianuarie, accessed August 21, 2025, [[https://admd.info/sinaxar.php?date=1736726400]{.underline}](https://admd.info/sinaxar.php?date=1736726400)' || '\n' ||
    '2. Ermil și Stratonic - OrthodoxWiki, accessed August 21, 2025, [[https://ro.orthodoxwiki.org/Ermil_%C8%99i_Stratonic]{.underline}](https://ro.orthodoxwiki.org/Ermil_%C8%99i_Stratonic)' || '\n' ||
    '3. Viața Sfântului Mucenic Ermil - Doxologia, accessed August 21, 2025, [[https://doxologia.ro/viata-sfantului-mucenic-ermil]{.underline}](https://doxologia.ro/viata-sfantului-mucenic-ermil)' || '\n' ||
    '4. Sfinții Mucenici Ermil și Stratonic (Secolele III -- IV) - Uniti Schimbam, accessed August 21, 2025, [[https://www.unitischimbam.ro/ermil-si-stratonic/]{.underline}](https://www.unitischimbam.ro/ermil-si-stratonic/)' || '\n' ||
    '5. Ἑρμύλου καί Στρατονίκου, accessed August 21, 2025, [[https://churchofcyprus.org.cy/cal/saint.php?articleID=447]{.underline}](https://churchofcyprus.org.cy/cal/saint.php?articleID=447)' || '\n' ||
    '6. Μνήμη των Αγίων Μαρτύρων Ερμύλου και Στρατονίκου (13 Ιανουαρίου), accessed August 21, 2025, [[https://churchofcyprus.org.cy/8787]{.underline}](https://churchofcyprus.org.cy/8787)' || '\n' ||
    '7. Μνήμη των Αγίων Μαρτύρων Ερμύλου και Στρατονίκου (13 Ιανουαρίου) - Nea Polis, accessed August 21, 2025, [[https://cyneapolis.com/categories/san-simera/%CE%BC%CE%BD%CE%AE%CE%BC%CE%B7-%CF%84%CF%89%CE%BD-%CE%B1%CE%B3%CE%AF%CF%89%CE%BD-%CE%BC%CE%B1%CF%81%CF%84%CF%8D%CF%81%CF%89%CE%BD-%CE%B5%CF%81%CE%BC%CF%8D%CE%BB%CE%BF%CF%85-%CE%BA%CE%B1%CE%B9-%CF%83%CF%84%CF%81%CE%B1%CF%84%CE%BF%CE%BD%CE%AF%CE%BA%CE%BF%CF%85-13-%CE%B9%CE%B1%CE%BD%CE%BF%CF%85%CE%B1%CF%81%CE%AF%CE%BF%CF%85]{.underline}](https://cyneapolis.com/categories/san-simera/%CE%BC%CE%BD%CE%AE%CE%BC%CE%B7-%CF%84%CF%89%CE%BD-%CE%B1%CE%B3%CE%AF%CF%89%CE%BD-%CE%BC%CE%B1%CF%81%CF%84%CF%8D%CF%81%CF%89%CE%BD-%CE%B5%CF%81%CE%BC%CF%8D%CE%BB%CE%BF%CF%85-%CE%BA%CE%B1%CE%B9-%CF%83%CF%84%CF%81%CE%B1%CF%84%CE%BF%CE%BD%CE%AF%CE%BA%CE%BF%CF%85-13-%CE%B9%CE%B1%CE%BD%CE%BF%CF%85%CE%B1%CF%81%CE%AF%CE%BF%CF%85)' || '\n' ||
    '8. Αποστολική Διακονία της Εκκλησίας της Ελλάδος, accessed August 21, 2025, [[https://apostoliki-diakonia.gr/gr_main/eortologio/eortologio.asp?file=jan/13.htm]{.underline}](https://apostoliki-diakonia.gr/gr_main/eortologio/eortologio.asp?file=jan/13.htm)' || '\n' ||
    '9. Житие святых | Храм в честь иконы Божией Матери Знамение (Абалакская) г. Томск, accessed August 21, 2025, [[https://znamenietomsk.ru/zitie/?ID=21333]{.underline}](https://znamenietomsk.ru/zitie/?ID=21333)' || '\n' ||
    '10. Martyrs Hermylus and Stratonicus of Belgrade (13 January) - Vema.com.au, accessed August 21, 2025, [[https://vema.com.au/martyrs-hermylus-and-stratonicus-of-belgrade-13-january-2/]{.underline}](https://vema.com.au/martyrs-hermylus-and-stratonicus-of-belgrade-13-january-2/)' || '\n' ||
    '11. Sts. Hermylus and Stratonicus: Channels of God''s Strength - Saint Elisabeth Convent, accessed August 21, 2025, [[https://obitel-minsk.org/en/sts-hermylus-and-stratonicus-channels-of-god-s-strength]{.underline}](https://obitel-minsk.org/en/sts-hermylus-and-stratonicus-channels-of-god-s-strength)' || '\n' ||
    '12. Holy Martyrs Hermylus and Stratonicus (315) - Ancient Faith Ministries, accessed August 21, 2025, [[https://www.ancientfaith.com/podcasts/saintoftheday/38572/]{.underline}](https://www.ancientfaith.com/podcasts/saintoftheday/38572/)' || '\n' ||
    '13. Saints Hermylus And Stratonicus - Catholic.net, accessed August 21, 2025, [[https://catholic.net/op/articles/1880/cat/1205/saints-hermylus-and-stratonicus.html]{.underline}](https://catholic.net/op/articles/1880/cat/1205/saints-hermylus-and-stratonicus.html)' || '\n' ||
    '14. Byzantine Saints: Martyrs Hermylus and Stratonicus of Belgrade (13 January) - YouTube, accessed August 21, 2025, [[https://www.youtube.com/watch?v=-1HBJSuOvEs]{.underline}](https://www.youtube.com/watch?v=-1HBJSuOvEs)' || '\n' ||
    '15. St. Martyrs Ermil (Ermilus) and Stratonicus | Serbian Orthodox Church [Official web site], accessed August 21, 2025, [[http://arhiva.spc.rs/eng/st_martyrs_ermil_ermilus_and_stratonicus.html]{.underline}](http://arhiva.spc.rs/eng/st_martyrs_ermil_ermilus_and_stratonicus.html)' || '\n' ||
    '16. Sinaxar - Mănăstirea Sihăstria Putnei, accessed August 21, 2025, [[https://www.sihastriaputnei.ro/sites/default/files/attachments/2020/02/sinaxar_ianuarie.pdf]{.underline}](https://www.sihastriaputnei.ro/sites/default/files/attachments/2020/02/sinaxar_ianuarie.pdf)' || '\n' ||
    '17. Άγιοι Έρμυλος και Στρατόνικος | Βίος & Γιορτή - Monastic Republic, accessed August 21, 2025, [[https://www.monasticrepublic.com/synaxaristis/ianouarios/agioi-ermylos-kai-stratonikos]{.underline}](https://www.monasticrepublic.com/synaxaristis/ianouarios/agioi-ermylos-kai-stratonikos)' || '\n' ||
    '18. Άγιοι Έρμυλος και Στρατόνικος - Ορθόδοξος Συναξαριστής, accessed August 21, 2025, [[https://www.saint.gr/11411/downloadpdf.aspx]{.underline}](https://www.saint.gr/11411/downloadpdf.aspx)' || '\n' ||
    '19. Мученики Ермил, диакон и Стратоник Сингидонские (Белградские): житие, иконы, день памяти - Азбука веры, accessed August 21, 2025, [[https://azbyka.ru/days/svv-ermil-singidonskij-belgradskij-stratonik-singidonskij-belgradskij]{.underline}](https://azbyka.ru/days/svv-ermil-singidonskij-belgradskij-stratonik-singidonskij-belgradskij)' || '\n' ||
    '20. Мученикам Ермилу и Стратонику (тропарь и кондак) - ПСАЛОМЩИКЪ - <, accessed August 21, 2025, [[http://diak.ortox.ru/__muchenikam_i_ispovednikam/view/id/1112201]{.underline}](http://diak.ortox.ru/__muchenikam_i_ispovednikam/view/id/1112201)' || '\n' ||
    '21. Мученик Стратоник - Православный calendar - Православие.Ru, accessed August 21, 2025, [[https://days.pravoslavie.ru/name/2080.htm]{.underline}](https://days.pravoslavie.ru/name/2080.htm)'
);