INSERT INTO core_schema.saint_lives (name_ro, life_description_ro)
VALUES (
    'Sfinții Împărați Constantin și Elena',
    '# Monografie Exhaustivă asupra Sfinților Mari Împărați și Întocmai cu Apostolii, Constantin și Elena: Hagiografie, Teologie Politică, Imnografie și Cultul Relicvelor în Spațiul Ortodox Românesc' || '\n\n' ||
    '## Introducere' || '\n\n' ||
    'În vasta constelație a sfințeniei creștine, puține figuri au exercitat o influență atât de profundă și de durabilă asupra istoriei universale și a ecleziologiei ortodoxe precum Sfinții Mari Împărați Constantin și Elena. Prăznuiți liturgic la data de 21 mai, acești doi sfinți, mamă și fiu, reprezintă chintesenta tranziției de la „era martirajului" la „era imperiului creștin", inaugurând o paradigmă a simfoniei bizantine care a modelat relația dintre Biserică și Stat pentru mai bine de un mileniu.' || '\n\n' ||
    'Prezentul raport de cercetare își propune să ofere o analiză exhaustivă, multi-dimensională, a vieții, activității și moștenirii lor, investigând sursele hagiografice, deciziile politice cu impact teologic, fenomenul minunilor, profunzimea textelor imnografice (Acatistul) și dinamica complexă a cultului moaștelor, cu o focalizare specială asupra manifestărilor acestui cult în România contemporană.' || '\n\n' ||
    '## Partea I: Contextul Istoric și Hagiografia Imperială' || '\n\n' ||
    '### 1.1. Criza Secolului al III-lea și Ascensiunea Tetrarhiei' || '\n\n' ||
    'Pentru a înțelege magnitudinea schimbării aduse de Constantin cel Mare, este imperativ să analizăm contextul premergător. Imperiul Roman de la sfârșitul secolului al III-lea se afla într-o criză profundă, marcată de instabilitate politică, presiuni la frontiere și o fragmentare internă. Împăratul Dioclețian a încercat să stabilizeze situația prin instituirea Tetrarhiei (guvernarea în patru), un sistem care împărțea puterea între doi auguști și doi cerezari.^1^' || '\n\n' ||
    'Flavius Valerius Constantinus s-a născut la Naissus (astăzi Niș, Serbia), cel mai probabil în jurul anului 272 d.Hr..^1^ Mama sa, Elena, o femeie de origine modestă (posibil fiica unui hangiu din Bithynia), a fost prima soție sau concubină oficială a lui Constantius Chlorus, fiind ulterior repudiată din rațiuni politice. Această traumă familială timpurie și reabilitarea ulterioară a Elenei de către fiul său vor juca un rol crucial în dinamica lor spirituală.' || '\n\n' ||
    '### 1.2. Constantin cel Mare: *Basileus* și *Isapostolos*' || '\n\n' ||
    '#### 1.2.1. Teofania de la Podul Milvius și Simbolismul Crucii' || '\n\n' ||
    'Momentul axial al convertirii și al carierei sale politice este Bătălia de la Podul Milvius (Ponte Milvio) din 28 octombrie 312, împotriva rivalului său, Maxențiu. Istoricii bisericești Eusebiu de Cezareea și Lactanțiu descriu în detaliu minunea care a precedat lupta.' || '\n\n' ||
    'În amiaza mare, Constantin a văzut pe cer, deasupra soarelui, o cruce luminoasă însoțită de inscripția grecească *„En toutoi nika"* (în latină: *In hoc signo vinces* - „Prin acest semn vei învinge").^1^ În noaptea următoare, Hristos i s-a arătat în vis, poruncindu-i să confecționeze un steag de luptă (*labarum*) care să poarte monograma hristică (Chi-Rho). Ascultarea de această poruncă divină a dus la o victorie categorică împotriva unei armate superioare numeric, Maxențiu înecându-se în apele Tibrului.^2^' || '\n\n' ||
    'Această victorie nu a fost doar militară, ci teologică. Ea a marcat înfrângerea zeităților păgâne tradiționale și a cultului *Sol Invictus* în fața „Dumnezeului creștinilor". Acatistul Sfinților Împărați rememorează poetic acest moment în Condacul 1: „Cel ce chipul Crucii strălucind pe cer mai mult decât soarele l-ai văzut și biruința semnului Domnului bine ți-a descoperit".^4^' || '\n\n' ||
    '#### 1.2.2. Edictul de la Milan (313)' || '\n\n' ||
    'Consecința politică imediată a convertirii a fost promulgarea Edictului de la Milan în 313, act semnat împreună cu Liciniu, împăratul Orientului. Deși adesea interpretat simplist ca o „oficializare" a creștinismului, Edictul a fost, în realitate, un act de toleranță religioasă universală.' || '\n\n' ||
    '**Prevederi cheie ale Edictului:**' || '\n\n' ||
    '- Acordarea libertății depline de cult creștinilor și tuturor celorlalte religii.^6^' || '\n' ||
    '- Restituirea imediată și fără plată a lăcașurilor de cult și a proprietăților confiscate creștinilor în timpul persecuțiilor lui Dioclețian.^8^' || '\n' ||
    '- Recunoașterea personalității juridice a comunităților creștine (Biserica).' || '\n\n' ||
    '#### 1.2.3. Sinodul I Ecumenic de la Niceea (325)' || '\n\n' ||
    'Constantin a convocat primul sinod ecumenic din istorie la Niceea, în Bitinia, pentru a păstra unitatea dogmatică a Bisericii în fața ereziei lui Arie.^2^' || '\n\n' ||
    'Rolul împăratului a fost acela de „episcop al treburilor din afară" (*episkopos ton ektos*). El a asigurat logistica transportului pentru cei 318 părinți sinodali și a deschis lucrările sinodului. Rezultatul a fost formularea primelor șapte articole ale Crezului și definirea consubstanțialității (*homoousios*) Fiului cu Tatăl.^1^ Acatistul îl numește pe Constantin „dărâmătorul idolilor" și cel care a luminat lumea cu dreapta credință.^3^' || '\n\n' ||
    '#### 1.2.4. Fondarea Constantinopolului -- „Noua Romă"' || '\n\n' ||
    'Inaugurat la 11 mai 330, Constantinopolul a fost închinat Preasfintei Născătoare de Dumnezeu.^8^ Orașul a devenit centrul lumii creștine pentru mai bine de o mie de ani, fiind dotat cu biserici magnifice, devenind depozitarul celor mai sfinte relicve ale creștinătății.' || '\n\n' ||
    '### 1.3. Sfânta Împărăteasă Elena: Arhetipul Arheologiei Sacre' || '\n\n' ||
    'Elena a primit titlul suprem de *Augusta* (Împărăteasă). Influența ei asupra lui Constantin a fost majoră, tradiția sugerând că ea a fost cea care a cultivat sămânța credinței în inima lui.^2^' || '\n\n' ||
    '#### 1.3.1. Pelerinajul în Țara Sfântă și *Inventio Crucis*' || '\n\n' ||
    'La vârsta de 80 de ani, Sfânta Elena a întreprins un pelerinaj istoric în Palestina pentru a curăța Locurile Sfinte. A ordonat săpături arheologice care au scos la iveală trei cruci, piroanele și titlul *INRI*.^2^ Identificarea Crucii Mântuitorului s-a făcut printr-o minune: patriarhul Macarie a atins crucile de o femeie moartă (sau grav bolnavă), iar la atingerea de Crucea Adevărată, aceasta a înviat (sau s-a vindecat instantaneu).^1^' || '\n\n' ||
    '#### 1.3.2. Activitatea Ctitoricească' || '\n\n' ||
    'Sfânta Elena a inițiat construcția unor bazilici monumentale:' || '\n\n' ||
    '- **Biserica Învierii (Anastasis)** de la Ierusalim (Sfântul Mormânt).' || '\n' ||
    '- **Biserica Nașterii Domnului** din Betleem.' || '\n' ||
    '- **Biserica Eleona** de pe Muntele Măslinilor (locul Înălțării).^2^' || '\n\n' ||
    '## Partea II: Analiza Teologică, Liturgică și Imnografică' || '\n\n' ||
    '### 2.1. Troparul Sfinților Împărați -- Exegeză' || '\n\n' ||
    '*„Chipul Crucii Tale pe cer văzându-l, și ca Pavel chemarea nu de la oameni luând, cel între împărați Apostolul Tău, Doamne, împărăteasca cetate în mâinile Tale a pus-o. Pe care păzește-o totdeauna în pace..."*.^4^' || '\n\n' ||
    '**Elemente exegetice:** Paralela cu Sfântul Pavel („ca Pavel chemarea nu de la oameni luând") este esențială, justificând titlul de *Isapostolos* („Întocmai cu Apostolii"). Actul de a pune „împărăteasca cetate în mâinile Tale" semnifică transfigurarea puterii politice.' || '\n\n' ||
    '### 2.2. Acatistul și Iconografia' || '\n\n' ||
    'Acatistul celebrează victoria Crucii și rolul Sfintei Elena ca „nouă David", care a adus Chivotul (Crucea) înapoi poporului.^3^' || '\n\n' ||
    '**Iconografia (Dionisie din Furna):** Ei sunt zugrăviți împreună, susținând Sfânta Cruce. Constantin poartă *sakkos* imperial și *loros*, iar Elena poartă haine imperiale și o mahramă albă sub coroană.^1,15^' || '\n\n' ||
    '## Partea III: Moaștele Sfinților -- Trasee Istorice și Prezența în România' || '\n\n' ||
    '### 3.1. Itinerariul Moaștelor' || '\n\n' ||
    'Moaștele Sfintei Elena au fost luate de cavalerii venețieni în 1211 și duse la Veneția, unde se păstrează trupul aproape întreg în **Biserica „Sant''Elena"**.^19^' || '\n\n' ||
    '### 3.2. Moaștele din România' || '\n\n' ||
    '#### 3.2.1. Odorul Permanent de la Catedrala Patriarhală (2002)' || '\n\n' ||
    'În 2002, o delegație din Cipru a oferit o raclă cu părticele din moaștele Sfinților Constantin și Elena, așezată definitiv în **Catedrala Patriarhală din București**, unde sunt ocrotitori istorici.^21^' || '\n\n' ||
    '#### 3.2.2. Pelerinajul Istoric din 2025' || '\n\n' ||
    'În perioada **30 aprilie -- 8 mai 2025**, racla cu moaștele întregi ale Sfintei Împărătese Elena a fost adusă de la Veneția la Mănăstirea Pantocrator (Teleorman), cu un popas istoric la București.^19,23^' || '\n\n' ||
    '## Partea IV: Minunile Sfinților' || '\n\n' ||
    'Sfinții sunt invocați pentru vindecarea bolilor de piele (după vindecarea lui Constantin de lepră), protecția împotriva atacurilor demonice și ajutor în procese sau nedreptăți.^1^' || '\n\n' ||
    '## Partea V: Dimensiunea Etnografică -- „Constantinul Puilor"' || '\n\n' ||
    'În calendarul popular, 21 mai este „Constantinul Puilor" sau „Constantin Graur", marcând momentul când păsările își învață puii să zboare.^30^' || '\n\n' ||
    '- **Interdicții Agrare:** Ultima zi în care se mai pot semăna culturi de vară; munca la câmp este oprită pentru a evita dăunătorii.^32^' || '\n' ||
    '- **Ritualul Focului Viu:** Păstorii aprind un foc sacru prin care trec oile pentru purificare și protecție.^30^' || '\n' ||
    '- **Impact Social:** Aproximativ **1,8 milioane de români** își serbează onomastica.^31^' || '\n\n' ||
    '## Concluzii' || '\n\n' ||
    'Sfinții Împărați Constantin și Elena rămân piloni vii ai identității ortodoxe. Moștenirea lor este o mărturie continuă a faptului că „prin acest semn" -- Crucea -- credința biruiește istoria.' || '\n\n' ||
    '#### Works cited' || '\n\n' ||
    '1. Sf.Constantin si Elena icoana cu viata lor cu aur si argint rara - MG Argenti, accessed January 26, 2026, [[http://www.mgargenti.ro/icoane-argint-sfinti-ortodocsi-nume-femei/sf-constantin-si-elena-icoana-cu-viata-lor-cu-aur-si-argint--282935]{.underline}](http://www.mgargenti.ro/icoane-argint-sfinti-ortodocsi-nume-femei/sf-constantin-si-elena-icoana-cu-viata-lor-cu-aur-si-argint--282935)' || '\n' ||
    '2. Sfinții Împărați Constantin și Elena. Cele mai importante tradiții și obiceiuri pe 21 mai. Care sunt florile care binecuvântează casa | Digi24, accessed January 26, 2026, [[https://www.digi24.ro/stiri/actualitate/evenimente/sfintii-imparati-constantin-si-elena-cele-mai-importante-traditii-si-obiceiuri-pe-21-mai-care-sunt-florile-care-binecuvanteaza-casa-3249067]{.underline}](https://www.digi24.ro/stiri/actualitate/evenimente/sfintii-imparati-constantin-si-elena-cele-mai-importante-traditii-si-obiceiuri-pe-21-mai-care-sunt-florile-care-binecuvanteaza-casa-3249067)' || '\n' ||
    '3. (DOC) Sfinții Împărați Constantin și Elena, aspecte liturgice. - Academia.edu, accessed January 26, 2026, [[https://www.academia.edu/33156042/Sfin%C8%9Bii_%C3%8Emp%C4%83ra%C8%9Bi_Constantin_%C8%99i_Elena_aspecte_liturgice]{.underline}](https://www.academia.edu/33156042/Sfin%C8%9Bii_%C3%8Emp%C4%83ra%C8%9Bi_Constantin_%C8%99i_Elena_aspecte_liturgice)' || '\n' ||
    '4. Acatistul Sfinților Împărați Constantin și Elena - TRINITAS TV, accessed January 26, 2026, [[https://www.trinitas.tv/acatistul-sfintilor-imparati-constantin-si-elena-2/]{.underline}](https://www.trinitas.tv/acatistul-sfintilor-imparati-constantin-si-elena-2/)' || '\n' ||
    '5. Acatistul Sfintilor Imparati Constantin si Elena CrestinOrtodox.ro, accessed January 26, 2026, [[https://www.crestinortodox.ro/acatiste/acatistul-sfintilor-imparati-constantin-elena-67079.html]{.underline}](https://www.crestinortodox.ro/acatiste/acatistul-sfintilor-imparati-constantin-elena-67079.html)' || '\n' ||
    '6. Viata Sfintilor Constantin si Elena - Edictul de la Milan (21 mai) - YouTube, accessed January 26, 2026, [[https://www.youtube.com/watch?v=yz_hYWKNFz0]{.underline}](https://www.youtube.com/watch?v=yz_hYWKNFz0)' || '\n' ||
    '7. Edictul de la Milano - Wikipedia, accessed January 26, 2026, [[https://ro.wikipedia.org/wiki/Edictul_de_la_Milano]{.underline}](https://ro.wikipedia.org/wiki/Edictul_de_la_Milano)' || '\n' ||
    '8. Viața Sfinților Mari Împărați, întocmai cu Apostolii, Constantin și mama sa, Elena, accessed January 26, 2026, [[https://doxologia.ro/viata-sfintilor-mari-imparati-intocmai-cu-apostolii-constantin-mama-sa-elena]{.underline}](https://doxologia.ro/viata-sfintilor-mari-imparati-intocmai-cu-apostolii-constantin-mama-sa-elena)' || '\n' ||
    '9. Sfinții Împărați Constantin și Elena ‒ drumul spre sfințenie - Doxologia, accessed January 26, 2026, [[https://doxologia.ro/sfintii-imparati-constantin-elena-drumul-spre-sfintenie]{.underline}](https://doxologia.ro/sfintii-imparati-constantin-elena-drumul-spre-sfintenie)' || '\n' ||
    '10. Troparul Sfinţilor Mari Împăraţi, întocmai cu Apostolii, Constantin şi mama sa, Elena, accessed January 26, 2026, [[https://doxologia.ro/troparul-sfintilor-mari-imparati-intocmai-cu-apostolii-constantin-mama-sa-elena]{.underline}](https://doxologia.ro/troparul-sfintilor-mari-imparati-intocmai-cu-apostolii-constantin-mama-sa-elena)' || '\n' ||
    '11. Troparul Sfintilor Constantin si Elena - YouTube, accessed January 26, 2026, [[https://www.youtube.com/watch?v=6G74co-Pz5Q]{.underline}](https://www.youtube.com/watch?v=6G74co-Pz5Q)' || '\n' ||
    '12. Troparul Sfintilor Constantin si Elena (Troparion of Saints Constantine and Helena) - YouTube, accessed January 26, 2026, [[https://www.youtube.com/watch?v=GO04olFAYXA]{.underline}](https://www.youtube.com/watch?v=GO04olFAYXA)' || '\n' ||
    '13. Acatistul Sfinților Împăraţi Constantin şi Elena - Biserica cu Lună Oradea, accessed January 26, 2026, [[https://www.bisericaculunaoradea.ro/acatistul-sfintilor-imparati-constantin-si-elena/]{.underline}](https://www.bisericaculunaoradea.ro/acatistul-sfintilor-imparati-constantin-si-elena/)' || '\n' ||
    '14. Acatistul Sfinţilor Împăraţi, întocmai cu Apostolii, Constantin şi Elena | Doxologia, accessed January 26, 2026, [[https://doxologia.ro/acatistul-sfintilor-imparati-intocmai-cu-apostolii-constantin-elena]{.underline}](https://doxologia.ro/acatistul-sfintilor-imparati-intocnow-apostolii-constantin-elena)' || '\n' ||
    '15. Erminia picturii bizantine a ieromonahului Dionisie din Furna - Doxologia, accessed January 26, 2026, [[https://doxologia.ro/erminia-picturii-bizantine-ieromonahului-dionisie-din-furna]{.underline}](https://doxologia.ro/erminia-picturii-bizantine-ieromonahului-dionisie-din-furna)' || '\n' ||
    '16. Dionisie Din Furna Erminia Picturii Bizantine : Free Download, Borrow, and Streaming, accessed January 26, 2026, [[https://archive.org/details/dionisie-din-furna-erminia-picturii-bizantine]{.underline}](https://archive.org/details/dionisie-din-furna-erminia-picturii-bizantine)' || '\n' ||
    '17. Erminia Picturii Bizantine | PDF - Scribd, accessed January 26, 2026, [[https://ro.scribd.com/document/118960070/Erminia-picturii-bizantine]{.underline}](https://ro.scribd.com/document/118960070/Erminia-picturii-bizantine)' || '\n' ||
    '18. Dionisie Din Furna, Erminia Picturii Bizantine | PDF - Scribd, accessed January 26, 2026, [[https://ro.scribd.com/document/688808097/2-Dionisie-Din-Furna-Erminia-Picturii-Bizantine]{.underline}](https://ro.scribd.com/document/688808097/2-Dionisie-Din-Furna-Erminia-Picturii-Bizantine)' || '\n' ||
    '19. Sfanta Elena - Moaștele Sfintei Împărătese ajung în România, accessed January 26, 2026, [[https://sfanta-elena.ro/]{.underline}](https://sfanta-elena.ro/)' || '\n' ||
    '20. Moaştele Sfintei Împărătese Elena au ajuns la Mănăstirea Pantocrator. Pelerinii sunt aşteptaţi până pe 8 mai | Digi24, accessed January 26, 2026, [[https://www.digi24.ro/stiri/actualitate/social/moastele-sfintei-imparatese-elena-au-ajuns-la-manastirea-pantocrator-pelerinii-sunt-asteptati-pana-pe-8-mai-3221057]{.underline}](https://www.digi24.ro/stiri/actualitate/social/moastele-sfintei-imparatese-elena-au-ajuns-la-manastirea-pantocrator-pelerinii-sunt-asteptati-pana-pe-8-mai-3221057)' || '\n' ||
    '21. Moastele *Sf. Dimitrie si ale Sf. Imparati Constantin si Elena* au fost introduse in Catredrala Patriarhala - Noutati ortodoxe, accessed January 26, 2026, [[https://www.noutati-ortodoxe.ro/moastele-i-sf-dimitrie-si-ale-sf-imparati-constantin-si-elena-i-au-fost-introduse-in-catredrala-patriarhala_l22085_p0.html]{.underline}](https://www.noutati-ortodoxe.ro/moastele-i-sf-dimitrie-si-ale-sf-imparati-constantin-si-elena-i-au-fost-introduse-in-catredrala-patriarhala_l22085_p0.html)' || '\n' ||
    '22. Sfinții Împărați Constantin și Elena, ocrotitorii Catedralei Patriarhale - Basilica.ro, accessed January 26, 2026, [[https://basilica.ro/sfintii-imparati-constantin-si-elena-ocrotitorii-catedralei-patriarhale-2/]{.underline}](https://basilica.ro/sfintii-imparati-constantin-si-elena-ocrotitorii-catedralei-patriarhale-2/)' || '\n' ||
    '23. (Foto) Pentru prima dată în România: Moaștele întregi ale Sfintei Împărătese Elena au fost întâmpinate la Catedrala Patriarhală | Doxologia, accessed January 26, 2026, [[https://doxologia.ro/foto-pentru-prima-data-romania-moastele-intregi-ale-sfintei-imparatese-elena-au-fost-intampinate-la]{.underline}](https://doxologia.ro/foto-pentru-prima-data-romania-moastele-intregi-ale-sfintei-imparatese-elena-au-fost-intampinate-la)' || '\n' ||
    '24. Moaștele Sfintei Împărătese Elena, pentru prima dată în țara noastră - Ziarul Lumina, accessed January 26, 2026, [[https://ziarullumina.ro/actualitate-religioasa/stiri/moastele-sfintei-imparatese-elena-pentru-prima-data-in-tara-noastra-197573.html]{.underline}](https://ziarullumina.ro/actualitate-religioasa/stiri/moastele-sfintei-imparatese-elena-pentru-prima-data-in-tara-noastra-197573.html)' || '\n' ||
    '25. Moaștele Sfinților Împărați Constantin și Elena de la Patriarhie, în eparhiile din vestul țării - Basilica, accessed January 26, 2026, [[https://basilica.ro/moastele-sfintilor-imparati-constantin-si-elena-de-la-patriarhie-in-eparhiile-din-vestul-tarii/]{.underline}](https://basilica.ro/moastele-sfintilor-imparati-constantin-si-elena-de-la-patriarhie-in-eparhiile-din-vestul-tarii/)' || '\n' ||
    '26. Pelerinaj cu moaștele Sfinților Împărați Constantin și Elena în vestul țării - Basilica.ro, accessed January 26, 2026, [[https://basilica.ro/pelerinaj-cu-moastele-sfintilor-imparati-constantin-si-elena-in-vestul-tarii/]{.underline}](https://basilica.ro/pelerinaj-cu-moastele-sfintilor-imparati-constantin-si-elena-in-vestul-tarii/)' || '\n' ||
    '27. Mânăstirea „Sfânta Elena de la mare" - MERG IN, accessed January 26, 2026, [[https://merg.in/costinesti/de-vizitat/monumente/manastirea-sfanta-elena-de-la-mare-3526.html]{.underline}](https://merg.in/costinesti/de-vizitat/monumente/manastirea-sfanta-elena-de-la-mare-3526.html)' || '\n' ||
    '28. Mănăstirea Sfânta Elena de la Mare -- Costinești - Calator prin Romania, accessed January 26, 2026, [[https://www.travellerinromania.com/itinerary/manastirea-sfanta-elena-de-la-mare-costinesti/]{.underline}](https://www.travellerinromania.com/itinerary/manastirea-sfanta-elena-de-la-mare-costinesti/)' || '\n' ||
    '29. Schitul Sfânta Elena de la Mare, Costinești - Audio Travel Guide, accessed January 26, 2026, [[https://audiotravelguide.ro/schitul-sfanta-elena-de-la-mare-costinesti/]{.underline}](https://audiotravelguide.ro/schitul-sfanta-elena-de-la-mare-costinesti/)' || '\n' ||
    '30. Obiceiuri și superstiții de Sfinţii Constantin şi Elena. Aproape 1,8 milioane de români îşi sărbătoresc onomastica - Adevarul, accessed January 26, 2026, [[https://adevarul.ro/stiri-interne/societate/obiceiuri-si-superstitii-de-sfintii-constantin-si-2444953.html]{.underline}](https://adevarul.ro/stiri-interne/societate/obiceiuri-si-superstitii-de-sfintii-constantin-si-2444953.html)' || '\n' ||
    '31. Tradiții Sf. Constantin și Elena. Ce trebuie să faci în această zi? - Kanal D2, accessed January 26, 2026, [[https://kanald2.ro/traditii-sf-constantin-si-elena-ce-trebuie-sa-faci-in-aceasta-zi-20474166]{.underline}](https://kanald2.ro/traditii-sf-constantin-si-elena-ce-trebuie-sa-faci-in-aceasta-zi-20474166)' || '\n' ||
    '32. 10 superstiții, interdicții și credințe populare de Sfinții Împărați Constantin și Elena. Ce să nu faci azi | Traditii, datini, obiceiuri | Radio Antena Satelor, accessed January 26, 2026, [[https://www.antenasatelor.ro/lada-de-zestre/lada-de-zestre/traditii-datini-obiceiuri/10-superstitii-interdictii-si-credinte-populare-de-sfintii-imparati-constantin-si-elena-ce-sa-nu-faci-azi-id16517.html]{.underline}](https://www.antenasatelor.ro/lada-de-zestre/lada-de-zestre/traditii-datini-obiceiuri/10-superstitii-interdictii-si-credinte-populare-de-sfintii-imparati-constantin-si-elena-ce-sa-nu-faci-azi-id16517.html)' || '\n' ||
    '33. Superstiții de Sfinții Împărați Constantin și Elena. Ce nu e bine să faci pe 21 mai, accessed January 26, 2026, [[https://stirileprotv.ro/divers/superstitii-de-sfintii-imparati-constantin-si-elena-ce-nu-e-bine-sa-faci-pe-21-mai.html]{.underline}](https://stirileprotv.ro/divers/superstitii-de-sfintii-imparati-constantin-si-elena-ce-nu-e-bine-sa-faci-pe-21-mai.html)' || '\n' ||
    '34. Ce nume sunt sărbătorite de ziua Sfinților Constantin și Elena. Lista celor mai populare prenume care se serbează pe 21 mai | Digi24, accessed January 26, 2026, [[https://www.digi24.ro/stiri/actualitate/evenimente/ce-nume-sunt-sarbatorite-de-ziua-sfintilor-constantin-si-elena-lista-celor-mai-populare-prenume-care-se-serbeaza-pe-21-mai-3249175]{.underline}](https://www.digi24.ro/stiri/actualitate/evenimente/ce-nume-sunt-sarbatorite-de-ziua-sfintilor-constantin-si-elena-lista-celor-mai-populare-prenume-care-se-serbeaza-pe-21-mai-3249175)' || '\n' ||
    '35. Sfinții Constantin și Elena, sărbătoriți pe 21 mai. De ce e bine să ai bujori în casă astăzi, accessed January 26, 2026, [[https://stirileprotv.ro/stiri/actualitate/sfintii-constantin-si-elena-sarbatoriti-pe-21-mai-de-ce-e-bine-sa-ai-bujori-in-casa-astazi.html]{.underline}](https://stirileprotv.ro/stiri/actualitate/sfintii-constantin-si-elena-sarbatoriti-pe-21-mai-de-ce-e-bine-sa-ai-bujori-in-casa-astazi.html)' || '\n' ||
    '36. Sfinții Constantin și Elena - tradiții și obiceiuri. Cine sunt românii care își sărbătoresc ziua onomastică pe 21 mai | Digi24, accessed January 26, 2026, [[https://www.digi24.ro/stiri/sfintii-constantin-si-elena-traditii-si-obiceiuri-cine-sunt-romanii-care-isi-sarbatoresc-ziua-onomastica-pe-21-mai-2797539]{.underline}](https://www.digi24.ro/stiri/sfintii-constantin-si-elena-traditii-si-obiceiuri-cine-sunt-romanii-care-isi-sarbatoresc-ziua-onomastica-pe-21-mai-2797539)'
);
