INSERT INTO core_schema.saint_lives (name_ro, life_description_ro)
VALUES (
    'Sfinții 40 de Mucenici din Sevastia',
    '# Sfinții 40 de Mucenici din Sevastia: Monografie Teologică, Istorică și Antropologică' || '\n\n' ||
    '## Rezumat Executiv' || '\n\n' ||
    'Prezentul raport de cercetare constituie o analiză exhaustivă a fenomenului religios, istoric și cultural asociat Sfinților 40 de Mucenici din Sevastia. Documentul explorează profunzimea martiriului petrecut în anul 320 d.Hr., în contextul geopolitic al tranziției de la tetrarhie la monarhia constantiniană, și urmărește evoluția cultului acestor sfinți până în contemporaneitate. Analiza integrează date hagiografice, evidențe liturgice, inventarierea relicvelor prezente pe teritoriul României și o disecție antropologică a tradițiilor populare (agrar-rituale) care marchează data de 9 martie. Obiectivul este de a oferi o imagine holistică, care să depășească simpla narare a faptelor, investigând semnificațiile teologice de ordin secund și terțiar, precum și mecanismele de supraviețuire a riturilor pre-creștine sub umbrela calendarului ortodox.' || '\n\n' ||
    '## Partea I: Contextul Istoric și Geopolitic al Martiriului' || '\n\n' ||
    '### 1.1. Criza Imperiului și Persecuția lui Licinius' || '\n\n' ||
    'Martiriul celor 40 de soldați din Sevastia nu este un eveniment izolat, ci punctul culminant al unei crize politico-religioase majore care a divizat Imperiul Roman la începutul secolului al IV-lea. Deși Edictul de la Mediolanum (313 d.Hr.) garantase libertatea de cult creștinilor, pacea a fost efemeră. Împăratul Licinius (308--324), stăpânitorul părții de Răsărit a Imperiului, a intrat într-un conflict deschis cu cumnatul și rivalul său, Constantin cel Mare, care controla Apusul.^1^' || '\n\n' ||
    'În viziunea lui Licinius, creștinismul nu mai era doar o religie tolerată, ci devenise vectorul de influență politică al lui Constantin. Creștinii din armata sa erau percepuți ca potențiali trădători, o „coloană a cincea" loială împăratului creștin din Vest. Astfel, decretul prin care se cerea tuturor soldaților să sacrifice zeilor păgâni nu a fost doar un act de pietate păgână, ci un test de loialitate politică și militară.^2^ Refuzul sacrificiului echivala cu trădarea statului și lezmajestatea, crime pedepsite cu moartea.^4^' || '\n\n' ||
    '### 1.2. Legio XII Fulminata: Elita Militară și Identitatea Creștină' || '\n\n' ||
    'Cei 40 de Mucenici nu erau simpli recruți, ci soldați veterani, făcând parte din **Legio XII Fulminata** („Legiunea Fulgerului" sau „Legiunea Tunetului"), o unitate de elită cu o istorie glorioasă, staționată în acea perioadă la Melitene, în Armenia, pentru a apăra frontiera estică împotriva perșilor.^1^' || '\n\n' ||
    'Această legiune avea o legătură istorică specială cu creștinismul. Tradiția consemnează „miracolul ploii" din timpul lui Marcus Aurelius (cca. 172 d.Hr.), atribuit rugăciunilor soldaților creștini din această legiune, care a salvat armata romană de la pieire prin sete. Faptul că martiriul a avut loc în sânul acestei unități subliniază tensiunea dramatică: elita militară a imperiului, „bărbați tari și nebiruiți în războaie" ^6^, alege să se sacrifice nu pe câmpul de luptă, ci în arena credinței. Apartenența lor la diverse naționalități (romani, greci, armeni) ^1^ reflectă caracterul universal al bisericii primare și capacitatea credinței de a transcende barierele etnice într-o fraternitate spirituală superioară coeziunii de cohortă.' || '\n\n' ||
    '### 1.3. Cadrul Juridic și Procedural al Interogatoriului' || '\n\n' ||
    'Procesul sfinților s-a desfășurat în cetatea Sevastia (actualul Sivas, Turcia), sub autoritatea guvernatorului Agricola (reprezentantul puterii administrative) și a ducelui Lysias (reprezentantul puterii militare).^1^ Interogatoriul, așa cum este păstrat în actele martirice, relevă o ciocnire între două sisteme de valori ireconciliabile.' || '\n\n' ||
    'Agricola a încercat inițial tactica persuasiunii, oferind onoruri, avansări în grad și bogății materiale („mari daruri") în schimbul unui gest formal de apostazie.^2^ Refuzul colectiv, articulat de Chirion (Kyrion), a fost fundamentat pe o distincție clară a autorității: „Cum am luptat și am biruit pe vrăjmași pentru împăratul pământesc, tot așa vom lupta și pentru Împăratul ceresc".^1^ Această declarație plasează loialitatea față de Hristos deasupra jurământului militar (*sacramentum militare*), transformând refuzul lor într-un act subversiv care mina însăși fundamentele disciplinei romane.' || '\n\n' ||
    '## Partea a II-a: Hagiografia și Fenomenologia Martiriului' || '\n\n' ||
    '### 2.1. Etapele Torturii și Simbolismul Elementelor' || '\n\n' ||
    'Martiriul celor 40 a fost conceput ca o execuție lentă, menită să inducă teroare și să ofere posibilitatea retractării. După o primă încercare eșuată de lapidare, în care pietrele s-au întors miraculos împotriva aruncătorilor ^1^, și după o perioadă de întemnițare menită să le slăbească rezistența psihică ^3^, s-a decis condamnarea la moarte prin îngheț.' || '\n\n' ||
    'Alegerea lacului Sevastiei în toiul iernii armenești (renumită pentru asprimea ei) nu a fost întâmplătoare. Apa și frigul, elemente primordiale, au fost instrumentate ca agenți ai morții. Sfinții au fost dezbrăcați și introduși în lac la lăsarea nopții, când temperatura scădea drastic.^1^' || '\n\n' ||
    '### 2.2. Antiteza Lacul Înghețat -- Baia Caldă' || '\n\n' ||
    'Elementul central al dramei hagiografice este juxtapunerea dintre lacul înghețat și baia caldă construită ostentativ pe mal.^2^ Această baie reprezintă ispita supremă: salvarea imediată, confortul trupesc și viața biologică, accesibile prin simpla negare a credinței.' || '\n\n' ||
    'Tradiția consemnează că unul dintre cei 40, copleșit de durerea fizică a degerăturilor, a cedat. El a ieșit din lac și a alergat spre baie. Însă, șocul termic dintre gerul extrem și căldura băii i-a provocat moartea instantanee.^1^ Teologic, acest episod este interpretat ca pierderea dublă: a vieții pământești și a celei veșnice.' || '\n\n' ||
    '### 2.3. Metanoia lui Aglaie și Restaurarea Numărului 40' || '\n\n' ||
    'În contrast cu dezertorul, apare figura lui Aglaie (sau Aglaius), temnicerul sau gardianul însărcinat cu paza martirilor. În timpul nopții, în timp ce sfinții se rugau, Aglaie a avut o teofanie: a văzut o lumină supranaturală încălzind apa și 39 de cununi coborând din cer asupra capetelor martirilor. A 40-a cunună rămăsese suspendată, fără destinatar, din cauza celui care fugise.^1^' || '\n\n' ||
    'Înțelesul profund al acestei viziuni l-a determinat pe Aglaie la o convertire instantanee. Strigând „Și eu sunt creștin!", el s-a dezbrăcat de hainele și armele sale și a intrat în apa înghețată, ocupând locul gol și restaurând integritatea grupului sacru de 40.^1^' || '\n\n' ||
    '### 2.4. Desăvârșirea Jertfei: Meliton și Mama Sa' || '\n\n' ||
    'În dimineața următoare, supraviețuitorii au fost scoși din lac pentru a li se aplica lovitura de grație prin *crurifragium* (zdrobirea fluierele picioarelor cu ciocane).^5^' || '\n\n' ||
    'Un detaliu de o rară forță emoțională îl privește pe Meliton, cel mai tânăr dintre mucenici. Deoarece încă respira după tortură, torționarii nu l-au aruncat în carul care transporta cadavrele spre rug, sperând că tinerețea îl va face să se răzgândească. Mama sa, prezentă la fața locului, a intervenit decisiv. Departe de a-l sfătui să renunțe pentru a-și salva viața, ea l-a ridicat pe umeri și a alergat după carul cu trupurile sfinților, îmbărbătându-l să reziste până la capăt: „Fiule, puțin mai rabdă, ca să fii desăvârșit!". Meliton și-a dat sufletul pe umerii mamei sale, care l-a așezat apoi alături de camarazii săi.^10^' || '\n\n' ||
    '## Partea a III-a: Prosopografie și Identitate -- Cei 40 de Sfinți' || '\n\n' ||
    '### 3.1. Lista Canonică a Mucenicilor' || '\n\n' ||
    'Conform Sinaxarelor și surselor liturgice ^4^, numele celor 40 de sfinți sunt: Chirion (Kyrion), Candid, Domnus, Isihie, Iraclie (Heraclie), Smaragd, Evnichie, Valent (Valens), Vivian, Claudie, Prisc, Teodul, Eutihie, Ioan, Xantie, Ilian, Sisinie, Aghie (Aggias), Aetie, Flavie, Acachie, Ecdit (Ecdicius), Lisimah, Alexandru, Ilie, Gorgonie, Teofil, Dometian, Gaius, Leontie, Atanasie, Chiril, Sacerdon, Nicolae, Valeriu, Filoctemon, Severian, Cudion (Chudion), Meliton și Aglaie (Aglaius).' || '\n\n' ||
    '## Partea a IV-a: Cultul Relicvelor -- Prezența Sfinților în România' || '\n\n' ||
    'Prezența fragmentelor din moaștele Sfinților 40 de Mucenici în România este remarcabilă prin densitate, Bucureștiul devenind un veritabil centru de pelerinaj în ziua de 9 martie.' || '\n\n' ||
    '### 4.1. Mănăstirea Antim: Epicentrul Pelerinajului' || '\n\n' ||
    'Cel mai important loc de venerare din capitală este **Mănăstirea Antim**. Aici se păstrează o raclă de argint care conține fragmente din oasele mucenicilor.' || '\n\n' ||
    '- **Istoric:** Aceste moaște au fost dăruite mănăstirii în anul **1883** de către Patriarhul Nicodim al Ierusalimului.^13^' || '\n' ||
    '- **Ritual:** În fiecare an, pe 9 martie, are loc o **procesiune solemnă** în jurul bisericii mari.^13^' || '\n\n' ||
    '### 4.2. Geografia Sacră a Moaștelor în România' || '\n\n' ||
    '| **Lăcaș de Cult** | **Localitate** | **Detalii Despre Moaște și Cult** | **Sursă** |' || '\n' ||
    '| :--- | :--- | :--- | :--- |' || '\n' ||
    '| **Mănăstirea Mihai Vodă** | București | Păstrează fragmente venerate de bucureșteni. | ^12^ |' || '\n' ||
    '| **Schitul Darvari** | București | Oază de liniște în centrul orașului, deține părți din moaște. | ^12^ |' || '\n' ||
    '| **Biserica Icoanei** | București | Important centru de pelerinaj, deține moaște în raclă. | ^16^ |' || '\n' ||
    '| **Biserica Dichiu** | București | Situată pe strada Icoanei, are hram și relicve. | ^12^ |' || '\n' ||
    '| **Biserica Sfântul Alexie** | București | Pe Calea Șerban Vodă, deține părticele sfinte. | ^12^ |' || '\n' ||
    '| **Mănăstirea Sâmbăta de Sus** | Brașov | Deține o casetă cu părți din moaște (zona Făgăraș). | ^19^ |' || '\n' ||
    '| **Mănăstirea Tismana** | Gorj | Unul dintre cele mai vechi așezăminte, deține relicve. | ^19^ |' || '\n' ||
    '| **Mănăstirea Polovragi** | Gorj | Deține moaște, fiind centru de pelerinaj în Oltenia. | ^19^ |' || '\n' ||
    '| **Mănăstirea Hurezi (Horezu)** | Vâlcea | Patrimoniu UNESCO, păstrează sfintele moaște. | ^19^ |' || '\n\n' ||
    '## Partea a V-a: Dimensiunea Teologică și Liturgică' || '\n\n' ||
    '**Troparul (Glas 1):** „Pentru durerile sfinților, care pentru Tine au pătimit, fii milostiv, Doamne, și toate durerile noastre le vindecă...".^20^' || '\n\n' ||
    '**Iconografia:** Sfinții sunt pictați stând în lac, seminuzi, tremurând. Deasupra lor, Hristos apare în slavă, trimițând cele 40 de cununi. Baia caldă este reprezentată lateral ca loc al ispitei și morții apostatului.^5,24^' || '\n\n' ||
    '## Partea a VI-a: Antropologie Agrară și Tradiții Populare -- „Mucenicii"' || '\n\n' ||
    'Sărbătoarea de pe 9 martie marchează debutul anului agricol.^10^' || '\n\n' ||
    '### 6.1. Simbolismul Alimentar: De la Trup la Grâu' || '\n\n' ||
    'Ritualul central este prepararea „mucenicilor" (sfințișori sau bradoși). Există o dicotomie regională:' || '\n\n' ||
    '1.  **Tradiția Moldovenească (Sfințișori):** Cozonac dospit în forma cifrei 8 (infinitul), uns cu miere și nucă (dulceața Raiului).^26^' || '\n' ||
    '2.  **Tradiția Muntenească și Dobrogeană (Mucenici fierți):** Figurine mici din aluat fierte în zeamă îndulcită (simbolizând Lacul Sevastiei).^10^' || '\n\n' ||
    '### 6.2. Ritualul Vitalității: Cele 40 (44) de Pahare' || '\n\n' ||
    'Tradiția impune consumul a 40 de pahare de vin, crezându-se că acesta se transformă în sânge proaspăt și putere de muncă.^10,11^' || '\n\n' ||
    '### 6.3. Focurile de Măcinici și Purificarea' || '\n\n' ||
    'Se aprind focuri în curți pentru a alunga gerul („Bătrâna iarnă"). Cenușa este presărată în jurul casei pentru protecție împotriva șerpilor și insectelor.^11^' || '\n\n' ||
    '## Concluzii' || '\n\n' ||
    'Martiriul Sfinților 40 de Mucenici rămâne un pilon al identității ortodoxe românești, unind eroismul militar al legiunilor romane cu rezistența spirituală a creștinismului primar și cu riturile agrare de regenerare a vieții.' || '\n\n' ||
    '#### Works cited' || '\n\n' ||
    '1. Viața Sfinților 40 de Mucenici | Doxologia, accessed January 25, 2026, [[https://doxologia.ro/viata-sfintilor-40-de-mucenici]{.underline}](https://doxologia.ro/viata-sfintilor-40-de-mucenici)' || '\n' ||
    '2. Sfinții 40 de Mucenici din Sevastia - O Chilie Athonită: Bucurii din Sfântul Munte, accessed January 25, 2026, [[https://www.chilieathonita.ro/2025/07/09/sfintii-40-de-mucenici-din-sevastia/]{.underline}](https://www.chilieathonita.ro/2025/07/09/sfintii-40-de-mucenici-din-sevastia/)' || '\n' ||
    '3. DOCUMENTAR: Sfinţii 40 de Mucenici din Sevastia - Rador Radio România, accessed January 25, 2026, [[https://www.rador.ro/2016/03/09/documentar-sfintii-40-de-mucenici-din-sevastia-2/]{.underline}](https://www.rador.ro/2016/03/09/documentar-sfintii-40-de-mucenici-din-sevastia-2/)' || '\n' ||
    '4. Sfinții 40 de Mucenici -- Cuvântul Înaltpreasfințitului Părinte Calinic, accessed January 25, 2026, [[https://www.arhiepiscopiasucevei.ro/sfintii-40-de-mucenici-cuvantul-inaltpreasfintitului-parinte-calinic-2/]{.underline}](https://www.arhiepiscopiasucevei.ro/sfintii-40-de-mucenici-cuvantul-inaltpreasfintitului-parinte-calinic-2/)' || '\n' ||
    '5. Sfinții 40 de mucenici din Sevastia - OrthodoxWiki, accessed January 25, 2026, [[https://ro.orthodoxwiki.org/Sfin%C8%9Bii_40_de_mucenici_din_Sevastia]{.underline}](https://ro.orthodoxwiki.org/Sfin%C8%9Bii_40_de_mucenici_din_Sevastia)' || '\n' ||
    '6. Viața sfinților 40 de Mucenici din Sevastia - Doxologia, accessed January 25, 2026, [[https://doxologia.ro/viata-sfintilor-40-de-mucenici-din-sevastia-0]{.underline}](https://doxologia.ro/viata-sfintilor-40-de-mucenici-din-sevastia-0)' || '\n' ||
    '7. Acatistul Sfinților 40 de Mucenici - Doxologia, accessed January 25, 2026, [[https://doxologia.ro/acatistul-sfintilor-40-de-mucenici]{.underline}](https://doxologia.ro/acatistul-sfintilor-40-de-mucenici)' || '\n' ||
    '8. Sfinții 40 de Mucenici din Sevastia | Doxologia, accessed January 25, 2026, [[https://doxologia.ro/sfintii-imparati-constantin-elena-drumul-spre-sfintenie]{.underline}](https://doxologia.ro/sfintii-imparati-constantin-elena-drumul-spre-sfintenie)' || '\n' ||
    '9. Sfintii 40 de Mucenici CrestinOrtodox.ro, accessed January 25, 2026, [[https://www.crestinortodox.ro/religie/sfintii-40-mucenici-87984.html]{.underline}](https://www.crestinortodox.ro/religie/sfintii-40-mucenici-87984.html)' || '\n' ||
    '10. Sfinții 40 de Mucenici din 9 martie 2025. Ziua cu cele mai multe tradiții populare. Obiceiul celor 44 de pahare de vin | Digi24, accessed January 25, 2026, [[https://www.digi24.ro/stiri/actualitate/evenimente/sfintii-40-de-mucenici-din-9-martie-2025-ziua-with-cele-mai-multe-traditii-populare-obiceiul-celor-44-de-pahare-de-vin-3144307]{.underline}](https://www.digi24.ro/stiri/actualitate/evenimente/sfintii-40-de-mucenici-din-9-martie-2025-ziua-with-cele-mai-multe-traditii-populare-obiceiul-celor-44-de-pahare-de-vin-3144307)' || '\n' ||
    '11. Sfintii 40 de Mucenici, traditii si obiceiuri. De ce barbatii trebuie sa ..., accessed January 25, 2026, [[https://stirileprotv.ro/stiri/social/sfintii-40-de-mucenici-traditii-si-obiceiuri-de-ce-barbatii-trebuie-sa-bea-40-de-pahare-de-vin.html]{.underline}](https://stirileprotv.ro/stiri/social/sfintii-40-de-mucenici-traditii-si-obiceiuri-de-ce-barbatii-trebuie-sa-bea-40-de-pahare-de-vin.html)' || '\n' ||
    '12. DOCUMENTAR: Sfinţii 40 de Mucenici din Sevastia - Rador Radio România, accessed January 25, 2026, [[https://www.rador.ro/2024/03/09/documentar-sfintii-40-de-mucenici-din-sevastia-8/]{.underline}](https://www.rador.ro/2024/03/09/documentar-sfintii-40-de-mucenici-din-sevastia-8/)' || '\n' ||
    '13. Procesiune cu moaștele Sfinților 40 de Mucenici, la Mănăstirea Antim - Doxologia, accessed January 25, 2026, [[https://doxologia.ro/procesiune-cu-moastele-sfintilor-40-de-mucenici-la-manastirea-antim]{.underline}](https://doxologia.ro/procesiune-cu-moastele-sfintilor-40-de-mucenici-la-manastirea-antim)' || '\n' ||
    '14. Procesiune cu moaștele Sfinților 40 de Mucenici la Mănăstirea Antim -- 2024 | În imagini, accessed January 25, 2026, [[https://basilica.ro/procesiune-cu-moastele-sfintilor-40-de-mucenici-la-manastirea-antim-2024-in-imagini/]{.underline}](https://basilica.ro/procesiune-cu-moastele-sfintilor-40-de-mucenici-la-manastirea-antim-2024-in-imagini/)' || '\n' ||
    '15. Sfinţii 40 de Mucenici din Sevastia, ocrotitori ai Mănăstirii Antim - Ziarul Lumina, accessed January 25, 2026, [[https://ziarullumina.ro/societate/reportaj/sfintii-40-de-mucenici-din-sevastia-ocrotitori-ai-manastirii-antim-196130.html]{.underline}](https://ziarullumina.ro/societate/reportaj/sfintii-40-de-mucenici-din-sevastia-ocrotitori-ai-manastirii-antim-196130.html)' || '\n' ||
    '16. Calendar Cu Sfintele Moaste Din Bucuresti | PDF - Scribd, accessed January 25, 2026, [[https://ro.scribd.com/doc/45802095/Calendar-Cu-Sfintele-Moaste-Din-Bucuresti]{.underline}](https://ro.scribd.com/doc/45802095/Calendar-Cu-Sfintele-Moaste-Din-Bucuresti)' || '\n' ||
    '17. Calendar al Sfintilor cu Moaste in Bucuresti CrestinOrtodox.ro, accessed January 25, 2026, [[https://www.crestinortodox.ro/pelerinaje/calendar-sfintilor-moaste-bucuresti-120001.html]{.underline}](https://www.crestinortodox.ro/pelerinaje/calendar-sfintilor-moaste-bucuresti-120001.html)' || '\n' ||
    '18. Sfinţii 40 de Mucenici din Sevastia Armeniei - Rucodelia, accessed January 25, 2026, [[https://rucodelia.ro/sfintii-40-de-mucenici-din-sevastia-armeniei/]{.underline}](https://rucodelia.ro/sfintii-40-de-mucenici-din-sevastia-armeniei/)' || '\n' ||
    '19. Lista celor mai importante moaşte - storage1.dms.mpinteractiv.ro, accessed January 25, 2026, [[http://storage0.dms.mpinteractiv.ro/media/1/186/3927/12250768/3/lista-celor-mai-importante-moaste.pdf]{.underline}](http://storage0.dms.mpinteractiv.ro/media/1/186/3927/12250768/3/lista-celor-mai-importante-moaste.pdf)' || '\n' ||
    '20. Acatistul Sfintilor 40 de Mucenici CrestinOrtodox.ro, accessed January 25, 2026, [[https://www.crestinortodox.ro/acatiste/acatistul-sfintilor-40-mucenici-67145.html]{.underline}](https://www.crestinortodox.ro/acatiste/acatistul-sfintilor-40-mucenici-67145.html)' || '\n' ||
    '21. Canon de rugăciune către Sfinţii 40 de Mucenici din Sevastia (1) - Doxologia, accessed January 25, 2026, [[https://doxologia.ro/canon-de-rugaciune-catre-sfintii-40-de-mucenici-din-sevastia-1]{.underline}](https://doxologia.ro/canon-de-rugaciune-catre-sfintii-40-de-mucenici-din-sevastia-1)' || '\n' ||
    '22. Condacul Sfinţilor 40 de Mucenici din Sevastia - Doxologia, accessed January 25, 2026, [[https://doxologia.ro/condacul-sfintilor-40-de-mucenici-din-sevastia]{.underline}](https://doxologia.ro/condacul-sfintilor-40-de-mucenici-din-sevastia)' || '\n' ||
    '23. Canon de rugăciune către Sfinţii 40 de Mucenici din Sevastia (2) - Doxologia, accessed January 25, 2026, [[https://doxologia.ro/canon-de-rugaciune-catre-sfintii-40-de-mucenici-din-sevastia-2]{.underline}](https://doxologia.ro/canon-de-rugaciune-catre-sfintii-40-de-mucenici-din-sevastia-2)' || '\n' ||
    '24. Erminia picturii bizantine a ieromonahului Dionisie din Furna - Doxologia, accessed January 25, 2026, [[https://doxologia.ro/erminia-picturii-bizantine-ieromonahului-dionisie-din-furna]{.underline}](https://doxologia.ro/erminia-picturii-bizantine-ieromonahului-dionisie-din-furna)' || '\n' ||
    '25. Erminia Picturii Bizantine | PDF - Scribd, accessed January 25, 2026, [[https://ro.scribd.com/doc/219035597/ErminiaPicturiiBizantine]{.underline}](https://ro.scribd.com/doc/219035597/ErminiaPicturiiBizantine)' || '\n' ||
    '26. Închinăm 40 de pahare sau ne rugăm Sfinților 40 de Mucenici? - Doxologia, accessed January 25, 2026, [[https://doxologia.ro/inchinam-40-de-pahare-ne-rugam-sfintilor-40-de-mucenici]{.underline}](https://doxologia.ro/inchinam-40-de-pahare-ne-rugam-sfintilor-40-de-mucenici)'
);
