INSERT INTO core_schema.saint_lives (name_ro, life_description_ro)
VALUES (
    'Sfinții Mucenici Chir și Ioan',
    '# Tratat Hagiografic și Eclesiologic: Sfinții Mucenici și Doctori fără de Arginți Chir și Ioan -- Paradigma Vindecării Teandrice în Istoria Bisericii' || '\n\n' ||
    '## 1. Introducere: Medicina Creștină și Contextul Alexandrin al Antichității Târzii' || '\n\n' ||
    'În istoria bimilenară a Bisericii Creștine, figura sfântului vindecător ocupă un loc central, reprezentând punctul de convergență dintre doctrina Întrupării și practica filantropiei sociale. Dintre numeroasele categorii de sfințenie, cea a „Doctorilor fără de arginți" (*Anargyroi*) se distinge printr-o radicalitate a dăruirii care contestă normele economice și sociale ale antichității. Sfinții Mucenici Chir și Ioan, prăznuiți liturgic la 31 ianuarie (martiriul) și 28 iunie (aflarea moaștelor), constituie unul dintre cele mai complexe studii de caz din hagiografia primelor secole. Viața și cultul lor nu sunt doar repere de evlavie, ci documente istorice vii care atestă tranziția de la medicina galenică și cultele taumaturgice păgâne (precum cel al lui Isis Medica) la terapeutica creștină, centrată pe Hristos ca *Iatros* suprem.' || '\n\n' ||
    'Prezenta cercetare își propune să exploreze exhaustiv dimensiunile istorice, teologice și liturgice ale acestor sfinți. Vom analiza parcursul lor biografic din cosmopolita Alexandrie până în asprimea deșertului arabic, martiriul suferit în timpul Marii Persecuții dioclețiene, precum și fenomenologia miracolului, așa cum a fost ea consemnată de patriarhul Sofronie al Ierusalimului. De asemenea, vom urmări traseul relicvelor sacre, de la Menouthis la Munchen și București, evidențiind continuitatea puterii tămăduitoare prin secole.' || '\n\n' ||
    '### 1.1 Contextul Istoric și Intelectual al Alexandriei' || '\n\n' ||
    'Pentru a înțelege formarea Sfântului Chir, este imperios necesar să plasăm biografia sa în contextul Alexandriei secolului al III-lea. Acest oraș nu era doar grânarul imperiului, ci și „creierul" acestuia. Școala medicală din Alexandria, moștenitoare a tradițiilor elenistice, era locul unde disecția și studiul anatomiei atinseseră culmi neegalate. Totuși, medicina vremii era adesea un amestec de empirism științific și fatalism magic. Într-un astfel de mediu, apariția unui medic creștin care refuza onorariile și integra rugăciunea în actul medical a reprezentat o revoluție paradigmatică.^1^' || '\n\n' ||
    '## 2. Hagiografia Canonică: Biografii Spirituale și Intersecții Destinale' || '\n\n' ||
    'Viețile Sfinților Chir și Ioan, deși convergente în martiriu, pornesc din puncte geografice și profesionale distincte, ilustrând universalitatea chemării la sfințenie.' || '\n\n' ||
    '### 2.1 Sfântul Chir: Medicul Alexandrin și Terapeutica Harului' || '\n\n' ||
    'Sfântul Chir (Kyros) s-a născut în Alexandria Egiptului, într-o perioadă de înflorire intelectuală, dar și de tensiune religioasă. Sursele hagiografice menționează apartenența sa la o familie creștină și o educație aleasă, care i-a permis accesul la elita medicală a vremii.^2^ Devenind un medic renumit, Chir a operat o distincție fundamentală față de colegii săi păgâni: el a refuzat monetizarea suferinței umane.' || '\n\n' ||
    '#### Metodologia „Anargyroi"' || '\n\n' ||
    'Termenul *Anargyroi* (fără arginți) nu descrie doar o gratuitate financiară, ci o libertate duhovnicească. Chir trata bolnavii nu doar cu ierburi și proceduri hipocratice, ci, fundamental, prin cuvânt și rugăciune. El a înțeles, anticipând medicina psihosomatică modernă, legătura intrinsecă dintre boala sufletului (păcatul) și boala trupului.' || '\n\n' ||
    '- **Diagnosticul Spiritual:** Sfântul Chir obișnuia să le spună pacienților săi că „boala sufletului este mai grea decât toate bolile trupului". El folosea scripturile profeților și apostolilor ca instrumente terapeutice, înlocuind aforismele lui Galen cu versetele biblice.^1^' || '\n' ||
    '- **Evanghelizare prin Medicină:** Cabinetul său a devenit un centru misionar. Mulți elini (păgâni), atrași de reputația sa medicală și de gratuitatea tratamentului, au descoperit prin el credința creștină. Vindecarea trupului devenea astfel doar preludiul vindecării ontologice prin Botez.^3^' || '\n\n' ||
    '#### Retragerea în Arabia' || '\n\n' ||
    'Odată cu izbucnirea persecuției sub Dioclețian (cca. 303 d.Hr.), Chir a fost denunțat prefectului Alexandriei. Decizia sa de a fugi în Arabia nu a fost un act de lașitate, ci unul de prudență evanghelică și strategie spirituală. Retrăgându-se în deșert, lângă Golful Persic, el a schimbat halatul de medic cu haina monahală. În solitudinea ascezei, darul său taumaturgic s-a purificat și intensificat: dacă în oraș folosea medicamente, în pustiu vindeca exclusiv prin rugăciune și semnul crucii.^4^ Această etapă marchează trecerea de la medicina naturală la cea supranaturală.' || '\n\n' ||
    '### 2.2 Sfântul Ioan: De la *Militia Saecularis* la *Militia Christi*' || '\n\n' ||
    'Sfântul Ioan era originar din Edesa, Mesopotamia, un oraș cu o cultură siriacă profundă și o tradiție creștină timpurie. Profesia sa a fost aceea de soldat în armata romană, o poziție care îi conferea statut și stabilitate materială. Totuși, conștiința sa creștină a intrat în conflict cu cerințele cultului imperial și cu brutalitatea vieții militare.^3^' || '\n\n' ||
    'Auzind de faima lui Chir, Ioan a abandonat cariera militară, averea și patria, pornind într-un pelerinaj inițiatic. După o oprire la Ierusalim, a ajuns în Alexandria și, neîntâlnindu-l pe Chir, a urmat urmele acestuia până în Arabia. Întâlnirea lor a fost providențială: Ioan a devenit ucenicul devotat al lui Chir, formforming un „duet" terapeutic. Dacă Chir era maestrul și inițiatorul, Ioan era „mâna dreaptă", ucenicul care, prin ascultare și imitare, a dobândit el însuși harisma vindecării.^5^' || '\n\n' ||
    '### 2.3 Tabel Comparativ: Profilurile Sfinților' || '\n\n' ||
    '| **Caracteristică** | **Sfântul Chir** | **Sfântul Ioan** |' || '\n' ||
    '| :--- | :--- | :--- |' || '\n' ||
    '| **Origine** | Alexandria, Egipt | Edesa, Mesopotamia |' || '\n' ||
    '| **Profesie Inițială** | Medic (Civil/Intelectual) | Soldat (Militar/Administrație) |' || '\n' ||
    '| **Tipul Convertirii** | Continuitate (Medicină -> Vindecare sacră) | Ruptură radicală (Armată -> Monahism) |' || '\n' ||
    '| **Locul Ascezei** | Pustiul Arabiei (lângă Golful Persic) | Pustiul Arabiei (alături de Chir) |' || '\n' ||
    '| **Atribute Iconografice** | Haine monahale/preoțești, cutie medicamente | Haine militare/laice sau de martir, cruce |' || '\n\n' ||
    '## 3. Martiriul de la Canopus: O Pedagogie a Suferinței' || '\n\n' ||
    'Momentul culminant al vieții lor pământești s-a consumat în cetatea Canopus, situată la aproximativ 12 stadii (cca. 2 km) de Alexandria. Acest episod subliniază dimensiunea comunitară a sfințeniei lor: ei nu au murit doar pentru propria credință, ci pentru a susține credința altora.' || '\n\n' ||
    '### 3.1 Cazul Atanasia și Fiicele Sale' || '\n\n' ||
    'Vestea arestării unei femei creștine, Atanasia, împreună cu cele trei fiice ale sale -- Teodota (15 ani), Teoctista (13 ani) și Eudoxia (11 ani) -- a ajuns până în pustia Arabiei. Sfinții Chir și Ioan au conștientizat riscul apostaziei: tortura romană era concepută să înfrângă voința, iar fragilitatea vârstei adolescentine a fiicelor, combinată cu instinctul matern al Atanasiei, putea duce la lepădarea de Hristos.^3^' || '\n\n' ||
    'Deplasându-se la Canopus, cei doi sfinți au intrat în temniță (sau au stat în apropierea locului de judecată), îmbărbătându-le pe femei. Gestul lor a fost rapid observat și raportat guvernatorului Syrianus. Acesta, înfuriat de intervenția lor, a dispus arestarea imediată a celor doi „străini".' || '\n\n' ||
    '### 3.2 Anatomia Torturii și Execuția' || '\n\n' ||
    'Procesul verbal al martiriului descrie o gradație a violenței menită să ofere un spectacol terifiant, atât pentru victime, cât și pentru spectatori.' || '\n\n' ||
    '1.  **Flagelarea:** Bătăi repetate cu bice și toiege pentru a slăbi rezistența fizică.' || '\n' ||
    '2.  **Tortura Termică și Chimică:** Arderea rănilor deschise cu făclii, urmată de turnarea unor substanțe iritante (oțet și sare) pentru a maximiza durerea neuropată.' || '\n' ||
    '3.  **Smoala Clocotită:** O pedeapsă extremă, turnarea de smoală fierbinte, menită să provoace arsuri profunde și asfixiere.^1^' || '\n\n' ||
    'În ciuda acestor atrocități, Chir și Ioan au rămas impasibili, refuzând să sacrifice idolilor. Mai mult, prezența lor stoică a funcționat ca un „scut duhovnicesc" pentru Atanasia și fiicele sale. Văzând curajul bărbaților, femeile au primit moartea prin sabie cu demnitate, fără a ceda. Ulterior, la data de **31 Ianuarie** (anul 292 sau 311 d.Hr.), Chir și Ioan au fost decapitați în același loc. Trupurile lor au fost recuperate în secret de creștini și depuse inițial în Biserica Sfântului Evanghelist Marcu din Alexandria.^4^' || '\n\n' ||
    '## 4. Translația Moaștelor și Lupta cu Păgânismul Rezidual: Cazul Menouthis' || '\n\n' ||
    'Istoria post-mortem a sfinților este la fel de dinamică precum viața lor. La începutul secolului al V-lea, cultul lor a devenit o armă strategică în mâinile Bisericii Alexandrine pentru creștinarea completă a Egiptului.' || '\n\n' ||
    '### 4.1 De la Isis Medica la „Doctorii cei Mari"' || '\n\n' ||
    'Localitatea Menouthis (actualul Abu Qir) era centrul unui cult persistent dedicat zeiței Isis, venerată ca vindecătoare. Practica centrală era *incubația*: bolnavii dormeau în templu sperând să primească vise revelatorii sau vindecare directă de la zeiță. Această zonă rămăsese un bastion al demonolatriei, rezistând evanghelizării.^6^' || '\n\n' ||
    'Patriarhul Teofil al Alexandriei a încercat să distrugă templul, dar cultul a supraviețuit clandestin sau sincretic. Succesorul său, Sfântul Chiril al Alexandriei (412-444 d.Hr.), a primit o revelație divină de a muta moaștele Sfinților Chir și Ioan de la Alexandria la Menouthis. **Translația Moaștelor (28 Iunie):** Mutarea relicvelor a avut un efect imediat. Prezența sfinților a „curățat" locul de duhurile necurate asociate cultului păgân. Creștinii au început să vină la mormântul mucenicilor pentru vindecare, replicând practica incubației, dar într-un context hristocentric. Astfel, sanctuarul lui Isis a fost înlocuit funcțional și spiritual de Biserica Sfinților Chir și Ioan.^2^' || '\n\n' ||
    '## 5. Fenomenologia Miracolului: Mărturia Sfântului Sofronie al Ierusalimului' || '\n\n' ||
    'Cea mai importantă sursă documentară despre minunile săvârșite la Menouthis este lucrarea *Thaumata* (Minunile), redactată de Sfântul Sofronie, Patriarhul Ierusalimului (634-638 d.Hr.). Sofronie nu a fost doar un cronicar, ci un beneficiar direct al harului sfinților.' || '\n\n' ||
    '### 5.1 Sofronie: Pacient și Teolog' || '\n\n' ||
    'În jurul anului 610 d.Hr., Sofronie, suferind de o afecțiune oculară gravă (oftalmie) care amenința să-l orbiască, a venit în pelerinaj la Menouthis. Aici, el a fost vindecat în urma rugăciunilor și a incubației în biserică. În semn de recunoștință, a compus o culegere de 70 de minuni, descriind cazuri clinice și intervenții supranaturale.^8^' || '\n\n' ||
    '**Perspectiva Teologică:** Cercetătorii moderni ^6^ subliniază că lucrarea lui Sofronie are și o miză polemică. Într-o epocă marcată de controversa monoenergistă, Sofronie folosește minunile sfinților pentru a demonstra ortodoxia credinței calcedoniene. Vindecările sunt prezentate ca acte de putere divină mediate de sfinți care mărturisesc dreapta credință.' || '\n\n' ||
    '### 5.2 Studii de Caz din *Thaumata*' || '\n\n' ||
    '#### Cazul Isidoros și Lămâia' || '\n\n' ||
    'Unul dintre cele mai plastice exemple este cel al lui Isidoros, care suferea de o boală pulmonară severă. Isidoros a avut o viziune în care sfinții i-au apărut și i-au poruncit să mănânce o lămâie întreagă. Deși părea absurd medical, Isidoros a ascultat. Ingestia lămâii i-a provocat o criză emetică violentă, în urma căreia a vomitat un vierme care îi devora plămânii. Acest caz ilustrează puterea sfinților de a folosi remedii naturale în moduri paradoxale.^9^' || '\n\n' ||
    '#### Cazul Photeinos și Fatalitatea' || '\n\n' ||
    'Photeinos, un aristocrat orb, era adeptul doctrinei fatalității (*heimarmene*). Vindecarea sa fizică a fost condiționată de vindecarea teologică. Sfinții i-au cerut să renunțe la această erezie. Doar după ce Photeinos a abjurat fatalismul și a mărturisit providența divină, vederea i-a fost restaurată. Acest caz subliniază legătura indisolubilă dintre ortodoxie (dreapta slăvire) și sănătate.^10^' || '\n\n' ||
    '## 6. Diseminarea Cultului: De la Răsărit la Apus și în Țările Române' || '\n\n' ||
    'După cucerirea arabă a Egiptului (sec. VII), moaștele au fost mutate pentru a fi salvate.' || '\n\n' ||
    '### 6.1 Roma și Munchen: Un Traseu European' || '\n\n' ||
    'Relicvele lor au ajuns la Roma, iar ulterior, părți importante au fost duse la Munchen. În **Residenz München** (Palatul Regal), Ducele Maximilian I a construit *Reiche Kapelle* (Capela Bogată), sfințită în 1607, unde a depus relicvele sfinților în racle prețioase.^11^' || '\n\n' ||
    '### 6.2 Prezența Sfinților în România' || '\n\n' ||
    '- **Spitalul Universitar de Urgență București (SUUB):** În curtea acestui spital funcționează o biserică de lemn sfințită în 2002, cu hramul Sfinților Chir și Ioan. Activitatea pastorală începută în 1993 a transformat acest loc într-un centru de pelerinaj pentru bolnavi.^13^' || '\n' ||
    '- **Mănăstirea Cernica:** Păstrează o tradiție puternică a vindecării, integrând în patrimoniul său spiritual și cinstirea sfinților doctori, prin părticele de moaște.^16^' || '\n\n' ||
    '## 7. Analiză Liturgică și Teologică: Acatistul Sfinților' || '\n\n' ||
    '### 7.1 Teme Majore în Acatist' || '\n\n' ||
    '#### Superioritatea Harului' || '\n\n' ||
    'Sfântul Chir este lăudat pentru că a depășit învățăturile lui Hipocrate și Galen, accesând o cunoaștere divină: *„Bucură-te, cel ce nu de la Galin și Hipocrate, ci de la Hristos ai învățat tămăduirea..."*.^1^' || '\n\n' ||
    '#### Gratuitatea ca Mărturisire (Anargyria)' || '\n\n' ||
    'Repetarea epitetului „fără de arginți" subliniază că sănătatea este un dar. Refuzul plății este un act de protest împotriva lăcomiei lumii și o afirmare a providenței divine.^17^' || '\n\n' ||
    '### 7.2 Structura Acatistului (Sinteză)' || '\n\n' ||
    '- **Condacul 1:** Invocarea lor ca „doctori iscusiți".' || '\n' ||
    '- **Icosul 2:** Activitatea medicală a lui Chir în Alexandria.' || '\n' ||
    '- **Icosul 3 & 5:** Convertirea lui Ioan.' || '\n' ||
    '- **Condacul 6:** Minunile săvârșite în pustiu.' || '\n' ||
    '- **Condacul 13:** Rugăciunea finală pentru cei bolnavi.^17^' || '\n\n' ||
    '## 8. Iconografie și Simbolism' || '\n\n' ||
    '### 8.1 Atribute Distinctive' || '\n\n' ||
    '- **Sfântul Chir:** Veșminte monahale, uneori epitrahil. Ține **cutia cu medicamente** și **lingurița** (*cochlear*).^18^' || '\n' ||
    '- **Sfântul Ioan:** Haine militare sau nobiliare, ținând de asemenea instrumentarul medical.^18^' || '\n\n' ||
    '## 9. Concluzii: Sfinții Chir și Ioan în Modernitate' || '\n\n' ||
    '1.  **Bioetică:** Medicul este un slujitor al vieții, nu un stăpân al ei.' || '\n' ||
    '2.  **Comunitate:** Prietenia duhovnicească dintre Chir și Ioan este un model de colaborare pe calea sfințeniei.' || '\n' ||
    '3.  **Speranță:** Minunile lor oferă speranță acolo unde medicina își atinge limitele.' || '\n\n' ||
    '#### Works cited' || '\n\n' ||
    '1. Sfinții Mucenici Chir și Ioan și Atanasia cu fiicele ei... accessed January 21, 2026, [[https://e-religie.ro/sinaxar/ianuarie/sinaxar-ziua-31-luna-1/]{.underline}](https://e-religie.ro/sinaxar/ianuarie/sinaxar-ziua-31-luna-1/)' || '\n' ||
    '2. Chir și Ioan - OrthodoxWiki, accessed January 21, 2026, [[https://ro.orthodoxwiki.org/Chir_%C8%99i_Ioan]{.underline}](https://ro.orthodoxwiki.org/Chir_%C8%99i_Ioan)' || '\n' ||
    '3. Chir și Ioan, sfinții doctori fără de arginți - Doxologia, accessed January 21, 2026, [[https://doxologia.ro/chir-ioan-sfintii-doctori-fara-de-arginti]{.underline}](https://doxologia.ro/chir-ioan-sfintii-doctori-fara-de-arginti)' || '\n' ||
    '4. Sfintii Chir si Ioan CrestinOrtodox.ro, accessed January 21, 2026, [[https://www.crestinortodox.ro/calendar-ortodox/sfintii-chir-ioan-99009.html]{.underline}](https://www.crestinortodox.ro/calendar-ortodox/sfintii-chir-ioan-99009.html)' || '\n' ||
    '5. Aducerea moaștelor Sfinţilor Mucenici doctori fără de arginți Chir și Ioan (Secolul al V-lea), accessed January 21, 2026, [[https://www.unitischimbam.ro/aducerea-moastelor-sf-mc-doctori-fara-de-arginti-chir-si-ioan/]{.underline}](https://www.unitischimbam.ro/aducerea-moastelor-sf-mc-doctori-fara-de-arginti-chir-si-ioan/)' || '\n' ||
    '6. The miracles of Saints Cyrus and John: The Greek text and its transmission, accessed January 21, 2026, [[https://researchers.mq.edu.au/en/publications/the-miracles-of-saints-cyrus-and-john-the-greek-text-and-its-tran/]{.underline}](https://researchers.mq.edu.au/en/publications/the-miracles-of-saints-cyrus-and-john-the-greek-text-and-its-tran/)' || '\n' ||
    '7. pilgrimage to the shrine of ss cyrus and john at menouthis in late antiquity - Brill, accessed January 21, 2026, [[https://brill.com/downloadpdf/book/edcoll/9789004298064/B9789004298064-s006.pdf]{.underline}](https://brill.com/downloadpdf/book/edcoll/9789004298064/B9789004298064-s006.pdf)' || '\n' ||
    '8. The Holy Martyrs Cyrus and John in the "Life of Saint John the Merciful", accessed January 21, 2026, [[https://www.johnsanidopoulos.com/2020/01/the-holy-martyrs-cyrus-and-john-in-life.html]{.underline}](https://www.johnsanidopoulos.com/2020/01/the-holy-martyrs-cyrus-and-john-in-life.html)' || '\n' ||
    '9. Sophronius of Jerusalem, in his Miracles of the Saints Cyrus and John, recounts how *Kyros and Ioannes healed a certain Isidoros... - figshare, accessed January 21, 2026, [[https://figshare.com/articles/online_resource/E06037_Sophronius_of_Jerusalem_in_his_Miracles_of_the_Saints_Cyrus_and_John_recounts_how_Kyros_and_Ioannes_Cyrus_and_John_physician_and_soldier_martyrs_of_Egypt_S00406_healed_a_certain_Isidoros_from_a_pulmonary_disease_at_their_shrine_at_Me/13877966]{.underline}](https://figshare.com/articles/online_resource/E06037_Sophronius_of_Jerusalem_in_his_Miracles_of_the_Saints_Cyrus_and_John_recounts_how_Kyros_and_Ioannes_Cyrus_and_John_physician_and_soldier_martyrs_of_Egypt_S00406_healed_a_certain_Isidoros_from_a_pulmonary_disease_at_their_shrine_at_Me/13877966)' || '\n' ||
    '10. Sophronius of Jerusalem... healed a certain Photeinos from blindness... - University of Oxford, accessed January 21, 2026, [[https://portal.sds.ox.ac.uk/articles/online_resource/E07113_Sophronius_of_Jerusalem_in_his_Miracles_of_the_Saints_Cyrus_and_John_recounts_how_Kyros_and_Ioannes_Cyrus_and_John_physician_and_soldier_martyrs_of_Egypt_S00406_healed_a_certain_Photeinos_from_blindness_at_their_shrine_at_Menouthis_n/13910387]{.underline}](https://portal.sds.ox.ac.uk/articles/online_resource/E07113_Sophronius_of_Jerusalem_in_his_Miracles_of_the_Saints_Cyrus_and_John_recounts_how_Kyros_and_Ioannes_Cyrus_and_John_physician_and_soldier_martyrs_of_Egypt_S00406_healed_a_certain_Photeinos_from_blindness_at_their_shrine_at_Menouthis_n/13910387)' || '\n' ||
    '11. Bavarian Palace Administration | Munich Residence | Residence Museum | Reliquary collection, accessed January 21, 2026, [[https://www.residenz-muenchen.de/englisch/museum/reliquien.htm]{.underline}](https://www.residenz-muenchen.de/englisch/museum/reliquien.htm)' || '\n' ||
    '12. Bavarian Palace Administration | Munich Residence | Residence Museum | Ornate Chapel, accessed January 21, 2026, [[https://www.residenz-muenchen.de/englisch/museum/reich_ka.htm]{.underline}](https://www.residenz-muenchen.de/englisch/museum/reich_ka.htm)' || '\n' ||
    '13. Asistenta religioasa si spirituala - București - SUUB, accessed January 21, 2026, [[https://www.suub.ro/pacientiviztatori-asistenta-religioasa-si-spirituala/]{.underline}](https://www.suub.ro/pacientiviztatori-asistenta-religioasa-si-spirituala/)' || '\n' ||
    '14. Preotul spitalului, sprijin pentru bolnavul aflat în suferinţă - Ziarul Lumina, accessed January 21, 2026, [[https://ziarullumina.ro/actualitate-religioasa/an-omagial/preotul-spitalului-sprijin-pentru-bolnavul-aflat-in-suferinta-186870.html]{.underline}](https://ziarullumina.ro/actualitate-religioasa/an-omagial/preotul-spitalului-sprijin-pentru-bolnavul-aflat-in-suferinta-186870.html)' || '\n' ||
    '15. Moaștele Sfântului Mucenic Ciprian - Doxologia, accessed January 21, 2026, [[https://doxologia.ro/moastele-sfantului-mucenic-ciprian]{.underline}](https://doxologia.ro/moastele-sfantului-mucenic-ciprian)' || '\n' ||
    '16. Sfinte Moaşte - // Sfinti Romani, accessed January 21, 2026, [[https://www.sfintiromani.ro/ro/pagina/69/aprilie_calinic_de_la_cernica_moaste.html]{.underline}](https://www.sfintiromani.ro/ro/pagina/69/aprilie_calinic_de_la_cernica_moaste.html)' || '\n' ||
    '17. Acatistul Sfinților Doctori fără de arginți Chir şi Ioan - Doxologia, accessed January 21, 2026, [[https://doxologia.ro/acatistul-sfintilor-doctori-fara-de-arginti-chir-ioan]{.underline}](https://doxologia.ro/acatistul-sfintilor-doctori-fara-de-arginti-chir-ioan)' || '\n' ||
    '18. Cyrus and John - Wikipedia, accessed January 21, 2026, [[https://en.wikipedia.org/wiki/Cyrus_and_John]{.underline}](https://en.wikipedia.org/wiki/Cyrus_and_John)' || '\n' ||
    '19. physician saints - icons and their interpretation, accessed January 21, 2026, [[https://russianicons.wordpress.com/tag/physician-saints/]{.underline}](https://russianicons.wordpress.com/tag/physician-saints/)'
);