INSERT INTO core_schema.saint_lives (name_ro, life_description_ro)
VALUES (
    'Sfântul Cuvios Teoctist',
    '# Viața Cuviosului Părinte Teoctist din Palestina: Stâlp al Pustiei Iudeii și Povățuitor de Sfinți' || '\n\n' ||
    '## Introducere -- Un Stâlp al Pustiei Iudeii' || '\n\n' ||
    'În peisajul duhovnicesc vibrant al Palestinei secolului al V-lea, o perioadă considerată pe drept cuvânt „epoca de aur" a monahismului pustnicesc, s-au ridicat figuri ascetice monumentale ale căror vieți au modelat etosul Ortodoxiei pentru veacurile ce aveau să vină. Printre acești stâlpi de foc ai credinței, alături de nume mai cunoscute precum Sfântul Eftimie cel Mare, se află și Cuviosul Teoctist, un părinte a cărui viață și lucrare sunt fundamental împletite cu cele ale marelui său contemporan și prieten duhovnicesc.^1^' || '\n\n' ||
    'Sfântul care face obiectul acestei cercetări este **Cuviosul Teoctist din Palestina**, împreună-nevoitorul Sfântul Eftimie, care a trecut la cele veșnice în anul 467 și a cărui pomenire Biserica Ortodoxă o săvârșește la data de **3 septembrie**. El este o personalitate distinctă de Cuviosul Teoctist din Sicilia, care este prăznuit la 4 ianuarie.^1^' || '\n\n' ||
    'Viața sa este definită de două teme centrale: pe de o parte, sinergia duhovnicească profundă cu Sfântul Eftimie, o prietenie sfântă ce a devenit un model de comuniune în Hristos; pe de altă parte, rolul său crucial de stareț și egumen, căruia i-a fost încredințată formarea duhovnicească a unei întregi generații de asceți.^6^' || '\n\n' ||
    '## Un singur suflet în două trupuri: Unirea duhovnicească cu Sfântul Eftimie' || '\n\n' ||
    'Tradiția hagiografică plasează începutul acestei prietenii sfinte în Lavra de la Faran, un renumit centru monastic de lângă Ierusalim. Sursele subliniază o legătură spirituală de o profunzime extraordinară, descriindu-i ca având „un singur suflet în două trupuri".^1^ Această imagine reflectă o unitate desăvârșită de voință și dragoste în Hristos.' || '\n\n' ||
    'Ritmul lor duhovnicesc comun era marcat de o rânduială ascetică unică. În fiecare an, după sărbătoarea Botezului Domnului, cei doi prieteni se retrăgeau împreună în adâncul pustiei, dedicându-se rugăciunii neîncetate. Se întorceau la comunitatea lor abia în Duminica Floriilor.^1^' || '\n\n' ||
    'După cinci ani de astfel de nevoință comună, călăuzirea divină i-a purtat într-o zonă izolată a pustiei Cutila (Wadi Mukellik). Aici au descoperit o peșteră mare, pe un versant abrupt, pe care au recunoscut-o ca fiind locul rânduit de Dumnezeu pentru viitoarea lor lucrare.^1^' || '\n\n' ||
    '## Mănăstirea Cuviosului Teoctist (Deir el-Muqalik): O fortăreață duhovnicească' || '\n\n' ||
    'Vestea despre prezența lor s-a răspândit rapid, atrăgând mulți ucenici. De comun acord, Sfântul Eftimie l-a rânduit pe înțeleptul Teoctist ca egumen al noii mănăstiri de obște (cenobiu), prima mare chinovie din pustiul Iudeii.^1^' || '\n\n' ||
    'Relatarea hagiografică este confirmată de arheologia modernă prin ruinele de la **Deir el-Muqalik**, care includ o biserică-peșteră integrată într-o structură de zidărie pe mai multe niveluri.^10^ Sub conducerea Cuviosului Teoctist, mănăstirea a devenit o academie duhovnicească unde marele **Sfânt Sava cel Sfințit** și-a început formarea spirituală.^1^' || '\n\n' ||
    '## Înțeleptul Egumen și Tămăduitorul de Suflete' || '\n\n' ||
    'Ca egumen, Sfântul Teoctist era renumit pentru discernământul său, slujind ca duhovnic și medic sufletesc pentru monahii și pelerinii aflați sub grija sa.^1^' || '\n\n' ||
    'Adevărata minune a vieții Sfântului Teoctist a fost transformarea duhovnicească a nenumărate suflete, făcând „pustiul cel neroditor" să aducă „rod însutit" prin rugăciune și nevoință.^2^' || '\n\n' ||
    '## Sfântul Repaus și Moștenirea Veșnică' || '\n\n' ||
    'Ajuns la adânci bătrâneți, Cuviosul Teoctist a fost cuprins de o boală grea, pe care a îndurat-o cu răbdare și smerenie. Sfântul Eftimie a rămas alături de el până la trecerea sa la Domnul.^20,3^' || '\n\n' ||
    'Cuviosul Teoctist a adormit în pace la **3 septembrie 467**. Slujba de înmormântare a fost săvârșită de însuși **Patriarhul Anastasie I al Ierusalimului**, alături de Sfântul Eftimie.^1,3^' || '\n\n' ||
    '## Cinstirea în Biserica Ortodoxă' || '\n\n' ||
    '**Tropar (Glas 8):** „Cu curgerile lacrimilor tale ai lucrat pustiul cel neroditor şi cu suspinurile cele dintru adânc ai făcut ostenelile tale însutit roditoare; şi te-ai făcut luminător lumii, strălucind cu minunile, Teoctist, părintele nostru..."^2^' || '\n\n' ||
    '**Condac (Glas 4):** „Pe înţeleptul lucrător al rugăciunii, pe al pustiului locuitor preavrednic şi împreună-nevoitor cu marele Eftimie, pe Cuviosul Teoctist să-l lăudăm..."^26^' || '\n\n' ||
    '#### Works cited' || '\n\n' ||
    '1. Teoctist din Palestina - OrthodoxWiki, accessed August 16, 2025, [[https://ro.orthodoxwiki.org/Teoctist_din_Palestina]{.underline}](https://ro.orthodoxwiki.org/Teoctist_din_Palestina)' || '\n' ||
    '2. Teoctist din Palestina (†467) - Uniti Schimbam, accessed August 16, 2025, [[https://www.unitischimbam.ro/teoctist-din-palestina/]{.underline}](https://www.unitischimbam.ro/teoctist-din-palestina/)' || '\n' ||
    '3. Sfântul Cuvios Teoctist al Palestinei... (+467). - Calendar ortodox, accessed August 16, 2025, [[https://calendar.ortodox.md/calendar/entry/RU/7b454556-a4eb-4a11-870b-6f11be71d16b]{.underline}](https://calendar.ortodox.md/calendar/entry/RU/7b454556-a4eb-4a11-870b-6f11be71d16b)' || '\n' ||
    '4. 03 Septembrie - Sfântul sfintitul mucenic Antim... :: Calendar crestin ortodox, accessed August 16, 2025, [[https://www.calendar-ortodox.ro/luna/septembrie/septembrie03.htm]{.underline}](https://www.calendar-ortodox.ro/luna/septembrie/septembrie03.htm)' || '\n' ||
    '5. Sfântul Cuvios Teoctist, egumen la Cucumia-Sicilia... - Calendar ortodox, accessed August 16, 2025, [[https://calendar.ortodox.md/calendar/entry/RU/84]{.underline}](https://calendar.ortodox.md/calendar/entry/RU/84)' || '\n' ||
    '6. Sfântul Cuvios Teoctist din Palestina | Doxologia, accessed August 16, 2025, [[https://doxologia.ro/sfantul-cuvios-teoctist-din-palestina]{.underline}](https://doxologia.ro/sfantul-cuvios-teoctist-din-palestina)' || '\n' ||
    '7. Sfântul Eftimie cel Mare -- Cuvântul Înalpreasfințitului Părinte Calinic, accessed August 16, 2025, [[https://www.arhiepiscopiasucevei.ro/sfantul-eftimie-cel-mare-cuvantul-inaltpreasfintitului-parinte-calinic/]{.underline}](https://www.arhiepiscopiasucevei.ro/sfantul-eftimie-cel-mare-cuvantul-inaltpreasfintitului-parinte-calinic/)' || '\n' ||
    '8. Eftimie cel Mare - OrthodoxWiki, accessed August 16, 2025, [[https://ro.orthodoxwiki.org/Eftimie_cel_Mare]{.underline}](https://ro.orthodoxwiki.org/Eftimie_cel_Mare)' || '\n' ||
    '9. Sfântul Eftimie cel Mare şi începuturile monahismului palestinian, accessed August 16, 2025, [[https://ziarullumina.ro/actualitate-religioasa/documentar/sfantul-eftimie-cel-mare-si-inceputurile-monahismului-palestinian-168598.html]{.underline}](https://ziarullumina.ro/actualitate-religioasa/documentar/sfantul-eftimie-cel-mare-si-inceputurile-monahismului-palestinian-168598.html)' || '\n' ||
    '10. Deir el-Muqalik - THEOCTISTUS | Huji, accessed August 16, 2025, [[https://dig.corps-cmhl.huji.ac.il/decorations/deir-el-muqalik-theoctistus]{.underline}](https://dig.corps-cmhl.huji.ac.il/decorations/deir-el-muqalik-theoctistus)' || '\n' ||
    '11. Deir el-Muqalik - THEOCTISTUS | Huji, accessed August 16, 2025, [[https://dig.corps-cmhl.huji.ac.il/Monasteries/deir-el-muqalik-theoctistus]{.underline}](https://dig.corps-cmhl.huji.ac.il/Monasteries/deir-el-muqalik-theoctistus)' || '\n' ||
    '12. (PDF) The Monastery of St. Theoctistus (Deir Muqallik) - ResearchGate, accessed August 16, 2025, [[https://www.researchgate.net/publication/281454942_The_Monastery_of_St_Theoctistus_Deir_Muqallik]{.underline}](https://www.researchgate.net/publication/281454942_The_Monastery_of_St_Theoctistus_Deir_Muqallik)' || '\n' ||
    '13. Cross-section and suggested reconstruction of unit A (by D. Abu-Hatzira). - ResearchGate, accessed August 16, 2025, [[https://www.researchgate.net/figure/Cross-section-and-suggested-reconstruction-of-unit-A-by-D-Abu-Hatzira_fig4_281454942]{.underline}](https://www.researchgate.net/figure/Cross-section-and-suggested-reconstruction-of-unit-A-by-D-Abu-Hatzira_fig4_281454942)' || '\n' ||
    '14. the economy and livelihoods - of the early christian monasteries in palestine - Helda, accessed August 16, 2025, [[https://helda.helsinki.fi/bitstreams/ca035807-d80a-4629-9fe3-d3daa2f8071e/download]{.underline}](https://helda.helsinki.fi/bitstreams/ca035807-d80a-4629-9fe3-d3daa2f8071e/download)' || '\n' ||
    '15. Sabbas the Sanctified - Wikipedia, accessed August 16, 2025, [[https://en.wikipedia.org/wiki/Sabbas_the_Sanctified]{.underline}](https://en.wikipedia.org/wiki/Sabbas_the_Sanctified)' || '\n' ||
    '16. Venerable Theoctistus - Orthodox Church in America, accessed August 16, 2025, [[https://www.oca.org/saints/lives/2023/09/03/102478-venerable-theoctistus]{.underline}](https://www.oca.org/saints/lives/2023/09/03/102478-venerable-theoctistus)' || '\n' ||
    '17. Sf. Sfințit Mc. Antim... Sf. Cuv. Teoctist din Palestina... - Basilica.ro, accessed August 16, 2025, [[https://basilica.ro/calendar-ortodox-3-septembrie/]{.underline}](https://basilica.ro/calendar-ortodox-3-septembrie/)' || '\n' ||
    '18. Όσιος Θεόκτιστος συνασκητής του Αγίου Ευθυμίου | Βίος & Γιορτή - Monastic Republic, accessed August 16, 2025, [[https://www.monasticrepublic.com/synaxaristis/septemvrios/osios-theoktistos-synaskitis-tou-agiou-eythymiou]{.underline}](https://www.monasticrepublic.com/synaxaristis/septemvrios/osios-theoktistos-synaskitis-tou-agiou-eythymiou)' || '\n' ||
    '19. Месяцеслов на 2025 год - 16 сентября. Тропари, кондаки, молитвы дня. - Православный молитвослов, accessed August 16, 2025, [[https://xn----7sbahbba0chrecjllhdbcuymu3s.xn--p1ai/07_calendar/09/16.html]{.underline}](https://xn----7sbahbba0chrecjllhdbcuymu3s.xn--p1ai/07_calendar/09/16.html)' || '\n' ||
    '20. Viața și acatistul Sfântului Cuvios Teoctist din Palestina - *** | Libraria Sophia, accessed August 16, 2025, [[https://www.librariasophia.ro/vieti-de-sfinti-si-mari-nevoitori/viata-si-acatistul-sfantului-cuvios-teoctist-din-palestina-1504.html]{.underline}](https://www.librariasophia.ro/vieti-de-sfinti-si-mari-nevoitori/viata-si-acatistul-sfantului-cuvios-teoctist-din-palestina-1504.html)' || '\n' ||
    '21. Viața și acatistul Sfântului Cuvios Teoctist din Palestina - *** | Libraria Sophia, accessed August 16, 2025, [[https://www.librariasophia.ro/carti-Via%C8%9Ba-%C8%99i-acatistul-Sf%C3%A2ntului-Cuvios-Teoctist-din-Palestina-*-*-*-so-19175.html]{.underline}](https://www.librariasophia.ro/carti-Via%C8%9Ba-%C8%99i-acatistul-Sf%C3%A2ntului-Cuvios-Teoctist-din-Palestina-*-*-*-so-19175.html)' || '\n' ||
    '22. Όσιος Θεόκτιστος συνασκητής του Μεγάλου Ευθυμίου - Ορθόδοξος Συναξαριστής, accessed August 16, 2025, [[https://www.saint.gr/939/saint.aspx]{.underline}](https://www.saint.gr/939/saint.aspx)' || '\n' ||
    '23. Ὁ Ὅσιος Θεόκτιστος συνασκητὴς τοῦ Μεγάλου Εὐθυμίου - μεγας συναξαριστης, accessed August 16, 2025, [[https://www.synaxarion.gr/gr/sid/540/sxsaintinfo.aspx]{.underline}](https://www.synaxarion.gr/gr/sid/540/sxsaintinfo.aspx)' || '\n' ||
    '24. Тропарь Феоктисту Палестинскому - Ortox, accessed August 16, 2025, [[https://ortox.ru/pravoslavnye-spravochniki/tropary/tropar-feoktistu-palestinskomu/]{.underline}](https://ortox.ru/pravoslavnye-spravochniki/tropary/tropar-feoktistu-palestinskomu/)' || '\n' ||
    '25. Феоктист Палестинский, игумен, прп. - Православие.Ru, accessed August 16, 2025, [[https://days.pravoslavie.ru/name/2238.htm]{.underline}](https://days.pravoslavie.ru/name/2238.htm)' || '\n' ||
    '26. Acatistul Sfântului Cuvios Teoctist din Palestina - Doxologia, accessed August 16, 2025, [[https://doxologia.ro/acatistul-sfantului-cuvios-teoctist-din-palestina]{.underline}](https://doxologia.ro/acatistul-sfantului-cuvios-teoctist-din-palestina)' || '\n' ||
    '27. Тропари преподобным Богу православные... accessed August 16, 2025, [[https://naafone.ru/molitvy/molitvosloviya/tropari-i-kondaki/tropari-prepodobnym/]{.underline}](https://naafone.ru/molitvy/molitvosloviya/tropari-i-kondaki/tropari-prepodobnym/)' || '\n' ||
    '28. Феоктист Палестинский: житие, иконы, day памяти - Азбука веры, accessed August 16, 2025, [[https://azbyka.ru/days/sv-feoktist-palestinskij]{.underline}](https://azbyka.ru/days/sv-feoktist-palestinskij)'
);